import TranslatedDepthSeven.AugmentedLinearNormalization
import TranslatedDepthSeven.HomogeneousNormalizationMinpolyInternal

/-!
# The actual hypersurface equation after adding one linear coordinate

Over the normal polynomial normalization ring, the kernel of evaluation
at an integral element is generated by its monic minimal polynomial.
The existing homogeneity theorem makes that polynomial homogeneous in all
normalization variables and the added variable. Reindexing gives the
literal principal kernel of the existing augmented coordinate map.

This does not yet assert birationality or equality of its degree with the
source degree; the proved degree bound is at most the source degree.
-/

namespace TranslatedDepthSeven
noncomputable section
open MvPolynomial Published
open scoped nonZeroDivisors
attribute [local instance] MvPolynomial.gradedAlgebra
set_option maxHeartbeats 3000000
set_option synthInstance.maxHeartbeats 300000

/-- The augmented polynomial coordinate map is literally univariate
evaluation over the normalization ring, after the displayed reindexing. -/
theorem augmentedLinearNormalizationHom_eq_polynomialEvaluation
    {K τ : Type*} [Field K]
    {I : Ideal (MvPolynomial τ K)}
    (D : HomogeneousLinearNormalizationData I) (u : MvPolynomial τ K ⧸ I) :
    let B := MvPolynomial (Fin D.parameterCount) K
    let A := MvPolynomial τ K ⧸ I
    letI : Algebra B A := D.hom.toRingHom.toAlgebra
    let e := (MvPolynomial.renameEquiv K (_root_.finSuccEquiv D.parameterCount)).trans
      (MvPolynomial.optionEquivLeft K (Fin D.parameterCount))
    augmentedLinearNormalizationHom D u =
      ((Polynomial.aeval u).restrictScalars K).comp e.toAlgHom := by
  letI : Algebra (MvPolynomial (Fin D.parameterCount) K) (MvPolynomial τ K ⧸ I) :=
    D.hom.toRingHom.toAlgebra
  dsimp only
  apply MvPolynomial.algHom_ext
  intro i
  refine Fin.cases ?_ (fun j ↦ ?_) i
  · simp only [augmentedLinearNormalizationHom_X_zero, AlgHom.comp_apply,
      AlgEquiv.toAlgHom_eq_coe, AlgHom.coe_coe, AlgEquiv.trans_apply,
      MvPolynomial.renameEquiv_apply, MvPolynomial.rename_X,
      finSuccEquiv_zero, MvPolynomial.optionEquivLeft_X_none]
    exact (Polynomial.aeval_X u).symm
  · simp only [augmentedLinearNormalizationHom_X_succ, AlgHom.comp_apply,
      AlgEquiv.toAlgHom_eq_coe, AlgHom.coe_coe, AlgEquiv.trans_apply,
      MvPolynomial.renameEquiv_apply, MvPolynomial.rename_X,
      finSuccEquiv_succ, MvPolynomial.optionEquivLeft_X_some]
    exact (Polynomial.aeval_C (R := MvPolynomial (Fin D.parameterCount) K) u (X j)).symm

/-- A homogeneous degree-one extra coordinate gives an irreducible
homogeneous generator of the actual augmented image kernel. -/
theorem augmentedLinearNormalization_exists_homogeneous_irreducible_kernel
    {K : Type*} [Field K] [CharZero K] {N r d : ℕ}
    (I : Ideal (MvPolynomial (Fin (N + 1)) K)) (hIprime : I.IsPrime)
    (hIhom : I.IsHomogeneous (homogeneousSubmodule (Fin (N + 1)) K))
    (hdegree : HasProjectiveDimensionDegree I r d)
    (D : HomogeneousLinearNormalizationData I)
    (w : MvPolynomial (Fin (N + 1)) K) (hwhom : w.IsHomogeneous 1) :
    ∃ e : ℕ, ∃ G : MvPolynomial (Fin (D.parameterCount + 1)) K,
      (augmentedLinearNormalizationHom D (Ideal.Quotient.mk I w)).Finite ∧
      RingHom.ker (augmentedLinearNormalizationHom D (Ideal.Quotient.mk I w)).toRingHom =
        Ideal.span ({G} : Set _) ∧
      G.IsHomogeneous e ∧ Irreducible G ∧ e ≤ d := by
  classical
  letI : I.IsPrime := hIprime
  let B := MvPolynomial (Fin D.parameterCount) K
  let A := MvPolynomial (Fin (N + 1)) K ⧸ I
  letI : Algebra B A := D.hom.toRingHom.toAlgebra
  letI : FaithfulSMul B A :=
    (faithfulSMul_iff_algebraMap_injective B A).mpr D.hom_injective
  letI : Module.Finite B A := D.hom_finite
  let u : A := Ideal.Quotient.mk I w
  let p := minpoly B u
  let E := (MvPolynomial.renameEquiv K (_root_.finSuccEquiv D.parameterCount)).trans
    (MvPolynomial.optionEquivLeft K (Fin D.parameterCount))
  let G := E.symm p
  have hu : IsIntegral B u := Algebra.IsIntegral.isIntegral u
  refine ⟨p.natDegree, G, augmentedLinearNormalizationHom_finite D u, ?_, ?_, ?_, ?_⟩
  · have hmap := augmentedLinearNormalizationHom_eq_polynomialEvaluation D u
    change augmentedLinearNormalizationHom D u =
      ((Polynomial.aeval u).restrictScalars K).comp E.toAlgHom at hmap
    ext f
    rw [RingHom.mem_ker, hmap]
    change Polynomial.aeval u (E f) = 0 ↔ f ∈ Ideal.span ({G} : Set _)
    rw [minpoly.isIntegrallyClosed_dvd_iff hu, Ideal.mem_span_singleton]
    change p ∣ E f ↔ E.symm p ∣ f
    simpa only [AlgEquiv.apply_symm_apply] using
      (map_dvd_iff E (a := E.symm p) (b := f))
  · have hhom := minpoly_isHomogeneous_of_linearNormalization I hIprime hIhom D w hwhom
    change ((MvPolynomial.optionEquivLeft K (Fin D.parameterCount)).symm p).IsHomogeneous
      p.natDegree at hhom
    change (MvPolynomial.rename (_root_.finSuccEquiv D.parameterCount).symm
      ((MvPolynomial.optionEquivLeft K (Fin D.parameterCount)).symm p)).IsHomogeneous p.natDegree
    exact hhom.rename_isHomogeneous
  · exact (minpoly.irreducible hu).map E.symm
  · exact (minpoly_natDegree_le_localized_rank u).trans
      (homogeneousLinearNormalization_genericRank_le_projectiveDegree I hIprime D hdegree).2

end
end TranslatedDepthSeven
