import Mathlib.RingTheory.LocalRing.Module
import Mathlib.RingTheory.Finiteness.Ideal

/-!
# Conormal generation gives the exact local ideal

This is the precise Nakayama step in the point-local component argument.
For nested ideals `J ⊆ I` in a local ring, it is enough that the image of
`J` span the image of `I` modulo `m I`.  If `I` is finitely generated, then
`J = I`.

No smoothness, dimension, component, or height assertion is hidden here.
Those hypotheses enter only when one proves the displayed conormal
surjectivity for the concrete equations.
-/

namespace TranslatedDepthSeven

variable {R : Type*} [CommRing R] [IsLocalRing R]

/-- A finite ideal is generated by a nested ideal as soon as the latter
surjects onto its conormal quotient `I / m I`. -/
theorem ideal_eq_of_conormal_map_le
    (J I : Ideal R) (hJI : J ≤ I) (hIfg : I.FG)
    (hconormal :
      Submodule.map
          (Submodule.mkQ (IsLocalRing.maximalIdeal R • (I : Submodule R R)))
          (I : Submodule R R) ≤
        Submodule.map
          (Submodule.mkQ (IsLocalRing.maximalIdeal R • (I : Submodule R R)))
          (J : Submodule R R)) :
    J = I := by
  apply (IsLocalRing.map_mkQ_eq hJI hIfg).mp
  exact le_antisymm (Submodule.map_mono hJI) hconormal

/-- Equality of the two conormal images is an equivalent, symmetric form of
the same criterion. -/
theorem ideal_eq_of_conormal_map_eq
    (J I : Ideal R) (hJI : J ≤ I) (hIfg : I.FG)
    (hconormal :
      Submodule.map
          (Submodule.mkQ (IsLocalRing.maximalIdeal R • (I : Submodule R R)))
          (J : Submodule R R) =
        Submodule.map
          (Submodule.mkQ (IsLocalRing.maximalIdeal R • (I : Submodule R R)))
          (I : Submodule R R)) :
    J = I := by
  apply ideal_eq_of_conormal_map_le J I hJI hIfg
  exact hconormal.ge

end TranslatedDepthSeven
