import TranslatedDepthSeven.DepthSevenJacobianCharts
import TranslatedDepthSeven.FiniteComponentFrontier
import TranslatedDepthSeven.PrincipalOpenReduction
import TranslatedDepthSeven.ExplicitEquationFamilySpecialFiber
import TranslatedDepthSeven.DepthSevenNormalizedJacobianPartition

/-!
# The literal exceptional locus of the depth-seven Jacobian charts

For a finite polynomial family, this file adjoins all of the finitely many
displayed `7 × 7` Jacobian determinants to the original equations.  The
resulting ideal defines the rank-at-most-six part of the common zero locus.

If one of those determinant polynomials does not belong to a fixed prime
ideal generated by the equations, the augmented ideal strictly contains the
prime.  Consequently every minimal prime of the augmented ideal has strictly
smaller quotient dimension.  This is the unconditional proper-closed-locus
consequence of a generic nonzero Jacobian minor; it does not use a Jacobian
criterion or assert that seven selected equations cut out the original prime
as a minimal component.

The final statements record the two exact integral specialization facts that
need no flatness or geometric-integrality assertion: principal-open reduction
preserves the literal augmented ideal, and a displayed determinant nonzero at
an integral point remains a rank certificate modulo every prime not dividing
its value.
-/

namespace TranslatedDepthSeven

noncomputable section

open MvPolynomial

set_option maxRecDepth 2000

universe u

variable {k : Type u} [Field k]

/-- The finite family of the determinants attached to every depth-seven
Jacobian chart. -/
def depthSevenJacobianMinorPolynomialFinset {N : ℕ}
    (equations : Finset (MvPolynomial (Fin N) k)) :
    Finset (MvPolynomial (Fin N) k) := by
  classical
  exact Finset.univ.image
    (fun C : DepthSevenJacobianChartIndex equations ↦ C.determinant)

@[simp]
theorem mem_depthSevenJacobianMinorPolynomialFinset_iff {N : ℕ}
    (equations : Finset (MvPolynomial (Fin N) k))
    (g : MvPolynomial (Fin N) k) :
    g ∈ depthSevenJacobianMinorPolynomialFinset equations ↔
      ∃ C : DepthSevenJacobianChartIndex equations, C.determinant = g := by
  classical
  constructor
  · intro hg
    obtain ⟨C, _hC, hCg⟩ := Finset.mem_image.mp hg
    exact ⟨C, hCg⟩
  · rintro ⟨C, rfl⟩
    exact Finset.mem_image.mpr ⟨C, Finset.mem_univ _, rfl⟩

/-- The original equations together with all displayed depth-seven
Jacobian determinants. -/
def depthSevenJacobianExceptionalEquationFinset {N : ℕ}
    (equations : Finset (MvPolynomial (Fin N) k)) :
    Finset (MvPolynomial (Fin N) k) := by
  classical
  exact equations ∪ depthSevenJacobianMinorPolynomialFinset equations

/-- The literal ideal of the rank-at-most-six part of the displayed common
zero locus. -/
def depthSevenJacobianExceptionalIdeal {N : ℕ}
    (equations : Finset (MvPolynomial (Fin N) k)) :
    Ideal (MvPolynomial (Fin N) k) :=
  Ideal.span
    (depthSevenJacobianExceptionalEquationFinset equations :
      Set (MvPolynomial (Fin N) k))

theorem depthSevenJacobianExceptionalIdeal_eq_sup {N : ℕ}
    (equations : Finset (MvPolynomial (Fin N) k)) :
    depthSevenJacobianExceptionalIdeal equations =
      Ideal.span (equations : Set (MvPolynomial (Fin N) k)) ⊔
        Ideal.span
          (depthSevenJacobianMinorPolynomialFinset equations :
            Set (MvPolynomial (Fin N) k)) := by
  classical
  rw [depthSevenJacobianExceptionalIdeal,
    depthSevenJacobianExceptionalEquationFinset, Finset.coe_union,
    Ideal.span_union]

/-- The augmented finite family cuts out exactly the original common zeros
at which every displayed depth-seven Jacobian minor vanishes. -/
theorem mem_finiteAffineCommonZeroLocus_exceptional_iff {N : ℕ}
    (equations : Finset (MvPolynomial (Fin N) k)) (z : Fin N → k) :
    z ∈ finiteAffineCommonZeroLocus
        (depthSevenJacobianExceptionalEquationFinset equations) ↔
      z ∈ finiteAffineCommonZeroLocus equations ∧
        IsDepthSevenJacobianRankAtMostSix equations z := by
  classical
  constructor
  · intro hz
    refine ⟨?_, ?_⟩
    · intro f hf
      exact hz f (Finset.mem_union_left _ hf)
    · by_contra hrank
      obtain ⟨C, hC⟩ :=
        exists_depthSevenJacobianChartIndex_of_not_rankAtMostSix
          equations z hrank
      apply hC
      apply hz C.determinant
      exact Finset.mem_union_right equations <|
        (mem_depthSevenJacobianMinorPolynomialFinset_iff
          equations C.determinant).mpr ⟨C, rfl⟩
  · rintro ⟨hz, hrank⟩ f hf
    rcases Finset.mem_union.mp hf with hf | hf
    · exact hz f hf
    · obtain ⟨C, rfl⟩ :=
        (mem_depthSevenJacobianMinorPolynomialFinset_iff equations f).mp hf
      exact hrank C.rows C.cols

/-- The determinant of each chart belongs to the exceptional ideal. -/
theorem DepthSevenJacobianChartIndex.determinant_mem_exceptionalIdeal
    {N : ℕ} {equations : Finset (MvPolynomial (Fin N) k)}
    (C : DepthSevenJacobianChartIndex equations) :
    C.determinant ∈ depthSevenJacobianExceptionalIdeal equations := by
  classical
  apply Ideal.subset_span
  exact Finset.mem_union_right equations <|
    (mem_depthSevenJacobianMinorPolynomialFinset_iff
      equations C.determinant).mpr ⟨C, rfl⟩

/-- The ideal generated by the original equations is contained in the
exceptional ideal. -/
theorem span_le_depthSevenJacobianExceptionalIdeal {N : ℕ}
    (equations : Finset (MvPolynomial (Fin N) k)) :
    Ideal.span (equations : Set (MvPolynomial (Fin N) k)) ≤
      depthSevenJacobianExceptionalIdeal equations := by
  rw [depthSevenJacobianExceptionalIdeal_eq_sup]
  exact le_sup_left

/-- A rank-seven point of a fixed closed subscheme selects a displayed
determinant which is not in its ideal.  This turns pointwise rank information
into the generic nonvanishing statement needed below without a Jacobian
criterion. -/
theorem exists_chart_determinant_notMem_of_not_rankAtMostSix {N : ℕ}
    (equations : Finset (MvPolynomial (Fin N) k))
    (P : Ideal (MvPolynomial (Fin N) k)) (z : Fin N → k)
    (hPz : P ≤ RingHom.ker (MvPolynomial.eval z))
    (hrank : ¬ IsDepthSevenJacobianRankAtMostSix equations z) :
    ∃ C : DepthSevenJacobianChartIndex equations, C.determinant ∉ P := by
  obtain ⟨C, hC⟩ :=
    exists_depthSevenJacobianChartIndex_of_not_rankAtMostSix
      equations z hrank
  refine ⟨C, ?_⟩
  intro hmem
  exact hC (RingHom.mem_ker.mp (hPz hmem))

/-- A single generic determinant outside the prime generated by the original
equations proves that the rank-at-most-six locus is a proper closed subset of
that prime component. -/
theorem prime_lt_depthSevenJacobianExceptionalIdeal_of_determinant_notMem
    {N : ℕ} {equations : Finset (MvPolynomial (Fin N) k)}
    (P : Ideal (MvPolynomial (Fin N) k))
    (hP : Ideal.span (equations : Set (MvPolynomial (Fin N) k)) = P)
    (C : DepthSevenJacobianChartIndex equations) (hD : C.determinant ∉ P) :
    P < depthSevenJacobianExceptionalIdeal equations := by
  have hle : P ≤ depthSevenJacobianExceptionalIdeal equations := by
    rw [← hP]
    exact span_le_depthSevenJacobianExceptionalIdeal equations
  refine lt_of_le_not_ge hle ?_
  intro hge
  exact hD (hge C.determinant_mem_exceptionalIdeal)

/-- Thus the existence of one literal rank-seven point on `P` makes the
augmented rank-at-most-six ideal strictly larger than `P`. -/
theorem prime_lt_depthSevenJacobianExceptionalIdeal_of_rankSevenPoint
    {N : ℕ} {equations : Finset (MvPolynomial (Fin N) k)}
    (P : Ideal (MvPolynomial (Fin N) k))
    (hP : Ideal.span (equations : Set (MvPolynomial (Fin N) k)) = P)
    (z : Fin N → k) (hPz : P ≤ RingHom.ker (MvPolynomial.eval z))
    (hrank : ¬ IsDepthSevenJacobianRankAtMostSix equations z) :
    P < depthSevenJacobianExceptionalIdeal equations := by
  obtain ⟨C, hC⟩ :=
    exists_chart_determinant_notMem_of_not_rankAtMostSix
      equations P z hPz hrank
  exact
    prime_lt_depthSevenJacobianExceptionalIdeal_of_determinant_notMem
      P hP C hC

/-- Every irreducible component of the exceptional locus strictly lies
inside the original prime component. -/
theorem prime_lt_exceptionalMinimalPrime_of_determinant_notMem
    {N : ℕ} {equations : Finset (MvPolynomial (Fin N) k)}
    (P Q : Ideal (MvPolynomial (Fin N) k))
    (hP : Ideal.span (equations : Set (MvPolynomial (Fin N) k)) = P)
    (C : DepthSevenJacobianChartIndex equations) (hD : C.determinant ∉ P)
    (hQ : Q ∈ finiteMinimalPrimes
      (depthSevenJacobianExceptionalIdeal equations)) :
    P < Q := by
  exact (prime_lt_depthSevenJacobianExceptionalIdeal_of_determinant_notMem
      P hP C hD).trans_le (le_of_mem_finiteMinimalPrimes hQ)

/-- Numerical dimension drop for every component of the proper exceptional
locus. -/
theorem ringKrullDim_exceptionalMinimalPrime_lt_of_determinant_notMem
    {N : ℕ} {equations : Finset (MvPolynomial (Fin N) k)}
    (P Q : Ideal (MvPolynomial (Fin N) k)) [P.IsPrime]
    (hP : Ideal.span (equations : Set (MvPolynomial (Fin N) k)) = P)
    (C : DepthSevenJacobianChartIndex equations) (hD : C.determinant ∉ P)
    (hQ : Q ∈ finiteMinimalPrimes
      (depthSevenJacobianExceptionalIdeal equations))
    (hPfinite : ringKrullDim
      (MvPolynomial (Fin N) k ⧸ P) < ⊤) :
    ringKrullDim (MvPolynomial (Fin N) k ⧸ Q) <
      ringKrullDim (MvPolynomial (Fin N) k ⧸ P) := by
  letI : Q.IsPrime := isPrime_of_mem_finiteMinimalPrimes hQ
  exact ringKrullDim_quotient_lt_of_prime_lt P Q
    (prime_lt_exceptionalMinimalPrime_of_determinant_notMem
      P Q hP C hD hQ) hPfinite

/-- A natural-number version of the preceding dimension drop. -/
theorem ringKrullDim_exceptionalMinimalPrime_lt_nat_of_determinant_notMem
    {N : ℕ} {equations : Finset (MvPolynomial (Fin N) k)}
    (P Q : Ideal (MvPolynomial (Fin N) k)) [P.IsPrime] {s : ℕ}
    (hP : Ideal.span (equations : Set (MvPolynomial (Fin N) k)) = P)
    (C : DepthSevenJacobianChartIndex equations) (hD : C.determinant ∉ P)
    (hQ : Q ∈ finiteMinimalPrimes
      (depthSevenJacobianExceptionalIdeal equations))
    (hPdim : ringKrullDim (MvPolynomial (Fin N) k ⧸ P) = s) :
    ringKrullDim (MvPolynomial (Fin N) k ⧸ Q) < s := by
  have hPfinite : ringKrullDim
      (MvPolynomial (Fin N) k ⧸ P) < ⊤ := by
    rw [hPdim]
    change (↑(s : ℕ∞) : WithBot ℕ∞) < ↑(⊤ : ℕ∞)
    exact WithBot.coe_lt_coe.mpr (ENat.coe_lt_top s)
  have hdrop :=
    ringKrullDim_exceptionalMinimalPrime_lt_of_determinant_notMem
      P Q hP C hD hQ hPfinite
  rwa [hPdim] at hdrop

/-- Every point on the literal exceptional locus lies on one of its finite
minimal-prime components; when one generic determinant is outside `P`, that
component strictly contains `P`. -/
theorem exists_exceptionalMinimalPrime_through_point
    {N : ℕ} {equations : Finset (MvPolynomial (Fin N) k)}
    (P : Ideal (MvPolynomial (Fin N) k))
    (hP : Ideal.span (equations : Set (MvPolynomial (Fin N) k)) = P)
    (C : DepthSevenJacobianChartIndex equations) (hD : C.determinant ∉ P)
    (z : Fin N → k)
    (hz : z ∈ finiteAffineCommonZeroLocus
      (depthSevenJacobianExceptionalEquationFinset equations)) :
    ∃ Q ∈ finiteMinimalPrimes
        (depthSevenJacobianExceptionalIdeal equations),
      P < Q ∧ Q ≤ RingHom.ker (MvPolynomial.eval z) := by
  obtain ⟨Q, hQ⟩ :=
    finiteEquationComponentsThroughPoint_nonempty_of_mem
      (depthSevenJacobianExceptionalEquationFinset equations) z hz
  have hQspec :=
    (mem_finiteEquationComponentsThroughPoint_iff
      (depthSevenJacobianExceptionalEquationFinset equations) z Q).mp hQ
  have hQmin : Q ∈ finiteMinimalPrimes
      (depthSevenJacobianExceptionalIdeal equations) := by
    simpa [finiteEquationMinimalPrimes, finiteEquationIdeal,
      depthSevenJacobianExceptionalIdeal] using hQspec.1
  exact ⟨Q, hQmin,
    prime_lt_exceptionalMinimalPrime_of_determinant_notMem
      P Q hP C hD hQmin,
    hQspec.2⟩

/-- If the original prime has natural-number quotient dimension `s`, the
component of the exceptional locus through a displayed exceptional point can
be chosen with quotient dimension strictly below `s`. -/
theorem exists_lowerDim_exceptionalMinimalPrime_through_point
    {N : ℕ} {equations : Finset (MvPolynomial (Fin N) k)}
    (P : Ideal (MvPolynomial (Fin N) k)) [P.IsPrime] {s : ℕ}
    (hP : Ideal.span (equations : Set (MvPolynomial (Fin N) k)) = P)
    (C : DepthSevenJacobianChartIndex equations) (hD : C.determinant ∉ P)
    (hPdim : ringKrullDim (MvPolynomial (Fin N) k ⧸ P) = s)
    (z : Fin N → k)
    (hz : z ∈ finiteAffineCommonZeroLocus
      (depthSevenJacobianExceptionalEquationFinset equations)) :
    ∃ Q ∈ finiteMinimalPrimes
        (depthSevenJacobianExceptionalIdeal equations),
      P < Q ∧ Q ≤ RingHom.ker (MvPolynomial.eval z) ∧
        ringKrullDim (MvPolynomial (Fin N) k ⧸ Q) < s := by
  obtain ⟨Q, hQ, hPQ, hQz⟩ :=
    exists_exceptionalMinimalPrime_through_point P hP C hD z hz
  exact ⟨Q, hQ, hPQ, hQz,
    ringKrullDim_exceptionalMinimalPrime_lt_nat_of_determinant_notMem
      P Q hP C hD hQ hPdim⟩

end

section IntegralSpecialization

/-- Away from the displayed denominator, coefficientwise reduction of the
literal integral rank-at-most-six ideal agrees exactly with reduction after
passing to the principal-open model. -/
theorem map_localized_depthSevenRankAtMostSixIdeal_to_ZMod
    (equations : Finset (MvPolynomial (Fin 13) ℤ))
    (Δ : ℤ) (p : ℕ) (hp : p.Prime) (hpΔ : ¬ p ∣ Δ.natAbs) :
    Ideal.map (MvPolynomial.map (awayIntToZMod Δ p hp hpΔ))
        (Ideal.map
          (MvPolynomial.map (algebraMap ℤ (Localization.Away Δ)))
          (Ideal.span
            (depthSevenRankAtMostSixEquationFinset equations :
              Set (MvPolynomial (Fin 13) ℤ)))) =
      Ideal.map (MvPolynomial.map (Int.castRingHom (ZMod p)))
        (Ideal.span
          (depthSevenRankAtMostSixEquationFinset equations :
            Set (MvPolynomial (Fin 13) ℤ))) := by
  exact map_localized_mvPolynomialIdeal_to_ZMod Δ p hp hpΔ _

/-- A literal depth-seven chart whose evaluated determinant is not divisible
by `p` bounds the tangent-kernel dimension of the displayed reduced equation
family by six. -/
theorem finrank_reducedEquationFamilyTangentKernel_le_six_of_chart
    (equations : Finset (MvPolynomial (Fin 13) ℤ))
    (x : Fin 13 → ℤ)
    (C : IntegralDepthSevenJacobianChartIndex equations)
    (p : ℕ) (hp : p.Prime)
    (hminor : ¬ (p : ℤ) ∣
      MvPolynomial.eval x C.determinant) :
    Module.finrank (ZMod p)
        (reducedEquationFamilyTangentKernel (p := p)
          (indexedFinsetFamily equations) x) ≤ 6 := by
  apply finrank_reducedEquationFamilyTangentKernel_le_of_minor_not_dvd
    hp (by omega) (indexedFinsetFamily equations) x C.rows C.cols
  rwa [IntegralDepthSevenJacobianChartIndex.determinant,
    eval_integralJacobianMinorPolynomial] at hminor

end IntegralSpecialization

end TranslatedDepthSeven
