import TranslatedDepthSeven.EquationFamilyTangentKernel
import TranslatedDepthSeven.HomogeneousCone
import Mathlib.LinearAlgebra.Projectivization.Subspace
import Mathlib.RingTheory.MvPolynomial.EulerIdentity

/-!
# Projectivized tangent spaces of finite homogeneous equation families

For a literal finite family of homogeneous integral equations and an
integral common zero, this file projectivizes the rational Jacobian kernel
defined in `EquationFamilyTangentKernel`.  It then proves directly that the
projective line generated by the base point and the direction of every full
integral line is contained in that projective tangent space.

The final results also show that the same projective line is contained in
the original common projective zero locus.  Thus both occurrences of the
word `projective` below refer to Mathlib's actual projectivization, not to an
informal dimension count.
-/

namespace TranslatedDepthSeven

noncomputable section

open scoped BigOperators LinearAlgebra.Projectivization

open Finset MvPolynomial Polynomial

/-- The actual rational projective tangent space cut out by the evaluated
Jacobian rows of the displayed equation family. -/
def equationFamilyRationalProjectiveTangentSpace {n : ℕ}
    (equations : Finset (MvPolynomial (Fin n) ℤ)) (h : IntVector n) :
    Projectivization.Subspace ℚ (Fin n → ℚ) :=
  (equationFamilyRationalTangentKernel equations h).projectivization

/-- Membership in the projective tangent space is exactly membership of a
nonzero representative in the literal rational Jacobian kernel. -/
@[simp]
theorem mk_mem_equationFamilyRationalProjectiveTangentSpace_iff
    {n : ℕ} (equations : Finset (MvPolynomial (Fin n) ℤ))
    (h : IntVector n) (x : Fin n → ℚ) (hx : x ≠ 0) :
    Projectivization.mk ℚ x hx ∈
        equationFamilyRationalProjectiveTangentSpace equations h ↔
      x ∈ equationFamilyRationalTangentKernel equations h := by
  rfl

/-- Euler's identity puts a homogeneous common zero itself in its rational
Jacobian kernel. -/
theorem intBasePoint_mem_equationFamilyRationalTangentKernel
    {n : ℕ} (equations : Finset (MvPolynomial (Fin n) ℤ))
    (degree : MvPolynomial (Fin n) ℤ → ℕ) (h : IntVector n)
    (hhom : ∀ f ∈ equations, f.IsHomogeneous (degree f))
    (hzero : ∀ f ∈ equations, MvPolynomial.eval h f = 0) :
    (fun i ↦ (h i : ℚ)) ∈
      equationFamilyRationalTangentKernel equations h := by
  rw [equationFamilyRationalTangentKernel, LinearMap.mem_ker]
  funext f
  change ∑ i, (MvPolynomial.eval h (MvPolynomial.pderiv i f.1) : ℚ) *
    (h i : ℚ) = 0
  have heuler := congrArg (MvPolynomial.eval h)
    (hhom f.1 f.2).sum_X_mul_pderiv
  have heulerZero :
      ∑ i, MvPolynomial.eval h (MvPolynomial.pderiv i f.1) * h i = 0 := by
    simpa [hzero f.1 f.2, nsmul_eq_mul, mul_comm] using heuler
  exact_mod_cast heulerZero

/-- Every rational linear combination of the base point and a full integral
line direction belongs to the affine cone over the projective tangent
space. -/
theorem rationalSpanPoint_mem_equationFamilyRationalTangentKernel
    {n : ℕ} (equations : Finset (MvPolynomial (Fin n) ℤ))
    (degree : MvPolynomial (Fin n) ℤ → ℕ) (h z : IntVector n)
    (hhom : ∀ f ∈ equations, f.IsHomogeneous (degree f))
    (hline : ∀ f ∈ equations, ∀ t : ℤ,
      MvPolynomial.eval (fun i ↦ h i + t * z i) f = 0)
    (a b : ℚ) :
    (fun i ↦ a * (h i : ℚ) + b * (z i : ℚ)) ∈
      equationFamilyRationalTangentKernel equations h := by
  let hℚ : Fin n → ℚ := fun i ↦ (h i : ℚ)
  let zℚ : Fin n → ℚ := fun i ↦ (z i : ℚ)
  have hh : hℚ ∈ equationFamilyRationalTangentKernel equations h :=
    intBasePoint_mem_equationFamilyRationalTangentKernel
      equations degree h hhom (fun f hf ↦ by simpa using hline f hf 0)
  have hz : zℚ ∈ equationFamilyRationalTangentKernel equations h :=
    intDirection_mem_equationFamilyRationalTangentKernel equations h z hline
  have hsum := (equationFamilyRationalTangentKernel equations h).add_mem
    ((equationFamilyRationalTangentKernel equations h).smul_mem a hh)
    ((equationFamilyRationalTangentKernel equations h).smul_mem b hz)
  simpa [hℚ, zℚ, Pi.smul_apply] using hsum

/-- The entire rational projective line generated by the base point and a
full integral line direction lies in the projective tangent space. -/
theorem rationalProjectiveLine_mem_equationFamilyRationalProjectiveTangentSpace
    {n : ℕ} (equations : Finset (MvPolynomial (Fin n) ℤ))
    (degree : MvPolynomial (Fin n) ℤ → ℕ) (h z : IntVector n)
    (hhom : ∀ f ∈ equations, f.IsHomogeneous (degree f))
    (hline : ∀ f ∈ equations, ∀ t : ℤ,
      MvPolynomial.eval (fun i ↦ h i + t * z i) f = 0)
    (a b : ℚ)
    (hv : (fun i ↦ a * (h i : ℚ) + b * (z i : ℚ)) ≠ 0) :
    Projectivization.mk ℚ
        (fun i ↦ a * (h i : ℚ) + b * (z i : ℚ)) hv ∈
      equationFamilyRationalProjectiveTangentSpace equations h := by
  rw [mk_mem_equationFamilyRationalProjectiveTangentSpace_iff]
  exact rationalSpanPoint_mem_equationFamilyRationalTangentKernel
    equations degree h z hhom hline a b

/-- The affine cone over the preceding projective tangent space has exact
dimension `n - rank(J_h)`. -/
theorem finrank_equationFamilyRationalProjectiveTangentCone
    {n : ℕ} (equations : Finset (MvPolynomial (Fin n) ℤ))
    (h : IntVector n) :
    Module.finrank ℚ
        (equationFamilyRationalTangentKernel equations h) =
      n - (equationFamilyRationalJacobianMatrix equations h).rank :=
  finrank_equationFamilyRationalTangentKernel equations h

/-! ## Containment in the original projective common zero locus -/

/-- The integral line-restriction identity remains valid at every rational
value of the line parameter after extending coefficients to `ℚ`. -/
theorem eval_map_linePolynomial_at_rat
    {n : ℕ} (f : MvPolynomial (Fin n) ℤ) (h z : IntVector n) (t : ℚ) :
    ((linePolynomial f h z).map (Int.castRingHom ℚ)).eval t =
      MvPolynomial.eval (fun i ↦ (h i : ℚ) + t * (z i : ℚ))
        (MvPolynomial.map (Int.castRingHom ℚ) f) := by
  induction f using MvPolynomial.induction_on with
  | C c => simp [linePolynomial]
  | add f g hf hg => simp [linePolynomial_add, hf, hg]
  | mul_X f i hf =>
      rw [linePolynomial_mul, Polynomial.map_mul, Polynomial.eval_mul, hf]
      simp [linePolynomial_X]

/-- Every rational point of the two-dimensional vector span of `h` and `z`
lies on all the original homogeneous equations, provided the integral affine
line `h + ℤ z` does. -/
theorem rationalSpanPoint_mem_integralAffineConeZeroSetOver
    {n : ℕ} (equations : Finset (MvPolynomial (Fin n) ℤ))
    (degree : MvPolynomial (Fin n) ℤ → ℕ) (h z : IntVector n)
    (hhom : ∀ f ∈ equations, f.IsHomogeneous (degree f))
    (hline : ∀ f ∈ equations, ∀ t : ℤ,
      MvPolynomial.eval (fun i ↦ h i + t * z i) f = 0)
    (a b : ℚ) :
    (fun i ↦ a * (h i : ℚ) + b * (z i : ℚ)) ∈
      integralAffineConeZeroSetOver ℚ equations := by
  intro f hf
  by_cases ha : a = 0
  · subst a
    have hzInt : z ∈ integralAffineConeZeroSet equations :=
      mem_integralAffineConeZeroSet_of_eval_line_zero
        equations degree hhom h z hline
    have hzℚ : (fun i ↦ (z i : ℚ)) ∈
        integralAffineConeZeroSetOver ℚ equations :=
      intCast_mem_integralAffineConeZeroSetOver equations hzInt
    have hscaled := smul_mem_integralAffineConeZeroSetOver
      equations degree hhom hzℚ b
    simpa using hscaled f hf
  · have hpoly : linePolynomial f h z = 0 :=
      Polynomial.zero_of_eval_zero _ fun t ↦ by
        rw [linePolynomial_eval]
        exact hline f hf t
    have hrat :
        MvPolynomial.eval
            (fun i ↦ (h i : ℚ) + (b / a) * (z i : ℚ))
            (MvPolynomial.map (Int.castRingHom ℚ) f) = 0 := by
      rw [← eval_map_linePolynomial_at_rat f h z (b / a), hpoly]
      simp
    have hfℚ :
        (MvPolynomial.map (Int.castRingHom ℚ) f).IsHomogeneous (degree f) :=
      (hhom f hf).map _
    have hvectors :
        (fun i ↦ a * (h i : ℚ) + b * (z i : ℚ)) =
          (fun i ↦ a * ((h i : ℚ) + (b / a) * (z i : ℚ))) := by
      funext i
      field_simp [ha]
    rw [hvectors, eval_smul_of_isHomogeneous
      (MvPolynomial.map (Int.castRingHom ℚ) f)
      (fun i ↦ (h i : ℚ) + (b / a) * (z i : ℚ)) a (degree f) hfℚ]
    rw [hrat, mul_zero]

/-- Hence the rational projective line generated by `h` and `z` lies in the
literal projectivized common zero locus of the original equations. -/
theorem rationalProjectiveLine_mem_integralProjectiveConeZeroSetOver
    {n : ℕ} (equations : Finset (MvPolynomial (Fin n) ℤ))
    (degree : MvPolynomial (Fin n) ℤ → ℕ) (h z : IntVector n)
    (hhom : ∀ f ∈ equations, f.IsHomogeneous (degree f))
    (hline : ∀ f ∈ equations, ∀ t : ℤ,
      MvPolynomial.eval (fun i ↦ h i + t * z i) f = 0)
    (a b : ℚ)
    (hv : (fun i ↦ a * (h i : ℚ) + b * (z i : ℚ)) ≠ 0) :
    Projectivization.mk ℚ
        (fun i ↦ a * (h i : ℚ) + b * (z i : ℚ)) hv ∈
      integralProjectiveConeZeroSetOver ℚ equations := by
  rw [mk_mem_integralProjectiveConeZeroSetOver_iff
    equations degree hhom _ hv]
  exact rationalSpanPoint_mem_integralAffineConeZeroSetOver
    equations degree h z hhom hline a b

end

end TranslatedDepthSeven
