import TranslatedDepthSeven.MultivariateHomogenization

/-!
# Homogenization of a finite equation family

This file applies the concrete multivariate homogenization construction to a
literal finite set of equations, all at one common target degree.  It proves
the exact affine-chart common-zero identity and records its elementary ideal-
theoretic form.
-/

namespace TranslatedDepthSeven

noncomputable section

open scoped LinearAlgebra.Projectivization

open MvPolynomial Finset

universe u v

variable {R : Type u} {σ : Type v} [CommSemiring R]

/-- Homogenize every equation in a finite family at the same target degree.
The use of `Finset.image` makes this a literal finite equation family. -/
def finiteFamilyHomogenization
    (equations : Finset (MvPolynomial σ R)) (d : ℕ) :
    Finset (MvPolynomial (Option σ) R) := by
  classical
  exact equations.image fun f ↦ multivariateHomogenization f d

/-- Apply dehomogenization to every member of a finite homogeneous-coordinate
equation family. -/
def finiteFamilyDehomogenization
    (equations : Finset (MvPolynomial (Option σ) R)) :
    Finset (MvPolynomial σ R) := by
  classical
  exact equations.image multivariateDehomogenization

/-- The affine common zero locus of a literal finite family. -/
def finiteAffineCommonZeroLocus
    (equations : Finset (MvPolynomial σ R)) : Set (σ → R) :=
  {z | ∀ f ∈ equations, eval z f = 0}

@[simp]
theorem mem_finiteAffineCommonZeroLocus_iff
    (equations : Finset (MvPolynomial σ R)) (z : σ → R) :
    z ∈ finiteAffineCommonZeroLocus equations ↔
      ∀ f ∈ equations, eval z f = 0 :=
  Iff.rfl

/-- All members of the common-degree homogenized family are homogeneous of
that common degree. -/
theorem finiteFamilyHomogenization_isHomogeneous
    (equations : Finset (MvPolynomial σ R)) (d : ℕ)
    {g : MvPolynomial (Option σ) R}
    (hg : g ∈ finiteFamilyHomogenization equations d) :
    g.IsHomogeneous d := by
  classical
  obtain ⟨f, _, rfl⟩ := Finset.mem_image.mp hg
  exact multivariateHomogenization_isHomogeneous f d

/-- If `d` dominates the total degree of every original equation, applying
dehomogenization to the finite homogenized family recovers that family
exactly. -/
theorem image_dehomogenization_finiteFamilyHomogenization
    (equations : Finset (MvPolynomial σ R)) (d : ℕ)
    (hdegree : ∀ f ∈ equations, f.totalDegree ≤ d) :
    finiteFamilyDehomogenization
      (finiteFamilyHomogenization equations d) = equations := by
  classical
  unfold finiteFamilyDehomogenization
  ext f
  constructor
  · intro hf
    obtain ⟨g, hg, hgf⟩ := Finset.mem_image.mp hf
    obtain ⟨p, hp, hpg⟩ := Finset.mem_image.mp hg
    subst g
    have hrecover := multivariateDehomogenization_homogenization
      p d (hdegree p hp)
    have hpf : p = f := hrecover.symm.trans hgf
    simpa [hpf] using hp
  · intro hf
    refine Finset.mem_image.mpr ⟨multivariateHomogenization f d, ?_, ?_⟩
    · exact Finset.mem_image.mpr ⟨f, hf, rfl⟩
    · exact multivariateDehomogenization_homogenization f d (hdegree f hf)

variable {K : Type u} [Field K]

/-- The projective common zero locus of a literal finite homogeneous
equation family. -/
def finiteProjectiveCommonZeroLocus
    (equations : Finset (MvPolynomial (Option σ) K)) :
    Set (ℙ K (Option σ → K)) :=
  {P | ∀ g ∈ equations, P ∈ homogeneousProjectiveHypersurface g}

@[simp]
theorem mem_finiteProjectiveCommonZeroLocus_iff
    (equations : Finset (MvPolynomial (Option σ) K))
    (P : ℙ K (Option σ → K)) :
    P ∈ finiteProjectiveCommonZeroLocus equations ↔
      ∀ g ∈ equations, P ∈ homogeneousProjectiveHypersurface g :=
  Iff.rfl

/-- On the standard affine chart, simultaneous vanishing of all the
homogenized equations is exactly simultaneous vanishing of the original
affine equations. -/
theorem affineChartPoint_mem_finiteProjectiveCommonZeroLocus_homogenization_iff
    (equations : Finset (MvPolynomial σ K)) (d : ℕ)
    (hdegree : ∀ f ∈ equations, f.totalDegree ≤ d)
    (z : σ → K) :
    affineChartPoint z ∈ finiteProjectiveCommonZeroLocus
        (finiteFamilyHomogenization equations d) ↔
      z ∈ finiteAffineCommonZeroLocus equations := by
  classical
  constructor
  · intro hz f hf
    have hh : multivariateHomogenization f d ∈
        finiteFamilyHomogenization equations d :=
      Finset.mem_image.mpr ⟨f, hf, rfl⟩
    exact
      (affineChartPoint_mem_homogeneousProjectiveHypersurface_homogenization_iff
        f d (hdegree f hf) z).mp (hz _ hh)
  · intro hz g hg
    obtain ⟨f, hf, rfl⟩ := Finset.mem_image.mp hg
    exact
      (affineChartPoint_mem_homogeneousProjectiveHypersurface_homogenization_iff
        f d (hdegree f hf) z).mpr (hz f hf)

/-- The ideal generated by a literal finite equation family. -/
def finiteEquationIdeal
    (equations : Finset (MvPolynomial σ K)) :
    Ideal (MvPolynomial σ K) :=
  Ideal.span (equations : Set (MvPolynomial σ K))

/-- The affine zero locus of an ideal, stated directly in terms of
evaluation. -/
def affineIdealZeroLocus
    (I : Ideal (MvPolynomial σ K)) : Set (σ → K) :=
  {z | ∀ g ∈ I, eval z g = 0}

@[simp]
theorem mem_affineIdealZeroLocus_iff
    (I : Ideal (MvPolynomial σ K)) (z : σ → K) :
    z ∈ affineIdealZeroLocus I ↔ ∀ g ∈ I, eval z g = 0 :=
  Iff.rfl

/-- The zero locus of the ideal generated by a finite equation family is
exactly its literal common zero locus. -/
theorem affineIdealZeroLocus_finiteEquationIdeal
    (equations : Finset (MvPolynomial σ K)) :
    affineIdealZeroLocus (finiteEquationIdeal equations) =
      finiteAffineCommonZeroLocus equations := by
  ext z
  constructor
  · intro hz f hf
    exact hz f (Ideal.subset_span hf)
  · intro hz g hg
    let J : Ideal (MvPolynomial σ K) := RingHom.ker (eval z)
    have hspan : finiteEquationIdeal equations ≤ J := by
      apply Ideal.span_le.mpr
      intro f hf
      change eval z f = 0
      exact hz f hf
    have hgJ : g ∈ J := hspan hg
    exact (RingHom.mem_ker.mp hgJ)

/-- At ideal level as well, dehomogenization carries the ideal generated by
the common-degree homogenized family exactly onto the ideal generated by the
original affine equations. -/
theorem map_finiteEquationIdeal_homogenization_eq
    (equations : Finset (MvPolynomial σ K)) (d : ℕ)
    (hdegree : ∀ f ∈ equations, f.totalDegree ≤ d) :
    (finiteEquationIdeal (finiteFamilyHomogenization equations d)).map
        multivariateDehomogenization.toRingHom =
      finiteEquationIdeal equations := by
  classical
  rw [finiteEquationIdeal, Ideal.map_span]
  change Ideal.span
      (multivariateDehomogenization ''
        (finiteFamilyHomogenization equations d :
          Set (MvPolynomial (Option σ) K))) = _
  rw [← Finset.coe_image]
  change Ideal.span
      (finiteFamilyDehomogenization
        (finiteFamilyHomogenization equations d) :
          Set (MvPolynomial σ K)) = _
  rw [image_dehomogenization_finiteFamilyHomogenization equations d hdegree]
  rfl

end

end TranslatedDepthSeven
