import TranslatedDepthSeven.FiniteFamilyIntersections
import Mathlib.RingTheory.Spectrum.Prime.Noetherian

/-!
# Finite minimal-prime component lists for literal equation families

This file attaches Mathlib's actual minimal primes to the ideals generated by
the finite equation families used elsewhere in the project.  In a Noetherian
polynomial ring the list is finite.  Its members are prime ideals containing
the displayed equations, distinct members are incomparable, and adjoining a
second equation family means taking minimal primes over the literal supremum
of the two generated ideals.

These are algebraic component identities only.  No projective saturation,
homogeneity of minimal primes, dimension, or degree assertion is made here.
-/

namespace TranslatedDepthSeven

noncomputable section

open Finset MvPolynomial

universe u v

variable {R : Type u} [CommRing R] [IsNoetherianRing R]

/-- The finite list of minimal primes over an ideal in a Noetherian ring. -/
def finiteMinimalPrimes (I : Ideal R) : Finset (Ideal R) :=
  I.finite_minimalPrimes_of_isNoetherianRing.toFinset

@[simp]
theorem mem_finiteMinimalPrimes_iff (I P : Ideal R) :
    P ∈ finiteMinimalPrimes I ↔ P ∈ I.minimalPrimes := by
  simp [finiteMinimalPrimes]

/-- Every member of the finite component list is prime. -/
theorem isPrime_of_mem_finiteMinimalPrimes {I P : Ideal R}
    (hP : P ∈ finiteMinimalPrimes I) : P.IsPrime :=
  Ideal.minimalPrimes_isPrime
    ((mem_finiteMinimalPrimes_iff I P).mp hP)

/-- Every member of the finite component list contains the original ideal. -/
theorem le_of_mem_finiteMinimalPrimes {I P : Ideal R}
    (hP : P ∈ finiteMinimalPrimes I) : I ≤ P :=
  ((mem_finiteMinimalPrimes_iff I P).mp hP).1.2

/-- Every prime containing `I` contains a member of the finite component
list.  This is the exact algebraic covering property used when passing from
an equation family to its irreducible components. -/
theorem exists_finiteMinimalPrime_le {I P : Ideal R} [P.IsPrime]
    (hIP : I ≤ P) :
    ∃ Q ∈ finiteMinimalPrimes I, Q ≤ P := by
  obtain ⟨Q, hQ, hQP⟩ := Ideal.exists_minimalPrimes_le hIP
  exact ⟨Q, (mem_finiteMinimalPrimes_iff I Q).mpr hQ, hQP⟩

/-- Distinct minimal primes over one ideal are incomparable. -/
theorem finiteMinimalPrimes_eq_of_le {I P Q : Ideal R}
    (hP : P ∈ finiteMinimalPrimes I)
    (hQ : Q ∈ finiteMinimalPrimes I)
    (hPQ : P ≤ Q) : P = Q := by
  have hQmin := (mem_finiteMinimalPrimes_iff I Q).mp hQ
  have hPprop : P.IsPrime ∧ I ≤ P :=
    ⟨isPrime_of_mem_finiteMinimalPrimes hP,
      le_of_mem_finiteMinimalPrimes hP⟩
  exact le_antisymm hPQ (hQmin.2 hPprop hPQ)

/-- For distinct components the ideal defining their intersection strictly
contains either component ideal.  The later dimension-drop argument may use
this statement without any informal appeal to a component ordering. -/
theorem lt_sup_of_distinct_finiteMinimalPrimes {I P Q : Ideal R}
    (hP : P ∈ finiteMinimalPrimes I)
    (hQ : Q ∈ finiteMinimalPrimes I)
    (hne : P ≠ Q) :
    P < P ⊔ Q ∧ Q < P ⊔ Q := by
  constructor
  · refine lt_of_le_of_ne le_sup_left ?_
    intro heq
    apply hne
    symm
    apply finiteMinimalPrimes_eq_of_le hQ hP
    rw [heq]
    exact le_sup_right
  · refine lt_of_le_of_ne le_sup_right ?_
    intro heq
    apply hne
    apply finiteMinimalPrimes_eq_of_le hP hQ
    rw [heq]
    exact le_sup_left

variable {K : Type v} [Field K] {σ : Type*} [Fintype σ]

/-- The finite algebraic component list attached to a literal finite
polynomial equation family. -/
def finiteEquationMinimalPrimes
    (equations : Finset (MvPolynomial σ K)) :
    Finset (Ideal (MvPolynomial σ K)) :=
  finiteMinimalPrimes (finiteEquationIdeal equations)

@[simp]
theorem mem_finiteEquationMinimalPrimes_iff
    (equations : Finset (MvPolynomial σ K))
    (P : Ideal (MvPolynomial σ K)) :
    P ∈ finiteEquationMinimalPrimes equations ↔
      P ∈ (finiteEquationIdeal equations).minimalPrimes := by
  simp [finiteEquationMinimalPrimes]

/-- A component of the union equation family is exactly a minimal prime over
the supremum of the two generated ideals. -/
theorem mem_finiteEquationMinimalPrimes_union_iff
    (equations₁ equations₂ : Finset (MvPolynomial σ K))
    (P : Ideal (MvPolynomial σ K)) :
    P ∈ finiteEquationMinimalPrimes
        (finiteEquationFamilyUnion equations₁ equations₂) ↔
      P ∈ (finiteEquationIdeal equations₁ ⊔
        finiteEquationIdeal equations₂).minimalPrimes := by
  rw [mem_finiteEquationMinimalPrimes_iff, finiteEquationIdeal_union]

/-- Every prime containing all equations from both families contains one of
the finitely many minimal-prime components of their literal intersection. -/
theorem exists_union_component_le
    (equations₁ equations₂ : Finset (MvPolynomial σ K))
    (P : Ideal (MvPolynomial σ K)) [P.IsPrime]
    (h₁ : finiteEquationIdeal equations₁ ≤ P)
    (h₂ : finiteEquationIdeal equations₂ ≤ P) :
    ∃ Q ∈ finiteEquationMinimalPrimes
        (finiteEquationFamilyUnion equations₁ equations₂), Q ≤ P := by
  change ∃ Q ∈ finiteMinimalPrimes
    (finiteEquationIdeal
      (finiteEquationFamilyUnion equations₁ equations₂)), Q ≤ P
  apply exists_finiteMinimalPrime_le
  rw [finiteEquationIdeal_union]
  exact sup_le h₁ h₂

end

end TranslatedDepthSeven
