import Mathlib.RingTheory.Localization.FractionRing
import Mathlib.RingTheory.IntegralClosure.IntegrallyClosed
import Mathlib.LinearAlgebra.FiniteDimensional.Basic

/-!
# Finite birational extensions of normal domains

This file isolates the elementary algebra behind the implication
``degree one implies linear'' when projective degree is computed by a finite
linear Noether normalization.  If an integral extension of domains has
fraction-field degree one and the base is integrally closed, then the
extension is already trivial.

There is no geometric degree definition in this statement.  In the intended
application the base is a polynomial ring generated by homogeneous linear
forms, and the displayed fraction-field finrank is the degree of that finite
linear projection.
-/

namespace TranslatedDepthSeven

noncomputable section

open scoped nonZeroDivisors

universe u v

/-- A displayed `D`-element spanning family for a finite extension of
domains bounds the degree of the induced fraction-field extension by `D`.

This is the upper-bound companion to the rank-one rigidity theorem below.
It uses only localization of the displayed spanning identity. -/
theorem fractionRing_finrank_le_of_span_fin
    {R : Type u} {A : Type v}
    [CommRing R] [IsDomain R]
    [CommRing A] [IsDomain A] [Algebra R A]
    [NoZeroSMulDivisors R A] [Module.Finite R A]
    {D : ℕ} (s : Fin D → A)
    (hs : Submodule.span R (Set.range s) = ⊤) :
    letI : Algebra (FractionRing R) (FractionRing A) :=
      FractionRing.liftAlgebra R (FractionRing A)
    Module.finrank (FractionRing R) (FractionRing A) ≤ D := by
  letI : Algebra (FractionRing R) (FractionRing A) :=
    FractionRing.liftAlgebra R (FractionRing A)
  letI : IsScalarTower R (FractionRing R) (FractionRing A) :=
    FractionRing.isScalarTower_liftAlgebra R (FractionRing A)
  have hspan :
      Submodule.span (FractionRing R)
          (algebraMap A (FractionRing A) '' Set.range s) = ⊤ :=
    span_eq_top_localization_localization
      (FractionRing R) R⁰ (FractionRing A) hs
  have himage :
      algebraMap A (FractionRing A) '' Set.range s =
        Set.range (fun i : Fin D ↦ algebraMap A (FractionRing A) (s i)) := by
    ext x
    constructor
    · rintro ⟨_, ⟨i, rfl⟩, rfl⟩
      exact ⟨i, rfl⟩
    · rintro ⟨i, rfl⟩
      exact ⟨s i, ⟨i, rfl⟩, rfl⟩
  rw [himage] at hspan
  simpa using finrank_le_of_span_eq_top hspan

/-- An integral extension of an integrally closed domain is trivial if its
induced fraction-field extension has finrank one. -/
theorem algebraMap_surjective_of_fractionRing_finrank_eq_one
    {R : Type u} {A : Type v}
    [CommRing R] [IsDomain R] [IsIntegrallyClosed R]
    [CommRing A] [IsDomain A] [Algebra R A]
    [NoZeroSMulDivisors R A] [Algebra.IsIntegral R A]
    (hdegree :
      letI : Algebra (FractionRing R) (FractionRing A) :=
        FractionRing.liftAlgebra R (FractionRing A)
      Module.finrank (FractionRing R) (FractionRing A) = 1) :
    Function.Surjective (algebraMap R A) := by
  letI : Algebra (FractionRing R) (FractionRing A) :=
    FractionRing.liftAlgebra R (FractionRing A)
  letI : IsScalarTower R (FractionRing R) (FractionRing A) :=
    FractionRing.isScalarTower_liftAlgebra R (FractionRing A)
  intro a
  have hsurjective :
      Function.Surjective
        (algebraMap (FractionRing R) (FractionRing A)) := by
    have hspan :=
      (finrank_eq_one_iff_of_nonzero'
        (1 : FractionRing A) one_ne_zero).mp hdegree
    intro z
    obtain ⟨k, hk⟩ := hspan z
    refine ⟨k, ?_⟩
    simpa [Algebra.smul_def] using hk
  obtain ⟨k, hk⟩ := hsurjective (algebraMap A (FractionRing A) a)
  have hkIntegral : IsIntegral R k := by
    rw [← isIntegral_algHom_iff
      (IsScalarTower.toAlgHom R (FractionRing R) (FractionRing A))
      (FaithfulSMul.algebraMap_injective
        (FractionRing R) (FractionRing A))]
    change IsIntegral R
      ((algebraMap (FractionRing R) (FractionRing A)) k)
    rw [hk]
    exact (Algebra.IsIntegral.isIntegral a).map
      (IsScalarTower.toAlgHom R A (FractionRing A))
  obtain ⟨r, hr⟩ := IsIntegrallyClosed.isIntegral_iff.mp hkIntegral
  refine ⟨r, (IsFractionRing.injective A (FractionRing A)) ?_⟩
  calc
    algebraMap A (FractionRing A) (algebraMap R A r) =
        algebraMap R (FractionRing A) r :=
      IsScalarTower.algebraMap_apply R A (FractionRing A) r
    _ = algebraMap (FractionRing R) (FractionRing A)
          (algebraMap R (FractionRing R) r) :=
      IsScalarTower.algebraMap_apply R (FractionRing R)
        (FractionRing A) r
    _ = algebraMap (FractionRing R) (FractionRing A) k := by rw [hr]
    _ = algebraMap A (FractionRing A) a := hk

/-- Consequently, a nontrivial finite normalization has fraction-field
finrank at least two.  Positivity is stated explicitly, since Mathlib's
`finrank` is zero for an infinite-dimensional extension. -/
theorem two_le_fractionRing_finrank_of_not_surjective
    {R : Type u} {A : Type v}
    [CommRing R] [IsDomain R] [IsIntegrallyClosed R]
    [CommRing A] [IsDomain A] [Algebra R A]
    [NoZeroSMulDivisors R A] [Algebra.IsIntegral R A]
    [Module.Finite R A]
    (hnonsurjective : ¬ Function.Surjective (algebraMap R A)) :
    letI : Algebra (FractionRing R) (FractionRing A) :=
      FractionRing.liftAlgebra R (FractionRing A)
    2 ≤ Module.finrank (FractionRing R) (FractionRing A) := by
  letI : Algebra (FractionRing R) (FractionRing A) :=
    FractionRing.liftAlgebra R (FractionRing A)
  have hne : Module.finrank (FractionRing R) (FractionRing A) ≠ 1 := by
    intro hdegree
    exact hnonsurjective
      (algebraMap_surjective_of_fractionRing_finrank_eq_one hdegree)
  have hpositive :
      0 < Module.finrank (FractionRing R) (FractionRing A) :=
    Module.finrank_pos
  omega

end

end TranslatedDepthSeven
