import TranslatedDepthSeven.FiniteEquationMinimalComponents
import Mathlib.FieldTheory.IntermediateField.Adjoin.Basic
import Mathlib.RingTheory.Polynomial.Basic

/-!
# Finite coefficient descent of a polynomial ideal

A finite family of polynomials over an algebraic extension `L/K` involves
only finitely many coefficients.  Adjoining those coefficients to `K`
gives a finite-dimensional intermediate field.  This file constructs the
polynomials over that literal intermediate field and proves that mapping
their coefficients back to `L` recovers the original family.

The final theorem applies Noetherian finite generation to one actual ideal
of a polynomial ring and produces a finite equation family over a finite
intermediate field whose coefficient extension generates the given ideal.
-/

namespace TranslatedDepthSeven

noncomputable section

open MvPolynomial

universe u v w

variable {K : Type u} {L : Type v} {σ : Type w}
  [Field K] [Field L] [Algebra K L]

/-- The literal finite set of all nonzero coefficients occurring in a
finite indexed polynomial family. -/
noncomputable def finitePolynomialFamilyCoefficients {n : ℕ}
    (f : Fin n → MvPolynomial σ L) : Finset L := by
  classical
  exact Finset.univ.biUnion fun i ↦ (f i).coeffs

/-- The intermediate field obtained by adjoining all coefficients of the
given finite polynomial family. -/
def finitePolynomialFamilyCoefficientField {n : ℕ}
    (K : Type u) [Field K] [Algebra K L]
    (f : Fin n → MvPolynomial σ L) : IntermediateField K L :=
  IntermediateField.adjoin K
    (finitePolynomialFamilyCoefficients f : Set L)

/-- Every coefficient of the family belongs to its coefficient field.
This includes zero coefficients, which need not occur in `coeffs`. -/
theorem coeff_mem_finitePolynomialFamilyCoefficientField {n : ℕ}
    (f : Fin n → MvPolynomial σ L) (i : Fin n) (m : σ →₀ ℕ) :
    coeff m (f i) ∈ finitePolynomialFamilyCoefficientField K f := by
  classical
  by_cases hzero : coeff m (f i) = 0
  · rw [hzero]
    exact (finitePolynomialFamilyCoefficientField K f).zero_mem
  · have hmem :
        coeff m (f i) ∈ finitePolynomialFamilyCoefficients f := by
      rw [finitePolynomialFamilyCoefficients, Finset.mem_biUnion]
      exact ⟨i, Finset.mem_univ i, coeff_mem_coeffs m hzero⟩
    exact IntermediateField.subset_adjoin K
      (finitePolynomialFamilyCoefficients f : Set L) hmem

/-- Algebraicity of `L/K` makes the field generated by the finite
coefficient set finite-dimensional over `K`. -/
theorem finiteDimensional_finitePolynomialFamilyCoefficientField
    [Algebra.IsAlgebraic K L] {n : ℕ}
    (f : Fin n → MvPolynomial σ L) :
    FiniteDimensional K (finitePolynomialFamilyCoefficientField K f) := by
  apply IntermediateField.finiteDimensional_adjoin
  intro x _hx
  exact (Algebra.IsAlgebraic.isAlgebraic x).isIntegral

/-- Rewrite a polynomial over an intermediate field which contains all of
its coefficients.  The construction is the literal finite monomial sum. -/
def polynomialOverIntermediateField
    (E : IntermediateField K L) (p : MvPolynomial σ L)
    (hcoeff : ∀ m, coeff m p ∈ E) : MvPolynomial σ E :=
  ∑ m ∈ p.support, monomial m ⟨coeff m p, hcoeff m⟩

/-- Mapping the coefficient-restricted polynomial back to `L` recovers the
original polynomial exactly. -/
theorem map_polynomialOverIntermediateField
    (E : IntermediateField K L) (p : MvPolynomial σ L)
    (hcoeff : ∀ m, coeff m p ∈ E) :
    MvPolynomial.map E.val
        (polynomialOverIntermediateField E p hcoeff) = p := by
  rw [polynomialOverIntermediateField]
  simp only [map_sum, MvPolynomial.map_monomial]
  exact (MvPolynomial.as_sum p).symm

/-- The finite polynomial family obtained by restricting every coefficient
to the literal field generated by all coefficients. -/
def descendedPolynomialFamily {n : ℕ}
    (f : Fin n → MvPolynomial σ L) :
    Fin n → MvPolynomial σ (finitePolynomialFamilyCoefficientField K f) :=
  fun i ↦ polynomialOverIntermediateField
    (finitePolynomialFamilyCoefficientField K f) (f i)
    (coeff_mem_finitePolynomialFamilyCoefficientField f i)

/-- Coefficient extension of each descended polynomial is the original
polynomial. -/
theorem map_descendedPolynomialFamily {n : ℕ}
    (f : Fin n → MvPolynomial σ L) (i : Fin n) :
    MvPolynomial.map (finitePolynomialFamilyCoefficientField K f).val
        (descendedPolynomialFamily (K := K) f i) = f i := by
  exact map_polynomialOverIntermediateField
    (finitePolynomialFamilyCoefficientField K f) (f i)
    (coeff_mem_finitePolynomialFamilyCoefficientField f i)

/-- A literal finite equation family over the coefficient field. -/
noncomputable def descendedPolynomialEquations {n : ℕ}
    (f : Fin n → MvPolynomial σ L) :
    Finset (MvPolynomial σ (finitePolynomialFamilyCoefficientField K f)) := by
  classical
  exact Finset.univ.image (descendedPolynomialFamily (K := K) f)

/-- The ideal generated by the descended finite equation family extends to
the ideal spanned by the original indexed family. -/
theorem map_finiteEquationIdeal_descendedPolynomialEquations {n : ℕ}
    (f : Fin n → MvPolynomial σ L) :
    Ideal.map
        (MvPolynomial.map
          (finitePolynomialFamilyCoefficientField K f).val)
        (finiteEquationIdeal
          (descendedPolynomialEquations (K := K) f)) =
      Ideal.span (Set.range f) := by
  classical
  rw [finiteEquationIdeal, Ideal.map_span]
  congr 1
  ext p
  constructor
  · rintro ⟨q, hq, rfl⟩
    rw [Finset.mem_coe, descendedPolynomialEquations,
      Finset.mem_image] at hq
    obtain ⟨i, _hi, rfl⟩ := hq
    exact ⟨i, (map_descendedPolynomialFamily f i).symm⟩
  · rintro ⟨i, rfl⟩
    refine ⟨descendedPolynomialFamily (K := K) f i, ?_,
      map_descendedPolynomialFamily f i⟩
    rw [Finset.mem_coe, descendedPolynomialEquations,
      Finset.mem_image]
    exact ⟨i, Finset.mem_univ i, rfl⟩

/-- Finite coefficient descent for one actual ideal.  For a polynomial
ideal `P` over an algebraic extension `L/K`, this constructs a finite-
dimensional intermediate field `E/K` and a finite family of equations over
`E` whose generated ideal extends coefficientwise to `P` over `L`. -/
theorem exists_finiteIntermediateField_finiteEquations_map_ideal_eq
    [Algebra.IsAlgebraic K L] [Fintype σ]
    (P : Ideal (MvPolynomial σ L)) :
    ∃ E : IntermediateField K L,
      FiniteDimensional K E ∧
      ∃ equations : Finset (MvPolynomial σ E),
        Ideal.map (MvPolynomial.map E.val)
            (finiteEquationIdeal equations) = P := by
  have hPfg : P.FG := IsNoetherian.noetherian P
  obtain ⟨n, f, hf⟩ :=
    Submodule.fg_iff_exists_fin_generating_family.mp hPfg
  let E : IntermediateField K L :=
    finitePolynomialFamilyCoefficientField K f
  have hEfinite : FiniteDimensional K E :=
    finiteDimensional_finitePolynomialFamilyCoefficientField f
  refine ⟨E, hEfinite,
    descendedPolynomialEquations (K := K) f, ?_⟩
  change Ideal.map
      (MvPolynomial.map
        (finitePolynomialFamilyCoefficientField K f).val)
      (finiteEquationIdeal
        (descendedPolynomialEquations (K := K) f)) = P
  rw [map_finiteEquationIdeal_descendedPolynomialEquations]
  exact hf

end

end TranslatedDepthSeven
