import TranslatedDepthSeven.HomogeneousIdealBridge

/-!
# Static intersection identities for finite equation families

This file records the elementary algebraic and point-set identities attached
to the union of two literal finite polynomial families.  It treats generated
ideals, affine common zero loci, and projective common zero loci of homogeneous
families.  It makes no scheme-theoretic, saturation, degree, dimension,
component, or irreducibility assertion.
-/

namespace TranslatedDepthSeven

noncomputable section

open scoped LinearAlgebra.Projectivization

open MvPolynomial Finset

universe u v

variable {K : Type u} {σ : Type v} [Field K]

/-- The literal finite union of two equation families, with the classical
decidable equality needed by `Finset.union` encapsulated in the definition. -/
def finiteEquationFamilyUnion
    {τ : Type*} {R : Type*} [CommSemiring R]
    (equations₁ equations₂ : Finset (MvPolynomial τ R)) :
    Finset (MvPolynomial τ R) := by
  classical
  exact equations₁ ∪ equations₂

@[simp]
theorem mem_finiteEquationFamilyUnion
    {τ : Type*} {R : Type*} [CommSemiring R]
    (equations₁ equations₂ : Finset (MvPolynomial τ R))
    (f : MvPolynomial τ R) :
    f ∈ finiteEquationFamilyUnion equations₁ equations₂ ↔
      f ∈ equations₁ ∨ f ∈ equations₂ := by
  classical
  unfold finiteEquationFamilyUnion
  exact Finset.mem_union

/-- The ideal generated by the union of two finite equation families is the
supremum of the two generated ideals. -/
theorem finiteEquationIdeal_union
    (equations₁ equations₂ : Finset (MvPolynomial σ K)) :
    finiteEquationIdeal
        (finiteEquationFamilyUnion equations₁ equations₂) =
      finiteEquationIdeal equations₁ ⊔ finiteEquationIdeal equations₂ := by
  classical
  unfold finiteEquationIdeal finiteEquationFamilyUnion
  rw [Finset.coe_union, Ideal.span_union]

/-- Simultaneous affine vanishing of the union is exactly simultaneous
membership in both affine common zero loci. -/
theorem finiteAffineCommonZeroLocus_union
    (equations₁ equations₂ : Finset (MvPolynomial σ K)) :
    finiteAffineCommonZeroLocus
        (finiteEquationFamilyUnion equations₁ equations₂) =
      finiteAffineCommonZeroLocus equations₁ ∩
        finiteAffineCommonZeroLocus equations₂ := by
  classical
  ext z
  change
    (∀ f ∈ finiteEquationFamilyUnion equations₁ equations₂,
      eval z f = 0) ↔
      (∀ f ∈ equations₁, eval z f = 0) ∧
        ∀ f ∈ equations₂, eval z f = 0
  constructor
  · intro hz
    constructor
    · intro f hf
      exact hz f ((mem_finiteEquationFamilyUnion equations₁ equations₂ f).2
        (Or.inl hf))
    · intro f hf
      exact hz f ((mem_finiteEquationFamilyUnion equations₁ equations₂ f).2
        (Or.inr hf))
  · rintro ⟨hz₁, hz₂⟩ f hf
    rcases (mem_finiteEquationFamilyUnion equations₁ equations₂ f).1 hf with hf | hf
    · exact hz₁ f hf
    · exact hz₂ f hf

/-- The same point-set identity for actual projective points and literal
finite projective common zero loci. -/
theorem finiteProjectiveCommonZeroLocus_union
    (equations₁ equations₂ :
      Finset (MvPolynomial (Option σ) K)) :
    finiteProjectiveCommonZeroLocus
        (finiteEquationFamilyUnion equations₁ equations₂) =
      finiteProjectiveCommonZeroLocus equations₁ ∩
        finiteProjectiveCommonZeroLocus equations₂ := by
  classical
  ext P
  change
    (∀ f ∈ finiteEquationFamilyUnion equations₁ equations₂,
      P ∈ homogeneousProjectiveHypersurface f) ↔
      (∀ f ∈ equations₁, P ∈ homogeneousProjectiveHypersurface f) ∧
        ∀ f ∈ equations₂, P ∈ homogeneousProjectiveHypersurface f
  constructor
  · intro hP
    constructor
    · intro f hf
      exact hP f ((mem_finiteEquationFamilyUnion equations₁ equations₂ f).2
        (Or.inl hf))
    · intro f hf
      exact hP f ((mem_finiteEquationFamilyUnion equations₁ equations₂ f).2
        (Or.inr hf))
  · rintro ⟨hP₁, hP₂⟩ f hf
    rcases (mem_finiteEquationFamilyUnion equations₁ equations₂ f).1 hf with hf | hf
    · exact hP₁ f hf
    · exact hP₂ f hf

local instance mvPolynomialStandardGradedAlgebraIntersections :
    GradedAlgebra (MvPolynomial.homogeneousSubmodule (Option σ) K) :=
  MvPolynomial.gradedAlgebra

/-- If both displayed families are individually homogeneous, so is every
member of their finite union. -/
theorem finiteEquationFamilyUnion_each_isHomogeneous
    (equations₁ equations₂ :
      Finset (MvPolynomial (Option σ) K))
    (hhom₁ : ∀ f ∈ equations₁, ∃ d : ℕ, f.IsHomogeneous d)
    (hhom₂ : ∀ f ∈ equations₂, ∃ d : ℕ, f.IsHomogeneous d)
    {g : MvPolynomial (Option σ) K}
    (hg : g ∈ finiteEquationFamilyUnion equations₁ equations₂) :
    ∃ d : ℕ, g.IsHomogeneous d := by
  classical
  rcases (mem_finiteEquationFamilyUnion equations₁ equations₂ g).1 hg with hg | hg
  · exact hhom₁ g hg
  · exact hhom₂ g hg

/-- At the level of Mathlib's actual homogeneous ideals, the homogeneous
ideal generated by the union is the supremum of the two generated
homogeneous ideals. -/
theorem finiteHomogeneousEquationIdeal_union
    (equations₁ equations₂ :
      Finset (MvPolynomial (Option σ) K))
    (hhom₁ : ∀ f ∈ equations₁, ∃ d : ℕ, f.IsHomogeneous d)
    (hhom₂ : ∀ f ∈ equations₂, ∃ d : ℕ, f.IsHomogeneous d) :
    finiteHomogeneousEquationIdeal
        (finiteEquationFamilyUnion equations₁ equations₂)
        (fun _g hg ↦ finiteEquationFamilyUnion_each_isHomogeneous
          equations₁ equations₂ hhom₁ hhom₂ hg) =
      finiteHomogeneousEquationIdeal equations₁ hhom₁ ⊔
        finiteHomogeneousEquationIdeal equations₂ hhom₂ := by
  apply HomogeneousIdeal.ext
  rw [finiteHomogeneousEquationIdeal_toIdeal]
  rw [HomogeneousIdeal.toIdeal_sup]
  rw [finiteHomogeneousEquationIdeal_toIdeal]
  rw [finiteHomogeneousEquationIdeal_toIdeal]
  exact finiteEquationIdeal_union equations₁ equations₂

/-- Consequently, the representative-defined projective zero locus of the
homogeneous ideal generated by the union is exactly the intersection of the
two representative-defined projective zero loci. -/
theorem projectiveHomogeneousIdealZeroLocus_union
    (equations₁ equations₂ :
      Finset (MvPolynomial (Option σ) K))
    (hhom₁ : ∀ f ∈ equations₁, ∃ d : ℕ, f.IsHomogeneous d)
    (hhom₂ : ∀ f ∈ equations₂, ∃ d : ℕ, f.IsHomogeneous d) :
    projectiveHomogeneousIdealZeroLocus
        (finiteHomogeneousEquationIdeal
          (finiteEquationFamilyUnion equations₁ equations₂)
          (fun _g hg ↦ finiteEquationFamilyUnion_each_isHomogeneous
            equations₁ equations₂ hhom₁ hhom₂ hg)) =
      projectiveHomogeneousIdealZeroLocus
          (finiteHomogeneousEquationIdeal equations₁ hhom₁) ∩
        projectiveHomogeneousIdealZeroLocus
          (finiteHomogeneousEquationIdeal equations₂ hhom₂) := by
  rw [projectiveHomogeneousIdealZeroLocus_finiteHomogeneousEquationIdeal]
  rw [projectiveHomogeneousIdealZeroLocus_finiteHomogeneousEquationIdeal]
  rw [projectiveHomogeneousIdealZeroLocus_finiteHomogeneousEquationIdeal]
  exact finiteProjectiveCommonZeroLocus_union equations₁ equations₂

end

end TranslatedDepthSeven
