import TranslatedDepthSeven.GaloisConjugateZeroLocus

/-!
# Static equation-family intersections with a Galois conjugate

This file turns the pointwise conjugation statements into literal finite
equation-family and ideal identities.  For a finite family `E` over a field
`K/ℚ` and a `ℚ`-algebra automorphism `g`, the family `E ∪ gE` cuts out exactly
the intersection of the loci cut out by `E` and `gE`.  The generated ideal of
`gE` is exactly the coefficient-automorphism image of the ideal generated by
`E`.

The rational-point consequences are static inclusions in these explicit
union-family loci.  No assertion is made that `gE` differs from `E`, or that
the intersection has smaller dimension.
-/

namespace TranslatedDepthSeven

noncomputable section

open scoped LinearAlgebra.Projectivization

open MvPolynomial Finset

universe u v

variable {K : Type u} {ι : Type v} [Field K] [Algebra ℚ K]

/-- The ideal generated by the coefficientwise conjugate finite equation
family is the image of the original generated ideal under the coefficient
automorphism. -/
theorem finiteEquationIdeal_conjugateEquationFamily
    (g : K ≃ₐ[ℚ] K) (equations : Finset (MvPolynomial ι K)) :
    finiteEquationIdeal (conjugateEquationFamily g equations) =
      (finiteEquationIdeal equations).map (conjugatePolynomial g).toRingHom := by
  classical
  rw [finiteEquationIdeal, finiteEquationIdeal, Ideal.map_span]
  congr 1
  ext f
  simp [conjugateEquationFamily]

/-- The explicit finite family consisting of the original equations together
with all their coefficientwise conjugates. -/
def equationFamilyWithConjugate (g : K ≃ₐ[ℚ] K)
    (equations : Finset (MvPolynomial ι K)) :
    Finset (MvPolynomial ι K) := by
  classical
  exact equations ∪ conjugateEquationFamily g equations

@[simp]
theorem mem_equationFamilyWithConjugate_iff
    (g : K ≃ₐ[ℚ] K) (equations : Finset (MvPolynomial ι K))
    (f : MvPolynomial ι K) :
    f ∈ equationFamilyWithConjugate g equations ↔
      f ∈ equations ∨ f ∈ conjugateEquationFamily g equations := by
  classical
  simp [equationFamilyWithConjugate]

/-- At ideal level, adjoining the conjugate equations forms the supremum of
the original ideal and its coefficientwise conjugate. -/
theorem finiteEquationIdeal_equationFamilyWithConjugate
    (g : K ≃ₐ[ℚ] K) (equations : Finset (MvPolynomial ι K)) :
    finiteEquationIdeal (equationFamilyWithConjugate g equations) =
      finiteEquationIdeal equations ⊔
        (finiteEquationIdeal equations).map
          (conjugatePolynomial g).toRingHom := by
  classical
  change Ideal.span
      (equationFamilyWithConjugate g equations :
        Set (MvPolynomial ι K)) = _
  rw [equationFamilyWithConjugate, Finset.coe_union, Ideal.span_union]
  change finiteEquationIdeal equations ⊔
      finiteEquationIdeal (conjugateEquationFamily g equations) = _
  rw [finiteEquationIdeal_conjugateEquationFamily]

/-- The affine common zero locus of `E ∪ gE` is literally the intersection
of the original and conjugate affine loci. -/
theorem finiteAffineCommonZeroLocus_equationFamilyWithConjugate
    (g : K ≃ₐ[ℚ] K) (equations : Finset (MvPolynomial ι K)) :
    finiteAffineCommonZeroLocus (equationFamilyWithConjugate g equations) =
      finiteAffineCommonZeroLocus equations ∩
        finiteAffineCommonZeroLocus (conjugateEquationFamily g equations) := by
  classical
  ext x
  constructor
  · intro hx
    constructor
    · intro f hf
      exact hx f ((mem_equationFamilyWithConjugate_iff
        g equations f).mpr (Or.inl hf))
    · intro f hf
      exact hx f ((mem_equationFamilyWithConjugate_iff
        g equations f).mpr (Or.inr hf))
  · rintro ⟨hx, hxg⟩ f hf
    rcases (mem_equationFamilyWithConjugate_iff
      g equations f).mp hf with hf | hf
    · exact hx f hf
    · exact hxg f hf

/-- Every affine rational point of the original locus lies on the explicit
union-family locus `E ∪ gE`. -/
theorem rationalPoint_mem_finiteAffineCommonZeroLocus_withConjugate
    (g : K ≃ₐ[ℚ] K) (equations : Finset (MvPolynomial ι K))
    (x : ι → ℚ)
    (hx : (fun i ↦ algebraMap ℚ K (x i)) ∈
      finiteAffineCommonZeroLocus equations) :
    (fun i ↦ algebraMap ℚ K (x i)) ∈
      finiteAffineCommonZeroLocus
        (equationFamilyWithConjugate g equations) := by
  rw [finiteAffineCommonZeroLocus_equationFamilyWithConjugate]
  exact rationalPoint_mem_finiteAffineCommonZeroLocus_inter_conjugate
    g equations x hx

/-! ## Homogeneous projective loci -/

/-- For a finite homogeneous-coordinate family, the actual projective common
zero locus of `E ∪ gE` is the intersection of the original and conjugate
projective loci.  This set identity itself does not require a homogeneity
hypothesis. -/
theorem finiteProjectiveCommonZeroLocus_equationFamilyWithConjugate
    {σ : Type v} (g : K ≃ₐ[ℚ] K)
    (equations : Finset (MvPolynomial (Option σ) K)) :
    finiteProjectiveCommonZeroLocus
        (equationFamilyWithConjugate g equations) =
      finiteProjectiveCommonZeroLocus equations ∩
        finiteProjectiveCommonZeroLocus
          (conjugateEquationFamily g equations) := by
  classical
  ext P
  constructor
  · intro hP
    constructor
    · intro f hf
      exact hP f ((mem_equationFamilyWithConjugate_iff
        g equations f).mpr (Or.inl hf))
    · intro f hf
      exact hP f ((mem_equationFamilyWithConjugate_iff
        g equations f).mpr (Or.inr hf))
  · rintro ⟨hP, hPg⟩ f hf
    rcases (mem_equationFamilyWithConjugate_iff
      g equations f).mp hf with hf | hf
    · exact hP f hf
    · exact hPg f hf

/-- Every projective point with rational homogeneous coordinates on the
original homogeneous locus lies on the explicit union-family locus
`E ∪ gE`. -/
theorem rationalProjectivePoint_mem_finiteProjectiveCommonZeroLocus_withConjugate
    {σ : Type v} (g : K ≃ₐ[ℚ] K)
    (equations : Finset (MvPolynomial (Option σ) K))
    (degree : MvPolynomial (Option σ) K → ℕ)
    (hhom : ∀ f ∈ equations, f.IsHomogeneous (degree f))
    (x : Option σ → ℚ)
    (hx0 : (fun i ↦ algebraMap ℚ K (x i)) ≠ 0)
    (hx : Projectivization.mk K (fun i ↦ algebraMap ℚ K (x i)) hx0 ∈
      finiteProjectiveCommonZeroLocus equations) :
    Projectivization.mk K (fun i ↦ algebraMap ℚ K (x i)) hx0 ∈
      finiteProjectiveCommonZeroLocus
        (equationFamilyWithConjugate g equations) := by
  rw [finiteProjectiveCommonZeroLocus_equationFamilyWithConjugate]
  exact
    rationalProjectivePoint_mem_finiteProjectiveCommonZeroLocus_inter_conjugate
      g equations degree hhom x hx0 hx

end

end TranslatedDepthSeven
