import TranslatedDepthSeven.FiniteFamilyHomogenization
import Mathlib.RingTheory.GradedAlgebra.Homogeneous.Ideal

/-!
# A homogeneous-ideal bridge for finite projective equation families

This file turns the ideal generated by a literal finite homogeneous equation
family into Mathlib's genuine `HomogeneousIdeal` for the standard total-degree
grading.  Its projective zero locus is defined through nonzero homogeneous
representatives and is proved equal to the literal finite common zero locus.

Only generated ideals and their point sets are treated here.  There are no
saturation, component, irreducibility, or degree claims.
-/

namespace TranslatedDepthSeven

noncomputable section

open scoped LinearAlgebra.Projectivization

open MvPolynomial Finset

universe u v

variable {K : Type u} {σ : Type v} [Field K]

local instance mvPolynomialStandardGradedAlgebra :
    GradedAlgebra (MvPolynomial.homogeneousSubmodule (Option σ) K) :=
  MvPolynomial.gradedAlgebra

/-- The ideal generated by a finite family of individually homogeneous
polynomials is homogeneous for the standard total-degree grading. -/
theorem finiteEquationIdeal_isHomogeneous
    (equations : Finset (MvPolynomial (Option σ) K))
    (hhom : ∀ f ∈ equations, ∃ d : ℕ, f.IsHomogeneous d) :
    (finiteEquationIdeal equations).IsHomogeneous
      (MvPolynomial.homogeneousSubmodule (Option σ) K) := by
  apply Ideal.homogeneous_span
  intro f hf
  obtain ⟨d, hd⟩ := hhom f hf
  exact ⟨d, hd⟩

/-- The actual Mathlib homogeneous ideal generated by the displayed finite
homogeneous equations. -/
def finiteHomogeneousEquationIdeal
    (equations : Finset (MvPolynomial (Option σ) K))
    (hhom : ∀ f ∈ equations, ∃ d : ℕ, f.IsHomogeneous d) :
    HomogeneousIdeal (MvPolynomial.homogeneousSubmodule (Option σ) K) :=
  ⟨finiteEquationIdeal equations,
    finiteEquationIdeal_isHomogeneous equations hhom⟩

@[simp]
theorem finiteHomogeneousEquationIdeal_toIdeal
    (equations : Finset (MvPolynomial (Option σ) K))
    (hhom : ∀ f ∈ equations, ∃ d : ℕ, f.IsHomogeneous d) :
    (finiteHomogeneousEquationIdeal equations hhom).toIdeal =
      finiteEquationIdeal equations :=
  rfl

/-- The projective zero locus of a homogeneous ideal, defined by the
existence of one nonzero representative annihilating every polynomial in the
underlying ideal. -/
def projectiveHomogeneousIdealZeroLocus
    (I : HomogeneousIdeal
      (MvPolynomial.homogeneousSubmodule (Option σ) K)) :
    Set (ℙ K (Option σ → K)) :=
  {P | ∃ (x : Option σ → K) (hx : x ≠ 0),
    P = Projectivization.mk K x hx ∧
      x ∈ affineIdealZeroLocus I.toIdeal}

@[simp]
theorem mem_projectiveHomogeneousIdealZeroLocus_iff
    (I : HomogeneousIdeal
      (MvPolynomial.homogeneousSubmodule (Option σ) K))
    (P : ℙ K (Option σ → K)) :
    P ∈ projectiveHomogeneousIdealZeroLocus I ↔
      ∃ (x : Option σ → K) (hx : x ≠ 0),
        P = Projectivization.mk K x hx ∧
          ∀ g ∈ I.toIdeal, eval x g = 0 :=
  Iff.rfl

/-- The representative-defined zero locus of the generated homogeneous ideal
is exactly the literal common projective zero locus of its finite homogeneous
generators. -/
theorem projectiveHomogeneousIdealZeroLocus_finiteHomogeneousEquationIdeal
    (equations : Finset (MvPolynomial (Option σ) K))
    (hhom : ∀ f ∈ equations, ∃ d : ℕ, f.IsHomogeneous d) :
    projectiveHomogeneousIdealZeroLocus
        (finiteHomogeneousEquationIdeal equations hhom) =
      finiteProjectiveCommonZeroLocus equations := by
  ext P
  constructor
  · rintro ⟨x, hx, rfl, hideal⟩ f hf
    refine ⟨x, hx, rfl, ?_⟩
    exact hideal f (Ideal.subset_span hf)
  · intro hP
    refine ⟨P.rep, P.rep_nonzero, (Projectivization.mk_rep P).symm, ?_⟩
    rw [finiteHomogeneousEquationIdeal_toIdeal]
    rw [affineIdealZeroLocus_finiteEquationIdeal]
    intro f hf
    obtain ⟨d, hd⟩ := hhom f hf
    have hPf : P ∈ homogeneousProjectiveHypersurface f := hP f hf
    have hrep :=
      (mk_mem_homogeneousProjectiveHypersurface_iff
        f d hd P.rep P.rep_nonzero).mp
        (by simpa only [Projectivization.mk_rep] using hPf)
    exact hrep

/-- Apply the homogeneous affine-coordinate pullback to every member of a
finite homogeneous equation family. -/
def finiteFamilyHomogeneousAffineChange
    (y₀ : σ → K) (r : K) (hr : r ≠ 0)
    (equations : Finset (MvPolynomial (Option σ) K)) :
    Finset (MvPolynomial (Option σ) K) := by
  classical
  exact equations.image
    (homogeneousAffinePolynomialChangeAlgEquiv y₀ r hr)

/-- The transformed finite family is still individually homogeneous. -/
theorem finiteFamilyHomogeneousAffineChange_each_isHomogeneous
    (y₀ : σ → K) (r : K) (hr : r ≠ 0)
    (equations : Finset (MvPolynomial (Option σ) K))
    (hhom : ∀ f ∈ equations, ∃ d : ℕ, f.IsHomogeneous d)
    {g : MvPolynomial (Option σ) K}
    (hg : g ∈ finiteFamilyHomogeneousAffineChange y₀ r hr equations) :
    ∃ d : ℕ, g.IsHomogeneous d := by
  classical
  obtain ⟨f, hf, rfl⟩ := Finset.mem_image.mp hg
  obtain ⟨d, hd⟩ := hhom f hf
  exact ⟨d,
    isHomogeneous_homogeneousAffinePolynomialChange y₀ r hr hd⟩

/-- Polynomial-coordinate transport carries the ideal generated by the
original finite family exactly to the ideal generated by the transformed
family. -/
theorem map_finiteEquationIdeal_homogeneousAffineChange
    (y₀ : σ → K) (r : K) (hr : r ≠ 0)
    (equations : Finset (MvPolynomial (Option σ) K)) :
    (finiteEquationIdeal equations).map
        (homogeneousAffinePolynomialChangeAlgEquiv y₀ r hr).toRingHom =
      finiteEquationIdeal
        (finiteFamilyHomogeneousAffineChange y₀ r hr equations) := by
  classical
  rw [finiteEquationIdeal, Ideal.map_span]
  change Ideal.span
      (homogeneousAffinePolynomialChangeAlgEquiv y₀ r hr ''
        (equations : Set (MvPolynomial (Option σ) K))) = _
  rw [← Finset.coe_image]
  rfl

/-- The projective automorphism transports the literal finite common zero
locus exactly to that of the polynomial pullbacks. -/
theorem projectiveAffineMap_mem_finiteProjectiveCommonZeroLocus_iff
    (y₀ : σ → K) (r : K) (hr : r ≠ 0)
    (equations : Finset (MvPolynomial (Option σ) K))
    (hhom : ∀ f ∈ equations, ∃ d : ℕ, f.IsHomogeneous d)
    (P : ℙ K (Option σ → K)) :
    projectiveAffineMap y₀ r hr P ∈
        finiteProjectiveCommonZeroLocus equations ↔
      P ∈ finiteProjectiveCommonZeroLocus
        (finiteFamilyHomogeneousAffineChange y₀ r hr equations) := by
  classical
  constructor
  · intro hP g hg
    obtain ⟨f, hf, rfl⟩ := Finset.mem_image.mp hg
    obtain ⟨d, hd⟩ := hhom f hf
    exact
      (projectiveAffineMap_mem_homogeneousProjectiveHypersurface_iff
        y₀ r hr f d hd P).mp (hP f hf)
  · intro hP f hf
    obtain ⟨d, hd⟩ := hhom f hf
    apply
      (projectiveAffineMap_mem_homogeneousProjectiveHypersurface_iff
        y₀ r hr f d hd P).mpr
    exact hP _ (Finset.mem_image.mpr ⟨f, hf, rfl⟩)

/-- Combining the homogeneous-ideal bridge with the preceding transport
identity gives exact projective transport for the generated homogeneous
ideals themselves. -/
theorem projectiveAffineMap_mem_generatedHomogeneousIdealZeroLocus_iff
    (y₀ : σ → K) (r : K) (hr : r ≠ 0)
    (equations : Finset (MvPolynomial (Option σ) K))
    (hhom : ∀ f ∈ equations, ∃ d : ℕ, f.IsHomogeneous d)
    (P : ℙ K (Option σ → K)) :
    projectiveAffineMap y₀ r hr P ∈
        projectiveHomogeneousIdealZeroLocus
          (finiteHomogeneousEquationIdeal equations hhom) ↔
      P ∈ projectiveHomogeneousIdealZeroLocus
        (finiteHomogeneousEquationIdeal
          (finiteFamilyHomogeneousAffineChange y₀ r hr equations)
          (fun _g hg ↦
            finiteFamilyHomogeneousAffineChange_each_isHomogeneous
              y₀ r hr equations hhom hg)) := by
  rw [projectiveHomogeneousIdealZeroLocus_finiteHomogeneousEquationIdeal]
  rw [projectiveHomogeneousIdealZeroLocus_finiteHomogeneousEquationIdeal]
  exact projectiveAffineMap_mem_finiteProjectiveCommonZeroLocus_iff
    y₀ r hr equations hhom P

end

end TranslatedDepthSeven
