import Mathlib.Algebra.MvPolynomial.Funext
import Mathlib.RingTheory.NoetherNormalization
import TranslatedDepthSeven.MultivariateHomogenization

/-!
# Homogeneous linear elimination

This file isolates the algebraic step which is absent from the polynomial
Noether normalization supplied by Mathlib.  A nonzero homogeneous equation
can be made monic in one variable by a *linear* shear.  Consequently that
variable is integral over the algebra generated by the remaining linear
coordinates.

No projective degree, Hilbert polynomial, or geometric genericity statement
is used here.
-/

namespace TranslatedDepthSeven

noncomputable section

open MvPolynomial Polynomial

universe u v

variable {K : Type u} {σ : Type v} [Field K]

@[simp]
theorem multivariateDehomogenization_monomial
    (m : Option σ →₀ ℕ) (a : K) :
    multivariateDehomogenization (monomial m a) = monomial m.some a := by
  rw [multivariateDehomogenization, MvPolynomial.aeval_monomial]
  rw [Finsupp.prod_option_index]
  · simp [monomial_eq]
  · simp
  · intro i x y
    simp [pow_add]

theorem finsupp_degree_option (m : Option σ →₀ ℕ) :
    m.degree = m none + m.some.degree := by
  simpa [Finsupp.degree_apply] using
    (Finsupp.sum_option_index_smul (R := ℕ) (M := ℕ) m
      (fun _ : Option σ ↦ 1))

theorem finsupp_eq_of_some_eq_of_degree_eq
    (m n : Option σ →₀ ℕ) (hm : m.degree = n.degree)
    (hsome : m.some = n.some) : m = n := by
  have hnone : m none = n none := by
    rw [finsupp_degree_option, finsupp_degree_option, hsome] at hm
    omega
  ext j
  cases j with
  | none => exact hnone
  | some i => exact DFunLike.congr_fun hsome i

theorem finsupp_some_injOn_support_of_isHomogeneous
    {f : MvPolynomial (Option σ) K} {d : ℕ}
    (hf : f.IsHomogeneous d) :
    Set.InjOn Finsupp.some (f.support : Set (Option σ →₀ ℕ)) := by
  intro m hm n hn hsome
  have hmdeg : m.degree = d := by
    rw [Finsupp.degree_eq_weight_one]
    exact hf (MvPolynomial.mem_support_iff.mp hm)
  have hndeg : n.degree = d := by
    rw [Finsupp.degree_eq_weight_one]
    exact hf (MvPolynomial.mem_support_iff.mp hn)
  have hnone : m none = n none := by
    rw [finsupp_degree_option] at hmdeg hndeg
    rw [hsome] at hmdeg
    omega
  ext j
  cases j with
  | none => exact hnone
  | some i => exact DFunLike.congr_fun hsome i

/-- On one homogeneous piece, dropping the exponent of the homogenizing
variable is injective on the support.  Hence dehomogenization retains every
displayed nonzero coefficient. -/
theorem coeff_multivariateDehomogenization_of_isHomogeneous
    (f : MvPolynomial (Option σ) K) (d : ℕ)
    (hf : f.IsHomogeneous d) (m : Option σ →₀ ℕ)
    (hmdeg : m.degree = d) :
    coeff m.some (multivariateDehomogenization f) = coeff m f := by
  classical
  nth_rw 1 [f.as_sum]
  simp only [map_sum, multivariateDehomogenization_monomial,
    MvPolynomial.coeff_sum, MvPolynomial.coeff_monomial]
  rw [Finset.sum_eq_single m]
  · simp
  · intro n hn hnm
    have hndeg : n.degree = d := by
      rw [Finsupp.degree_eq_weight_one]
      exact hf (MvPolynomial.mem_support_iff.mp hn)
    have hne : n.some ≠ m.some := by
      intro h
      exact hnm (finsupp_eq_of_some_eq_of_degree_eq n m
        (hndeg.trans hmdeg.symm) h)
    simp [hne]
  · intro hmnot
    simpa using MvPolynomial.notMem_support_iff.mp hmnot

/-- A nonzero homogeneous polynomial remains nonzero after setting the
homogenizing coordinate equal to one. -/
theorem multivariateDehomogenization_ne_zero_of_isHomogeneous
    (f : MvPolynomial (Option σ) K) (d : ℕ)
    (hf : f.IsHomogeneous d) (hne : f ≠ 0) :
    multivariateDehomogenization f ≠ 0 := by
  obtain ⟨m, hm⟩ := MvPolynomial.support_nonempty.mpr hne
  intro hzero
  have hcoeff := coeff_multivariateDehomogenization_of_isHomogeneous
    f d hf m (by
      rw [Finsupp.degree_eq_weight_one]
      exact hf (MvPolynomial.mem_support_iff.mp hm))
  rw [hzero, MvPolynomial.coeff_zero] at hcoeff
  exact MvPolynomial.mem_support_iff.mp hm hcoeff.symm

/-- Over an infinite field, every nonzero homogeneous polynomial is nonzero
at a point of the standard affine chart. -/
theorem exists_eval_affineChartVector_ne_zero_of_isHomogeneous
    [Infinite K] (f : MvPolynomial (Option σ) K) (d : ℕ)
    (hf : f.IsHomogeneous d) (hne : f ≠ 0) :
    ∃ c : σ → K, eval (affineChartVector c) f ≠ 0 := by
  have hdehom : multivariateDehomogenization f ≠ 0 :=
    multivariateDehomogenization_ne_zero_of_isHomogeneous f d hf hne
  by_contra h
  push_neg at h
  apply hdehom
  apply MvPolynomial.funext
  intro c
  rw [eval_multivariateDehomogenization]
  exact h c

/-- Substitution of degree-one forms commutes with extraction of every
homogeneous component. -/
theorem homogeneousComponent_aeval_degreeOne
    {τ : Type*} (l : σ → MvPolynomial τ K)
    (hl : ∀ i, (l i).IsHomogeneous 1)
    (p : MvPolynomial σ K) (k : ℕ) :
    homogeneousComponent k (aeval l p) =
      aeval l (homogeneousComponent k p) := by
  classical
  conv_lhs =>
    rw [← p.sum_homogeneousComponent]
    simp only [map_sum]
  by_cases hk : k ∈ Finset.range (p.totalDegree + 1)
  · rw [Finset.sum_eq_single k]
    · have hh : (aeval l (homogeneousComponent k p)).IsHomogeneous k := by
        simpa using (homogeneousComponent_isHomogeneous k p).aeval l hl
      rw [homogeneousComponent_of_mem hh]
      simp
    · intro j hj hjk
      have hh : (aeval l (homogeneousComponent j p)).IsHomogeneous j := by
        simpa using (homogeneousComponent_isHomogeneous j p).aeval l hl
      rw [homogeneousComponent_of_mem hh]
      simp [Ne.symm hjk]
    · exact fun h ↦ (h hk).elim
  · have hpk : homogeneousComponent k p = 0 := by
      apply homogeneousComponent_eq_zero
      simpa only [Finset.mem_range, Nat.lt_add_one_iff, not_le] using hk
    rw [hpk, map_zero]
    apply Finset.sum_eq_zero
    intro j hj
    have hjk : j ≠ k := by
      intro h
      exact hk (h ▸ hj)
    have hh : (aeval l (homogeneousComponent j p)).IsHomogeneous j := by
      simpa using (homogeneousComponent_isHomogeneous j p).aeval l hl
    rw [homogeneousComponent_of_mem hh]
    simp [Ne.symm hjk]

/-- For a degree-`d` homogeneous polynomial, the coefficient of
`X_none^d`, viewed through `optionEquivLeft`, is the scalar obtained by
evaluating on the `none`-coordinate axis. -/
theorem coeff_optionEquivLeft_degree_eq_C_eval_affineChartVector_zero
    [Finite σ] (f : MvPolynomial (Option σ) K) (d : ℕ)
    (hf : f.IsHomogeneous d) :
    (optionEquivLeft K σ f).coeff d =
      MvPolynomial.C (eval (affineChartVector (0 : σ → K)) f) := by
  let p : Polynomial (MvPolynomial σ K) := optionEquivLeft K σ f
  have hp : ((optionEquivLeft K σ).symm p).IsHomogeneous d := by
    simpa [p] using hf
  have hcoeffhom : (p.coeff d).IsHomogeneous 0 :=
    hp.coeff_isHomogeneous_of_optionEquivLeft_symm d 0 (by omega)
  have hdegree : (p.coeff d).totalDegree = 0 := by
    rw [MvPolynomial.totalDegree_zero_iff_isHomogeneous]
    exact hcoeffhom
  have hconstant : p.coeff d = MvPolynomial.C (coeff 0 (p.coeff d)) :=
    MvPolynomial.totalDegree_eq_zero_iff_eq_C.mp
      hdegree
  rw [hconstant]
  congr 1
  let m : Option σ →₀ ℕ := (0 : σ →₀ ℕ).optionElim d
  have hmdeg : m.degree = d := by simp [m]
  have hdehom := coeff_multivariateDehomogenization_of_isHomogeneous
    f d hf m hmdeg
  have hoption := optionEquivLeft_coeff_coeff K σ m f
  have heval :
      eval (affineChartVector (0 : σ → K)) f =
        coeff 0 (multivariateDehomogenization f) := by
    rw [← eval_multivariateDehomogenization]
    simp only [MvPolynomial.eval_zero, MvPolynomial.constantCoeff_eq]
  simpa [p, m, heval] using hoption.trans hdehom.symm

/-- The top coefficient after the linear shear
`X_some i ↦ c i * X_none + X_some i` is evaluation of the original
homogeneous equation at `[1:c]`. -/
theorem coeff_optionEquivLeft_homogeneousAffinePolynomialChange
    [Finite σ] (c : σ → K) (f : MvPolynomial (Option σ) K) (d : ℕ)
    (hf : f.IsHomogeneous d) :
    (optionEquivLeft K σ
      (homogeneousAffinePolynomialChangeAlgEquiv c 1 one_ne_zero f)).coeff d =
        MvPolynomial.C (eval (affineChartVector c) f) := by
  rw [coeff_optionEquivLeft_degree_eq_C_eval_affineChartVector_zero _ d
    (isHomogeneous_homogeneousAffinePolynomialChange c 1 one_ne_zero hf)]
  congr 1
  change aeval (affineChartVector (0 : σ → K))
      (homogeneousAffinePolynomialChangeAlgEquiv c 1 one_ne_zero f) =
    aeval (affineChartVector c) f
  rw [aeval_homogeneousAffinePolynomialChange]
  have hvector :
      homogeneousAffineLinearEquiv c 1 one_ne_zero
        (affineChartVector (0 : σ → K)) = affineChartVector c := by
    funext j
    cases j with
    | none => simp [affineChartVector]
    | some i => simp [affineChartVector]
  rw [hvector]

/-- A suitable homogeneous linear shear makes the equation have unit leading
coefficient in `X_none`. -/
theorem exists_homogeneous_linear_shear_leadingCoeff_isUnit
    [Infinite K] [Finite σ]
    (f : MvPolynomial (Option σ) K) (d : ℕ)
    (hf : f.IsHomogeneous d) (hne : f ≠ 0) :
    ∃ c : σ → K,
      IsUnit (optionEquivLeft K σ
        (homogeneousAffinePolynomialChangeAlgEquiv c 1 one_ne_zero f)).leadingCoeff := by
  obtain ⟨c, hc⟩ :=
    exists_eval_affineChartVector_ne_zero_of_isHomogeneous f d hf hne
  refine ⟨c, ?_⟩
  let g := homogeneousAffinePolynomialChangeAlgEquiv c 1 one_ne_zero f
  let p := optionEquivLeft K σ g
  have hg : g.IsHomogeneous d :=
    isHomogeneous_homogeneousAffinePolynomialChange c 1 one_ne_zero hf
  have hgne : g ≠ 0 :=
    (homogeneousAffinePolynomialChangeAlgEquiv c 1 one_ne_zero).injective.ne hne
  have hcoeff : p.coeff d = MvPolynomial.C (eval (affineChartVector c) f) := by
    simpa [p, g] using
      coeff_optionEquivLeft_homogeneousAffinePolynomialChange c f d hf
  have hcoeffne : p.coeff d ≠ 0 := by
    rw [hcoeff]
    exact MvPolynomial.C_ne_zero.mpr hc
  have hnat_le : p.natDegree ≤ d := by
    dsimp only [p]
    rw [MvPolynomial.natDegree_optionEquivLeft]
    exact (MvPolynomial.degreeOf_le_totalDegree g none).trans_eq
      (hg.totalDegree hgne)
  have hnat : p.natDegree = d :=
    le_antisymm hnat_le (Polynomial.le_natDegree_of_ne_zero hcoeffne)
  rw [Polynomial.leadingCoeff, hnat, hcoeff]
  exact hc.isUnit.map MvPolynomial.C

/-- The pointwise form of the preceding shear lemma.  It is useful when one
coefficient of the shear has been prescribed, for example when a
distinguished projective coordinate must remain fixed. -/
theorem homogeneous_linear_shear_leadingCoeff_isUnit_of_eval_ne_zero
    [Finite σ] (c : σ → K)
    (f : MvPolynomial (Option σ) K) (d : ℕ)
    (hf : f.IsHomogeneous d)
    (hc : eval (affineChartVector c) f ≠ 0) :
    IsUnit (optionEquivLeft K σ
      (homogeneousAffinePolynomialChangeAlgEquiv
        c 1 one_ne_zero f)).leadingCoeff := by
  let g := homogeneousAffinePolynomialChangeAlgEquiv c 1 one_ne_zero f
  let p := optionEquivLeft K σ g
  have hg : g.IsHomogeneous d :=
    isHomogeneous_homogeneousAffinePolynomialChange c 1 one_ne_zero hf
  have hcoeff : p.coeff d = MvPolynomial.C (eval (affineChartVector c) f) := by
    simpa [p, g] using
      coeff_optionEquivLeft_homogeneousAffinePolynomialChange c f d hf
  have hcoeffne : p.coeff d ≠ 0 := by
    rw [hcoeff]
    exact MvPolynomial.C_ne_zero.mpr hc
  have hgne : g ≠ 0 := by
    intro hgzero
    apply hcoeffne
    simp [p, hgzero]
  have hnat_le : p.natDegree ≤ d := by
    dsimp only [p]
    rw [MvPolynomial.natDegree_optionEquivLeft]
    exact (MvPolynomial.degreeOf_le_totalDegree g none).trans_eq
      (hg.totalDegree hgne)
  have hnat : p.natDegree = d :=
    le_antisymm hnat_le (Polynomial.le_natDegree_of_ne_zero hcoeffne)
  rw [Polynomial.leadingCoeff, hnat, hcoeff]
  exact hc.isUnit.map MvPolynomial.C

/-- The quotient by an ideal transported through `optionEquivLeft` is the
same algebra as the original multivariable quotient. -/
def optionEquivLeftQuotientAlgEquiv
    (J : Ideal (MvPolynomial (Option σ) K)) :
    ((MvPolynomial σ K)[X] ⧸ J.map (optionEquivLeft K σ)) ≃ₐ[K]
      (MvPolynomial (Option σ) K ⧸ J) :=
  Ideal.quotientEquivAlg (J.map (optionEquivLeft K σ)) J
    (optionEquivLeft K σ).symm <| by
      symm
      change Ideal.map
          (optionEquivLeft K σ).symm.toRingEquiv.toRingHom
          (Ideal.map (optionEquivLeft K σ).toRingEquiv.toRingHom J) = J
      rw [Ideal.map_map]
      have hcomp :
          (optionEquivLeft K σ).symm.toRingEquiv.toRingHom.comp
            (optionEquivLeft K σ).toRingEquiv.toRingHom = RingHom.id _ :=
        (optionEquivLeft K σ).toRingEquiv.symm_toRingHom_comp_toRingHom
      rw [hcomp, Ideal.map_id]

/-- The coefficient algebra map into a polynomial quotient. -/
def polynomialCoefficientQuotientHom
    (L : Ideal ((MvPolynomial σ K)[X])) :
    MvPolynomial σ K →ₐ[K] ((MvPolynomial σ K)[X] ⧸ L) :=
  ((Ideal.Quotient.mkₐ (MvPolynomial σ K) L).comp
    (Algebra.ofId (MvPolynomial σ K) ((MvPolynomial σ K)[X]))).restrictScalars K

/-- The linear elimination map into the original quotient.  Its generators
are the pullbacks of the unchanged coefficient variables through the inverse
shear. -/
def homogeneousLinearEliminationHom
    (c : σ → K) (I : Ideal (MvPolynomial (Option σ) K)) :
    MvPolynomial σ K →ₐ[K] (MvPolynomial (Option σ) K ⧸ I) :=
  (homogeneousAffinePolynomialChangeQuotientAlgEquiv
      c 1 one_ne_zero I).symm.toAlgHom.comp
    ((optionEquivLeftQuotientAlgEquiv
      (I.map (homogeneousAffinePolynomialChangeAlgEquiv
        c 1 one_ne_zero))).toAlgHom.comp
      (polynomialCoefficientQuotientHom
        ((I.map (homogeneousAffinePolynomialChangeAlgEquiv
          c 1 one_ne_zero)).map (optionEquivLeft K σ))))

/-- The literal degree-one forms defining the elimination map. -/
def homogeneousLinearEliminationForm (c : σ → K) (i : σ) :
    MvPolynomial (Option σ) K :=
  X (some i) - MvPolynomial.C (c i) * X none

theorem homogeneousLinearEliminationForm_isHomogeneous
    (c : σ → K) (i : σ) :
    (homogeneousLinearEliminationForm c i).IsHomogeneous 1 := by
  exact (isHomogeneous_X (R := K) (some i)).sub
    (isHomogeneous_C_mul_X (c i) none)

/-- A homogeneous relation whose transformed leading coefficient is a unit
makes the displayed linear elimination map integral. -/
theorem homogeneousLinearEliminationHom_isIntegral
    (c : σ → K) (I : Ideal (MvPolynomial (Option σ) K))
    (f : MvPolynomial (Option σ) K) (hfI : f ∈ I)
    (hlead : IsUnit (optionEquivLeft K σ
      (homogeneousAffinePolynomialChangeAlgEquiv c 1 one_ne_zero f)).leadingCoeff) :
    (homogeneousLinearEliminationHom c I).IsIntegral := by
  let T := homogeneousAffinePolynomialChangeAlgEquiv c 1 one_ne_zero
  let J := I.map T
  let L := J.map (optionEquivLeft K σ)
  let p := optionEquivLeft K σ (T f)
  have hpL : p ∈ L := by
    exact Ideal.mem_map_of_mem (optionEquivLeft K σ)
      (Ideal.mem_map_of_mem T hfI)
  have hmonic :
      (hlead.unit⁻¹.val • p).Monic :=
    monic_of_isUnit_leadingCoeff_inv_smul hlead
  have hbase : (polynomialCoefficientQuotientHom L).IsIntegral := by
    simpa [polynomialCoefficientQuotientHom] using
      hmonic.quotient_isIntegral
        (Submodule.smul_of_tower_mem L hlead.unit⁻¹.val hpL)
  have hfirst := hbase.trans _ _
    (RingHom.isIntegral_of_surjective _
      (optionEquivLeftQuotientAlgEquiv J).surjective)
  have hsecond := hfirst.trans _ _
    (RingHom.isIntegral_of_surjective _
      (homogeneousAffinePolynomialChangeQuotientAlgEquiv
        c 1 one_ne_zero I).symm.surjective)
  simpa [homogeneousLinearEliminationHom, T, J, L] using hsecond

@[simp]
theorem homogeneousLinearEliminationHom_X
    (c : σ → K) (I : Ideal (MvPolynomial (Option σ) K)) (i : σ) :
    homogeneousLinearEliminationHom c I (X i) =
      Ideal.Quotient.mk I
        (X (some i) - MvPolynomial.C (c i) * X none) := by
  let T := homogeneousAffinePolynomialChangeAlgEquiv c 1 one_ne_zero
  let J := I.map T
  let L := J.map (optionEquivLeft K σ)
  let E₁ := optionEquivLeftQuotientAlgEquiv J
  let E₂ := homogeneousAffinePolynomialChangeQuotientAlgEquiv
    c 1 one_ne_zero I
  change E₂.symm (E₁ (polynomialCoefficientQuotientHom L (X i))) = _
  have h₀ : polynomialCoefficientQuotientHom L (X i) =
      Ideal.Quotient.mk L (Polynomial.C (X i)) := by
    simpa [polynomialCoefficientQuotientHom,
      Polynomial.algebraMap_apply] using
      (Ideal.Quotient.mk_algebraMap
        (R₁ := MvPolynomial σ K) L (X i)).symm
  rw [h₀]
  have h₁ : E₁ (Ideal.Quotient.mk L (Polynomial.C (X i))) =
      Ideal.Quotient.mk J (X (some i)) := by
    dsimp only [E₁]
    rw [optionEquivLeftQuotientAlgEquiv,
      Ideal.quotientEquivAlg_mk]
    congr 1
    apply (optionEquivLeft K σ).injective
    simp [MvPolynomial.optionEquivLeft_X_some]
  rw [h₁]
  have h₂ : E₂.symm (Ideal.Quotient.mk J (X (some i))) =
      Ideal.Quotient.mk I
        (X (some i) - MvPolynomial.C (c i) * X none) := by
    change (Ideal.quotientEquivAlg I J T rfl).symm
      (Ideal.Quotient.mk J (X (some i))) = _
    rw [Ideal.quotientEquivAlg_symm,
      Ideal.quotientEquivAlg_mk]
    simp [T, homogeneousAffinePolynomialChangeAlgEquiv,
      homogeneousAffinePolynomialChangeInvHom]
  exact h₂

/-- The abstract composite used to prove integrality is exactly evaluation
at the displayed degree-one forms followed by the quotient map. -/
theorem homogeneousLinearEliminationHom_apply
    (c : σ → K) (I : Ideal (MvPolynomial (Option σ) K))
    (p : MvPolynomial σ K) :
    homogeneousLinearEliminationHom c I p =
      Ideal.Quotient.mk I (aeval (homogeneousLinearEliminationForm c) p) := by
  let q : MvPolynomial σ K →ₐ[K]
      (MvPolynomial (Option σ) K ⧸ I) :=
    (Ideal.Quotient.mkₐ K I).comp
      (aeval (homogeneousLinearEliminationForm c))
  have hq : homogeneousLinearEliminationHom c I = q := by
    apply MvPolynomial.algHom_ext
    intro i
    rw [homogeneousLinearEliminationHom_X]
    simp [q, homogeneousLinearEliminationForm]
  exact DFunLike.congr_fun hq p

local instance mvPolynomialLinearEliminationGradedAlgebra :
    GradedAlgebra (MvPolynomial.homogeneousSubmodule σ K) :=
  MvPolynomial.gradedAlgebra

/-- Every nonzero homogeneous ideal contains a nonzero homogeneous
polynomial.  This is the relation-selection step needed before each
elimination. -/
theorem exists_nonzero_isHomogeneous_mem_of_isHomogeneous_ne_bot
    (I : Ideal (MvPolynomial σ K))
    (hI : I.IsHomogeneous (MvPolynomial.homogeneousSubmodule σ K))
    (hne : I ≠ ⊥) :
    ∃ f : MvPolynomial σ K, ∃ d : ℕ,
      f ∈ I ∧ f.IsHomogeneous d ∧ f ≠ 0 := by
  obtain ⟨p, hpI, hpne⟩ := Submodule.exists_mem_ne_zero_of_ne_bot hne
  have hexists : ∃ d : ℕ, homogeneousComponent d p ≠ 0 := by
    by_contra h
    push_neg at h
    apply hpne
    rw [← p.sum_homogeneousComponent]
    simp [h]
  obtain ⟨d, hd⟩ := hexists
  refine ⟨homogeneousComponent d p, d, ?_,
    homogeneousComponent_isHomogeneous d p, hd⟩
  have hcomponent := hI d hpI
  rw [← DirectSum.Decomposition.decompose'_eq] at hcomponent
  rw [MvPolynomial.decomposition.decompose'_apply] at hcomponent
  exact hcomponent

/-- If the original ideal is homogeneous, then the kernel created by one
linear elimination step is homogeneous as well.  This is the key fact which
allows the construction to be iterated without leaving degree one. -/
theorem kernel_homogeneousLinearEliminationHom_isHomogeneous
    (c : σ → K) (I : Ideal (MvPolynomial (Option σ) K))
    (hI : I.IsHomogeneous
      (MvPolynomial.homogeneousSubmodule (Option σ) K)) :
    (RingHom.ker (homogeneousLinearEliminationHom c I)).IsHomogeneous
      (MvPolynomial.homogeneousSubmodule σ K) := by
  intro k p hp
  rw [← DirectSum.Decomposition.decompose'_eq]
  rw [MvPolynomial.decomposition.decompose'_apply]
  rw [RingHom.mem_ker] at hp ⊢
  rw [homogeneousLinearEliminationHom_apply] at hp ⊢
  have hpI : aeval (homogeneousLinearEliminationForm c) p ∈ I :=
    Ideal.Quotient.eq_zero_iff_mem.mp hp
  have hcomponentI :
      homogeneousComponent k
        (aeval (homogeneousLinearEliminationForm c) p) ∈ I := by
    have := hI k hpI
    rw [← DirectSum.Decomposition.decompose'_eq] at this
    rw [MvPolynomial.decomposition.decompose'_apply] at this
    exact this
  apply Ideal.Quotient.eq_zero_iff_mem.mpr
  rw [← homogeneousComponent_aeval_degreeOne
    (homogeneousLinearEliminationForm c)
    (homogeneousLinearEliminationForm_isHomogeneous c) p k]
  exact hcomponentI

/-- In this affine quotient situation, integrality of the displayed map is
automatically module-finiteness: the target is already of finite type over
the ground field. -/
theorem homogeneousLinearEliminationHom_finite_of_isIntegral
    [Finite σ] (c : σ → K) (I : Ideal (MvPolynomial (Option σ) K))
    (hint : (homogeneousLinearEliminationHom c I).IsIntegral) :
    (homogeneousLinearEliminationHom c I).Finite := by
  let g := homogeneousLinearEliminationHom c I
  have hcomp :
      algebraMap K (MvPolynomial (Option σ) K ⧸ I) =
        g.toRingHom.comp (algebraMap K (MvPolynomial σ K)) := by
    ext x
    exact (g.commutes x).symm
  have hfiniteTypeK :
      (algebraMap K (MvPolynomial (Option σ) K ⧸ I)).FiniteType :=
    RingHom.finiteType_algebraMap.mpr inferInstance
  have hgfiniteType : g.toRingHom.FiniteType :=
    RingHom.FiniteType.of_comp_finiteType (hcomp ▸ hfiniteTypeK)
  exact hint.to_finite hgfiniteType

/-- One-step homogeneous linear Noether elimination.  A chosen nonzero
homogeneous relation produces a finite map from a polynomial algebra whose
generators are the explicit degree-one forms
`X_some i - c i * X_none`. -/
theorem exists_finite_homogeneousLinearEliminationHom
    [Infinite K] [Finite σ]
    (I : Ideal (MvPolynomial (Option σ) K))
    (f : MvPolynomial (Option σ) K) (d : ℕ)
    (hfI : f ∈ I) (hf : f.IsHomogeneous d) (hne : f ≠ 0) :
    ∃ c : σ → K,
      (homogeneousLinearEliminationHom c I).Finite ∧
      ∀ i, homogeneousLinearEliminationHom c I (X i) =
        Ideal.Quotient.mk I
          (X (some i) - MvPolynomial.C (c i) * X none) := by
  obtain ⟨c, hlead⟩ :=
    exists_homogeneous_linear_shear_leadingCoeff_isUnit f d hf hne
  have hint := homogeneousLinearEliminationHom_isIntegral c I f hfI hlead
  exact ⟨c,
    homogeneousLinearEliminationHom_finite_of_isIntegral c I hint,
    homogeneousLinearEliminationHom_X c I⟩

/-- One-step elimination with a prescribed shear point.  If its
`i₀`-coordinate is zero, the corresponding linear coordinate is literally
fixed by the map. -/
theorem finite_homogeneousLinearEliminationHom_of_eval_ne_zero
    [Finite σ] (I : Ideal (MvPolynomial (Option σ) K))
    (f : MvPolynomial (Option σ) K) (d : ℕ)
    (hfI : f ∈ I) (hf : f.IsHomogeneous d)
    (c : σ → K) (hc : eval (affineChartVector c) f ≠ 0) :
    (homogeneousLinearEliminationHom c I).Finite := by
  have hlead :=
    homogeneous_linear_shear_leadingCoeff_isUnit_of_eval_ne_zero
      c f d hf hc
  exact homogeneousLinearEliminationHom_finite_of_isIntegral c I
    (homogeneousLinearEliminationHom_isIntegral c I f hfI hlead)

theorem homogeneousLinearEliminationHom_fixes_of_eq_zero
    (c : σ → K) (I : Ideal (MvPolynomial (Option σ) K))
    (i₀ : σ) (hc : c i₀ = 0) :
    homogeneousLinearEliminationHom c I (X i₀) =
      Ideal.Quotient.mk I (X (some i₀)) := by
  rw [homogeneousLinearEliminationHom_X, hc]
  simp

/-! ## Iteration -/

/-- Concrete output of homogeneous linear Noether normalization.  The
normalizing polynomial algebra is presented by literal degree-one forms in
the original coordinates. -/
structure HomogeneousLinearNormalizationData
    {K : Type u} [Field K] {τ : Type v}
    (I : Ideal (MvPolynomial τ K)) where
  parameterCount : ℕ
  forms : Fin parameterCount → MvPolynomial τ K
  forms_isHomogeneous : ∀ i, (forms i).IsHomogeneous 1
  injective : Function.Injective
    ((Ideal.Quotient.mkₐ K I).comp (aeval forms))
  finite : ((Ideal.Quotient.mkₐ K I).comp (aeval forms)).Finite

/-- Renaming variables through an equivalence preserves homogeneous ideals. -/
theorem map_renameEquiv_isHomogeneous
    {τ : Type*} (e : σ ≃ τ) (I : Ideal (MvPolynomial σ K))
    (hI : I.IsHomogeneous (MvPolynomial.homogeneousSubmodule σ K)) :
    (I.map (MvPolynomial.renameEquiv K e)).IsHomogeneous
      (MvPolynomial.homogeneousSubmodule τ K) := by
  rw [Ideal.IsHomogeneous.iff_exists] at hI ⊢
  obtain ⟨S, rfl⟩ := hI
  let T : Set (SetLike.homogeneousSubmonoid
      (MvPolynomial.homogeneousSubmodule τ K)) :=
    {q | ∃ p : SetLike.homogeneousSubmonoid
        (MvPolynomial.homogeneousSubmodule σ K),
      p ∈ S ∧ q.1 = MvPolynomial.rename e p.1}
  refine ⟨T, ?_⟩
  rw [Ideal.map_span]
  apply congrArg Ideal.span
  ext q
  constructor
  · rintro ⟨_, ⟨p, hp, rfl⟩, rfl⟩
    refine ⟨⟨MvPolynomial.rename e p.1, ?_⟩, ?_, rfl⟩
    · obtain ⟨d, hd⟩ := p.2
      exact ⟨d, hd.rename_isHomogeneous⟩
    · exact ⟨p, hp, rfl⟩
  · rintro ⟨q', ⟨p, hp, hq'⟩, rfl⟩
    refine ⟨p.1, ⟨p, hp, rfl⟩, ?_⟩
    simpa [MvPolynomial.renameEquiv_apply] using hq'.symm

namespace HomogeneousLinearNormalizationData

/-- The finite injective map represented by a normalization datum. -/
def hom {τ : Type v} {I : Ideal (MvPolynomial τ K)}
    (D : HomogeneousLinearNormalizationData I) :
    MvPolynomial (Fin D.parameterCount) K →ₐ[K]
      (MvPolynomial τ K ⧸ I) :=
  (Ideal.Quotient.mkₐ K I).comp (aeval D.forms)

theorem hom_injective {τ : Type v} {I : Ideal (MvPolynomial τ K)}
    (D : HomogeneousLinearNormalizationData I) :
    Function.Injective D.hom :=
  D.injective

theorem hom_finite {τ : Type v} {I : Ideal (MvPolynomial τ K)}
    (D : HomogeneousLinearNormalizationData I) : D.hom.Finite :=
  D.finite

end HomogeneousLinearNormalizationData

/-- Evaluating renamed forms and then passing to the original quotient is
the transport, through the quotient equivalence, of evaluation before the
renaming. -/
theorem normalizationHom_renameEquiv
    {τ : Type*} (e : σ ≃ τ) (I : Ideal (MvPolynomial σ K))
    (s : ℕ) (l : Fin s → MvPolynomial τ K) :
    (Ideal.Quotient.mkₐ K I).comp
        (aeval (fun i ↦ MvPolynomial.rename e.symm (l i))) =
      (Ideal.quotientEquivAlg I
          (I.map (MvPolynomial.renameEquiv K e))
          (MvPolynomial.renameEquiv K e) rfl).symm.toAlgHom.comp
        ((Ideal.Quotient.mkₐ K
          (I.map (MvPolynomial.renameEquiv K e))).comp (aeval l)) := by
  apply MvPolynomial.algHom_ext
  intro i
  simp [Ideal.quotientEquivAlg_symm,
    MvPolynomial.renameEquiv_apply]

/-- Pull a normalization datum back through a renaming of variables. -/
def HomogeneousLinearNormalizationData.renameEquiv
    {τ : Type*} (e : σ ≃ τ) (I : Ideal (MvPolynomial σ K))
    (D : HomogeneousLinearNormalizationData
      (I.map (MvPolynomial.renameEquiv K e))) :
    HomogeneousLinearNormalizationData I where
  parameterCount := D.parameterCount
  forms := fun i ↦ MvPolynomial.rename e.symm (D.forms i)
  forms_isHomogeneous := fun i ↦
    (D.forms_isHomogeneous i).rename_isHomogeneous
  injective := by
    rw [normalizationHom_renameEquiv e I D.parameterCount D.forms]
    exact (Ideal.quotientEquivAlg I
      (I.map (MvPolynomial.renameEquiv K e))
      (MvPolynomial.renameEquiv K e) rfl).symm.injective.comp D.injective
  finite := by
    rw [normalizationHom_renameEquiv e I D.parameterCount D.forms]
    exact AlgHom.Finite.comp
      (AlgHom.Finite.of_surjective _
        (Ideal.quotientEquivAlg I
          (I.map (MvPolynomial.renameEquiv K e))
          (MvPolynomial.renameEquiv K e) rfl).symm.surjective)
      D.finite

/-- Factoring an algebra map through its kernel does not change evaluation
of a polynomial in its displayed coordinate images. -/
theorem kerLift_comp_normalizationHom
    {τ : Type*} (I : Ideal (MvPolynomial τ K))
    (l : σ → MvPolynomial τ K)
    (h : MvPolynomial σ K →ₐ[K] (MvPolynomial τ K ⧸ I))
    (hh : h = (Ideal.Quotient.mkₐ K I).comp (aeval l))
    (s : ℕ) (g : Fin s → MvPolynomial σ K) :
    (Ideal.kerLiftAlg h).comp
        ((Ideal.Quotient.mkₐ K (RingHom.ker h)).comp (aeval g)) =
      (Ideal.Quotient.mkₐ K I).comp
        (aeval (fun i ↦ aeval l (g i))) := by
  apply MvPolynomial.algHom_ext
  intro i
  rw [AlgHom.comp_apply, AlgHom.comp_apply]
  simp only [MvPolynomial.aeval_X, Ideal.Quotient.mkₐ_eq_mk,
    Ideal.kerLiftAlg_mk]
  rw [hh]
  simp

/-- If an algebra map is finite, so is its injective factor through its
kernel. -/
theorem kerLiftAlg_finite_of_finite
    {A B : Type*} [CommRing A] [CommRing B]
    [Algebra K A] [Algebra K B] (h : A →ₐ[K] B) (hh : h.Finite) :
    (Ideal.kerLiftAlg h).Finite := by
  have hcomp : (Ideal.kerLiftAlg h).comp
      (Ideal.Quotient.mkₐ K (RingHom.ker h)) = h := by
    apply AlgHom.ext
    intro a
    exact Ideal.kerLiftAlg_mk h a
  exact AlgHom.Finite.of_comp_finite (hcomp.symm ▸ hh)

/-- The identity coordinates normalize the zero ideal. -/
def homogeneousLinearNormalizationDataBot (n : ℕ) :
    HomogeneousLinearNormalizationData
      (⊥ : Ideal (MvPolynomial (Fin n) K)) := by
  let h : MvPolynomial (Fin n) K →ₐ[K]
      (MvPolynomial (Fin n) K ⧸
        (⊥ : Ideal (MvPolynomial (Fin n) K))) :=
    (Ideal.Quotient.mkₐ K ⊥).comp (aeval (X : Fin n → _))
  have hh : h = Ideal.Quotient.mkₐ K ⊥ := by
    apply MvPolynomial.algHom_ext
    intro i
    simp [h]
  exact
    { parameterCount := n
      forms := X
      forms_isHomogeneous := fun i ↦ isHomogeneous_X (R := K) i
      injective := by
        change Function.Injective h
        rw [hh]
        exact (Ideal.Quotient.mk_bijective_iff_eq_bot ⊥).mpr rfl |>.injective
      finite := by
        change h.Finite
        rw [hh]
        exact AlgHom.Finite.of_surjective _
          (Ideal.Quotient.mkₐ_surjective K ⊥) }

/-- A proper ideal in a polynomial algebra on no variables is zero. -/
theorem ideal_eq_bot_of_isEmpty
    [IsEmpty σ] (I : Ideal (MvPolynomial σ K)) (hI : I ≠ ⊤) :
    I = ⊥ := by
  apply bot_unique
  intro p hp
  by_contra hpne
  have heq := MvPolynomial.eq_C_of_isEmpty p
  have hcoeff : coeff 0 p ≠ 0 := fun h ↦
    hpne (heq.trans (h ▸ map_zero MvPolynomial.C))
  obtain ⟨c, -, hc⟩ := isUnit_iff_exists.mp hcoeff.isUnit
  have hone : c • p = 1 := by
    rw [MvPolynomial.smul_eq_C_mul, heq, ← map_mul, hc,
      MvPolynomial.C_1]
  exact hI ((Ideal.eq_top_iff_one I).mpr
    (hone ▸ I.smul_of_tower_mem c hp))

/-- Iterated homogeneous linear Noether normalization for a homogeneous
prime ideal.  Unlike Mathlib's general normalization theorem, every
parameter in the result is visibly a degree-one form in the original
coordinates. -/
theorem exists_homogeneousLinearNormalizationData
    [Infinite K] (n : ℕ) (I : Ideal (MvPolynomial (Fin n) K))
    (hprime : I.IsPrime)
    (hhom : I.IsHomogeneous
      (MvPolynomial.homogeneousSubmodule (Fin n) K)) :
    Nonempty (HomogeneousLinearNormalizationData I) := by
  induction n with
  | zero =>
      have hbot : I = ⊥ :=
        ideal_eq_bot_of_isEmpty I hprime.ne_top
      subst I
      exact ⟨homogeneousLinearNormalizationDataBot 0⟩
  | succ n ih =>
      by_cases hbot : I = ⊥
      · subst I
        exact ⟨homogeneousLinearNormalizationDataBot (n + 1)⟩
      · let e : Fin (n + 1) ≃ Option (Fin n) := _root_.finSuccEquiv n
        let T : MvPolynomial (Fin (n + 1)) K ≃ₐ[K]
            MvPolynomial (Option (Fin n)) K :=
          MvPolynomial.renameEquiv K e
        let J : Ideal (MvPolynomial (Option (Fin n)) K) := I.map T
        have hJhom : J.IsHomogeneous
            (MvPolynomial.homogeneousSubmodule (Option (Fin n)) K) := by
          simpa [J, T] using map_renameEquiv_isHomogeneous e I hhom
        have hJne : J ≠ ⊥ := by
          dsimp only [J, T]
          exact (Ideal.map_eq_bot_iff_of_injective
            (MvPolynomial.renameEquiv K e).injective).not.mpr hbot
        letI : I.IsPrime := hprime
        have hJprime : J.IsPrime := by
          dsimp only [J, T]
          infer_instance
        obtain ⟨f, d, hfJ, hfhom, hfne⟩ :=
          exists_nonzero_isHomogeneous_mem_of_isHomogeneous_ne_bot
            J hJhom hJne
        obtain ⟨c, hcfinite, -⟩ :=
          exists_finite_homogeneousLinearEliminationHom
            J f d hfJ hfhom hfne
        let h : MvPolynomial (Fin n) K →ₐ[K]
            (MvPolynomial (Option (Fin n)) K ⧸ J) :=
          homogeneousLinearEliminationHom c J
        let l : Fin n → MvPolynomial (Option (Fin n)) K :=
          homogeneousLinearEliminationForm c
        have hh : h = (Ideal.Quotient.mkₐ K J).comp (aeval l) := by
          apply MvPolynomial.algHom_ext
          intro i
          simp [h, l, homogeneousLinearEliminationHom_X,
            homogeneousLinearEliminationForm]
        have hhfinite : h.Finite := by
          simpa [h] using hcfinite
        let P : Ideal (MvPolynomial (Fin n) K) := RingHom.ker h
        have hPhom : P.IsHomogeneous
            (MvPolynomial.homogeneousSubmodule (Fin n) K) := by
          simpa [P, h] using
            kernel_homogeneousLinearEliminationHom_isHomogeneous
              c J hJhom
        letI : J.IsPrime := hJprime
        have hPprime : P.IsPrime := by
          dsimp only [P]
          exact RingHom.ker_isPrime h
        obtain ⟨D⟩ := ih P hPprime hPhom
        have hl : ∀ i, (l i).IsHomogeneous 1 := by
          intro i
          exact homogeneousLinearEliminationForm_isHomogeneous c i
        let DJ : HomogeneousLinearNormalizationData J :=
          { parameterCount := D.parameterCount
            forms := fun i ↦ aeval l (D.forms i)
            forms_isHomogeneous := fun i ↦ by
              simpa using (D.forms_isHomogeneous i).aeval l hl
            injective := by
              rw [← kerLift_comp_normalizationHom J l h hh
                D.parameterCount D.forms]
              exact (Ideal.kerLiftAlg_injective h).comp D.injective
            finite := by
              rw [← kerLift_comp_normalizationHom J l h hh
                D.parameterCount D.forms]
              exact AlgHom.Finite.comp
                (kerLiftAlg_finite_of_finite h hhfinite) D.finite }
        exact ⟨DJ.renameEquiv e I⟩

/-! ## Retaining a distinguished coordinate -/

/-- Reindex `X₀,X₁,…,Xₙ₊₁` so that `X₁` is the variable to be
eliminated, while `X₀` becomes the distinguished variable in the retained
coefficient ring. -/
def distinguishedFinSuccEquiv (n : ℕ) :
    Option (Fin (n + 1)) ≃ Option (Option (Fin n)) :=
  (Equiv.optionCongr (_root_.finSuccEquiv n)).trans
    (Equiv.swap none (some none))

@[simp]
theorem distinguishedFinSuccEquiv_none (n : ℕ) :
    distinguishedFinSuccEquiv n none = some none := by
  simp [distinguishedFinSuccEquiv]

@[simp]
theorem distinguishedFinSuccEquiv_some_zero (n : ℕ) :
    distinguishedFinSuccEquiv n (some 0) = none := by
  simp [distinguishedFinSuccEquiv]

@[simp]
theorem distinguishedFinSuccEquiv_some_succ (n : ℕ) (i : Fin n) :
    distinguishedFinSuccEquiv n (some i.succ) = some (some i) := by
  simp only [distinguishedFinSuccEquiv, Equiv.trans_apply,
    Equiv.optionCongr_apply]
  rw [Equiv.swap_apply_of_ne_of_ne] <;> simp

@[simp]
theorem distinguishedFinSuccEquiv_symm_some_none (n : ℕ) :
    (distinguishedFinSuccEquiv n).symm (some none) = none := by
  apply (distinguishedFinSuccEquiv n).injective
  simp

/-- Under the distinguished reindexing, avoidance of `X₀` is transported
to avoidance of the retained variable `X_(some none)`. -/
theorem X_some_none_not_mem_map_distinguishedFinSuccEquiv
    (n : ℕ) (I : Ideal (MvPolynomial (Option (Fin (n + 1))) K))
    (hX : X none ∉ I) :
    X (some none) ∉
      I.map (MvPolynomial.renameEquiv K (distinguishedFinSuccEquiv n)) := by
  intro hx
  apply hX
  have hxcomap : X none ∈
      (I.map (MvPolynomial.renameEquiv K
        (distinguishedFinSuccEquiv n))).comap
          (MvPolynomial.renameEquiv K (distinguishedFinSuccEquiv n)) := by
    change MvPolynomial.rename (distinguishedFinSuccEquiv n)
      (X none : MvPolynomial (Option (Fin (n + 1))) K) ∈
        I.map (MvPolynomial.renameEquiv K (distinguishedFinSuccEquiv n))
    simpa using hx
  rw [Ideal.comap_map_of_bijective _
    (MvPolynomial.renameEquiv K
      (distinguishedFinSuccEquiv n)).bijective] at hxcomap
  exact hxcomap

/-- A homogeneous linear normalization which visibly retains `X_none` as
one of its parameters. -/
structure DistinguishedHomogeneousLinearNormalizationData
    {τ : Type v} (I : Ideal (MvPolynomial (Option τ) K)) where
  toLinearNormalization : HomogeneousLinearNormalizationData I
  parameterCount_pos : 0 < toLinearNormalization.parameterCount
  fixes_distinguished :
    toLinearNormalization.forms ⟨0, parameterCount_pos⟩ = X none

/-- The distinguished coordinate itself normalizes the zero ideal in one
variable. -/
def distinguishedHomogeneousLinearNormalizationDataBotZero :
    DistinguishedHomogeneousLinearNormalizationData
      (⊥ : Ideal (MvPolynomial (Option (Fin 0)) K)) := by
  let e : Fin 1 ≃ Option (Fin 0) := _root_.finSuccEquiv 0
  let l : Fin 1 → MvPolynomial (Option (Fin 0)) K :=
    fun _ ↦ X none
  have haeval : MvPolynomial.aeval l =
      (MvPolynomial.renameEquiv K e).toAlgHom := by
    apply MvPolynomial.algHom_ext
    intro i
    have hi : i = 0 := Fin.eq_zero i
    subst i
    simp [l, e]
  let D : HomogeneousLinearNormalizationData
      (⊥ : Ideal (MvPolynomial (Option (Fin 0)) K)) :=
    { parameterCount := 1
      forms := l
      forms_isHomogeneous := fun _ ↦ isHomogeneous_X (R := K) none
      injective := by
        rw [haeval]
        exact (Ideal.Quotient.mk_bijective_iff_eq_bot ⊥).mpr rfl |>.injective.comp
          (MvPolynomial.renameEquiv K e).injective
      finite := by
        rw [haeval]
        exact AlgHom.Finite.comp
          (AlgHom.Finite.of_surjective _
            (Ideal.Quotient.mkₐ_surjective K ⊥))
          (AlgHom.Finite.of_surjective _
            (MvPolynomial.renameEquiv K e).surjective) }
  exact
    { toLinearNormalization := D
      parameterCount_pos := Nat.zero_lt_one
      fixes_distinguished := by simp [D, l] }

/-- The exact relation input needed at a distinguished elimination step.
It says that a nonzero homogeneous prime ideal, avoiding the retained
coordinate `X_(some none)`, contains a homogeneous equation which is
nonzero at `[1:c]` with `c none = 0`.  No geometric terminology is hidden in
this definition. -/
def DistinguishedAffineChartRelationSupply (K : Type u) [Field K] : Prop :=
  ∀ (n : ℕ)
    (J : Ideal (MvPolynomial (Option (Option (Fin n))) K)),
    J.IsPrime →
    J.IsHomogeneous
      (MvPolynomial.homogeneousSubmodule (Option (Option (Fin n))) K) →
    J ≠ ⊥ → X (some none) ∉ J →
    ∃ (f : MvPolynomial (Option (Option (Fin n))) K) (d : ℕ)
      (c : Option (Fin n) → K),
      f ∈ J ∧ f.IsHomogeneous d ∧ c none = 0 ∧
        eval (affineChartVector c) f ≠ 0

/-- Cancelling one variable lowers the homogeneous degree by one. -/
theorem isHomogeneous_of_X_mul
    {τ : Type*} (i : τ) (g : MvPolynomial τ K) (d : ℕ)
    (hhom : (X i * g).IsHomogeneous d) (hne : g ≠ 0) :
    g.IsHomogeneous (d - 1) ∧ 0 < d := by
  obtain ⟨m₀, hm₀⟩ := MvPolynomial.exists_coeff_ne_zero hne
  have hm₀' : MvPolynomial.coeff (Finsupp.single i 1 + m₀)
      (X i * g) ≠ 0 := by
    simpa using hm₀
  have hone : Finsupp.weight (1 : τ → ℕ) (Finsupp.single i 1) = 1 := by
    simp [Finsupp.weight_apply]
  have hdegree₀ := hhom hm₀'
  have hdpos : 0 < d := by
    rw [map_add, hone] at hdegree₀
    omega
  refine ⟨?_, hdpos⟩
  intro m hm
  have hm' : MvPolynomial.coeff (Finsupp.single i 1 + m)
      (X i * g) ≠ 0 := by
    simpa using hm
  have hdegree := hhom hm'
  rw [map_add, hone] at hdegree
  omega

/-- Evaluation after setting `X_(some none)=0` can be read as the constant
coefficient after swapping that variable into the polynomial position. -/
theorem eval_affineChartVector_eq_eval_swap_coeff_zero
    (n : ℕ) (f : MvPolynomial (Option (Option (Fin n))) K)
    (z : Fin n → K) :
    let s : Equiv.Perm (Option (Option (Fin n))) :=
      Equiv.swap none (some none)
    let F := MvPolynomial.rename s f
    let g := (optionEquivLeft K (Option (Fin n)) F).coeff 0
    let c : Option (Fin n) → K := fun u ↦ Option.elim u 0 z
    eval (affineChartVector c) f = eval (affineChartVector z) g := by
  dsimp only
  let s : Equiv.Perm (Option (Option (Fin n))) :=
    Equiv.swap none (some none)
  let b : Option (Fin n) → K := affineChartVector z
  let c : Option (Fin n) → K := fun u ↦ Option.elim u 0 z
  have hassign :
      (fun x ↦ Option.elim x 0 b) ∘ s = affineChartVector c := by
    funext x
    cases x with
    | none => simp [s, b, affineChartVector]
    | some u =>
        cases u with
        | none => simp [s, b, c, affineChartVector]
        | some i =>
            simp only [s, Function.comp_apply]
            rw [Equiv.swap_apply_of_ne_of_ne] <;>
              simp [b, c, affineChartVector]
  calc
    eval (affineChartVector c) f =
        eval (fun x ↦ Option.elim x 0 b) (MvPolynomial.rename s f) := by
      rw [MvPolynomial.eval_rename, hassign]
    _ = Polynomial.eval 0
        (Polynomial.map (eval b)
          (optionEquivLeft K (Option (Fin n))
            (MvPolynomial.rename s f))) :=
      MvPolynomial.optionEquivLeft_elim_eval K (Option (Fin n)) b 0 _
    _ = eval b
        ((optionEquivLeft K (Option (Fin n))
          (MvPolynomial.rename s f)).coeff 0) := by
      rw [Polynomial.eval_map, Polynomial.eval₂_at_zero]
    _ = eval (affineChartVector z)
        ((optionEquivLeft K (Option (Fin n))
          (MvPolynomial.rename s f)).coeff 0) := rfl

/-- Over an infinite field the distinguished affine-chart relation supply
is automatic.  The proof chooses a homogeneous relation of minimal degree,
so it cannot be divisible by the distinguished variable; its restriction to
that hyperplane is then a nonzero homogeneous polynomial, and hence is
nonzero somewhere on the remaining standard affine chart. -/
theorem distinguishedAffineChartRelationSupply_of_infinite
    [Infinite K] : DistinguishedAffineChartRelationSupply K := by
  classical
  intro n J hprime hhom hJne hX
  let Q : ℕ → Prop := fun d ↦
    ∃ f : MvPolynomial (Option (Option (Fin n))) K,
      f ∈ J ∧ f.IsHomogeneous d ∧ f ≠ 0
  have hQ : ∃ d, Q d := by
    obtain ⟨f, d, hfJ, hfhom, hfne⟩ :=
      exists_nonzero_isHomogeneous_mem_of_isHomogeneous_ne_bot
        J hhom hJne
    exact ⟨d, f, hfJ, hfhom, hfne⟩
  let d := Nat.find hQ
  obtain ⟨f, hfJ, hfhom, hfne⟩ : Q d := Nat.find_spec hQ
  have hnotdvd :
      ¬(X (some none) :
        MvPolynomial (Option (Option (Fin n))) K) ∣ f := by
    rintro ⟨g, hfg⟩
    have hgne : g ≠ 0 := by
      intro hg
      apply hfne
      rw [hfg, hg, mul_zero]
    have hprodHom : (X (some none) * g).IsHomogeneous d := by
      simpa [hfg] using hfhom
    obtain ⟨hghom, hdpos⟩ :=
      isHomogeneous_of_X_mul (some none) g d hprodHom hgne
    have hprodJ : X (some none) * g ∈ J := by
      simpa [hfg] using hfJ
    have hgJ : g ∈ J :=
      (hprime.mem_or_mem hprodJ).resolve_left hX
    have hQprev : Q (d - 1) := ⟨g, hgJ, hghom, hgne⟩
    have hminimal : d ≤ d - 1 := by
      change Nat.find hQ ≤ d - 1
      exact Nat.find_min' hQ hQprev
    omega
  let s : Equiv.Perm (Option (Option (Fin n))) :=
    Equiv.swap none (some none)
  let E : MvPolynomial (Option (Option (Fin n))) K ≃ₐ[K]
      (MvPolynomial (Option (Fin n)) K)[X] :=
    (MvPolynomial.renameEquiv K s).trans
      (optionEquivLeft K (Option (Fin n)))
  let p : (MvPolynomial (Option (Fin n)) K)[X] := E f
  have hEX : E (X (some none)) = Polynomial.X := by
    dsimp only [E, AlgEquiv.trans_apply]
    rw [MvPolynomial.renameEquiv_apply, MvPolynomial.rename_X]
    have hs : s (some none) = none := by simp [s]
    rw [hs]
    exact MvPolynomial.optionEquivLeft_X_none K (Option (Fin n))
  have hpnotdvd : ¬ Polynomial.X ∣ p := by
    intro hp
    apply hnotdvd
    obtain ⟨q, hq⟩ := hp
    refine ⟨E.symm q, ?_⟩
    apply E.injective
    rw [map_mul, E.apply_symm_apply, hEX]
    exact hq
  let g : MvPolynomial (Option (Fin n)) K := p.coeff 0
  have hgne : g ≠ 0 := by
    intro hg
    apply hpnotdvd
    rw [Polynomial.X_dvd_iff]
    exact hg
  have hFhom : ((optionEquivLeft K (Option (Fin n))).symm p).IsHomogeneous d := by
    have hpull : (optionEquivLeft K (Option (Fin n))).symm p =
        MvPolynomial.rename s f := by
      simp [p, E]
    rw [hpull]
    exact hfhom.rename_isHomogeneous
  have hghom : g.IsHomogeneous d := by
    exact hFhom.coeff_isHomogeneous_of_optionEquivLeft_symm 0 d (by omega)
  obtain ⟨z, hz⟩ :=
    exists_eval_affineChartVector_ne_zero_of_isHomogeneous
      g d hghom hgne
  let c : Option (Fin n) → K := fun u ↦ Option.elim u 0 z
  refine ⟨f, d, c, hfJ, hfhom, ?_, ?_⟩
  · rfl
  · have heval : eval (affineChartVector c) f =
        eval (affineChartVector z) g := by
      simpa [s, E, p, g, c] using
        eval_affineChartVector_eq_eval_swap_coeff_zero n f z
    intro hzero
    apply hz
    rw [← heval]
    exact hzero

/-- In one homogeneous variable there is only one monomial of each total
degree. -/
theorem finsupp_option_fin_zero_eq_single_none
    (m : Option (Fin 0) →₀ ℕ) :
    m = Finsupp.single none m.degree := by
  apply Finsupp.ext
  intro i
  cases i with
  | none =>
      rw [finsupp_degree_option]
      have hsome : m.some = 0 := Subsingleton.elim _ _
      rw [hsome]
      simp
  | some i => exact Fin.elim0 i

theorem isHomogeneous_option_fin_zero_eq_monomial
    (f : MvPolynomial (Option (Fin 0)) K) (d : ℕ)
    (hf : f.IsHomogeneous d) :
    f = monomial (Finsupp.single none d)
      (coeff (Finsupp.single none d) f) := by
  classical
  ext m
  by_cases hm : m = Finsupp.single none d
  · subst m
    simp
  · have hmdegree : m.degree ≠ d := by
      intro hdegree
      apply hm
      rw [finsupp_option_fin_zero_eq_single_none m, hdegree]
    rw [hf.coeff_eq_zero hmdegree]
    simp [MvPolynomial.coeff_monomial, Ne.symm hm]

/-- The one-variable terminal condition in the distinguished recursion is
automatic for a homogeneous prime ideal avoiding the distinguished
variable. -/
theorem homogeneousPrime_option_fin_zero_eq_bot
    (P : Ideal (MvPolynomial (Option (Fin 0)) K))
    (hprime : P.IsPrime)
    (hhom : P.IsHomogeneous
      (MvPolynomial.homogeneousSubmodule (Option (Fin 0)) K))
    (hX : X none ∉ P) :
    P = ⊥ := by
  by_contra hP
  obtain ⟨f, d, hfP, hfhom, hfne⟩ :=
    exists_nonzero_isHomogeneous_mem_of_isHomogeneous_ne_bot
      P hhom hP
  let a : K := coeff (Finsupp.single none d) f
  have hfshape : f = MvPolynomial.C a * X none ^ d := by
    rw [isHomogeneous_option_fin_zero_eq_monomial f d hfhom]
    exact MvPolynomial.C_mul_X_pow_eq_monomial.symm
  have ha : a ≠ 0 := by
    intro ha
    apply hfne
    simp [hfshape, ha]
  have hpow : (X none : MvPolynomial (Option (Fin 0)) K) ^ d ∈ P := by
    have hscaled := P.smul_of_tower_mem a⁻¹ hfP
    rw [hfshape, MvPolynomial.smul_eq_C_mul] at hscaled
    simpa [ha] using hscaled
  exact hX (hprime.mem_of_pow_mem d hpow)

/-- Iterated linear normalization retaining `X₀`.  The two hypotheses are
written as exact algebraic statements: the one-variable terminal ideal is
zero, and at every nonterminal stage a relation nonvanishing at a point
with distinguished coordinate zero is available.  Thus any geometric
proper-infinity argument which proves precisely these statements can be
inserted without changing the algebraic recursion. -/
theorem exists_distinguishedHomogeneousLinearNormalizationData
    [Infinite K]
    (hsupply : DistinguishedAffineChartRelationSupply K)
    (hterminal : ∀
      (P : Ideal (MvPolynomial (Option (Fin 0)) K)),
      P.IsPrime →
      P.IsHomogeneous
        (MvPolynomial.homogeneousSubmodule (Option (Fin 0)) K) →
      X none ∉ P → P = ⊥)
    (n : ℕ) (I : Ideal (MvPolynomial (Option (Fin n)) K))
    (hprime : I.IsPrime)
    (hhom : I.IsHomogeneous
      (MvPolynomial.homogeneousSubmodule (Option (Fin n)) K))
    (hX : X none ∉ I) :
    Nonempty (DistinguishedHomogeneousLinearNormalizationData I) := by
  induction n with
  | zero =>
      have hbot := hterminal I hprime hhom hX
      subst I
      exact ⟨distinguishedHomogeneousLinearNormalizationDataBotZero⟩
  | succ n ih =>
      by_cases hbot : I = ⊥
      · subst I
        let e₀ : Fin (n + 2) ≃ Option (Fin (n + 1)) :=
          _root_.finSuccEquiv (n + 1)
        let l₀ : Fin (n + 2) →
            MvPolynomial (Option (Fin (n + 1))) K :=
          fun i ↦ X (e₀ i)
        have haeval₀ : MvPolynomial.aeval l₀ =
            (MvPolynomial.renameEquiv K e₀).toAlgHom := by
          apply MvPolynomial.algHom_ext
          intro i
          simp [l₀]
        let D : HomogeneousLinearNormalizationData
            (⊥ : Ideal (MvPolynomial (Option (Fin (n + 1))) K)) :=
          { parameterCount := n + 2
            forms := l₀
            forms_isHomogeneous := fun i ↦
              isHomogeneous_X (R := K) (e₀ i)
            injective := by
              rw [haeval₀]
              exact (Ideal.Quotient.mk_bijective_iff_eq_bot ⊥).mpr rfl
                |>.injective.comp (MvPolynomial.renameEquiv K e₀).injective
            finite := by
              rw [haeval₀]
              exact AlgHom.Finite.comp
                (AlgHom.Finite.of_surjective _
                  (Ideal.Quotient.mkₐ_surjective K ⊥))
                (AlgHom.Finite.of_surjective _
                  (MvPolynomial.renameEquiv K e₀).surjective) }
        refine ⟨
          { toLinearNormalization := D
            parameterCount_pos := by
              change 0 < n + 2
              omega
            fixes_distinguished := ?_ }⟩
        simp [D, l₀, e₀]
      · let e : Option (Fin (n + 1)) ≃ Option (Option (Fin n)) :=
          distinguishedFinSuccEquiv n
        let T : MvPolynomial (Option (Fin (n + 1))) K ≃ₐ[K]
            MvPolynomial (Option (Option (Fin n))) K :=
          MvPolynomial.renameEquiv K e
        let J : Ideal (MvPolynomial (Option (Option (Fin n))) K) :=
          I.map T
        have hJhom : J.IsHomogeneous
            (MvPolynomial.homogeneousSubmodule
              (Option (Option (Fin n))) K) := by
          simpa [J, T] using map_renameEquiv_isHomogeneous e I hhom
        have hJne : J ≠ ⊥ := by
          dsimp only [J, T]
          exact (Ideal.map_eq_bot_iff_of_injective
            (MvPolynomial.renameEquiv K e).injective).not.mpr hbot
        letI : I.IsPrime := hprime
        have hJprime : J.IsPrime := by
          dsimp only [J, T]
          infer_instance
        have hJX : X (some none) ∉ J := by
          simpa [J, T, e] using
            X_some_none_not_mem_map_distinguishedFinSuccEquiv n I hX
        obtain ⟨f, d, c, hfJ, hfhom, hc₀, hceval⟩ :=
          hsupply n J hJprime hJhom hJne hJX
        have hcfinite :
            (homogeneousLinearEliminationHom c J).Finite :=
          finite_homogeneousLinearEliminationHom_of_eval_ne_zero
            J f d hfJ hfhom c hceval
        let h : MvPolynomial (Option (Fin n)) K →ₐ[K]
            (MvPolynomial (Option (Option (Fin n))) K ⧸ J) :=
          homogeneousLinearEliminationHom c J
        let l : Option (Fin n) →
            MvPolynomial (Option (Option (Fin n))) K :=
          homogeneousLinearEliminationForm c
        have hh : h = (Ideal.Quotient.mkₐ K J).comp (aeval l) := by
          apply MvPolynomial.algHom_ext
          intro i
          simp [h, l, homogeneousLinearEliminationHom_X,
            homogeneousLinearEliminationForm]
        have hhfinite : h.Finite := by
          simpa [h] using hcfinite
        let P : Ideal (MvPolynomial (Option (Fin n)) K) := RingHom.ker h
        have hPhom : P.IsHomogeneous
            (MvPolynomial.homogeneousSubmodule (Option (Fin n)) K) := by
          simpa [P, h] using
            kernel_homogeneousLinearEliminationHom_isHomogeneous
              c J hJhom
        letI : J.IsPrime := hJprime
        have hPprime : P.IsPrime := by
          dsimp only [P]
          exact RingHom.ker_isPrime h
        have hPX : X none ∉ P := by
          intro hxP
          have hxP' : X none ∈ RingHom.ker h := by
            simpa only [P] using hxP
          have hxzero : h (X none) = 0 := by
            exact RingHom.mem_ker.mp hxP'
          have hfix : h (X none) =
              Ideal.Quotient.mk J (X (some none)) := by
            change homogeneousLinearEliminationHom c J (X none) = _
            exact homogeneousLinearEliminationHom_fixes_of_eq_zero
              c J none hc₀
          rw [hfix] at hxzero
          exact hJX (Ideal.Quotient.eq_zero_iff_mem.mp hxzero)
        obtain ⟨Ddist⟩ := ih P hPprime hPhom hPX
        let D := Ddist.toLinearNormalization
        have hl : ∀ i, (l i).IsHomogeneous 1 := by
          intro i
          exact homogeneousLinearEliminationForm_isHomogeneous c i
        let DJ : HomogeneousLinearNormalizationData J :=
          { parameterCount := D.parameterCount
            forms := fun i ↦ aeval l (D.forms i)
            forms_isHomogeneous := fun i ↦ by
              simpa using (D.forms_isHomogeneous i).aeval l hl
            injective := by
              rw [← kerLift_comp_normalizationHom J l h hh
                D.parameterCount D.forms]
              exact (Ideal.kerLiftAlg_injective h).comp D.injective
            finite := by
              rw [← kerLift_comp_normalizationHom J l h hh
                D.parameterCount D.forms]
              exact AlgHom.Finite.comp
                (kerLiftAlg_finite_of_finite h hhfinite) D.finite }
        let DI : HomogeneousLinearNormalizationData I :=
          DJ.renameEquiv e I
        refine ⟨
          { toLinearNormalization := DI
            parameterCount_pos := Ddist.parameterCount_pos
            fixes_distinguished := ?_ }⟩
        change MvPolynomial.rename e.symm
          (aeval l (D.forms ⟨0, Ddist.parameterCount_pos⟩)) = X none
        rw [Ddist.fixes_distinguished]
        simp [l, homogeneousLinearEliminationForm, hc₀, e]

/-- Clean distinguished endpoint: the affine-chart relation supply is the
only extra input.  The terminal case is discharged algebraically by
`homogeneousPrime_option_fin_zero_eq_bot`. -/
theorem exists_distinguishedHomogeneousLinearNormalizationData_of_relationSupply
    [Infinite K]
    (hsupply : DistinguishedAffineChartRelationSupply K)
    (n : ℕ) (I : Ideal (MvPolynomial (Option (Fin n)) K))
    (hprime : I.IsPrime)
    (hhom : I.IsHomogeneous
      (MvPolynomial.homogeneousSubmodule (Option (Fin n)) K))
    (hX : X none ∉ I) :
    Nonempty (DistinguishedHomogeneousLinearNormalizationData I) :=
  exists_distinguishedHomogeneousLinearNormalizationData hsupply
    homogeneousPrime_option_fin_zero_eq_bot n I hprime hhom hX

/-- Homogeneous linear Noether normalization retaining `X₀`, with no
extra relation hypothesis: over an infinite field, homogeneity, primality,
and `X₀ ∉ I` supply all required elimination relations. -/
theorem exists_distinguishedHomogeneousLinearNormalizationData_of_X_not_mem
    [Infinite K]
    (n : ℕ) (I : Ideal (MvPolynomial (Option (Fin n)) K))
    (hprime : I.IsPrime)
    (hhom : I.IsHomogeneous
      (MvPolynomial.homogeneousSubmodule (Option (Fin n)) K))
    (hX : X none ∉ I) :
    Nonempty (DistinguishedHomogeneousLinearNormalizationData I) :=
  exists_distinguishedHomogeneousLinearNormalizationData_of_relationSupply
    distinguishedAffineChartRelationSupply_of_infinite
    n I hprime hhom hX

end

end TranslatedDepthSeven
