import TranslatedDepthSeven.IsolatedVertexQuotientGeometry
import TranslatedDepthSeven.ProjectiveHilbertCoefficientExtension
import TranslatedDepthSeven.TranslatedConeIdealStructure
import TranslatedDepthSeven.ConcreteExceptionalLocus
import TranslatedDepthSeven.GradedLinearSubstitution

/-!
# Components of a four-plane section of the isolated-vertex quotient

This file records the literal projective intersection which occurs after a
quotient residue packet has been put in an affine eight-plane.  Its
components are actual minimal prime ideals over `Qbar`.  The elementary
part of the argument (linear equations, the vertex test, and the finite
partition by dimension and degree) is proved in the kernel.

Two ordinary projective-geometric component correspondences are isolated as
textbook inputs.  They say only how irreducible components behave under the
linear projection from the vertex of a cone.  They contain no point-count,
no reservoir assertion, and no determinant-method conclusion.
-/

namespace TranslatedDepthSeven

noncomputable section

open scoped BigOperators
open Matrix MvPolynomial Published

attribute [local instance] MvPolynomial.gradedAlgebra

set_option maxHeartbeats 4000000

/-! ## Literal ideals and the vertex -/

/-- A row of a matrix, regarded as a homogeneous linear polynomial over an
arbitrary coefficient field. -/
def matrixRowLinearPolynomial {K : Type*} [Field K] {c N : ℕ}
    (A : Matrix (Fin c) (Fin N) K) (i : Fin c) :
    MvPolynomial (Fin N) K :=
  ∑ j, C (A i j) * X j

theorem matrixRowLinearPolynomial_isHomogeneous
    {K : Type*} [Field K] {c N : ℕ}
    (A : Matrix (Fin c) (Fin N) K) (i : Fin c) :
    (matrixRowLinearPolynomial A i).IsHomogeneous 1 := by
  apply MvPolynomial.IsHomogeneous.sum Finset.univ _ 1
  intro j _hj
  exact MvPolynomial.isHomogeneous_C_mul_X _ _

@[simp]
theorem eval_matrixRowLinearPolynomial {K : Type*} [Field K] {c N : ℕ}
    (A : Matrix (Fin c) (Fin N) K) (i : Fin c) (x : Fin N → K) :
    eval x (matrixRowLinearPolynomial A i) = (Matrix.mulVec A x) i := by
  simp [matrixRowLinearPolynomial, Matrix.mulVec, dotProduct]

/-- The homogeneous ideal generated by the rows of a matrix. -/
def matrixRowLinearIdeal {K : Type*} [Field K] {c N : ℕ}
    (A : Matrix (Fin c) (Fin N) K) : Ideal (MvPolynomial (Fin N) K) :=
  Ideal.span (Set.range (matrixRowLinearPolynomial A))

theorem matrixRowLinearIdeal_isHomogeneous
    {K : Type*} [Field K] {c N : ℕ}
    (A : Matrix (Fin c) (Fin N) K) :
    (matrixRowLinearIdeal A).IsHomogeneous
      (MvPolynomial.homogeneousSubmodule (Fin N) K) := by
  apply Ideal.homogeneous_span
  rintro f ⟨i, rfl⟩
  exact ⟨1, matrixRowLinearPolynomial_isHomogeneous A i⟩

/-- Adjoin a zero first column to a matrix of homogeneous equations. -/
def matrixPrependZeroColumn {K : Type*} [Zero K] {c N : ℕ}
    (A : Matrix (Fin c) (Fin N) K) : Matrix (Fin c) (Fin (N + 1)) K :=
  fun i j ↦ Fin.cases 0 (A i) j

/-- Adjoining a zero column does not change matrix rank. -/
theorem matrixPrependZeroColumn_rank
    {K : Type*} [Field K] {c N : ℕ}
    (A : Matrix (Fin c) (Fin N) K) :
    (matrixPrependZeroColumn A).rank = A.rank := by
  have hmul (v : Fin (N + 1) → K) :
      (matrixPrependZeroColumn A).mulVec v =
        A.mulVec (fun j ↦ v j.succ) := by
    funext i
    simp [Matrix.mulVec, dotProduct, matrixPrependZeroColumn,
      Fin.sum_univ_succ]
  have hrange :
      LinearMap.range (matrixPrependZeroColumn A).mulVecLin =
        LinearMap.range A.mulVecLin := by
    ext y
    constructor
    · rintro ⟨v, rfl⟩
      exact ⟨fun j ↦ v j.succ, by simpa using (hmul v).symm⟩
    · rintro ⟨w, rfl⟩
      refine ⟨Fin.cases 0 w, ?_⟩
      change (matrixPrependZeroColumn A).mulVec (Fin.cases 0 w) = A.mulVec w
      rw [hmul]
      rfl
  rw [Matrix.rank, Matrix.rank, hrange]

theorem matrixRowLinearIdeal_le_evaluationKernel_iff
    {K : Type*} [Field K] {c N : ℕ}
    (A : Matrix (Fin c) (Fin N) K) (x : Fin N → K) :
    matrixRowLinearIdeal A ≤ RingHom.ker (eval x) ↔
      Matrix.mulVec A x = 0 := by
  constructor
  · intro h
    funext i
    have hi : matrixRowLinearPolynomial A i ∈ matrixRowLinearIdeal A :=
      Ideal.subset_span (Set.mem_range_self i)
    have hzero := RingHom.mem_ker.mp (h hi)
    simpa only [eval_matrixRowLinearPolynomial] using hzero
  · intro h
    apply Ideal.span_le.2
    rintro f ⟨i, rfl⟩
    apply RingHom.mem_ker.mpr
    rw [eval_matrixRowLinearPolynomial]
    simpa using congrFun h i

/-- A proper homogeneous ideal contains no nonzero constant term.  Written
as an ideal containment, this says that its affine cone contains the
origin. -/
theorem homogeneousPrimeIdeal_le_eval_zero
    {K : Type*} [Field K] {N : ℕ}
    (I : Ideal (MvPolynomial (Fin N) K))
    (hIprime : I.IsPrime)
    (hIhomogeneous : I.IsHomogeneous
      (MvPolynomial.homogeneousSubmodule (Fin N) K)) :
    I ≤ RingHom.ker (eval (0 : Fin N → K)) := by
  intro f hf
  apply RingHom.mem_ker.mpr
  have hzeroComponent : homogeneousComponent 0 f ∈ I :=
    homogeneousComponent_mem_of_mem_homogeneousIdeal I hIhomogeneous hf 0
  rw [MvPolynomial.homogeneousComponent_zero] at hzeroComponent
  have hconstant : f.coeff 0 = 0 := by
    by_contra hne
    have hone : (1 : MvPolynomial (Fin N) K) ∈ I := by
      have hmul := I.mul_mem_left (C (f.coeff 0)⁻¹) hzeroComponent
      rwa [← MvPolynomial.C.map_mul, inv_mul_cancel₀ hne,
        MvPolynomial.C_1] at hmul
    exact hIprime.ne_top ((Ideal.eq_top_iff_one I).mpr hone)
  simp only [MvPolynomial.eval_zero, MvPolynomial.constantCoeff_eq,
    hconstant]

/-- The coordinate cone over a proper homogeneous prime contains every
point on its vertex axis. -/
theorem projectiveConeIdealExtension_le_vertexAxis_eval
    {K : Type*} [Field K] {N : ℕ}
    (I : Ideal (MvPolynomial (Fin N) K))
    (hIprime : I.IsPrime)
    (hIhomogeneous : I.IsHomogeneous
      (MvPolynomial.homogeneousSubmodule (Fin N) K))
    (r : K) :
    projectiveConeIdealExtension I ≤
      RingHom.ker (eval (fun j : Option (Fin N) ↦ j.elim r (fun _ ↦ 0))) := by
  rw [projectiveConeIdealExtension, Ideal.map_le_iff_le_comap]
  intro f hf
  apply RingHom.mem_ker.mpr
  rw [MvPolynomial.eval_rename]
  exact RingHom.mem_ker.mp
    (homogeneousPrimeIdeal_le_eval_zero I hIprime hIhomogeneous hf)

/-- The homogeneous affine transform of a cone contains the inverse image
of its coordinate vertex. -/
theorem translatedProjectiveConeIdeal_le_vertex_eval
    {K : Type*} [Field K] {N : ℕ}
    (b : Fin N → K) (m : K) (hm : m ≠ 0)
    (I : Ideal (MvPolynomial (Fin N) K))
    (hIprime : I.IsPrime)
    (hIhomogeneous : I.IsHomogeneous
      (MvPolynomial.homogeneousSubmodule (Fin N) K)) :
    translatedProjectiveConeIdeal b m hm I ≤
      RingHom.ker (eval (fun j : Option (Fin N) ↦
        j.elim m (fun i ↦ -b i))) := by
  unfold translatedProjectiveConeIdeal
  rw [Ideal.map_le_iff_le_comap]
  intro f hf
  apply RingHom.mem_ker.mpr
  change aeval (fun j : Option (Fin N) ↦ j.elim m (fun i ↦ -b i))
    (homogeneousAffinePolynomialChangeAlgEquiv b m hm f) = 0
  rw [aeval_homogeneousAffinePolynomialChange]
  have haxis := projectiveConeIdealExtension_le_vertexAxis_eval
    I hIprime hIhomogeneous m
  have hv :
      homogeneousAffineLinearEquiv b m hm
          (fun j : Option (Fin N) ↦ j.elim m (fun i ↦ -b i)) =
        (fun j : Option (Fin N) ↦ j.elim m (fun _ ↦ 0)) := by
    funext j
    cases j with
    | none => simp [homogeneousAffineLinearEquiv]
    | some i =>
      simp only [homogeneousAffineLinearEquiv, LinearEquiv.coe_mk,
          LinearMap.coe_mk, AddHom.coe_mk, Option.elim_none,
          Option.elim_some]
      ring
  rw [hv]
  exact RingHom.mem_ker.mp (haxis hf)

/-- Extending a homogeneous ideal by an unused cone coordinate preserves
homogeneity. -/
theorem projectiveConeIdealExtension_isHomogeneous
    {K : Type*} [Field K] {N : ℕ}
    (I : Ideal (MvPolynomial (Fin N) K))
    (hI : I.IsHomogeneous
      (MvPolynomial.homogeneousSubmodule (Fin N) K)) :
    (projectiveConeIdealExtension I).IsHomogeneous
      (MvPolynomial.homogeneousSubmodule (Option (Fin N)) K) := by
  rw [Ideal.IsHomogeneous.iff_exists] at hI ⊢
  obtain ⟨S, rfl⟩ := hI
  let T : Set (SetLike.homogeneousSubmonoid
      (MvPolynomial.homogeneousSubmodule (Option (Fin N)) K)) :=
    {q | ∃ p : SetLike.homogeneousSubmonoid
        (MvPolynomial.homogeneousSubmodule (Fin N) K),
      p ∈ S ∧ q.1 = MvPolynomial.rename some p.1}
  refine ⟨T, ?_⟩
  rw [projectiveConeIdealExtension, Ideal.map_span]
  apply congrArg Ideal.span
  ext q
  constructor
  · rintro ⟨_, ⟨p, hp, rfl⟩, rfl⟩
    refine ⟨⟨MvPolynomial.rename some p.1, ?_⟩, ?_, rfl⟩
    · obtain ⟨d, hd⟩ := p.2
      exact ⟨d, hd.rename_isHomogeneous⟩
    · exact ⟨p, hp, rfl⟩
  · rintro ⟨q', ⟨p, hp, hq'⟩, rfl⟩
    exact ⟨p.1, ⟨p, hp, rfl⟩, hq'.symm⟩

/-- The displayed homogeneous affine polynomial automorphism preserves
homogeneous ideals. -/
theorem map_homogeneousAffinePolynomialChange_isHomogeneous
    {K : Type*} [Field K] {N : ℕ}
    (b : Fin N → K) (m : K) (hm : m ≠ 0)
    (I : Ideal (MvPolynomial (Option (Fin N)) K))
    (hI : I.IsHomogeneous
      (MvPolynomial.homogeneousSubmodule (Option (Fin N)) K)) :
    (I.map (homogeneousAffinePolynomialChangeAlgEquiv b m hm)).IsHomogeneous
      (MvPolynomial.homogeneousSubmodule (Option (Fin N)) K) := by
  rw [Ideal.IsHomogeneous.iff_exists] at hI ⊢
  obtain ⟨S, rfl⟩ := hI
  let T : Set (SetLike.homogeneousSubmonoid
      (MvPolynomial.homogeneousSubmodule (Option (Fin N)) K)) :=
    {q | ∃ p : SetLike.homogeneousSubmonoid
        (MvPolynomial.homogeneousSubmodule (Option (Fin N)) K),
      p ∈ S ∧
        q.1 = homogeneousAffinePolynomialChangeAlgEquiv b m hm p.1}
  refine ⟨T, ?_⟩
  rw [Ideal.map_span]
  apply congrArg Ideal.span
  ext q
  constructor
  · rintro ⟨_, ⟨p, hp, rfl⟩, rfl⟩
    refine ⟨⟨homogeneousAffinePolynomialChangeAlgEquiv b m hm p.1, ?_⟩,
      ?_, rfl⟩
    · obtain ⟨d, hd⟩ := p.2
      exact ⟨d, isHomogeneous_homogeneousAffinePolynomialChange
        b m hm hd⟩
    · exact ⟨p, hp, rfl⟩
  · rintro ⟨q', ⟨p, hp, hq'⟩, rfl⟩
    exact ⟨p.1, ⟨p, hp, rfl⟩, hq'.symm⟩

theorem translatedProjectiveConeIdeal_isHomogeneous
    {K : Type*} [Field K] {N : ℕ}
    (b : Fin N → K) (m : K) (hm : m ≠ 0)
    (I : Ideal (MvPolynomial (Fin N) K))
    (hI : I.IsHomogeneous
      (MvPolynomial.homogeneousSubmodule (Fin N) K)) :
    (translatedProjectiveConeIdeal b m hm I).IsHomogeneous
      (MvPolynomial.homogeneousSubmodule (Option (Fin N)) K) := by
  exact map_homogeneousAffinePolynomialChange_isHomogeneous b m hm _
    (projectiveConeIdealExtension_isHomogeneous I hI)

/-- Reindex the translated projective cone over an ideal in twelve
homogeneous coordinates into the standard thirteen homogeneous coordinates.
The first coordinate is the homogenizing/vertex coordinate. -/
def isolatedVertexTranslatedConeFinIdeal
    {K : Type*} [Field K]
    (b : Fin 12 → K) (m : K) (hm : m ≠ 0)
    (J : Ideal (MvPolynomial (Fin 12) K)) :
    Ideal (MvPolynomial (Fin 13) K) :=
  (translatedProjectiveConeIdeal b m hm J).map
    (MvPolynomial.renameEquiv K (_root_.finSuccEquiv 12).symm)

theorem isolatedVertexTranslatedConeFinIdeal_isHomogeneous
    {K : Type*} [Field K]
    (b : Fin 12 → K) (m : K) (hm : m ≠ 0)
    (J : Ideal (MvPolynomial (Fin 12) K))
    (hJ : J.IsHomogeneous
      (MvPolynomial.homogeneousSubmodule (Fin 12) K)) :
    (isolatedVertexTranslatedConeFinIdeal b m hm J).IsHomogeneous
      (MvPolynomial.homogeneousSubmodule (Fin 13) K) := by
  apply map_renameEquiv_isHomogeneous
  exact translatedProjectiveConeIdeal_isHomogeneous b m hm J hJ

/-- The vector `(m,-b)` in the same standard thirteen coordinates. -/
def isolatedVertexQuotientProjectiveVertexVector
    {K : Type*} [Field K] (b : Fin 12 → K) (m : K) : Fin 13 → K :=
  fun i ↦
    match _root_.finSuccEquiv 12 i with
    | none => m
    | some j => -b j

/-- The translated cone contains its literal translated vertex.  This is
proved from the ideal maps, rather than included in the projective
component-correspondence input. -/
theorem isolatedVertexTranslatedConeFinIdeal_le_vertex_eval
    (b : Fin 12 → Qbar) (m : Qbar) (hm : m ≠ 0)
    (I : Ideal (MvPolynomial (Fin 12) Qbar))
    (hIprime : I.IsPrime)
    (hIhomogeneous : I.IsHomogeneous
      (MvPolynomial.homogeneousSubmodule (Fin 12) Qbar)) :
    isolatedVertexTranslatedConeFinIdeal b m hm I ≤
      RingHom.ker (eval (isolatedVertexQuotientProjectiveVertexVector b m)) := by
  unfold isolatedVertexTranslatedConeFinIdeal
  rw [Ideal.map_le_iff_le_comap]
  intro f hf
  apply RingHom.mem_ker.mpr
  rw [MvPolynomial.renameEquiv_apply, MvPolynomial.eval_rename]
  have htranslated := translatedProjectiveConeIdeal_le_vertex_eval
    b m hm I hIprime hIhomogeneous
  have hv :
      isolatedVertexQuotientProjectiveVertexVector b m ∘
          (_root_.finSuccEquiv 12).symm =
        (fun j : Option (Fin 12) ↦ j.elim m (fun i ↦ -b i)) := by
    funext j
    cases j <;> simp [isolatedVertexQuotientProjectiveVertexVector]
  rw [hv]
  exact RingHom.mem_ker.mp (htranslated hf)

/-- The literal projective node ideal cut out by the translated quotient
cone and four independent homogeneous equations. -/
def isolatedVertexQuotientNodeIdeal
    {K : Type*} [Field K]
    (J : Ideal (MvPolynomial (Fin 12) K))
    (b : Fin 12 → K) (m : K) (hm : m ≠ 0)
    (A : Matrix (Fin 4) (Fin 13) K) :
    Ideal (MvPolynomial (Fin 13) K) :=
  isolatedVertexTranslatedConeFinIdeal b m hm J ⊔ matrixRowLinearIdeal A

/-- The actual finite list of geometric irreducible components of the
quotient node. -/
def isolatedVertexQuotientNodeComponents
    (J : Ideal (MvPolynomial (Fin 12) Qbar))
    (b : Fin 12 → Qbar) (m : Qbar) (hm : m ≠ 0)
    (A : Matrix (Fin 4) (Fin 13) Qbar) :
    Finset (Ideal (MvPolynomial (Fin 13) Qbar)) :=
  finiteMinimalPrimes (isolatedVertexQuotientNodeIdeal J b m hm A)

theorem isolatedVertexQuotientNodeIdeal_isHomogeneous
    (J : Ideal (MvPolynomial (Fin 12) Qbar))
    (hJ : J.IsHomogeneous
      (MvPolynomial.homogeneousSubmodule (Fin 12) Qbar))
    (b : Fin 12 → Qbar) (m : Qbar) (hm : m ≠ 0)
    (A : Matrix (Fin 4) (Fin 13) Qbar) :
    (isolatedVertexQuotientNodeIdeal J b m hm A).IsHomogeneous
      (MvPolynomial.homogeneousSubmodule (Fin 13) Qbar) := by
  exact (isolatedVertexTranslatedConeFinIdeal_isHomogeneous b m hm J hJ).sup
    (matrixRowLinearIdeal_isHomogeneous A)

theorem isolatedVertexQuotientNodeComponent_isHomogeneous
    (J : Ideal (MvPolynomial (Fin 12) Qbar))
    (hJ : J.IsHomogeneous
      (MvPolynomial.homogeneousSubmodule (Fin 12) Qbar))
    (b : Fin 12 → Qbar) (m : Qbar) (hm : m ≠ 0)
    (A : Matrix (Fin 4) (Fin 13) Qbar)
    (P : Ideal (MvPolynomial (Fin 13) Qbar))
    (hP : P ∈ isolatedVertexQuotientNodeComponents J b m hm A) :
    P.IsHomogeneous
      (MvPolynomial.homogeneousSubmodule (Fin 13) Qbar) := by
  apply isHomogeneous_of_mem_minimalPrimes_of_isHomogeneous
    (isolatedVertexQuotientNodeIdeal_isHomogeneous J hJ b m hm A)
  exact (mem_finiteMinimalPrimes_iff _ _).mp hP

/-- Literal containment of the translated quotient vertex in a homogeneous
component. -/
def QuotientComponentContainsVertex
    (b : Fin 12 → Qbar) (m : Qbar)
    (P : Ideal (MvPolynomial (Fin 13) Qbar)) : Prop :=
  isolatedVertexQuotientProjectiveVertexVector b m ∈ affineIdealZeroLocus P

/-- A component of the node cannot contain the quotient vertex when the
four-plane itself avoids that vertex. -/
theorem quotientNodeComponent_not_containsVertex_of_plane_avoids
    (J : Ideal (MvPolynomial (Fin 12) Qbar))
    (b : Fin 12 → Qbar) (m : Qbar) (hm : m ≠ 0)
    (A : Matrix (Fin 4) (Fin 13) Qbar)
    (hvertex : Matrix.mulVec A
      (isolatedVertexQuotientProjectiveVertexVector b m) ≠ 0)
    (P : Ideal (MvPolynomial (Fin 13) Qbar))
    (hP : P ∈ isolatedVertexQuotientNodeComponents J b m hm A) :
    ¬ QuotientComponentContainsVertex b m P := by
  intro hcontains
  have hnodeP : isolatedVertexQuotientNodeIdeal J b m hm A ≤ P :=
    le_of_mem_finiteMinimalPrimes hP
  have hrowsP : matrixRowLinearIdeal A ≤ P :=
    (le_sup_right : matrixRowLinearIdeal A ≤
      isolatedVertexTranslatedConeFinIdeal b m hm J ⊔
        matrixRowLinearIdeal A).trans hnodeP
  have hrowsKernel : matrixRowLinearIdeal A ≤
      RingHom.ker (eval (isolatedVertexQuotientProjectiveVertexVector b m)) := by
    intro f hf
    exact RingHom.mem_ker.mpr (hcontains f (hrowsP hf))
  exact hvertex
    ((matrixRowLinearIdeal_le_evaluationKernel_iff A
      (isolatedVertexQuotientProjectiveVertexVector b m)).mp hrowsKernel)

/-! ## Actual source-section lift witnesses -/

/-- An actual geometric component of a linear section of the source cone,
together with its dimension, degree, and the numerical exceptional-locus
condition.  No quotient component is hidden in this structure. -/
structure QuotientNodeExceptionalLift
    (J : Ideal (MvPolynomial (Fin 12) Qbar))
    (b : Fin 12 → Qbar) (m : Qbar) (hm : m ≠ 0)
    (A : Matrix (Fin 4) (Fin 13) Qbar)
    (quotientComponent : Ideal (MvPolynomial (Fin 13) Qbar))
    (quotientDimension quotientDegree : ℕ) where
  quotientComponent_mem : quotientComponent ∈
    isolatedVertexQuotientNodeComponents J b m hm A
  quotientHilbert : HasGeometricProjectiveDimensionDegree quotientComponent
    quotientDimension quotientDegree
  codimension : ℕ
  one_le_codimension : 1 ≤ codimension
  codimension_le_four : codimension ≤ 4
  sectionMatrix : Matrix (Fin codimension) (Fin 13) Qbar
  sectionRank : sectionMatrix.rank = codimension
  sourceComponent : Ideal (MvPolynomial (Fin 13) Qbar)
  sourceComponent_mem : sourceComponent ∈ finiteMinimalPrimes
    (projectiveConeFinIdeal Qbar 11 J ⊔ matrixRowLinearIdeal sectionMatrix)
  sourceDimension : ℕ
  sourceDegree : ℕ
  sourceHilbert : HasGeometricProjectiveDimensionDegree sourceComponent
    sourceDimension sourceDegree
  exceptional : IsDepthSevenExceptionalComponent
    (c := codimension) sourceComponent

namespace StandardAG

/-- Generalized Bezout and Krull height for a four-plane section of a
geometrically integral projective fivefold.  It supplies Hilbert data for
the actual geometric minimal primes and bounds their total degree.  This is
the only component-enumeration input below.

References: Hartshorne I.7.1 and I.7.7, or the Stacks Project, Tags `00KD`,
`00KP`, and `0B04`. -/
def GeometricFourPlaneSectionComponentDegreeMass : Prop :=
  ∀ (J : Ideal (MvPolynomial (Fin 12) Qbar))
    (b : Fin 12 → Qbar) (m : Qbar) (hm : m ≠ 0)
    (A : Matrix (Fin 4) (Fin 13) Qbar) (degree : ℕ),
    J.IsPrime →
    J.IsHomogeneous (MvPolynomial.homogeneousSubmodule (Fin 12) Qbar) →
    HasProjectiveDimensionDegree (N := 11) J 4 degree →
    A.rank = 4 →
      ∃ componentDimension componentDegree :
          Ideal (MvPolynomial (Fin 13) Qbar) → ℕ,
        (∀ P ∈ isolatedVertexQuotientNodeComponents J b m hm A,
          1 ≤ componentDimension P ∧
          HasGeometricProjectiveDimensionDegree P
            (componentDimension P) (componentDegree P)) ∧
        ∑ P ∈ isolatedVertexQuotientNodeComponents J b m hm A,
          componentDegree P ≤ degree

/-- Component correspondence when the quotient node plane avoids its
vertex.  Projection identifies a node component of dimension `s` and degree
`e` with a component of the codimension-three base section; adjoining the
original isolated vertex gives the displayed source-cone component of
dimension `s+1` and the same degree.

This is the componentwise form of the standard projection-from-a-point
dictionary for projective cones. -/
def QuotientNodeAwayVertexComponentLift : Prop :=
  ∀ (J : Ideal (MvPolynomial (Fin 12) Qbar))
    (b : Fin 12 → Qbar) (m : Qbar) (hm : m ≠ 0)
    (A : Matrix (Fin 4) (Fin 13) Qbar)
    (P : Ideal (MvPolynomial (Fin 13) Qbar)) (s e : ℕ),
    A.rank = 4 →
    Matrix.mulVec A (isolatedVertexQuotientProjectiveVertexVector b m) ≠ 0 →
    P ∈ isolatedVertexQuotientNodeComponents J b m hm A →
    HasGeometricProjectiveDimensionDegree P s e →
      ∃ B : Matrix (Fin 3) (Fin 13) Qbar,
        B.rank = 3 ∧
        ∃ Q : Ideal (MvPolynomial (Fin 13) Qbar),
          Q ∈ finiteMinimalPrimes
            (projectiveConeFinIdeal Qbar 11 J ⊔ matrixRowLinearIdeal B) ∧
          HasGeometricProjectiveDimensionDegree Q (s + 1) e

/-- Component correspondence when the quotient node plane contains its
vertex.  Every node component is the translated cone over an actual
component of the codimension-four section of the base.  Adjoining the
original isolated vertex gives the displayed source-cone component, with
the same dimension and degree as the quotient component.

The equality with `isolatedVertexTranslatedConeFinIdeal` is retained, so
the radial conclusion is about the actual component ideal. -/
def QuotientNodeVertexContainedComponentLift : Prop :=
  ∀ (J : Ideal (MvPolynomial (Fin 12) Qbar))
    (b : Fin 12 → Qbar) (m : Qbar) (hm : m ≠ 0)
    (A : Matrix (Fin 4) (Fin 13) Qbar)
    (P : Ideal (MvPolynomial (Fin 13) Qbar)) (s e : ℕ),
    A.rank = 4 →
    Matrix.mulVec A (isolatedVertexQuotientProjectiveVertexVector b m) = 0 →
    P ∈ isolatedVertexQuotientNodeComponents J b m hm A →
    HasGeometricProjectiveDimensionDegree P s e →
      ∃ B : Matrix (Fin 4) (Fin 12) Qbar,
        B.rank = 4 ∧
        ∃ R : Ideal (MvPolynomial (Fin 12) Qbar),
          R ∈ finiteMinimalPrimes (J ⊔ matrixRowLinearIdeal B) ∧
          ∃ r : ℕ,
            HasProjectiveDimensionDegree (N := 11) R r e ∧
            s = r + 1 ∧
            P = isolatedVertexTranslatedConeFinIdeal b m hm R ∧
            ∃ Q : Ideal (MvPolynomial (Fin 13) Qbar),
              Q ∈ finiteMinimalPrimes
                (projectiveConeFinIdeal Qbar 11 J ⊔
                  matrixRowLinearIdeal (matrixPrependZeroColumn B)) ∧
              HasGeometricProjectiveDimensionDegree Q s e

/-- A geometrically integral zero-dimensional projective scheme over an
algebraically closed field is one reduced point and has degree one. -/
def AlgebraicallyClosedIntegralProjectiveZerofoldDegreeOne : Prop :=
  ∀ (N d : ℕ) (I : Ideal (MvPolynomial (Fin (N + 1)) Qbar)),
    I.IsPrime →
    I.IsHomogeneous
      (MvPolynomial.homogeneousSubmodule (Fin (N + 1)) Qbar) →
    HasProjectiveDimensionDegree I 0 d → d = 1

end StandardAG

/-! ## Component dispositions -/

def IsGeometricallyIntegralProjectiveQuotientComponent
    (P : Ideal (MvPolynomial (Fin 13) Qbar)) : Prop :=
  P.IsPrime ∧ P.IsHomogeneous
    (MvPolynomial.homogeneousSubmodule (Fin 13) Qbar)

/-- An actual geometrically integral component which is projectively
zero-dimensional.  Its degree is retained rather than silently replaced by
one; the latter conclusion needs geometric reducedness/integrality. -/
def IsZeroDimensionalQuotientNodeComponent
    (P : Ideal (MvPolynomial (Fin 13) Qbar)) (s e : ℕ) : Prop :=
  IsGeometricallyIntegralProjectiveQuotientComponent P ∧
    HasGeometricProjectiveDimensionDegree P s e ∧ s = 0 ∧ e = 1

/-- An actual radial line component through the displayed quotient vertex. -/
def IsRadialQuotientNodeLine
    (b : Fin 12 → Qbar) (m : Qbar)
    (P : Ideal (MvPolynomial (Fin 13) Qbar)) (s e : ℕ) : Prop :=
  IsGeometricallyIntegralProjectiveQuotientComponent P ∧
    HasGeometricProjectiveDimensionDegree P s e ∧
    s = 1 ∧ e = 1 ∧ QuotientComponentContainsVertex b m P

/-- An actual geometrically integral nonradial curve.  The lower bound two
is part of the data, so degree-one components cannot enter this class. -/
def IsNonradialIntegralQuotientNodeCurve
    (b : Fin 12 → Qbar) (m : Qbar)
    (P : Ideal (MvPolynomial (Fin 13) Qbar)) (s e : ℕ) : Prop :=
  IsGeometricallyIntegralProjectiveQuotientComponent P ∧
    HasGeometricProjectiveDimensionDegree P s e ∧
    s = 1 ∧ 2 ≤ e ∧ ¬ QuotientComponentContainsVertex b m P

/-- The four mutually intelligible outcomes for an actual quotient-node
component.  The first three are intrinsic properties of that component;
the fourth retains the actual source-section component to which it lifts. -/
def QuotientNodeComponentDisposition
    (J : Ideal (MvPolynomial (Fin 12) Qbar))
    (b : Fin 12 → Qbar) (m : Qbar) (hm : m ≠ 0)
    (A : Matrix (Fin 4) (Fin 13) Qbar)
    (P : Ideal (MvPolynomial (Fin 13) Qbar)) (s e : ℕ) : Prop :=
  IsZeroDimensionalQuotientNodeComponent P s e ∨
    IsRadialQuotientNodeLine b m P s e ∨
    IsNonradialIntegralQuotientNodeCurve b m P s e ∨
    Nonempty (QuotientNodeExceptionalLift J b m hm A P s e)

/-- If the four-plane avoids the quotient vertex, a component of dimension
at least two lifts to an excess component of a codimension-three source
section. -/
theorem exists_exceptionalLift_of_plane_avoids_of_two_le_dimension
    (hAway : StandardAG.QuotientNodeAwayVertexComponentLift)
    (J : Ideal (MvPolynomial (Fin 12) Qbar))
    (b : Fin 12 → Qbar) (m : Qbar) (hm : m ≠ 0)
    (A : Matrix (Fin 4) (Fin 13) Qbar) (hA : A.rank = 4)
    (hvertex : Matrix.mulVec A
      (isolatedVertexQuotientProjectiveVertexVector b m) ≠ 0)
    (P : Ideal (MvPolynomial (Fin 13) Qbar))
    (hP : P ∈ isolatedVertexQuotientNodeComponents J b m hm A)
    (s e : ℕ) (hHilbert : HasGeometricProjectiveDimensionDegree P s e)
    (hs : 2 ≤ s) :
    Nonempty (QuotientNodeExceptionalLift J b m hm A P s e) := by
  obtain ⟨B, hB, Q, hQ, hQHilbert⟩ :=
    hAway J b m hm A P s e hA hvertex hP hHilbert
  refine ⟨{
    quotientComponent_mem := hP
    quotientHilbert := hHilbert
    codimension := 3
    one_le_codimension := by omega
    codimension_le_four := by omega
    sectionMatrix := B
    sectionRank := hB
    sourceComponent := Q
    sourceComponent_mem := hQ
    sourceDimension := s + 1
    sourceDegree := e
    sourceHilbert := hQHilbert
    exceptional := ?_ }⟩
  apply isDepthSevenExceptionalComponent_of_dimension_gt_expected
    (c := 3) (r := s + 1) (d := e)
  · omega
  · omega
  · exact hQHilbert
  · omega

/-- If the four-plane avoids the quotient vertex, a quotient curve of
degree at most seven lifts to the low-degree component of a codimension-
three source section. -/
theorem exists_exceptionalLift_of_plane_avoids_of_curve_degree_le_seven
    (hAway : StandardAG.QuotientNodeAwayVertexComponentLift)
    (J : Ideal (MvPolynomial (Fin 12) Qbar))
    (b : Fin 12 → Qbar) (m : Qbar) (hm : m ≠ 0)
    (A : Matrix (Fin 4) (Fin 13) Qbar) (hA : A.rank = 4)
    (hvertex : Matrix.mulVec A
      (isolatedVertexQuotientProjectiveVertexVector b m) ≠ 0)
    (P : Ideal (MvPolynomial (Fin 13) Qbar))
    (hP : P ∈ isolatedVertexQuotientNodeComponents J b m hm A)
    (s e : ℕ) (hHilbert : HasGeometricProjectiveDimensionDegree P s e)
    (hs : s = 1) (he : e ≤ 7) :
    Nonempty (QuotientNodeExceptionalLift J b m hm A P s e) := by
  obtain ⟨B, hB, Q, hQ, hQHilbert⟩ :=
    hAway J b m hm A P s e hA hvertex hP hHilbert
  refine ⟨{
    quotientComponent_mem := hP
    quotientHilbert := hHilbert
    codimension := 3
    one_le_codimension := by omega
    codimension_le_four := by omega
    sectionMatrix := B
    sectionRank := hB
    sourceComponent := Q
    sourceComponent_mem := hQ
    sourceDimension := s + 1
    sourceDegree := e
    sourceHilbert := hQHilbert
    exceptional := ?_ }⟩
  left
  refine ⟨by omega, by omega, Or.inr ⟨e, ?_, he⟩⟩
  simpa [hs] using hQHilbert

/-- If the four-plane contains the quotient vertex, every component of
dimension at least two lifts to a positive-dimensional component of a
codimension-four source section and is therefore exceptional. -/
theorem exists_exceptionalLift_of_plane_contains_of_two_le_dimension
    (hContained : StandardAG.QuotientNodeVertexContainedComponentLift)
    (J : Ideal (MvPolynomial (Fin 12) Qbar))
    (b : Fin 12 → Qbar) (m : Qbar) (hm : m ≠ 0)
    (A : Matrix (Fin 4) (Fin 13) Qbar) (hA : A.rank = 4)
    (hvertex : Matrix.mulVec A
      (isolatedVertexQuotientProjectiveVertexVector b m) = 0)
    (P : Ideal (MvPolynomial (Fin 13) Qbar))
    (hP : P ∈ isolatedVertexQuotientNodeComponents J b m hm A)
    (s e : ℕ) (hHilbert : HasGeometricProjectiveDimensionDegree P s e)
    (hs : 2 ≤ s) :
    Nonempty (QuotientNodeExceptionalLift J b m hm A P s e) := by
  obtain ⟨B, hB, R, hR, r, hRHilbert, hsr, hPeq,
      Q, hQ, hQHilbert⟩ :=
    hContained J b m hm A P s e hA hvertex hP hHilbert
  refine ⟨{
    quotientComponent_mem := hP
    quotientHilbert := hHilbert
    codimension := 4
    one_le_codimension := by omega
    codimension_le_four := by omega
    sectionMatrix := matrixPrependZeroColumn B
    sectionRank := ?_
    sourceComponent := Q
    sourceComponent_mem := hQ
    sourceDimension := s
    sourceDegree := e
    sourceHilbert := hQHilbert
    exceptional := ?_ }⟩
  · simpa only [matrixPrependZeroColumn_rank] using hB
  · right
    exact ⟨rfl, s, e, hQHilbert, hs⟩

/-- In the vertex-contained case, a one-dimensional component is literally
the translated cone over a geometrically integral zero-dimensional base;
hence it is a degree-one radial line. -/
theorem radialLine_of_plane_contains_of_dimension_one
    (hContained : StandardAG.QuotientNodeVertexContainedComponentLift)
    (hZero : StandardAG.AlgebraicallyClosedIntegralProjectiveZerofoldDegreeOne)
    (J : Ideal (MvPolynomial (Fin 12) Qbar))
    (hJhomogeneous : J.IsHomogeneous
      (MvPolynomial.homogeneousSubmodule (Fin 12) Qbar))
    (b : Fin 12 → Qbar) (m : Qbar) (hm : m ≠ 0)
    (A : Matrix (Fin 4) (Fin 13) Qbar) (hA : A.rank = 4)
    (hvertex : Matrix.mulVec A
      (isolatedVertexQuotientProjectiveVertexVector b m) = 0)
    (P : Ideal (MvPolynomial (Fin 13) Qbar))
    (hP : P ∈ isolatedVertexQuotientNodeComponents J b m hm A)
    (s e : ℕ) (hHilbert : HasGeometricProjectiveDimensionDegree P s e)
    (hs : s = 1) :
    IsRadialQuotientNodeLine b m P s e := by
  obtain ⟨B, hB, R, hR, r, hRHilbert, hsr, hPeq,
      Q, hQ, hQHilbert⟩ :=
    hContained J b m hm A P s e hA hvertex hP hHilbert
  have hr : r = 0 := by omega
  have hsupHomogeneous :
      (J ⊔ matrixRowLinearIdeal B).IsHomogeneous
        (MvPolynomial.homogeneousSubmodule (Fin 12) Qbar) :=
    hJhomogeneous.sup (matrixRowLinearIdeal_isHomogeneous B)
  have hRhomogeneous : R.IsHomogeneous
      (MvPolynomial.homogeneousSubmodule (Fin 12) Qbar) := by
    apply isHomogeneous_of_mem_minimalPrimes_of_isHomogeneous
      hsupHomogeneous
    exact (mem_finiteMinimalPrimes_iff _ _).mp hR
  have hRprime : R.IsPrime := isPrime_of_mem_finiteMinimalPrimes hR
  have hRHilbertZero : HasProjectiveDimensionDegree (N := 11) R 0 e := by
    simpa [hr] using hRHilbert
  have he : e = 1 := hZero 11 e R hRprime hRhomogeneous hRHilbertZero
  have hcontains : QuotientComponentContainsVertex b m P := by
    rw [hPeq]
    intro f hf
    exact RingHom.mem_ker.mp
      (isolatedVertexTranslatedConeFinIdeal_le_vertex_eval
        b m hm R hRprime hRhomogeneous hf)
  have hPhomogeneous := isolatedVertexQuotientNodeComponent_isHomogeneous
    J hJhomogeneous b m hm A P hP
  exact ⟨⟨isPrime_of_mem_finiteMinimalPrimes hP, hPhomogeneous⟩,
    hHilbert, hs, he, hcontains⟩

/-- Componentwise quotient-node classification.  The proof is a literal
case split according to whether the four-plane contains the quotient
vertex.  In the avoiding case only nonradial curves of degree at least eight
survive outside the source exceptional locus; in the containing case the
only nonexceptional positive-dimensional components are radial lines. -/
theorem quotientNodeComponentDisposition_of_standard_projection
    (hAway : StandardAG.QuotientNodeAwayVertexComponentLift)
    (hContained : StandardAG.QuotientNodeVertexContainedComponentLift)
    (hZero : StandardAG.AlgebraicallyClosedIntegralProjectiveZerofoldDegreeOne)
    (J : Ideal (MvPolynomial (Fin 12) Qbar))
    (hJhomogeneous : J.IsHomogeneous
      (MvPolynomial.homogeneousSubmodule (Fin 12) Qbar))
    (b : Fin 12 → Qbar) (m : Qbar) (hm : m ≠ 0)
    (A : Matrix (Fin 4) (Fin 13) Qbar) (hA : A.rank = 4)
    (P : Ideal (MvPolynomial (Fin 13) Qbar))
    (hP : P ∈ isolatedVertexQuotientNodeComponents J b m hm A)
    (s e : ℕ) (hHilbert : HasGeometricProjectiveDimensionDegree P s e) :
    QuotientNodeComponentDisposition J b m hm A P s e := by
  have hPprime : P.IsPrime := isPrime_of_mem_finiteMinimalPrimes hP
  have hPhomogeneous := isolatedVertexQuotientNodeComponent_isHomogeneous
    J hJhomogeneous b m hm A P hP
  by_cases hs0 : s = 0
  · have hHilbertZero : HasProjectiveDimensionDegree (N := 12) P 0 e := by
      simpa [HasGeometricProjectiveDimensionDegree, hs0] using hHilbert
    have he := hZero 12 e P hPprime hPhomogeneous hHilbertZero
    exact Or.inl ⟨⟨hPprime, hPhomogeneous⟩, hHilbert, hs0, he⟩
  have hs1 : 1 ≤ s := Nat.one_le_iff_ne_zero.mpr hs0
  by_cases hvertex : Matrix.mulVec A
      (isolatedVertexQuotientProjectiveVertexVector b m) = 0
  · by_cases hs : s = 1
    · exact Or.inr (Or.inl
        (radialLine_of_plane_contains_of_dimension_one
          hContained hZero J hJhomogeneous b m hm A hA hvertex
          P hP s e hHilbert hs))
    · have hs2 : 2 ≤ s := by omega
      exact Or.inr (Or.inr (Or.inr
        (exists_exceptionalLift_of_plane_contains_of_two_le_dimension
          hContained J b m hm A hA hvertex P hP s e hHilbert hs2)))
  · by_cases hs : s = 1
    · by_cases he : e ≤ 7
      · exact Or.inr (Or.inr (Or.inr
          (exists_exceptionalLift_of_plane_avoids_of_curve_degree_le_seven
            hAway J b m hm A hA hvertex P hP s e hHilbert hs he)))
      · have he8 : 8 ≤ e := by omega
        exact Or.inr (Or.inr (Or.inl
          ⟨⟨hPprime, hPhomogeneous⟩, hHilbert, hs, by omega,
            quotientNodeComponent_not_containsVertex_of_plane_avoids
              J b m hm A hvertex P hP⟩))
    · have hs2 : 2 ≤ s := by omega
      exact Or.inr (Or.inr (Or.inr
        (exists_exceptionalLift_of_plane_avoids_of_two_le_dimension
          hAway J b m hm A hA hvertex P hP s e hHilbert hs2)))

/-! The following four finite sets make the word "split" literal.  The
first three are determined by intrinsic properties of the actual component
ideal.  The fourth is their complement in the actual minimal-prime list. -/

def quotientNodeZeroDimensionalComponents
    (J : Ideal (MvPolynomial (Fin 12) Qbar))
    (b : Fin 12 → Qbar) (m : Qbar) (hm : m ≠ 0)
    (A : Matrix (Fin 4) (Fin 13) Qbar)
    (componentDimension componentDegree :
      Ideal (MvPolynomial (Fin 13) Qbar) → ℕ) :
    Finset (Ideal (MvPolynomial (Fin 13) Qbar)) := by
  classical
  exact (isolatedVertexQuotientNodeComponents J b m hm A).filter fun P ↦
    IsZeroDimensionalQuotientNodeComponent P
      (componentDimension P) (componentDegree P)

def quotientNodeRadialLineComponents
    (J : Ideal (MvPolynomial (Fin 12) Qbar))
    (b : Fin 12 → Qbar) (m : Qbar) (hm : m ≠ 0)
    (A : Matrix (Fin 4) (Fin 13) Qbar)
    (componentDimension componentDegree :
      Ideal (MvPolynomial (Fin 13) Qbar) → ℕ) :
    Finset (Ideal (MvPolynomial (Fin 13) Qbar)) := by
  classical
  exact (isolatedVertexQuotientNodeComponents J b m hm A).filter fun P ↦
    IsRadialQuotientNodeLine b m P
      (componentDimension P) (componentDegree P)

def quotientNodeNonradialCurveComponents
    (J : Ideal (MvPolynomial (Fin 12) Qbar))
    (b : Fin 12 → Qbar) (m : Qbar) (hm : m ≠ 0)
    (A : Matrix (Fin 4) (Fin 13) Qbar)
    (componentDimension componentDegree :
      Ideal (MvPolynomial (Fin 13) Qbar) → ℕ) :
    Finset (Ideal (MvPolynomial (Fin 13) Qbar)) := by
  classical
  exact (isolatedVertexQuotientNodeComponents J b m hm A).filter fun P ↦
    IsNonradialIntegralQuotientNodeCurve b m P
      (componentDimension P) (componentDegree P)

def quotientNodeExceptionalResidualComponents
    (J : Ideal (MvPolynomial (Fin 12) Qbar))
    (b : Fin 12 → Qbar) (m : Qbar) (hm : m ≠ 0)
    (A : Matrix (Fin 4) (Fin 13) Qbar)
    (componentDimension componentDegree :
      Ideal (MvPolynomial (Fin 13) Qbar) → ℕ) :
    Finset (Ideal (MvPolynomial (Fin 13) Qbar)) := by
  classical
  exact (isolatedVertexQuotientNodeComponents J b m hm A).filter fun P ↦
    ¬ IsZeroDimensionalQuotientNodeComponent P
        (componentDimension P) (componentDegree P) ∧
      ¬ IsRadialQuotientNodeLine b m P
        (componentDimension P) (componentDegree P) ∧
      ¬ IsNonradialIntegralQuotientNodeCurve b m P
        (componentDimension P) (componentDegree P)

/-- Membership in the actual node-component list is equivalent to
membership in one of the four displayed finite pieces.  This is purely
propositional and introduces no geometric input. -/
theorem mem_isolatedVertexQuotientNodeComponents_iff_fourWay
    (J : Ideal (MvPolynomial (Fin 12) Qbar))
    (b : Fin 12 → Qbar) (m : Qbar) (hm : m ≠ 0)
    (A : Matrix (Fin 4) (Fin 13) Qbar)
    (componentDimension componentDegree :
      Ideal (MvPolynomial (Fin 13) Qbar) → ℕ) :
    ∀ P, P ∈ isolatedVertexQuotientNodeComponents J b m hm A ↔
      P ∈ quotientNodeZeroDimensionalComponents J b m hm A
          componentDimension componentDegree ∨
        P ∈ quotientNodeRadialLineComponents J b m hm A
          componentDimension componentDegree ∨
        P ∈ quotientNodeNonradialCurveComponents J b m hm A
          componentDimension componentDegree ∨
        P ∈ quotientNodeExceptionalResidualComponents J b m hm A
          componentDimension componentDegree := by
  classical
  intro P
  simp only [quotientNodeZeroDimensionalComponents,
    quotientNodeRadialLineComponents,
    quotientNodeNonradialCurveComponents,
    quotientNodeExceptionalResidualComponents, Finset.mem_filter]
  tauto

/-- The three intrinsic classes are pairwise disjoint.  The residual class
is disjoint from each of them by its literal definition. -/
theorem quotientNodeComponent_intrinsicClasses_disjoint
    (J : Ideal (MvPolynomial (Fin 12) Qbar))
    (b : Fin 12 → Qbar) (m : Qbar) (hm : m ≠ 0)
    (A : Matrix (Fin 4) (Fin 13) Qbar)
    (componentDimension componentDegree :
      Ideal (MvPolynomial (Fin 13) Qbar) → ℕ) :
    (∀ P, P ∈ quotientNodeZeroDimensionalComponents J b m hm A
          componentDimension componentDegree →
        P ∉ quotientNodeRadialLineComponents J b m hm A
          componentDimension componentDegree) ∧
      (∀ P, P ∈ quotientNodeZeroDimensionalComponents J b m hm A
          componentDimension componentDegree →
        P ∉ quotientNodeNonradialCurveComponents J b m hm A
          componentDimension componentDegree) ∧
      (∀ P, P ∈ quotientNodeRadialLineComponents J b m hm A
          componentDimension componentDegree →
        P ∉ quotientNodeNonradialCurveComponents J b m hm A
          componentDimension componentDegree) := by
  classical
  constructor
  · intro P hzero hradial
    simp only [quotientNodeZeroDimensionalComponents, Finset.mem_filter] at hzero
    simp only [quotientNodeRadialLineComponents, Finset.mem_filter] at hradial
    have hs0 := hzero.2.2.2.1
    have hs1 := hradial.2.2.2.1
    omega
  constructor
  · intro P hzero hnonradial
    simp only [quotientNodeZeroDimensionalComponents, Finset.mem_filter] at hzero
    simp only [quotientNodeNonradialCurveComponents, Finset.mem_filter] at hnonradial
    have hs0 := hzero.2.2.2.1
    have hs1 := hnonradial.2.2.2.1
    omega
  · intro P hradial hnonradial
    simp only [quotientNodeRadialLineComponents, Finset.mem_filter] at hradial
    simp only [quotientNodeNonradialCurveComponents, Finset.mem_filter] at hnonradial
    exact hnonradial.2.2.2.2.2 hradial.2.2.2.2.2

/-- Every component in the literal residual finite set carries an actual
source exceptional-component lift. -/
theorem quotientNodeExceptionalResidualComponents_have_lifts
    (hAway : StandardAG.QuotientNodeAwayVertexComponentLift)
    (hContained : StandardAG.QuotientNodeVertexContainedComponentLift)
    (hZero : StandardAG.AlgebraicallyClosedIntegralProjectiveZerofoldDegreeOne)
    (J : Ideal (MvPolynomial (Fin 12) Qbar))
    (hJhomogeneous : J.IsHomogeneous
      (MvPolynomial.homogeneousSubmodule (Fin 12) Qbar))
    (b : Fin 12 → Qbar) (m : Qbar) (hm : m ≠ 0)
    (A : Matrix (Fin 4) (Fin 13) Qbar) (hA : A.rank = 4)
    (componentDimension componentDegree :
      Ideal (MvPolynomial (Fin 13) Qbar) → ℕ)
    (hHilbert : ∀ P ∈ isolatedVertexQuotientNodeComponents J b m hm A,
      HasGeometricProjectiveDimensionDegree P
        (componentDimension P) (componentDegree P)) :
    ∀ P ∈ quotientNodeExceptionalResidualComponents J b m hm A
        componentDimension componentDegree,
      Nonempty (QuotientNodeExceptionalLift J b m hm A P
        (componentDimension P) (componentDegree P)) := by
  classical
  intro P hP
  have hspec := (Finset.mem_filter.mp hP)
  obtain ⟨hPnode, hnotzero, hnotradial, hnotnonradial⟩ := hspec
  have hDisposition := quotientNodeComponentDisposition_of_standard_projection
    hAway hContained hZero J hJhomogeneous b m hm A hA P hPnode
      (componentDimension P) (componentDegree P) (hHilbert P hPnode)
  rcases hDisposition with hzero | hradial | hnonradial | hexceptional
  · exact False.elim (hnotzero hzero)
  · exact False.elim (hnotradial hradial)
  · exact False.elim (hnotnonradial hnonradial)
  · exact hexceptional

/-- Finite node decomposition with literal degree mass.  The functions
`componentDimension` and `componentDegree` apply to the actual minimal-prime
ideals in `isolatedVertexQuotientNodeComponents`; no anonymous component
labels are introduced. -/
theorem exists_quotientNodeComponentDecomposition
    (hMass : StandardAG.GeometricFourPlaneSectionComponentDegreeMass)
    (hAway : StandardAG.QuotientNodeAwayVertexComponentLift)
    (hContained : StandardAG.QuotientNodeVertexContainedComponentLift)
    (hZero : StandardAG.AlgebraicallyClosedIntegralProjectiveZerofoldDegreeOne)
    (J : Ideal (MvPolynomial (Fin 12) Qbar))
    (hJprime : J.IsPrime)
    (hJhomogeneous : J.IsHomogeneous
      (MvPolynomial.homogeneousSubmodule (Fin 12) Qbar))
    (degree : ℕ) (hJHilbert : HasProjectiveDimensionDegree (N := 11) J 4 degree)
    (b : Fin 12 → Qbar) (m : Qbar) (hm : m ≠ 0)
    (A : Matrix (Fin 4) (Fin 13) Qbar) (hA : A.rank = 4) :
    ∃ componentDimension componentDegree :
        Ideal (MvPolynomial (Fin 13) Qbar) → ℕ,
      (∀ P ∈ isolatedVertexQuotientNodeComponents J b m hm A,
        1 ≤ componentDimension P ∧
        HasGeometricProjectiveDimensionDegree P
          (componentDimension P) (componentDegree P) ∧
        QuotientNodeComponentDisposition J b m hm A P
          (componentDimension P) (componentDegree P)) ∧
      ∑ P ∈ isolatedVertexQuotientNodeComponents J b m hm A,
        componentDegree P ≤ degree := by
  obtain ⟨componentDimension, componentDegree, hcomponents, hdegree⟩ :=
    hMass J b m hm A degree hJprime hJhomogeneous hJHilbert hA
  refine ⟨componentDimension, componentDegree, ?_, hdegree⟩
  intro P hP
  obtain ⟨hdim, hHilbert⟩ := hcomponents P hP
  exact ⟨hdim, hHilbert,
    quotientNodeComponentDisposition_of_standard_projection
      hAway hContained hZero J hJhomogeneous b m hm A hA
      P hP (componentDimension P) (componentDegree P) hHilbert⟩

end

end TranslatedDepthSeven
