import TranslatedDepthSeven.IsolatedVertexQuotientSourceSectionRank
import TranslatedDepthSeven.IsolatedVertexQuotientExceptionalLocusAdapter

/-!
# Literal exceptional lifts of quotient-node components

This file replaces the algebraically-closed section matrix in
`QuotientNodeExceptionalLift` by the explicit integral codimension-three or
codimension-four matrix obtained from the quotient plane.  The matrix is
then returned to the original coordinates by the fixed unimodular change.
Consequently the resulting component is an actual component in the
definition of `MemDepthSevenExceptionalLocus`, and its height is bounded by
the elementary formulas proved in
`IsolatedVertexQuotientSourceSectionHeight`.

Only the component correspondence under the displayed projective linear
maps remains a textbook algebraic-geometric input.  It is stated below for
the exact ideals and matrices; it contains neither a point count nor a
branch estimate.
-/

namespace TranslatedDepthSeven

noncomputable section

open MvPolynomial

attribute [local instance] MvPolynomial.gradedAlgebra

set_option maxHeartbeats 3000000

/-- Coefficientwise inclusion of an integral vector into the fixed
algebraic closure. -/
def qbarIntVector {N : ℕ} (x : IntVector N) : Fin N → Qbar :=
  fun i ↦ algebraMap ℚ Qbar (x i : ℚ)

/-- Coefficientwise inclusion of an integral matrix into the fixed
algebraic closure. -/
def qbarIntMatrix {c N : ℕ} (A : Matrix (Fin c) (Fin N) ℤ) :
    Matrix (Fin c) (Fin N) Qbar :=
  (A.map (Int.castRingHom ℚ)).map (algebraMap ℚ Qbar)

/-- A nonzero integer remains nonzero in `Qbar`. -/
theorem qbarIntCast_ne_zero {m : ℤ} (hm : m ≠ 0) :
    algebraMap ℚ Qbar (m : ℚ) ≠ 0 := by
  intro h
  have hmQ : (m : ℚ) = 0 :=
    (map_eq_zero_iff (algebraMap ℚ Qbar)
      (FaithfulSMul.algebraMap_injective ℚ Qbar)).mp h
  exact hm (by exact_mod_cast hmQ)

/-- The literal geometric lower ideal generated by the displayed integral
lower equation family. -/
def geometricIsolatedVertexLowerIdeal
    (lowerEquations : Finset (MvPolynomial (Fin 12) ℤ)) :
    Ideal (MvPolynomial (Fin 12) Qbar) :=
  (isolatedVertexLowerRationalIdeal lowerEquations).map
    (MvPolynomial.map (algebraMap ℚ Qbar))

/-- The exact quotient-node component list for integral translation data
and an integral four-plane. -/
def integralIsolatedVertexQuotientNodeComponents
    (lowerEquations : Finset (MvPolynomial (Fin 12) ℤ))
    (b : IntVector 12) (m : ℤ) (hm : m ≠ 0)
    (A : Matrix (Fin 4) (Fin 13) ℤ) :
    Finset (Ideal (MvPolynomial (Fin 13) Qbar)) :=
  isolatedVertexQuotientNodeComponents
    (geometricIsolatedVertexLowerIdeal lowerEquations)
    (qbarIntVector b) (algebraMap ℚ Qbar (m : ℚ))
    (qbarIntCast_ne_zero hm) (qbarIntMatrix A)

/-- The standard affine representative `(1,w)` of a quotient point, after
coefficient extension to the fixed algebraic closure. -/
def geometricQuotientRationalHomogeneousAffinePoint
    (w : IntVector 12) : Fin 13 → Qbar :=
  fun j ↦ algebraMap ℚ Qbar (quotientRationalHomogeneousAffinePoint w j)

/-- The translated spatial source point `b+m*w`, allowing the dilation to
be an arbitrary nonzero integer. -/
def integralQuotientAffinePoint
    (b w : IntVector 12) (m : ℤ) : IntVector 12 :=
  fun j ↦ b j + m * w j

/-- Exact source/quotient incidence for the affine normalization used in
the manuscript. -/
theorem dropFirst_pointEquiv_integralAffineMap_eq_integralQuotientAffinePoint
    (U : IntegralUnimodularChange 13) (x₀ z : IntVector 13) (m : ℕ) :
    dropFirstIntVector (U.pointEquiv (integralAffineMap x₀ z m)) =
      integralQuotientAffinePoint
        (dropFirstIntVector (U.pointEquiv x₀))
        (dropFirstIntVector (U.pointEquiv z)) (m : ℤ) := by
  rw [U.pointEquiv_integralAffineMap,
    dropFirstIntVector_integralAffineMap]
  rfl

/-- The explicit height assigned to the codimension-four original source
section. -/
def integralQuotientOriginalSourceFourSectionHeightBound
    (U : IntegralUnimodularChange 13) (H : ℕ) : ℕ :=
  Nat.factorial 4 *
    (13 * H * integralMatrixL1Norm U.forward) ^ 4

/-- The explicit height assigned to the codimension-three original source
section. -/
def integralQuotientOriginalSourceThreeSectionHeightBound
    (U : IntegralUnimodularChange 13) (H X M : ℕ) : ℕ :=
  Nat.factorial 3 *
    (13 * (2 * ((M + 12 * X) * H) * H) *
      integralMatrixL1Norm U.forward) ^ 3

/-- A quotient-node component together with an actual bounded-height
rational source section and an actual geometric component of that literal
section.  This is exactly the data missing from the earlier numerical lift.
-/
structure LiteralOriginalSourceExceptionalLift
    (equations : Finset (MvPolynomial (Fin 13) ℤ))
    (lowerEquations : Finset (MvPolynomial (Fin 12) ℤ))
    (coordinateChange : IntegralUnimodularChange 13)
    (b : IntVector 12) (m : ℤ) (hm : m ≠ 0)
    (A : Matrix (Fin 4) (Fin 13) ℤ)
    (quotientComponent : Ideal (MvPolynomial (Fin 13) Qbar))
    (quotientDimension quotientDegree heightBound : ℕ) where
  quotientComponent_mem : quotientComponent ∈
    integralIsolatedVertexQuotientNodeComponents lowerEquations b m hm A
  quotientHilbert : HasGeometricProjectiveDimensionDegree quotientComponent
    quotientDimension quotientDegree
  codimension : ℕ
  one_le_codimension : 1 ≤ codimension
  codimension_le_four : codimension ≤ 4
  sectionMatrixInt : Matrix (Fin codimension) (Fin 13) ℤ
  sectionRank : (sectionMatrixInt.map (Int.castRingHom ℚ)).rank = codimension
  sectionHeight : rationalProjectiveLinearHeight
      (sectionMatrixInt.map (Int.castRingHom ℚ)) ≤ heightBound
  sourceComponent : Ideal (MvPolynomial (Fin 13) Qbar)
  sourceComponent_mem : IsProjectiveSectionComponent equations
    (sectionMatrixInt.map (Int.castRingHom ℚ)) sourceComponent
  sourceDimension : ℕ
  sourceDegree : ℕ
  sourceHilbert : HasGeometricProjectiveDimensionDegree sourceComponent
    sourceDimension sourceDegree
  exceptional : IsDepthSevenExceptionalComponent
    (c := codimension) sourceComponent
  source_incidence :
    ∀ (x : IntVector 13) (hx : x ≠ 0) (w : IntVector 12),
      dropFirstIntVector (coordinateChange.pointEquiv x) =
          integralQuotientAffinePoint b w m →
      geometricQuotientRationalHomogeneousAffinePoint w ∈
          affineIdealZeroLocus quotientComponent →
      ProjectivePointVanishesOnGeometricIdeal sourceComponent
        (integralProjectiveClass x hx)

namespace LiteralOriginalSourceExceptionalLift

/-- Enlarging the permitted section height preserves exceptional-locus
membership. -/
theorem memDepthSevenExceptionalLocus_mono
    {equations : Finset (MvPolynomial (Fin 13) ℤ)}
    {H₀ H₁ : ℕ} {x : Projectivization ℚ (Fin 13 → ℚ)}
    (hH : H₀ ≤ H₁)
    (hx : MemDepthSevenExceptionalLocus equations H₀ x) :
    MemDepthSevenExceptionalLocus equations H₁ x := by
  obtain ⟨c, hc₁, hc₄, A, hA, hheight, P, hcomponent,
    hexceptional, hxP⟩ := hx
  exact ⟨c, hc₁, hc₄, A, hA, hheight.trans hH, P,
    hcomponent, hexceptional, hxP⟩

/-- Once a source point is known to lie on the retained source component,
the literal exceptional-locus conclusion is immediate, with no further
geometry or descent. -/
theorem memDepthSevenExceptionalLocus
    {equations : Finset (MvPolynomial (Fin 13) ℤ)}
    {lowerEquations : Finset (MvPolynomial (Fin 12) ℤ)}
    {U : IntegralUnimodularChange 13}
    {b : IntVector 12} {m : ℤ} {hm : m ≠ 0}
    {A : Matrix (Fin 4) (Fin 13) ℤ}
    {P : Ideal (MvPolynomial (Fin 13) Qbar)}
    {s e heightBound : ℕ}
    (L : LiteralOriginalSourceExceptionalLift equations lowerEquations U
      b m hm A P s e heightBound)
    (x : Projectivization ℚ (Fin 13 → ℚ))
    (hx : ProjectivePointVanishesOnGeometricIdeal L.sourceComponent x) :
    MemDepthSevenExceptionalLocus equations heightBound x := by
  exact ⟨L.codimension, L.one_le_codimension, L.codimension_le_four,
    L.sectionMatrixInt.map (Int.castRingHom ℚ), L.sectionRank,
    L.sectionHeight, L.sourceComponent, L.sourceComponent_mem,
    L.exceptional, hx⟩

/-- Pointwise form of the quotient lift.  The two displayed hypotheses are
the exact incidence relation between the original integral source point and
its affine quotient representative. -/
theorem memDepthSevenExceptionalLocus_of_quotientPoint
    {equations : Finset (MvPolynomial (Fin 13) ℤ)}
    {lowerEquations : Finset (MvPolynomial (Fin 12) ℤ)}
    {U : IntegralUnimodularChange 13}
    {b : IntVector 12} {m : ℤ} {hm : m ≠ 0}
    {A : Matrix (Fin 4) (Fin 13) ℤ}
    {P : Ideal (MvPolynomial (Fin 13) Qbar)}
    {s e heightBound : ℕ}
    (L : LiteralOriginalSourceExceptionalLift equations lowerEquations U
      b m hm A P s e heightBound)
    (x : IntVector 13) (hx : x ≠ 0) (w : IntVector 12)
    (hspatial : dropFirstIntVector (U.pointEquiv x) =
      integralQuotientAffinePoint b w m)
    (hP : geometricQuotientRationalHomogeneousAffinePoint w ∈
      affineIdealZeroLocus P) :
    MemDepthSevenExceptionalLocus equations heightBound
      (integralProjectiveClass x hx) := by
  apply L.memDepthSevenExceptionalLocus
  exact L.source_incidence x hx w hspatial hP

/-- The same pointwise lift with any larger ambient height cutoff. -/
theorem memDepthSevenExceptionalLocus_of_quotientPoint_of_height_le
    {equations : Finset (MvPolynomial (Fin 13) ℤ)}
    {lowerEquations : Finset (MvPolynomial (Fin 12) ℤ)}
    {U : IntegralUnimodularChange 13}
    {b : IntVector 12} {m : ℤ} {hm : m ≠ 0}
    {A : Matrix (Fin 4) (Fin 13) ℤ}
    {P : Ideal (MvPolynomial (Fin 13) Qbar)}
    {s e heightBound ambientHeightBound : ℕ}
    (L : LiteralOriginalSourceExceptionalLift equations lowerEquations U
      b m hm A P s e heightBound)
    (hheight : heightBound ≤ ambientHeightBound)
    (x : IntVector 13) (hx : x ≠ 0) (w : IntVector 12)
    (hspatial : dropFirstIntVector (U.pointEquiv x) =
      integralQuotientAffinePoint b w m)
    (hP : geometricQuotientRationalHomogeneousAffinePoint w ∈
      affineIdealZeroLocus P) :
    MemDepthSevenExceptionalLocus equations ambientHeightBound
      (integralProjectiveClass x hx) := by
  apply memDepthSevenExceptionalLocus_mono hheight
  exact L.memDepthSevenExceptionalLocus_of_quotientPoint
    x hx w hspatial hP

end LiteralOriginalSourceExceptionalLift

namespace StandardAG

/-- Component correspondence for the *displayed* integral quotient plane
and the *displayed* original-coordinate source sections.

The equation-family identity says that the homogeneous unimodular change
sends the original equations to the cone on `lowerEquations`.  The first
conclusion is the vertex-contained case.  The second is the complementary
case after choosing a row with nonzero vertex evaluation.  The dimensions
and degrees are the usual cone/projection values.

The final clause retains incidence: if `(1,w)` lies on the quotient
component and an integral source point has transformed spatial coordinates
`b+m*w`, then its projective class lies on the selected source component.

This is a static projective component statement under an invertible linear
map and a join with one point.  It assumes no height or counting estimate. -/
def IntegralQuotientNodeOriginalSourceComponentProjection : Prop :=
  ∀ (equations : Finset (MvPolynomial (Fin 13) ℤ))
    (U : IntegralUnimodularChange 13)
    (lowerEquations : Finset (MvPolynomial (Fin 12) ℤ))
    (b : IntVector 12) (m : ℤ) (hm : m ≠ 0)
    (A : Matrix (Fin 4) (Fin 13) ℤ)
    (P : Ideal (MvPolynomial (Fin 13) Qbar)) (s e : ℕ),
    U.transformEquationFinset equations =
      liftEquationFinsetAfterFirst lowerEquations →
    (geometricIsolatedVertexLowerIdeal lowerEquations).IsHomogeneous
      (MvPolynomial.homogeneousSubmodule (Fin 12) Qbar) →
    (A.map (Int.castRingHom ℚ)).rank = 4 →
    P ∈ integralIsolatedVertexQuotientNodeComponents
      lowerEquations b m hm A →
    HasGeometricProjectiveDimensionDegree P s e →
      (integralQuotientSourceVertexEvaluation A b m = 0 →
        ∃ Q : Ideal (MvPolynomial (Fin 13) Qbar),
          IsProjectiveSectionComponent equations
            ((integralQuotientOriginalSourceSectionMatrix U
              (integralQuotientSourceFourSectionMatrix A)).map
                (Int.castRingHom ℚ)) Q ∧
          HasGeometricProjectiveDimensionDegree Q s e ∧
          ∀ (x : IntVector 13) (hx : x ≠ 0) (w : IntVector 12),
            dropFirstIntVector (U.pointEquiv x) =
                integralQuotientAffinePoint b w m →
            geometricQuotientRationalHomogeneousAffinePoint w ∈
                affineIdealZeroLocus P →
            ProjectivePointVanishesOnGeometricIdeal Q
              (integralProjectiveClass x hx)) ∧
      (∀ i₀ : Fin 4,
        integralQuotientSourceVertexEvaluation A b m i₀ ≠ 0 →
          ∃ Q : Ideal (MvPolynomial (Fin 13) Qbar),
            IsProjectiveSectionComponent equations
              ((integralQuotientOriginalSourceSectionMatrix U
                (integralQuotientSourceThreeSectionMatrix A b m i₀)).map
                  (Int.castRingHom ℚ)) Q ∧
            HasGeometricProjectiveDimensionDegree Q (s + 1) e ∧
            ∀ (x : IntVector 13) (hx : x ≠ 0) (w : IntVector 12),
              dropFirstIntVector (U.pointEquiv x) =
                  integralQuotientAffinePoint b w m →
              geometricQuotientRationalHomogeneousAffinePoint w ∈
                  affineIdealZeroLocus P →
              ProjectivePointVanishesOnGeometricIdeal Q
                (integralProjectiveClass x hx))

end StandardAG

/-- In the vertex-avoiding case, a quotient component of dimension at least
two yields a literal codimension-three excess component of the original
source section. -/
theorem exists_literalOriginalSourceExceptionalLift_of_away_of_two_le_dimension
    (hProjection : StandardAG.IntegralQuotientNodeOriginalSourceComponentProjection)
    (equations : Finset (MvPolynomial (Fin 13) ℤ))
    (U : IntegralUnimodularChange 13)
    (lowerEquations : Finset (MvPolynomial (Fin 12) ℤ))
    (hfamily : U.transformEquationFinset equations =
      liftEquationFinsetAfterFirst lowerEquations)
    (hLowerHomogeneous :
      (geometricIsolatedVertexLowerIdeal lowerEquations).IsHomogeneous
        (MvPolynomial.homogeneousSubmodule (Fin 12) Qbar))
    (b : IntVector 12) (m : ℤ) (hm : m ≠ 0)
    (A : Matrix (Fin 4) (Fin 13) ℤ)
    (hA : (A.map (Int.castRingHom ℚ)).rank = 4)
    (H X M : ℕ) (hAentry : ∀ i j, (A i j).natAbs ≤ H)
    (hb : ∀ j, (b j).natAbs ≤ X) (hmBound : m.natAbs ≤ M)
    (hvertex : integralQuotientSourceVertexEvaluation A b m ≠ 0)
    (P : Ideal (MvPolynomial (Fin 13) Qbar))
    (hP : P ∈ integralIsolatedVertexQuotientNodeComponents
      lowerEquations b m hm A)
    (s e : ℕ) (hHilbert : HasGeometricProjectiveDimensionDegree P s e)
    (hs : 2 ≤ s) :
    Nonempty (LiteralOriginalSourceExceptionalLift equations lowerEquations U
      b m hm A P s e
      (integralQuotientOriginalSourceThreeSectionHeightBound U H X M)) := by
  have hpivot : ∃ i₀ : Fin 4,
      integralQuotientSourceVertexEvaluation A b m i₀ ≠ 0 := by
    by_contra h
    push_neg at h
    exact hvertex (funext h)
  obtain ⟨i₀, hi₀⟩ := hpivot
  obtain ⟨Q, hQcomponent, hQHilbert, hQincidence⟩ :=
    (hProjection equations U lowerEquations b m hm A P s e
      hfamily hLowerHomogeneous hA hP hHilbert).2 i₀ hi₀
  have hRanks := integralQuotientOriginalSourceSection_rank_dichotomy
    standardLinearAlgebra_isolatedVertexQuotientSourceSectionRanks
      U A b m hm hA
  refine ⟨{
    quotientComponent_mem := hP
    quotientHilbert := hHilbert
    codimension := 3
    one_le_codimension := by omega
    codimension_le_four := by omega
    sectionMatrixInt := integralQuotientOriginalSourceSectionMatrix U
      (integralQuotientSourceThreeSectionMatrix A b m i₀)
    sectionRank := hRanks.2 i₀ hi₀
    sectionHeight := ?_
    sourceComponent := Q
    sourceComponent_mem := hQcomponent
    sourceDimension := s + 1
    sourceDegree := e
    sourceHilbert := hQHilbert
    exceptional := ?_
    source_incidence := hQincidence }⟩
  · exact integralQuotientOriginalSourceThreeSectionMatrix_height_le
      U A b m i₀ hAentry hb hmBound
  · apply isDepthSevenExceptionalComponent_of_dimension_gt_expected
      (c := 3) (r := s + 1) (d := e)
    · omega
    · omega
    · exact hQHilbert
    · omega

/-- In the vertex-avoiding case, a quotient curve of degree at most seven
yields a literal low-degree codimension-three source component. -/
theorem exists_literalOriginalSourceExceptionalLift_of_away_of_curve_degree_le_seven
    (hProjection : StandardAG.IntegralQuotientNodeOriginalSourceComponentProjection)
    (equations : Finset (MvPolynomial (Fin 13) ℤ))
    (U : IntegralUnimodularChange 13)
    (lowerEquations : Finset (MvPolynomial (Fin 12) ℤ))
    (hfamily : U.transformEquationFinset equations =
      liftEquationFinsetAfterFirst lowerEquations)
    (hLowerHomogeneous :
      (geometricIsolatedVertexLowerIdeal lowerEquations).IsHomogeneous
        (MvPolynomial.homogeneousSubmodule (Fin 12) Qbar))
    (b : IntVector 12) (m : ℤ) (hm : m ≠ 0)
    (A : Matrix (Fin 4) (Fin 13) ℤ)
    (hA : (A.map (Int.castRingHom ℚ)).rank = 4)
    (H X M : ℕ) (hAentry : ∀ i j, (A i j).natAbs ≤ H)
    (hb : ∀ j, (b j).natAbs ≤ X) (hmBound : m.natAbs ≤ M)
    (hvertex : integralQuotientSourceVertexEvaluation A b m ≠ 0)
    (P : Ideal (MvPolynomial (Fin 13) Qbar))
    (hP : P ∈ integralIsolatedVertexQuotientNodeComponents
      lowerEquations b m hm A)
    (s e : ℕ) (hHilbert : HasGeometricProjectiveDimensionDegree P s e)
    (hs : s = 1) (he : e ≤ 7) :
    Nonempty (LiteralOriginalSourceExceptionalLift equations lowerEquations U
      b m hm A P s e
      (integralQuotientOriginalSourceThreeSectionHeightBound U H X M)) := by
  have hpivot : ∃ i₀ : Fin 4,
      integralQuotientSourceVertexEvaluation A b m i₀ ≠ 0 := by
    by_contra h
    push_neg at h
    exact hvertex (funext h)
  obtain ⟨i₀, hi₀⟩ := hpivot
  obtain ⟨Q, hQcomponent, hQHilbert, hQincidence⟩ :=
    (hProjection equations U lowerEquations b m hm A P s e
      hfamily hLowerHomogeneous hA hP hHilbert).2 i₀ hi₀
  have hRanks := integralQuotientOriginalSourceSection_rank_dichotomy
    standardLinearAlgebra_isolatedVertexQuotientSourceSectionRanks
      U A b m hm hA
  refine ⟨{
    quotientComponent_mem := hP
    quotientHilbert := hHilbert
    codimension := 3
    one_le_codimension := by omega
    codimension_le_four := by omega
    sectionMatrixInt := integralQuotientOriginalSourceSectionMatrix U
      (integralQuotientSourceThreeSectionMatrix A b m i₀)
    sectionRank := hRanks.2 i₀ hi₀
    sectionHeight := ?_
    sourceComponent := Q
    sourceComponent_mem := hQcomponent
    sourceDimension := s + 1
    sourceDegree := e
    sourceHilbert := hQHilbert
    exceptional := ?_
    source_incidence := hQincidence }⟩
  · exact integralQuotientOriginalSourceThreeSectionMatrix_height_le
      U A b m i₀ hAentry hb hmBound
  · left
    refine ⟨by omega, by omega, Or.inr ⟨e, ?_, he⟩⟩
    simpa [hs] using hQHilbert

/-- In the vertex-contained case, every quotient component of dimension at
least two yields a literal codimension-four excess component of the original
source section. -/
theorem exists_literalOriginalSourceExceptionalLift_of_contained_of_two_le_dimension
    (hProjection : StandardAG.IntegralQuotientNodeOriginalSourceComponentProjection)
    (equations : Finset (MvPolynomial (Fin 13) ℤ))
    (U : IntegralUnimodularChange 13)
    (lowerEquations : Finset (MvPolynomial (Fin 12) ℤ))
    (hfamily : U.transformEquationFinset equations =
      liftEquationFinsetAfterFirst lowerEquations)
    (hLowerHomogeneous :
      (geometricIsolatedVertexLowerIdeal lowerEquations).IsHomogeneous
        (MvPolynomial.homogeneousSubmodule (Fin 12) Qbar))
    (b : IntVector 12) (m : ℤ) (hm : m ≠ 0)
    (A : Matrix (Fin 4) (Fin 13) ℤ)
    (hA : (A.map (Int.castRingHom ℚ)).rank = 4)
    (H : ℕ) (hAentry : ∀ i j, (A i j).natAbs ≤ H)
    (hvertex : integralQuotientSourceVertexEvaluation A b m = 0)
    (P : Ideal (MvPolynomial (Fin 13) Qbar))
    (hP : P ∈ integralIsolatedVertexQuotientNodeComponents
      lowerEquations b m hm A)
    (s e : ℕ) (hHilbert : HasGeometricProjectiveDimensionDegree P s e)
    (hs : 2 ≤ s) :
    Nonempty (LiteralOriginalSourceExceptionalLift equations lowerEquations U
      b m hm A P s e
      (integralQuotientOriginalSourceFourSectionHeightBound U H)) := by
  obtain ⟨Q, hQcomponent, hQHilbert, hQincidence⟩ :=
    (hProjection equations U lowerEquations b m hm A P s e
      hfamily hLowerHomogeneous hA hP hHilbert).1 hvertex
  have hRanks := integralQuotientOriginalSourceSection_rank_dichotomy
    standardLinearAlgebra_isolatedVertexQuotientSourceSectionRanks
      U A b m hm hA
  refine ⟨{
    quotientComponent_mem := hP
    quotientHilbert := hHilbert
    codimension := 4
    one_le_codimension := by omega
    codimension_le_four := by omega
    sectionMatrixInt := integralQuotientOriginalSourceSectionMatrix U
      (integralQuotientSourceFourSectionMatrix A)
    sectionRank := hRanks.1 hvertex
    sectionHeight := ?_
    sourceComponent := Q
    sourceComponent_mem := hQcomponent
    sourceDimension := s
    sourceDegree := e
    sourceHilbert := hQHilbert
    exceptional := ?_
    source_incidence := hQincidence }⟩
  · exact integralQuotientOriginalSourceFourSectionMatrix_height_le
      U A hAentry
  · right
    exact ⟨rfl, s, e, hQHilbert, hs⟩

end

end TranslatedDepthSeven
