import TranslatedDepthSeven.MonicCoordinateModuleFinite
import TranslatedDepthSeven.FiniteNormalizationPointCount
import TranslatedDepthSeven.PrimeAffineNoetherNormalization

/-!
# Product-of-degrees bounds from monic coordinate relations

Suppose that a commutative algebra is generated by finitely many elements
`x i`, and that `x i` satisfies a displayed monic polynomial `p i`.  The
usual reduction of powers modulo `p i` gives a module-spanning family of
cardinality at most the product of the degrees of the `p i`.

The proof below makes that elementary argument literal.  It multiplies the
one-variable power families supplied by
`Submodule.span_range_natDegree_eq_adjoin`; collisions among the resulting
monomials can only decrease the cardinality.  Thus no freeness, flatness,
Hilbert polynomial, or fibre-regularity assertion is used.

After arbitrary specialization of the coefficient ring to a field, the
same family bounds the vector-space dimension of every scalar fibre.  Over
a finite coefficient field it also gives the corresponding global point
bound over affine normalization space.
-/

namespace TranslatedDepthSeven

noncomputable section

open Polynomial
open scoped Pointwise TensorProduct

universe u v w

/-- The scalar fibre of two displayed ring homomorphisms.  Naming this type
keeps the algebra structures, and hence the tensor product, definitionally
tied to the two maps.  This avoids any ambiguity when the rings themselves
carry other natural algebra structures. -/
abbrev ringHomScalarFibre
    (R : Type u) (K : Type w) (A : Type v)
    [CommRing R] [CommRing K] [CommRing A]
    (phi : R →+* K) (g : R →+* A) : Type max v w :=
  letI : Algebra R K := phi.toAlgebra
  letI : Algebra R A := g.toAlgebra
  K ⊗[R] A

/-- For a finite family of integral elements with displayed monic
relations, the algebra generated by those elements has a spanning finset
whose cardinality is at most the product of the displayed degrees.

The index finset is retained in the statement because this is the exact
inductive form of the elementary power-reduction argument. -/
theorem exists_finset_span_adjoin_card_le_prod_natDegree
    {R : Type u} {A : Type v} [CommRing R] [CommRing A] [Algebra R A]
    {ι : Type*} [DecidableEq ι]
    (s : Finset ι) (x : ι → A) (p : ι → R[X])
    (hrelation : ∀ i ∈ s,
      (p i).Monic ∧ (p i).eval₂ (algebraMap R A) (x i) = 0) :
    ∃ T : Finset A,
      Submodule.span R (T : Set A) =
        (Algebra.adjoin R (x '' (s : Set ι))).toSubmodule ∧
      T.card ≤ ∏ i ∈ s, (p i).natDegree := by
  classical
  induction s using Finset.induction_on with
  | empty =>
      refine ⟨{1}, ?_, by simp⟩
      rw [Finset.coe_singleton, Finset.coe_empty, Set.image_empty,
        Algebra.adjoin_empty, Algebra.toSubmodule_bot,
        Submodule.one_eq_span]
  | @insert a s ha ih =>
      obtain ⟨T, hTspan, hTcard⟩ :=
        ih (fun i hi => hrelation i (Finset.mem_insert_of_mem hi))
      let U : Finset A :=
        (Finset.range (p a).natDegree).image (x a ^ ·)
      have hUspan : Submodule.span R (U : Set A) =
          (Algebra.adjoin R ({x a} : Set A)).toSubmodule := by
        simpa only [U] using
          (Submodule.span_range_natDegree_eq_adjoin
            (hrelation a (Finset.mem_insert_self a s)).1
            (by simpa only [aeval_def] using
              (hrelation a (Finset.mem_insert_self a s)).2))
      refine ⟨U * T, ?_, ?_⟩
      · rw [Finset.coe_mul, ← Submodule.span_mul_span, hUspan, hTspan,
          ← Algebra.adjoin_union_coe_submodule]
        congr 2
        ext y
        constructor
        · rintro (rfl | ⟨i, hi, rfl⟩)
          · exact ⟨a, by simp, rfl⟩
          · exact ⟨i, by simp [hi], rfl⟩
        · rintro ⟨i, hi, rfl⟩
          change i ∈ insert a s at hi
          rcases Finset.mem_insert.mp hi with rfl | hi
          · exact Or.inl rfl
          · exact Or.inr ⟨i, hi, rfl⟩
      · refine (Finset.card_mul_le).trans ?_
        rw [Finset.prod_insert ha]
        apply Nat.mul_le_mul
        · exact (Finset.card_image_le).trans_eq (Finset.card_range _)
        · exact hTcard

/-- If the displayed elements generate the whole algebra, the preceding
finset spans the whole underlying module. -/
theorem exists_finset_span_top_card_le_prod_natDegree
    {R : Type u} {A : Type v} [CommRing R] [CommRing A] [Algebra R A]
    {N : ℕ} (x : Fin N → A) (p : Fin N → R[X])
    (hgenerate : Algebra.adjoin R (Set.range x) = ⊤)
    (hrelation : ∀ i,
      (p i).Monic ∧ (p i).eval₂ (algebraMap R A) (x i) = 0) :
    ∃ T : Finset A,
      Submodule.span R (T : Set A) = ⊤ ∧
      T.card ≤ ∏ i, (p i).natDegree := by
  classical
  obtain ⟨T, hTspan, hTcard⟩ :=
    exists_finset_span_adjoin_card_le_prod_natDegree
      Finset.univ x p (fun i _hi => hrelation i)
  refine ⟨T, ?_, ?_⟩
  · rw [Finset.coe_univ, Set.image_univ, hgenerate] at hTspan
    exact hTspan
  · simpa using hTcard

/-- The product of the displayed monic degrees bounds every field-valued
scalar fibre of the algebra.  The coefficient specialization is completely
arbitrary; neither injectivity nor flatness is required. -/
theorem finrank_scalarFibre_le_prod_natDegree
    (R : Type u) (K : Type w) (A : Type v)
    [CommRing R] [Field K] [CommRing A]
    [Algebra R K] [Algebra R A]
    {N : ℕ} (x : Fin N → A) (p : Fin N → R[X])
    (hgenerate : Algebra.adjoin R (Set.range x) = ⊤)
    (hrelation : ∀ i,
      (p i).Monic ∧ (p i).eval₂ (algebraMap R A) (x i) = 0) :
    Module.finrank K (K ⊗[R] A) ≤ ∏ i, (p i).natDegree := by
  classical
  obtain ⟨T, hTspan, hTcard⟩ :=
    exists_finset_span_top_card_le_prod_natDegree
      x p hgenerate hrelation
  let e : T ≃ Fin T.card := T.equivFin
  let spanningFamily : Fin T.card → A :=
    fun i => (e.symm i : T)
  have hfamilyRange : Set.range spanningFamily = (T : Set A) := by
    ext y
    constructor
    · rintro ⟨i, rfl⟩
      exact (e.symm i).property
    · intro hy
      let z : T := ⟨y, hy⟩
      exact ⟨e z, by simp [spanningFamily, z]⟩
  have hspan :
      Submodule.span R (Set.range spanningFamily) = ⊤ := by
    rw [hfamilyRange]
    exact hTspan
  exact (finrank_scalarFibre_le_of_span_fin
    R K A T.card spanningFamily hspan).trans hTcard

/-- Map-explicit version of `finrank_scalarFibre_le_prod_natDegree`.
The named scalar-fibre type is convenient when a concrete polynomial ring
also has canonical instances which are not definitionally the displayed
normalization structure map. -/
theorem finrank_ringHomScalarFibre_le_prod_natDegree
    (R : Type u) (K : Type w) (A : Type v)
    [CommRing R] [Field K] [CommRing A]
    (phi : R →+* K) (g : R →+* A)
    {N : ℕ} (x : Fin N → A) (p : Fin N → R[X])
    (hgenerate :
      letI : Algebra R A := g.toAlgebra
      Algebra.adjoin R (Set.range x) = ⊤)
    (hrelation : ∀ i,
      (p i).Monic ∧ (p i).eval₂ g (x i) = 0) :
    Module.finrank K (ringHomScalarFibre R K A phi g) ≤
      ∏ i, (p i).natDegree := by
  letI : Algebra R K := phi.toAlgebra
  letI : Algebra R A := g.toAlgebra
  exact finrank_scalarFibre_le_prod_natDegree
    R K A x p hgenerate hrelation

/-- Scheme-theoretic length form of
`finrank_ringHomScalarFibre_le_prod_natDegree`.  The monic relations make
the scalar fibre finite-dimensional, so its module length over the field is
its vector-space dimension. -/
theorem length_ringHomScalarFibre_le_prod_natDegree
    (R : Type u) (K : Type w) (A : Type v)
    [CommRing R] [Field K] [CommRing A]
    (phi : R →+* K) (g : R →+* A)
    {N : ℕ} (x : Fin N → A) (p : Fin N → R[X])
    (hgenerate :
      letI : Algebra R A := g.toAlgebra
      Algebra.adjoin R (Set.range x) = ⊤)
    (hrelation : ∀ i,
      (p i).Monic ∧ (p i).eval₂ g (x i) = 0) :
    Module.length K (ringHomScalarFibre R K A phi g) ≤
      (∏ i, (p i).natDegree : ℕ∞) := by
  letI : Algebra R K := phi.toAlgebra
  letI : Algebra R A := g.toAlgebra
  letI : Module.Finite R A :=
    moduleFinite_of_monic_coordinate_relations
      x hgenerate p hrelation
  letI : Module.Finite K (K ⊗[R] A) :=
    Module.Finite.base_change R K A
  rw [Module.length_eq_finrank]
  exact_mod_cast finrank_scalarFibre_le_prod_natDegree
    R K A x p hgenerate hrelation

/-- Quantitative finite-field point bound associated with a displayed
normalization map.  The only input beyond the map is a generating family
with monic relations; the constant is the literal product of their degrees.
-/
theorem natCard_algHom_le_prod_natDegree_mul_pow
    (k : Type u) (A : Type v) (d : ℕ)
    [Field k] [Finite k] [CommRing A] [Algebra k A]
    (g : MvPolynomial (Fin d) k →ₐ[k] A)
    {N : ℕ} (x : Fin N → A)
    (p : Fin N → (MvPolynomial (Fin d) k)[X])
    (hgenerate :
      letI : Algebra (MvPolynomial (Fin d) k) A :=
        g.toRingHom.toAlgebra
      Algebra.adjoin (MvPolynomial (Fin d) k) (Set.range x) = ⊤)
    (hrelation : ∀ i,
      (p i).Monic ∧ (p i).eval₂ g.toRingHom (x i) = 0) :
    Nat.card (A →ₐ[k] k) ≤
      (∏ i, (p i).natDegree) * Nat.card k ^ d := by
  classical
  let B := MvPolynomial (Fin d) k
  letI : Algebra B A := g.toRingHom.toAlgebra
  obtain ⟨T, hTspan, hTcard⟩ :=
    exists_finset_span_top_card_le_prod_natDegree
      x p hgenerate hrelation
  let e : T ≃ Fin T.card := T.equivFin
  let spanningFamily : Fin T.card → A :=
    fun i => (e.symm i : T)
  have hfamilyRange : Set.range spanningFamily = (T : Set A) := by
    ext y
    constructor
    · rintro ⟨i, rfl⟩
      exact (e.symm i).property
    · intro hy
      let z : T := ⟨y, hy⟩
      exact ⟨e z, by simp [spanningFamily, z]⟩
  have hspan : Submodule.span B (Set.range spanningFamily) = ⊤ := by
    rw [hfamilyRange]
    exact hTspan
  exact (natCard_algHom_le_mul_pow_of_normalization_span
    k A d T.card g spanningFamily hspan).trans
      (Nat.mul_le_mul_right (Nat.card k ^ d) hTcard)

/-- A finite algebra certified by finitely many monic coordinate relations
has Krull dimension no larger than its coefficient ring.  This is only an
upper bound.  Without injectivity or flatness, no equality and no
equidimensionality statement follows after specialization. -/
theorem ringKrullDim_le_of_monic_generators
    {R : Type u} {A : Type v} [CommRing R] [CommRing A] [Algebra R A]
    {N : ℕ} (x : Fin N → A) (p : Fin N → R[X])
    (hgenerate : Algebra.adjoin R (Set.range x) = ⊤)
    (hrelation : ∀ i,
      (p i).Monic ∧ (p i).eval₂ (algebraMap R A) (x i) = 0) :
    ringKrullDim A ≤ ringKrullDim R := by
  letI : Module.Finite R A :=
    moduleFinite_of_monic_coordinate_relations
      x hgenerate p hrelation
  exact ringKrullDim_le_of_isIntegral

end

end TranslatedDepthSeven
