import Mathlib.RingTheory.AdjoinRoot
import Mathlib.RingTheory.Adjoin.Polynomial

/-!
# The algebra generated by one integral coordinate

If a polynomial `f` vanishes at `x`, evaluation factors through
`AdjoinRoot f`.  The range of the resulting map is exactly the subalgebra
generated by `x`.  More generally, relative to a previously constructed map
`B →ₐ[R] A`, the new range is the join of the old range with `R[x]`; a
two-step formula is also proved explicitly.  In particular, a finite list of
such steps is surjective once its selected coordinates generate the target.
Monicity is not needed for surjectivity; it is needed only for the finite-free
rank bound in `MonicAdjoinRootTowerRank.lean`.
-/

namespace TranslatedDepthSeven

noncomputable section

open Polynomial

variable {R A : Type*} [CommRing R] [CommRing A] [Algebra R A]

/-- Evaluation through `AdjoinRoot f` has precisely the algebra generated by
the selected root as its range. -/
theorem range_adjoinRoot_liftAlgHom_eq_adjoin_singleton
    (f : R[X]) (x : A) (hx : Polynomial.aeval x f = 0) :
    (AdjoinRoot.liftAlgHom f (Algebra.ofId R A) x hx).range =
      Algebra.adjoin R ({x} : Set A) := by
  ext y
  constructor
  · rintro ⟨z, rfl⟩
    induction z using AdjoinRoot.induction_on with
    | ih p =>
        change
          AdjoinRoot.liftAlgHom f (Algebra.ofId R A) x hx
              (AdjoinRoot.mk f p) ∈ Algebra.adjoin R ({x} : Set A)
        simpa [AdjoinRoot.liftAlgHom_mk, Polynomial.aeval_def] using
          (Polynomial.aeval_mem_adjoin_singleton (p := p) R x)
  · intro hy
    obtain ⟨p, hp⟩ := Algebra.adjoin_mem_exists_aeval R x hy
    refine ⟨AdjoinRoot.mk f p, ?_⟩
    change AdjoinRoot.liftAlgHom f (Algebra.ofId R A) x hx
        (AdjoinRoot.mk f p) = y
    simpa [AdjoinRoot.liftAlgHom_mk, Polynomial.aeval_def] using hp

/-- A vanishing relation gives a surjection from the corresponding
`AdjoinRoot` whenever the chosen coordinate generates the target algebra. -/
theorem adjoinRoot_liftAlgHom_surjective_of_adjoin_singleton_eq_top
    (f : R[X]) (x : A) (hx : Polynomial.aeval x f = 0)
    (hgen : Algebra.adjoin R ({x} : Set A) = ⊤) :
    Function.Surjective
      (AdjoinRoot.liftAlgHom f (Algebra.ofId R A) x hx) := by
  rw [← AlgHom.range_eq_top]
  exact (range_adjoinRoot_liftAlgHom_eq_adjoin_singleton f x hx).trans hgen

section Relative

variable {B : Type*} [CommRing B] [Algebra R B]

/-- Relative form of `range_adjoinRoot_liftAlgHom_eq_adjoin_singleton`.
If `phi : B →ₐ[R] A` is a previously constructed algebra map and a
polynomial over `B` vanishes at `x : A`, then adjoining that root enlarges
the old range by precisely the `R`-subalgebra generated by `x`.

This is the induction step for an iterated triangular presentation: no
claim that `B` embeds into `A` is needed. -/
theorem range_adjoinRoot_liftAlgHom_eq_sup
    (f : B[X]) (phi : B →ₐ[R] A) (x : A)
    (hx : f.eval₂ phi x = 0) :
    (AdjoinRoot.liftAlgHom f phi x hx).range =
      phi.range ⊔ Algebra.adjoin R ({x} : Set A) := by
  apply le_antisymm
  · rintro _ ⟨z, rfl⟩
    induction z using AdjoinRoot.induction_on with
    | ih p =>
        change p.eval₂ phi x ∈ phi.range ⊔ Algebra.adjoin R ({x} : Set A)
        let C : Subalgebra R A :=
          phi.range ⊔ Algebra.adjoin R ({x} : Set A)
        let phiC : B →ₐ[R] C := phi.codRestrict C (fun b =>
          Algebra.mem_sup_left ⟨b, rfl⟩)
        let xC : C :=
          ⟨x, Algebra.mem_sup_right (Algebra.subset_adjoin rfl)⟩
        have hp : ((p.eval₂ phiC xC : C) : A) = p.eval₂ phi x := by
          simpa [phiC, xC] using
            (Polynomial.hom_eval₂ p phiC.toRingHom C.val.toRingHom xC)
        rw [← hp]
        exact (p.eval₂ phiC xC).property
  · apply sup_le
    · rintro _ ⟨b, rfl⟩
      refine ⟨AdjoinRoot.of f b, ?_⟩
      simp
    · apply Algebra.adjoin_le
      rintro _ (rfl : _ = x)
      refine ⟨AdjoinRoot.root f, ?_⟩
      simp

/-- Surjectivity criterion for one relative triangular step.  Repeating this
statement for a finite list of explicit algebra generators produces a
surjection from the corresponding iterated `AdjoinRoot` tower. -/
theorem adjoinRoot_liftAlgHom_surjective_of_range_sup_eq_top
    (f : B[X]) (phi : B →ₐ[R] A) (x : A)
    (hx : f.eval₂ phi x = 0)
    (hgen : phi.range ⊔ Algebra.adjoin R ({x} : Set A) = ⊤) :
    Function.Surjective (AdjoinRoot.liftAlgHom f phi x hx) := by
  rw [← AlgHom.range_eq_top,
    range_adjoinRoot_liftAlgHom_eq_sup f phi x hx]
  exact hgen

/-- Two relative triangular steps, written out without introducing a tower
interface.  The formula makes the induction used for any finite list of
coordinates completely explicit. -/
theorem range_two_adjoinRoot_liftAlgHom_eq_sup
    (f : B[X]) (phi : B →ₐ[R] A) (x : A)
    (hx : f.eval₂ phi x = 0)
    (g : (AdjoinRoot f)[X]) (y : A)
    (hy : g.eval₂ (AdjoinRoot.liftAlgHom f phi x hx) y = 0) :
    (AdjoinRoot.liftAlgHom g
      (AdjoinRoot.liftAlgHom f phi x hx) y hy).range =
      (phi.range ⊔ Algebra.adjoin R ({x} : Set A)) ⊔
        Algebra.adjoin R ({y} : Set A) := by
  rw [range_adjoinRoot_liftAlgHom_eq_sup g
      (AdjoinRoot.liftAlgHom f phi x hx) y hy,
    range_adjoinRoot_liftAlgHom_eq_sup f phi x hx]

/-- Surjectivity after two relative triangular steps. -/
theorem two_adjoinRoot_liftAlgHom_surjective
    (f : B[X]) (phi : B →ₐ[R] A) (x : A)
    (hx : f.eval₂ phi x = 0)
    (g : (AdjoinRoot f)[X]) (y : A)
    (hy : g.eval₂ (AdjoinRoot.liftAlgHom f phi x hx) y = 0)
    (hgen : (phi.range ⊔ Algebra.adjoin R ({x} : Set A)) ⊔
      Algebra.adjoin R ({y} : Set A) = ⊤) :
    Function.Surjective
      (AdjoinRoot.liftAlgHom g
        (AdjoinRoot.liftAlgHom f phi x hx) y hy) := by
  rw [← AlgHom.range_eq_top,
    range_two_adjoinRoot_liftAlgHom_eq_sup f phi x hx g y hy]
  exact hgen

end Relative

end

end TranslatedDepthSeven
