import TranslatedDepthSeven.PublishedCountingTheorems
import Mathlib.RingTheory.MvPolynomial.Localization
import Mathlib.RingTheory.UniqueFactorizationDomain.Multiplicity

/-!
# Primitive integral equations and their projective closure

This file proves the precise multivariable Gauss-lemma statement needed
when Salberger's theorem is applied to a projected hypersurface.  The
notion of primitive used here is literal: every integer dividing every
coefficient is a unit.  No assertion about a parameterized family or
about specialization of components is involved.
-/

namespace TranslatedDepthSeven

noncomputable section

open MvPolynomial Published

attribute [local instance] MvPolynomial.algebraMvPolynomial

/-- An integral multivariable polynomial is primitive when an integer
which divides all its coefficients is necessarily a unit. -/
def IsPrimitiveIntegralMvPolynomial {N : ℕ}
    (G : MvPolynomial (Fin N) ℤ) : Prop :=
  ∀ n : ℤ, (∀ m, n ∣ G.coeff m) → IsUnit n

/-- A factor of a primitive integral polynomial which becomes a unit
after coefficient extension to `ℚ` was already a unit over `ℤ`.

The proof is the elementary content argument: such a factor is a
constant integer, and that integer divides every coefficient of the
primitive polynomial. -/
theorem isUnit_of_map_isUnit_of_dvd_primitive
    {N : ℕ} {G A : MvPolynomial (Fin N) ℤ}
    (hprimitive : IsPrimitiveIntegralMvPolynomial G)
    (hAG : A ∣ G)
    (hAunit : IsUnit (MvPolynomial.map (Int.castRingHom ℚ) A)) :
    IsUnit A := by
  have hdegreeMap :
      (MvPolynomial.map (Int.castRingHom ℚ) A).totalDegree = 0 :=
    (MvPolynomial.isUnit_iff_totalDegree_of_isReduced.mp hAunit).2
  have hdegree : A.totalDegree = 0 := by
    rw [MvPolynomial.totalDegree,
      MvPolynomial.support_map_of_injective A Int.cast_injective] at hdegreeMap
    exact hdegreeMap
  have hAeq : A = MvPolynomial.C (A.coeff 0) :=
    MvPolynomial.totalDegree_eq_zero_iff_eq_C.mp hdegree
  let n : ℤ := A.coeff 0
  have hncoeff : ∀ m, n ∣ G.coeff m := by
    intro m
    obtain ⟨Q, hQ⟩ := hAG
    refine ⟨Q.coeff m, ?_⟩
    rw [hQ, hAeq, MvPolynomial.coeff_C_mul]
  rw [hAeq]
  exact (hprimitive n hncoeff).map MvPolynomial.C

/-- Multivariable Gauss lemma in the only direction needed here: a
primitive integral polynomial which is irreducible after extension to
`ℚ` is irreducible over `ℤ`. -/
theorem irreducible_of_primitive_of_map_irreducible
    {N : ℕ} {G : MvPolynomial (Fin N) ℤ}
    (hprimitive : IsPrimitiveIntegralMvPolynomial G)
    (hirreducible :
      Irreducible (MvPolynomial.map (Int.castRingHom ℚ) G)) :
    Irreducible G := by
  refine ⟨fun hunit ↦ hirreducible.not_isUnit
      (hunit.map (MvPolynomial.map (Int.castRingHom ℚ))), ?_⟩
  intro A B hG
  have hGmap : MvPolynomial.map (Int.castRingHom ℚ) G =
      MvPolynomial.map (Int.castRingHom ℚ) A *
        MvPolynomial.map (Int.castRingHom ℚ) B := by
    simpa using congrArg (MvPolynomial.map (Int.castRingHom ℚ)) hG
  exact (hirreducible.isUnit_or_isUnit hGmap).imp
    (fun hA ↦ isUnit_of_map_isUnit_of_dvd_primitive
      hprimitive ⟨B, hG⟩ hA)
    (fun hB ↦ isUnit_of_map_isUnit_of_dvd_primitive
      hprimitive ⟨A, by simpa [mul_comm] using hG⟩ hB)

/-- The contraction to `ℤ` of the rational principal ideal generated by
a primitive integral irreducible equation is exactly its integral
principal ideal.

This is the principal-ideal form of multivariable Gauss's lemma.  The
last step uses the ideal correspondence for localization at the nonzero
integers. -/
theorem projectiveIntegralClosureIdeal_span_primitive
    {N : ℕ} (G : MvPolynomial (Fin (N + 1)) ℤ)
    (hprimitive : IsPrimitiveIntegralMvPolynomial G)
    (hirreducible :
      Irreducible (MvPolynomial.map (Int.castRingHom ℚ) G)) :
    projectiveIntegralClosureIdeal
        (Ideal.span {MvPolynomial.map (Int.castRingHom ℚ) G}) =
      Ideal.span {G} := by
  let J : Ideal (MvPolynomial (Fin (N + 1)) ℤ) := Ideal.span {G}
  let M : Submonoid (MvPolynomial (Fin (N + 1)) ℤ) :=
    (nonZeroDivisors ℤ).map MvPolynomial.C
  have hGirreducible : Irreducible G :=
    irreducible_of_primitive_of_map_irreducible hprimitive hirreducible
  have hGprime : Prime G :=
    UniqueFactorizationMonoid.irreducible_iff_prime.mp hGirreducible
  have hJprime : J.IsPrime := by
    exact (Ideal.span_singleton_prime hGprime.ne_zero).mpr hGprime
  have halgebraMap :
      algebraMap (MvPolynomial (Fin (N + 1)) ℤ)
          (MvPolynomial (Fin (N + 1)) ℚ) =
        intPolynomialToRat := rfl
  have hmapJ : Ideal.map intPolynomialToRat J =
      Ideal.span {MvPolynomial.map (Int.castRingHom ℚ) G} := by
    change Ideal.map intPolynomialToRat (Ideal.span {G}) = _
    rw [Ideal.map_span]
    congr 1
    ext F
    simp [intPolynomialToRat]
  have hmapJne : Ideal.map
      (algebraMap (MvPolynomial (Fin (N + 1)) ℤ)
        (MvPolynomial (Fin (N + 1)) ℚ)) J ≠ ⊤ := by
    rw [halgebraMap, hmapJ]
    exact (Ideal.span_singleton_prime hirreducible.ne_zero).mpr
      (UniqueFactorizationMonoid.irreducible_iff_prime.mp hirreducible) |>.ne_top
  have hdisjoint : Disjoint (M : Set (MvPolynomial (Fin (N + 1)) ℤ))
      (J : Set (MvPolynomial (Fin (N + 1)) ℤ)) := by
    exact (IsLocalization.map_algebraMap_ne_top_iff_disjoint M
      (MvPolynomial (Fin (N + 1)) ℚ) J).mp hmapJne
  have hcontract := IsLocalization.comap_map_of_isPrime_disjoint M
    (MvPolynomial (Fin (N + 1)) ℚ) J hJprime hdisjoint
  rw [halgebraMap, hmapJ] at hcontract
  simpa [projectiveIntegralClosureIdeal, J] using hcontract

end

end TranslatedDepthSeven
