import TranslatedDepthSeven.AugmentedLinearNormalization
import TranslatedDepthSeven.FiniteBirationalNormality
import Mathlib.FieldTheory.IntermediateField.Adjoin.Algebra

/-!
# A primitive added coordinate gives generic degree one

This file proves the fraction-field part of the familiar construction of a
birational linear projection.  If a finite normalization is augmented by an
element which generates the ambient function field over the normalization
field, then the fraction field of the augmented image is the whole ambient
function field.  Everything here is commutative algebra; no geometric
projection theorem or degree comparison is used.
-/

namespace TranslatedDepthSeven

noncomputable section

open MvPolynomial

universe u v

/-- If the field generated by the image of a domain is the target field,
then the canonical lift from its fraction field is onto. -/
theorem fractionRing_liftAlgHom_surjective_of_adjoin_range_eq_top
    {K : Type u} {B : Type v} {L : Type*}
    [Field K] [CommRing B] [IsDomain B] [Algebra K B]
    [Field L] [Algebra K L]
    (g : B →ₐ[K] L) (hg : Function.Injective g)
    (hgen : IntermediateField.adjoin K (g.range : Set L) = ⊤) :
    Function.Surjective
      (IsFractionRing.liftAlgHom
        (K := FractionRing B) hg : FractionRing B →ₐ[K] L) := by
  rw [← AlgHom.fieldRange_eq_top]
  exact (IsFractionRing.liftAlgHom_fieldRange hg).trans hgen

/-- Under the algebra structure furnished by the lifted fraction-field map,
the preceding generation condition is exactly generic degree one. -/
theorem fractionRing_finrank_eq_one_of_adjoin_range_eq_top
    {K : Type u} {B : Type v} {L : Type*}
    [Field K] [CommRing B] [IsDomain B] [Algebra K B]
    [Field L] [Algebra K L]
    (g : B →ₐ[K] L) (hg : Function.Injective g)
    (hgen : IntermediateField.adjoin K (g.range : Set L) = ⊤) :
    let f : FractionRing B →ₐ[K] L :=
      IsFractionRing.liftAlgHom (K := FractionRing B) hg
    letI : Algebra (FractionRing B) L := f.toRingHom.toAlgebra
    Module.finrank (FractionRing B) L = 1 := by
  dsimp only
  let f : FractionRing B →ₐ[K] L :=
    IsFractionRing.liftAlgHom (K := FractionRing B) hg
  letI : Algebra (FractionRing B) L := f.toRingHom.toAlgebra
  apply (finrank_eq_one_iff_of_nonzero' (1 : L) one_ne_zero).2
  intro z
  obtain ⟨c, rfl⟩ :=
    fractionRing_liftAlgHom_surjective_of_adjoin_range_eq_top g hg hgen z
  refine ⟨c, ?_⟩
  rw [Algebra.smul_def, mul_one]
  change f c = f c
  rfl

/-- The same generation condition gives a canonical algebra equivalence of
function fields. -/
def fractionRingAlgEquivOfAdjoinRangeEqTop
    {K : Type u} {B : Type v} {L : Type*}
    [Field K] [CommRing B] [IsDomain B] [Algebra K B]
    [Field L] [Algebra K L]
    (g : B →ₐ[K] L) (hg : Function.Injective g)
    (hgen : IntermediateField.adjoin K (g.range : Set L) = ⊤) :
    FractionRing B ≃ₐ[K] L :=
  AlgEquiv.ofBijective
    (IsFractionRing.liftAlgHom
      (K := FractionRing B) hg : FractionRing B →ₐ[K] L)
    ⟨(IsFractionRing.liftAlgHom
      (K := FractionRing B) hg : FractionRing B →ₐ[K] L).injective,
      fractionRing_liftAlgHom_surjective_of_adjoin_range_eq_top
        g hg hgen⟩

/-! ## Application to a homogeneous linear normalization -/

/-- If the old normalization coordinates together with `u` generate the
function field, then the fraction field of the scheme-theoretic image of
the augmented coordinate map is the whole function field.

The hypothesis is written without choosing an identification of the old
rational-function field with its image: it simply says that the images of
the old normalization algebra and `u` generate `FractionRing A` as a field
over `K`. -/
theorem augmentedLinearNormalization_image_adjoin_eq_top_of_primitive
    {K : Type u} [Field K] {tau : Type v}
    {I : Ideal (MvPolynomial tau K)} (hIprime : I.IsPrime)
    (D : HomogeneousLinearNormalizationData I)
    (u : MvPolynomial tau K ⧸ I)
    (hprimitive :
      let A := MvPolynomial tau K ⧸ I
      let L := FractionRing A
      let oldToL : MvPolynomial (Fin D.parameterCount) K →ₐ[K] L :=
        (IsScalarTower.toAlgHom K A L).comp D.hom
      IntermediateField.adjoin K
        ((oldToL.range : Set L) ∪ {algebraMap A L u}) = ⊤) :
    let A := MvPolynomial tau K ⧸ I
    let L := FractionRing A
    let h := augmentedLinearNormalizationHom D u
    let J := RingHom.ker h
    let B := MvPolynomial (Fin (D.parameterCount + 1)) K ⧸ J
    let imageToSource : B →ₐ[K] A := Ideal.kerLiftAlg h
    let imageToL : B →ₐ[K] L :=
      (IsScalarTower.toAlgHom K A L).comp imageToSource
    IntermediateField.adjoin K (imageToL.range : Set L) = ⊤ := by
  dsimp only at hprimitive ⊢
  letI : I.IsPrime := hIprime
  let A := MvPolynomial tau K ⧸ I
  let L := FractionRing A
  let h := augmentedLinearNormalizationHom D u
  let J := RingHom.ker h
  have hJprime : J.IsPrime := RingHom.ker_isPrime h
  letI : J.IsPrime := hJprime
  let B := MvPolynomial (Fin (D.parameterCount + 1)) K ⧸ J
  let imageToSource : B →ₐ[K] A := Ideal.kerLiftAlg h
  let imageToL : B →ₐ[K] L :=
    (IsScalarTower.toAlgHom K A L).comp imageToSource
  let oldToL : MvPolynomial (Fin D.parameterCount) K →ₐ[K] L :=
    (IsScalarTower.toAlgHom K A L).comp D.hom
  have hsubset :
      (oldToL.range : Set L) ∪ {algebraMap A L u} ⊆
        (imageToL.range : Set L) := by
    intro z hz
    rcases hz with hz | hz
    · obtain ⟨b, rfl⟩ := hz
      refine ⟨Ideal.Quotient.mk J
        (mvPolynomialSuccInclusion K D.parameterCount b), ?_⟩
      change algebraMap A L
          (h (mvPolynomialSuccInclusion K D.parameterCount b)) =
        algebraMap A L (D.hom b)
      rw [← augmentedLinearNormalizationHom_comp_succInclusion D u]
      rfl
    · have hz' : z = algebraMap A L u := by simpa using hz
      subst z
      refine ⟨Ideal.Quotient.mk J (X 0), ?_⟩
      change algebraMap A L (h (X 0)) = algebraMap A L u
      rw [augmentedLinearNormalizationHom_X_zero]
  apply top_unique
  rw [← hprimitive]
  exact IntermediateField.adjoin.mono K _ _ hsubset

/-- Exact birationality theorem for normalization plus a primitive
linear coordinate.  The image ring is the quotient by the literal kernel
of the augmented coordinate map.  Its injection into the source is finite,
and the induced map of fraction fields is bijective.  The generic
`finrank = 1` formulation is supplied by
`fractionRing_finrank_eq_one_of_adjoin_range_eq_top`. -/
theorem augmentedLinearNormalization_genericDegreeOne_of_primitive
    {K : Type u} [Field K] {tau : Type v}
    {I : Ideal (MvPolynomial tau K)} (hIprime : I.IsPrime)
    (D : HomogeneousLinearNormalizationData I)
    (u : MvPolynomial tau K ⧸ I)
    (hprimitive :
      let A := MvPolynomial tau K ⧸ I
      let L := FractionRing A
      let oldToL : MvPolynomial (Fin D.parameterCount) K →ₐ[K] L :=
        (IsScalarTower.toAlgHom K A L).comp D.hom
      IntermediateField.adjoin K
        ((oldToL.range : Set L) ∪ {algebraMap A L u}) = ⊤) :
    let A := MvPolynomial tau K ⧸ I
    let L := FractionRing A
    let h := augmentedLinearNormalizationHom D u
    let J := RingHom.ker h
    let _ : J.IsPrime := RingHom.ker_isPrime h
    let B := MvPolynomial (Fin (D.parameterCount + 1)) K ⧸ J
    let imageToSource : B →ₐ[K] A := Ideal.kerLiftAlg h
    let imageToL : B →ₐ[K] L :=
      (IsScalarTower.toAlgHom K A L).comp imageToSource
    let fractionImageToL : FractionRing B →ₐ[K] L :=
      IsFractionRing.liftAlgHom (K := FractionRing B) (g := imageToL)
        ((IsFractionRing.injective A L).comp
          (Ideal.kerLiftAlg_injective h))
    imageToSource.Finite ∧
      Function.Bijective fractionImageToL := by
  dsimp only at hprimitive ⊢
  letI : I.IsPrime := hIprime
  let A := MvPolynomial tau K ⧸ I
  let L := FractionRing A
  let h := augmentedLinearNormalizationHom D u
  let J := RingHom.ker h
  have hJprime : J.IsPrime := RingHom.ker_isPrime h
  letI : J.IsPrime := hJprime
  let B := MvPolynomial (Fin (D.parameterCount + 1)) K ⧸ J
  let imageToSource : B →ₐ[K] A := Ideal.kerLiftAlg h
  let imageToL : B →ₐ[K] L :=
    (IsScalarTower.toAlgHom K A L).comp imageToSource
  have himageInjective : Function.Injective imageToL :=
    (IsFractionRing.injective A L).comp
      (Ideal.kerLiftAlg_injective h)
  let fractionImageToL : FractionRing B →ₐ[K] L :=
    IsFractionRing.liftAlgHom (K := FractionRing B) (g := imageToL)
      himageInjective
  have hgen : IntermediateField.adjoin K
      (imageToL.range : Set L) = ⊤ :=
    augmentedLinearNormalization_image_adjoin_eq_top_of_primitive
      hIprime D u hprimitive
  refine ⟨?_, ?_, ?_⟩
  · exact kerLiftAlg_finite_of_finite h
      (augmentedLinearNormalizationHom_finite D u)
  · exact fractionImageToL.injective
  · exact fractionRing_liftAlgHom_surjective_of_adjoin_range_eq_top
      imageToL himageInjective hgen

end

end TranslatedDepthSeven
