import TranslatedDepthSeven.HomogeneousMinimalComponents
import Mathlib.RingTheory.Ideal.Colon
import Mathlib.RingTheory.GradedAlgebra.Homogeneous.Ideal
import Mathlib.RingTheory.GradedAlgebra.Radical
import Mathlib.RingTheory.MvPolynomial.Homogeneous
import Mathlib.RingTheory.MvPolynomial.Ideal

/-!
# Coordinate-chart saturation of projective prime components

For the standard grading of a multivariate polynomial ring, Mathlib's
irrelevant homogeneous ideal is the ordinary ideal generated by the
coordinates.  Hence a prime which does not contain the irrelevant ideal
misses at least one coordinate.  Primality then gives the precise chart
saturation statement

`X i ^ n * f ∈ P ↔ f ∈ P`.

The final theorem packages this with homogeneous minimal-prime extraction.
No scheme-theoretic or Proj machinery is used.
-/

namespace TranslatedDepthSeven

noncomputable section

open MvPolynomial

universe u v

variable {K : Type u} {σ : Type v} [Field K]

local instance projectivePrimeChartStandardGradedAlgebra :
    GradedAlgebra (MvPolynomial.homogeneousSubmodule σ K) :=
  MvPolynomial.gradedAlgebra

/-- Mathlib's irrelevant ideal for the standard total-degree grading of
`K[σ]`. -/
abbrev mvPolynomialIrrelevantIdeal : Ideal (MvPolynomial σ K) :=
  (HomogeneousIdeal.irrelevant
    (MvPolynomial.homogeneousSubmodule σ K)).toIdeal

/-- Projection to degree zero is the constant polynomial associated to the
constant coefficient. -/
theorem projZeroRingHom_homogeneousSubmodule_apply
    (f : MvPolynomial σ K) :
    GradedRing.projZeroRingHom
        (MvPolynomial.homogeneousSubmodule σ K) f =
      C (constantCoeff f) := by
  rw [GradedRing.projZeroRingHom_apply]
  change (MvPolynomial.decomposition.decompose' f 0 : MvPolynomial σ K) = _
  rw [MvPolynomial.decomposition.decompose'_apply,
    MvPolynomial.homogeneousComponent_zero]
  rfl

/-- The standard irrelevant ideal is exactly the ideal generated by the
coordinate variables. -/
theorem mvPolynomialIrrelevantIdeal_eq_span_X :
    mvPolynomialIrrelevantIdeal (K := K) (σ := σ) =
      Ideal.span (Set.range (MvPolynomial.X : σ → MvPolynomial σ K)) := by
  ext f
  rw [show f ∈ mvPolynomialIrrelevantIdeal (K := K) (σ := σ) ↔
      constantCoeff f = 0 by
    change f ∈ HomogeneousIdeal.irrelevant
        (MvPolynomial.homogeneousSubmodule σ K) ↔ constantCoeff f = 0
    rw [HomogeneousIdeal.mem_irrelevant_iff]
    change GradedRing.projZeroRingHom
        (MvPolynomial.homogeneousSubmodule σ K) f = 0 ↔
      constantCoeff f = 0
    rw [projZeroRingHom_homogeneousSubmodule_apply,
      MvPolynomial.C_eq_zero]]
  rw [show f ∈ Ideal.span
        (Set.range (MvPolynomial.X : σ → MvPolynomial σ K)) ↔
      constantCoeff f = 0 by
    rw [show Set.range (MvPolynomial.X : σ → MvPolynomial σ K) =
        MvPolynomial.X '' (Set.univ : Set σ) by simp]
    rw [MvPolynomial.mem_ideal_span_X_image]
    constructor
    · intro h
      by_contra hconstant
      have hzeroSupport : (0 : σ →₀ ℕ) ∈ f.support := by
        rw [MvPolynomial.mem_support_iff]
        simpa [MvPolynomial.constantCoeff_eq] using hconstant
      obtain ⟨i, _hi, hzeroi⟩ := h 0 hzeroSupport
      exact hzeroi rfl
    · intro hconstant m hm
      have hmzero : m ≠ 0 := by
        intro hm0
        subst m
        have hcoeff : coeff 0 f ≠ 0 := MvPolynomial.mem_support_iff.mp hm
        exact hcoeff (by simpa [MvPolynomial.constantCoeff_eq] using hconstant)
      have hexists : ∃ i, m i ≠ 0 := by
        by_contra hnone
        push_neg at hnone
        apply hmzero
        ext i
        exact hnone i
      obtain ⟨i, hi⟩ := hexists
      exact ⟨i, Set.mem_univ i, hi⟩]

/-- If a prime does not contain the irrelevant ideal, then some coordinate
is absent from the prime. -/
theorem exists_X_notMem_of_irrelevant_not_le
    {P : Ideal (MvPolynomial σ K)}
    (hirr : ¬ mvPolynomialIrrelevantIdeal (K := K) (σ := σ) ≤ P) :
    ∃ i : σ, X i ∉ P := by
  rw [mvPolynomialIrrelevantIdeal_eq_span_X] at hirr
  by_contra h
  push_neg at h
  exact hirr (Ideal.span_le.mpr <| by
    rintro _ ⟨i, rfl⟩
    exact h i)

/-- Elementwise saturation of a prime with respect to a coordinate absent
from it.  This is the form used on the standard Proj chart `D₊(X i)`. -/
theorem X_pow_mul_mem_prime_iff
    {P : Ideal (MvPolynomial σ K)} (hP : P.IsPrime)
    {i : σ} (hi : X i ∉ P) (n : ℕ) (f : MvPolynomial σ K) :
    X i ^ n * f ∈ P ↔ f ∈ P := by
  constructor
  · intro hmul
    exact (hP.mem_or_mem hmul).resolve_left fun hpow ↦
      hi (hP.mem_of_pow_mem n hpow)
  · exact fun hf ↦ P.mul_mem_left (X i ^ n) hf

/-- Equivalent ideal-theoretic form: every colon by a power of the chosen
coordinate is the original prime. -/
theorem colon_span_X_pow_eq_prime
    {P : Ideal (MvPolynomial σ K)} (hP : P.IsPrime)
    {i : σ} (hi : X i ∉ P) (n : ℕ) :
    P.colon (Ideal.span ({X i ^ n} : Set (MvPolynomial σ K))) = P := by
  ext f
  rw [Ideal.mem_colon_singleton]
  simpa [mul_comm] using X_pow_mul_mem_prime_iff hP hi n f

/-- A prime component not containing the irrelevant ideal admits one
coordinate chart on which it is saturated by every power of that
coordinate. -/
theorem exists_coordinate_with_prime_chart_saturation
    {P : Ideal (MvPolynomial σ K)} (hP : P.IsPrime)
    (hirr : ¬ mvPolynomialIrrelevantIdeal (K := K) (σ := σ) ≤ P) :
    ∃ i : σ, X i ∉ P ∧
      (∀ n f, X i ^ n * f ∈ P ↔ f ∈ P) ∧
      ∀ n, P.colon
        (Ideal.span ({X i ^ n} : Set (MvPolynomial σ K))) = P := by
  obtain ⟨i, hi⟩ := exists_X_notMem_of_irrelevant_not_le hirr
  exact ⟨i, hi, X_pow_mul_mem_prime_iff hP hi,
    colon_span_X_pow_eq_prime hP hi⟩

/-- The complete projective-chart qualification for a homogeneous prime:
homogeneity is retained, and one standard coordinate chart has trivial
saturation by every power of its coordinate. -/
theorem homogeneousPrime_projective_chart_qualification
    {P : Ideal (MvPolynomial σ K)}
    (hPhom : P.IsHomogeneous (MvPolynomial.homogeneousSubmodule σ K))
    (hP : P.IsPrime)
    (hirr : ¬ mvPolynomialIrrelevantIdeal (K := K) (σ := σ) ≤ P) :
    P.IsHomogeneous (MvPolynomial.homogeneousSubmodule σ K) ∧
      ∃ i : σ, X i ∉ P ∧
        (∀ n f, X i ^ n * f ∈ P ↔ f ∈ P) ∧
        ∀ n, P.colon
          (Ideal.span ({X i ^ n} : Set (MvPolynomial σ K))) = P := by
  exact ⟨hPhom, exists_coordinate_with_prime_chart_saturation hP hirr⟩

/-- Projective qualification after homogeneous minimal-prime extraction:
the selected affine-cone component is homogeneous, and if it does not
contain the irrelevant ideal then it has a coordinate chart on which all
coordinate-power saturations are trivial. -/
theorem finiteEquationMinimalPrime_of_isHomogeneous_exists_chart_saturation
    [Fintype σ]
    (equations : Finset (MvPolynomial σ K))
    {P : Ideal (MvPolynomial σ K)}
    (hP : P ∈ finiteEquationMinimalPrimes equations)
    (hPhom : P.IsHomogeneous (MvPolynomial.homogeneousSubmodule σ K))
    (hirr : ¬ mvPolynomialIrrelevantIdeal (K := K) (σ := σ) ≤ P) :
    P.IsHomogeneous (MvPolynomial.homogeneousSubmodule σ K) ∧
      ∃ i : σ, X i ∉ P ∧
        (∀ n f, X i ^ n * f ∈ P ↔ f ∈ P) ∧
        ∀ n, P.colon
          (Ideal.span ({X i ^ n} : Set (MvPolynomial σ K))) = P := by
  have hPprime : P.IsPrime := by
    apply isPrime_of_mem_finiteMinimalPrimes
    exact hP
  exact homogeneousPrime_projective_chart_qualification hPhom hPprime hirr

/-- Fully literal finite-equation form.  If every displayed equation is
homogeneous, then a selected minimal prime is homogeneous; if it does not
contain the irrelevant ideal, it also has a standard coordinate chart with
trivial coordinate-power saturation. -/
theorem finiteEquationMinimalPrime_isHomogeneous_and_exists_chart_saturation
    [Fintype σ]
    (equations : Finset (MvPolynomial σ K))
    (hhom : ∀ f ∈ equations, ∃ d : ℕ, f.IsHomogeneous d)
    {P : Ideal (MvPolynomial σ K)}
    (hP : P ∈ finiteEquationMinimalPrimes equations)
    (hirr : ¬ mvPolynomialIrrelevantIdeal (K := K) (σ := σ) ≤ P) :
    P.IsHomogeneous (MvPolynomial.homogeneousSubmodule σ K) ∧
      ∃ i : σ, X i ∉ P ∧
        (∀ n f, X i ^ n * f ∈ P ↔ f ∈ P) ∧
        ∀ n, P.colon
          (Ideal.span ({X i ^ n} : Set (MvPolynomial σ K))) = P := by
  have hPhom : P.IsHomogeneous
      (MvPolynomial.homogeneousSubmodule σ K) :=
    finiteEquationMinimalPrime_isHomogeneous equations hhom hP
  exact finiteEquationMinimalPrime_of_isHomogeneous_exists_chart_saturation
    equations hP hPhom hirr

end

end TranslatedDepthSeven
