import TranslatedDepthSeven.ProjectiveConeJoin
import Mathlib.RingTheory.Polynomial.Quotient

/-!
# The homogeneous-coordinate ideal of a projective cone

Adjoining the unused vertex coordinate to a homogeneous ideal is simply
polynomial extension by one variable.  This file records that statement at
the level of literal ideals and quotient rings.  It is the scheme-theoretic
counterpart of the point-set join identity in `ProjectiveConeJoin`.
-/

namespace TranslatedDepthSeven

noncomputable section

set_option maxHeartbeats 1000000

open MvPolynomial

universe u v

variable {K : Type u} [Field K] {σ : Type v}

/-- Extend an ideal in the original homogeneous coordinates to the ring with
one additional, unused vertex coordinate. -/
def projectiveConeIdealExtension
    (I : Ideal (MvPolynomial σ K)) :
    Ideal (MvPolynomial (Option σ) K) :=
  I.map (MvPolynomial.rename some)

/-- Under `optionEquivLeft`, inclusion of the original variables is exactly
the constant-polynomial embedding. -/
@[simp]
theorem optionEquivLeft_rename_some
    (f : MvPolynomial σ K) :
    MvPolynomial.optionEquivLeft K σ (MvPolynomial.rename some f) =
      Polynomial.C f := by
  induction f using MvPolynomial.induction_on with
  | C a =>
      rw [MvPolynomial.rename_C, MvPolynomial.optionEquivLeft_C]
  | add p q hp hq => simp [hp, hq]
  | mul_X p i hp =>
      calc
        MvPolynomial.optionEquivLeft K σ
            (MvPolynomial.rename some (p * MvPolynomial.X i)) =
            MvPolynomial.optionEquivLeft K σ
              (MvPolynomial.rename some p *
                MvPolynomial.rename some (MvPolynomial.X i)) := by
          rw [map_mul]
        MvPolynomial.optionEquivLeft K σ
            (MvPolynomial.rename some p *
              MvPolynomial.rename some (MvPolynomial.X i)) =
            MvPolynomial.optionEquivLeft K σ
                (MvPolynomial.rename some p) *
              MvPolynomial.optionEquivLeft K σ
                (MvPolynomial.rename some (MvPolynomial.X i)) :=
          map_mul _ _ _
        _ = Polynomial.C p * Polynomial.C (MvPolynomial.X i) := by
          rw [hp, MvPolynomial.rename_X,
            MvPolynomial.optionEquivLeft_X_some]
        _ = Polynomial.C (p * MvPolynomial.X i) := by
          rw [Polynomial.C_mul]

/-- The cone ideal becomes the coefficientwise extension `I K[X]` after
splitting off the vertex variable. -/
theorem map_projectiveConeIdealExtension_optionEquivLeft
    (I : Ideal (MvPolynomial σ K)) :
    (projectiveConeIdealExtension I).map
        (MvPolynomial.optionEquivLeft K σ) =
      I.map Polynomial.C := by
  rw [projectiveConeIdealExtension]
  calc
    (I.map (MvPolynomial.rename some)).map
        (MvPolynomial.optionEquivLeft K σ) =
        I.map ((MvPolynomial.optionEquivLeft K σ).toAlgHom.comp
          (MvPolynomial.rename some)) := by
      exact I.map_mapₐ (MvPolynomial.rename some)
        (MvPolynomial.optionEquivLeft K σ).toAlgHom
    _ = I.map Polynomial.C := by
      apply congrArg (fun φ : MvPolynomial σ K →+*
        Polynomial (MvPolynomial σ K) ↦ I.map φ)
      apply MvPolynomial.ringHom_ext
      · intro r
        simp
      · intro i
        change (MvPolynomial.optionEquivLeft K σ)
          (MvPolynomial.rename some (MvPolynomial.X i)) =
            Polynomial.C (MvPolynomial.X i)
        rw [MvPolynomial.rename_X]
        exact MvPolynomial.optionEquivLeft_X_some K σ i

/-- A finite equation family viewed in the enlarged coordinate ring. -/
def renameSomeEquationFinset
    (equations : Finset (MvPolynomial σ K)) :
    Finset (MvPolynomial (Option σ) K) := by
  classical
  exact equations.image (MvPolynomial.rename some)

/-- Extending the ideal generated by a finite homogeneous equation family is
literally the ideal generated by the same equations in the enlarged set of
coordinates.  Homogeneity is not needed for this ideal identity. -/
theorem finiteEquationIdeal_image_rename_some
    (equations : Finset (MvPolynomial σ K)) :
    finiteEquationIdeal
        (renameSomeEquationFinset equations) =
      projectiveConeIdealExtension (finiteEquationIdeal equations) := by
  classical
  unfold renameSomeEquationFinset projectiveConeIdealExtension
  change Ideal.span
      (↑(equations.image (MvPolynomial.rename some)) :
        Set (MvPolynomial (Option σ) K)) =
    (Ideal.span (↑equations : Set (MvPolynomial σ K))).map
      (MvPolynomial.rename some)
  rw [Ideal.map_span]
  rw [← Finset.coe_image]

/-- The homogeneous coordinate ring of the cone is canonically a polynomial
ring in the vertex coordinate over the original homogeneous coordinate
ring. -/
def projectiveConeQuotientRingEquiv
    (I : Ideal (MvPolynomial σ K)) :
    (MvPolynomial (Option σ) K ⧸ projectiveConeIdealExtension I) ≃+*
      Polynomial (MvPolynomial σ K ⧸ I) :=
  (Ideal.quotientEquivAlg
      (projectiveConeIdealExtension I) (I.map Polynomial.C)
      (MvPolynomial.optionEquivLeft K σ)
      (map_projectiveConeIdealExtension_optionEquivLeft I).symm).toRingEquiv.trans
    (I.polynomialQuotientEquivQuotientPolynomial).symm

/-- Polynomial extension by the vertex coordinate preserves primality. -/
theorem projectiveConeIdealExtension_isPrime
    (I : Ideal (MvPolynomial σ K)) (hI : I.IsPrime) :
    (projectiveConeIdealExtension I).IsPrime := by
  have hmap : (I.map Polynomial.C :
      Ideal (Polynomial (MvPolynomial σ K))).IsPrime :=
    (Ideal.isPrime_map_C_iff_isPrime I).2 hI
  let e := MvPolynomial.optionEquivLeft K σ
  have hcomap : (projectiveConeIdealExtension I) =
      (I.map Polynomial.C).comap e := by
    rw [← map_projectiveConeIdealExtension_optionEquivLeft I]
    exact (Ideal.comap_map_of_bijective e e.bijective).symm
  rw [hcomap]
  exact hmap.comap e

/-- The cone quotient is a domain whenever the original quotient is. -/
theorem projectiveConeQuotient_isDomain
    (I : Ideal (MvPolynomial σ K)) (hI : I.IsPrime) :
    IsDomain
      (MvPolynomial (Option σ) K ⧸ projectiveConeIdealExtension I) := by
  exact (Ideal.Quotient.isDomain_iff_prime _).2
    (projectiveConeIdealExtension_isPrime I hI)

end

end TranslatedDepthSeven
