import TranslatedDepthSeven.ProjectiveBertiniSmoothCoordinateSection

/-!
# The marked smooth chart and coordinate complements cover the affine variety

The actual affine coordinate differences generate the ideal of the marked
point. Thus a principal chart containing that point, together with the
complements of these coordinate hyperplanes, is a literal principal cover.
-/

namespace TranslatedDepthSeven
noncomputable section
open MvPolynomial
set_option maxHeartbeats 2000000
set_option synthInstance.maxHeartbeats 300000

/-- The point ideal is generated by the actual affine coordinate
differences, before any quotient is taken. -/
theorem bertini_span_coordinateDifferences_eq_eval_ker
    {K : Type*} [Field K] {N : ℕ} (z : Fin N → K) :
    Ideal.span (Set.range (fun i : Fin N ↦ (X i - C (z i) : MvPolynomial (Fin N) K))) =
      RingHom.ker (aeval z).toRingHom := by
  let I := Ideal.span (Set.range (fun i : Fin N ↦ (X i - C (z i) : MvPolynomial (Fin N) K)))
  let q := Ideal.Quotient.mkₐ K I
  have hcomp : q = (Algebra.ofId K (MvPolynomial (Fin N) K ⧸ I)).comp (aeval z) := by
    apply MvPolynomial.algHom_ext
    intro i
    have hi : X i - C (z i) ∈ I := Ideal.subset_span ⟨i, rfl⟩
    have hz : q (X i - C (z i)) = 0 := Ideal.Quotient.eq_zero_iff_mem.mpr hi
    have h := sub_eq_zero.mp (by simpa only [map_sub] using hz)
    simpa only [AlgHom.comp_apply, aeval_X, AlgHom.commutes, Algebra.ofId_apply] using h
  apply le_antisymm
  · apply Ideal.span_le.mpr
    rintro _ ⟨i, rfl⟩
    change aeval z (X i - C (z i)) = 0
    simp
  · intro f hf
    apply Ideal.Quotient.eq_zero_iff_mem.mp
    change q f = 0
    rw [hcomp]
    change algebraMap K (MvPolynomial (Fin N) K ⧸ I) (aeval z f) = 0
    rw [show aeval z f = 0 from hf, map_zero]

/-- The same coordinate differences generate the point ideal in the
displayed affine coordinate ring. -/
theorem bertini_span_quotient_coordinateDifferences_eq_point_ker
    {K : Type*} [Field K] {N : ℕ}
    (J : Ideal (MvPolynomial (Fin N) K)) (z : Fin N → K)
    (hz : J ≤ RingHom.ker (aeval z).toRingHom) :
    Ideal.span (Set.range (fun i : Fin N ↦ Ideal.Quotient.mk J (X i - C (z i)))) =
      RingHom.ker (affineQuotientRationalPoint J z hz).toRingHom := by
  have hker := Ideal.ker_quotient_lift (I := J)
    (aeval z : MvPolynomial (Fin N) K →ₐ[K] K).toRingHom hz
  change _ = RingHom.ker (Ideal.Quotient.lift J (aeval z).toRingHom hz)
  rw [hker, ← bertini_span_coordinateDifferences_eq_eval_ker z,
    Ideal.map_span, ← Set.range_comp]
  rfl

/-- A denominator nonzero at the marked point and all actual coordinate
differences generate the unit ideal. This is the principal cover used to
join the smooth neighborhood to the elementary incidence charts. -/
theorem bertini_span_marked_denominator_coordinateDifferences_eq_top
    {K : Type*} [Field K] {N : ℕ}
    (J : Ideal (MvPolynomial (Fin N) K)) (z : Fin N → K)
    (hz : J ≤ RingHom.ker (aeval z).toRingHom)
    (s : MvPolynomial (Fin N) K ⧸ J)
    (hs : affineQuotientRationalPoint J z hz s ≠ 0) :
    Ideal.span (insert s (Set.range (fun i : Fin N ↦
      Ideal.Quotient.mk J (X i - C (z i))))) = ⊤ := by
  rw [Ideal.span_insert, bertini_span_quotient_coordinateDifferences_eq_point_ker J z hz]
  let M := RingHom.ker (affineQuotientRationalPoint J z hz).toRingHom
  have hmax : M.IsMaximal := rationalPoint_ker_isMaximal (affineQuotientRationalPoint J z hz)
  apply hmax.out.2
  apply lt_of_le_of_ne le_sup_right
  intro heq
  have hmem : s ∈ Ideal.span {s} ⊔ M :=
    (show Ideal.span {s} ≤ Ideal.span {s} ⊔ M from le_sup_left)
      (Ideal.mem_span_singleton_self s)
  rw [← heq] at hmem
  exact hs hmem

end
end TranslatedDepthSeven
