import TranslatedDepthSeven.ProjectiveZerofoldFirstChartInternal
import Mathlib.FieldTheory.IsAlgClosed.Basic

/-!
# An integral projective zero-fold over an algebraically closed field

A positive eventual projective Hilbert value guarantees a coordinate which
does not vanish identically.  On that coordinate chart, the affine Hilbert
filtration is eventually constant.  Its coordinate ring is therefore finite
over the ground field.  Since it is a domain and the field is algebraically
closed, mathlib's minimal-polynomial argument identifies it with that field.
The constant Hilbert value is consequently one.

This does not assume saturation, a Nullstellensatz interface, or a
zero-dimensional degree theorem.
-/

namespace TranslatedDepthSeven

noncomputable section

open MvPolynomial Published

attribute [local instance] MvPolynomial.gradedAlgebra

set_option maxHeartbeats 2000000
set_option synthInstance.maxHeartbeats 200000

universe u v

variable {K : Type u} [Field K]

/-- Every positive-degree homogeneous polynomial belongs to the ideal
generated by the coordinate variables. -/
theorem positiveHomogeneous_mem_span_coordinates
    {σ : Type*} (f : MvPolynomial σ K) {k : ℕ}
    (hk : 0 < k) (hf : f.IsHomogeneous k) :
    f ∈ Ideal.span (Set.range (MvPolynomial.X : σ → MvPolynomial σ K)) := by
  classical
  rw [show Set.range (MvPolynomial.X : σ → MvPolynomial σ K) =
    MvPolynomial.X '' (Set.univ : Set σ) by simp]
  apply MvPolynomial.mem_ideal_span_X_image.2
  intro m hm
  have hmdegree : m.degree = k := by
    rw [Finsupp.degree_eq_weight_one]
    exact hf (MvPolynomial.mem_support_iff.1 hm)
  have hmne : m ≠ 0 := by
    intro hzero
    simp only [hzero, Finsupp.degree_zero] at hmdegree
    omega
  obtain ⟨i, hi⟩ : ∃ i, m i ≠ 0 := by
    by_contra h
    push_neg at h
    exact hmne (Finsupp.ext h)
  exact ⟨i, Set.mem_univ i, hi⟩

/-- A positive projective Hilbert value in a positive degree forces some
coordinate to survive.  No saturation or primality is needed here. -/
theorem exists_coordinate_not_mem_of_positive_projectiveHilbertPiece
    {N k : ℕ} (I : Ideal (MvPolynomial (Fin (N + 1)) K))
    (hk : 0 < k)
    (hpositive : 0 < Module.finrank K (projectiveHilbertPiece K N I k)) :
    ∃ i : Fin (N + 1), X i ∉ I := by
  classical
  by_contra h
  push_neg at h
  have hspan : Ideal.span
      (Set.range (MvPolynomial.X : Fin (N + 1) → MvPolynomial (Fin (N + 1)) K)) ≤ I := by
    apply Ideal.span_le.2
    rintro _ ⟨i, rfl⟩
    exact h i
  have hbot : projectiveHilbertPiece K N I k = ⊥ := by
    apply bot_unique
    intro x hx
    obtain ⟨f, hf, rfl⟩ := Submodule.mem_map.1 hx
    rw [Submodule.mem_bot]
    exact (Ideal.Quotient.eq_zero_iff_mem).2
      (hspan (positiveHomogeneous_mem_span_coordinates f hk hf))
  rw [hbot] at hpositive
  simpa using hpositive

/-- A finite domain over an algebraically closed field has dimension one
as a vector space.  This is mathlib's minimal-polynomial argument. -/
theorem finiteDomain_finrank_eq_one_of_isAlgClosed
    (A : Type v) [CommRing A] [IsDomain A] [Algebra K A]
    [IsAlgClosed K] [Module.Finite K A] : Module.finrank K A = 1 := by
  let e : K ≃ₐ[K] A := AlgEquiv.ofBijective (Algebra.ofId K A)
    IsAlgClosed.algebraMap_bijective_of_isIntegral
  simpa using e.symm.toLinearEquiv.finrank_eq

/-- The precise degree-one input for the quotient-node decomposition,
proved from its literal Hilbert-polynomial hypotheses. -/
theorem algebraicallyClosedIntegralProjectiveZerofoldDegreeOne_internal :
    StandardAG.AlgebraicallyClosedIntegralProjectiveZerofoldDegreeOne := by
  intro N d I hIprime hIhomogeneous hIdegree
  classical
  obtain ⟨_hdim, hdpos, Hpoly, hHdegree, hHlc, k₀, hHeventual⟩ := hIdegree
  have hHconstant : Hpoly = Polynomial.C (d : ℚ) := by
    have h := Polynomial.eq_C_of_natDegree_eq_zero hHdegree
    have hcoeff : Hpoly.coeff 0 = (d : ℚ) := by
      simpa only [Polynomial.leadingCoeff, hHdegree, Nat.factorial_zero,
        Nat.cast_one, div_one] using hHlc
    simpa only [hcoeff] using h
  have hIconstant : ∀ k ≥ k₀,
      Module.finrank Qbar (projectiveHilbertPiece Qbar N I k) = d := by
    intro k hk
    have h := hHeventual k hk
    rw [hHconstant, Polynomial.eval_C] at h
    exact_mod_cast h
  obtain ⟨i, hi⟩ :=
    exists_coordinate_not_mem_of_positive_projectiveHilbertPiece I
      (Nat.succ_pos k₀) (by rw [hIconstant (k₀ + 1) (by omega)]; exact hdpos)
  let idx : Fin (N + 1) ≃ Option (Fin N) :=
    (Equiv.swap i 0).trans (_root_.finSuccEquiv N)
  let e : MvPolynomial (Fin (N + 1)) Qbar ≃ₐ[Qbar]
      MvPolynomial (Option (Fin N)) Qbar := MvPolynomial.renameEquiv Qbar idx
  let J := I.map e
  let C₀ := J.map multivariateDehomogenization.toRingHom
  have hJhomogeneous : J.IsHomogeneous
      (MvPolynomial.homogeneousSubmodule (Option (Fin N)) Qbar) := by
    simpa only [J, e] using map_renameEquiv_isHomogeneous idx I hIhomogeneous
  have hJprime : J.IsPrime := by
    letI : I.IsPrime := hIprime
    dsimp only [J, e]
    infer_instance
  have hJX : X (none : Option (Fin N)) ∉ J := by
    intro hmem
    obtain ⟨f, hf, hfeq⟩ :=
      (Ideal.mem_map_iff_of_surjective e e.surjective).1 hmem
    have hfX : f = X i := by
      apply e.injective
      rw [hfeq]
      change X (none : Option (Fin N)) = MvPolynomial.rename idx (X i)
      rw [MvPolynomial.rename_X]
      simp [idx]
    exact hi (hfX ▸ hf)
  have hCprime : C₀.IsPrime :=
    map_multivariateDehomogenization_isPrime J hJhomogeneous hJprime hJX
  have hCconstant : ∀ k ≥ k₀,
      Module.finrank Qbar (affineHilbertFiltration Qbar N C₀ k) = d := by
    intro k hk
    have hrename :
        Module.finrank Qbar (projectiveHilbertPiece Qbar N I k) =
          Module.finrank Qbar
            (quotientHomogeneousComponent Qbar (Option (Fin N)) J k) :=
      finrank_quotientHomogeneousComponent_map_renameEquiv Qbar idx I k
    have hchart := finrank_projective_eq_affine_dehomogenization
      J hJhomogeneous hJprime hJX (k := k)
    exact hchart.symm.trans (hrename.symm.trans (hIconstant k hk))
  obtain ⟨v, hv⟩ :=
    exists_affineQuotient_spanningFamily_of_eventual_constant_hilbert C₀ k₀ hCconstant
  let A := MvPolynomial (Fin N) Qbar ⧸ C₀
  letI : C₀.IsPrime := hCprime
  letI : Module.Finite Qbar A := Module.finite_def.mpr <|
    Submodule.fg_iff_exists_fin_generating_family.mpr ⟨d, v, hv⟩
  have hA : Module.finrank Qbar A = 1 :=
    finiteDomain_finrank_eq_one_of_isAlgClosed A
  have hle := (affineHilbertFiltration Qbar N C₀ k₀).subtype.finrank_le_finrank_of_injective
    (Submodule.subtype_injective _)
  rw [hCconstant k₀ le_rfl, hA] at hle
  omega

end

end TranslatedDepthSeven
