import TranslatedDepthSeven.DistinguishedNormalizationBoundaryRestrictionInternal
import TranslatedDepthSeven.ProjectiveBoundaryHomogeneousInternal
import TranslatedDepthSeven.ProjectiveDegreeSpanSectionAlgebra
import TranslatedDepthSeven.RankSevenNonvertexProjectionInternal

/-!
# Exact degree of a prime hyperplane boundary

For a homogeneous projective source which meets the standard affine chart,
the boundary at infinity is the literal proper hyperplane section by `X₀`.
If that boundary is prime, the Hilbert-difference theorem shows that it has
one lower projective dimension and the same degree.  This file also checks
the graded quotient transport from the section ideal in all coordinates to
the specialized boundary ideal in the remaining coordinates.
-/

namespace TranslatedDepthSeven

noncomputable section

open MvPolynomial Published

attribute [local instance] MvPolynomial.gradedAlgebra

set_option maxHeartbeats 3000000
set_option synthInstance.maxHeartbeats 500000

/-- The kernel of setting the first variable equal to zero is the principal
ideal generated by that variable. -/
theorem ker_rationalSpecializeFirstCoordinate_zero {n : ℕ} :
    RingHom.ker
        (rationalSpecializeFirstCoordinate (d := n) 0).toRingHom =
      Ideal.span ({X (0 : Fin (n + 1))} :
        Set (MvPolynomial (Fin (n + 1)) ℚ)) := by
  ext p
  rw [RingHom.mem_ker, Ideal.mem_span_singleton]
  constructor
  · exact X_zero_dvd_of_rationalSpecializeFirstCoordinate_zero p
  · rintro ⟨q, rfl⟩
    simp [rationalSpecializeFirstCoordinate]

/-- Contracting the boundary ideal back to the original homogeneous
coordinate ring gives the literal hyperplane section by `X₀`. -/
theorem comap_projectiveBoundaryIdeal_eq_hyperplaneSection {n : ℕ}
    (I : Ideal (MvPolynomial (Fin (n + 1)) ℚ)) :
    (projectiveBoundaryIdeal I).comap
        (rationalSpecializeFirstCoordinate 0).toRingHom =
      I ⊔ Ideal.span ({X (0 : Fin (n + 1))} : Set _) := by
  rw [projectiveBoundaryIdeal,
    Ideal.comap_map_of_surjective
      (rationalSpecializeFirstCoordinate 0).toRingHom
      (rationalSpecializeFirstCoordinate_zero_surjective n),
    ← RingHom.ker_eq_comap_bot,
    ker_rationalSpecializeFirstCoordinate_zero]

/-- A split homogeneous specialization transports the complete projective
dimension--degree certificate between a boundary ideal and its contraction.
-/
theorem projectiveBoundary_dimensionDegree_iff_comap
    {N r degree : ℕ}
    (I : Ideal (MvPolynomial (Fin (N + 2)) ℚ)) :
    HasProjectiveDimensionDegree
        ((projectiveBoundaryIdeal I).comap
          (rationalSpecializeFirstCoordinate 0).toRingHom) r degree ↔
      HasProjectiveDimensionDegree (projectiveBoundaryIdeal I) r degree := by
  let f : MvPolynomial (Fin (N + 2)) ℚ →ₐ[ℚ]
      MvPolynomial (Fin (N + 1)) ℚ :=
    rationalSpecializeFirstCoordinate 0
  let g : MvPolynomial (Fin (N + 1)) ℚ →ₐ[ℚ]
      MvPolynomial (Fin (N + 2)) ℚ :=
    MvPolynomial.rename Fin.succ
  have hf : Function.Surjective f := by
    exact rationalSpecializeFirstCoordinate_zero_surjective (N + 1)
  have hright : f.comp g = AlgHom.id ℚ _ := by
    apply MvPolynomial.algHom_ext
    intro i
    simp [f, g, rationalSpecializeFirstCoordinate]
  have hfhom : ∀ (d : ℕ) (p : MvPolynomial (Fin (N + 2)) ℚ),
      p.IsHomogeneous d → (f p).IsHomogeneous d := by
    intro d p hp
    simpa [f, rationalSpecializeFirstCoordinate,
      restrictFirstPolynomialToZero] using
      (restrictFirstPolynomialToZero_isHomogeneous hp)
  have hghom : ∀ (d : ℕ) (p : MvPolynomial (Fin (N + 1)) ℚ),
      p.IsHomogeneous d → (g p).IsHomogeneous d := by
    intro d p hp
    exact hp.rename_isHomogeneous
  exact hasProjectiveDimensionDegree_comap_surjective_iff
    f hf g hright hfhom hghom (projectiveBoundaryIdeal I) r degree

/-- A prime boundary at infinity of a homogeneous prime projective variety
which meets the standard chart has one lower projective dimension and the
same degree. -/
theorem projectiveBoundary_hasProjectiveDimensionDegree
    {N r degree : ℕ}
    (I : Ideal (MvPolynomial (Fin (N + 2)) ℚ))
    (hIprime : I.IsPrime)
    (hIhom : I.IsHomogeneous
      (homogeneousSubmodule (Fin (N + 2)) ℚ))
    (hIdegree : HasProjectiveDimensionDegree I (r + 1) degree)
    (hX : X (0 : Fin (N + 2)) ∉ I)
    (hboundaryPrime : (projectiveBoundaryIdeal I).IsPrime) :
    HasProjectiveDimensionDegree (projectiveBoundaryIdeal I) r degree := by
  have hsectionPrime :
      (I ⊔ Ideal.span ({X (0 : Fin (N + 2))} : Set _)).IsPrime := by
    rw [← comap_projectiveBoundaryIdeal_eq_hyperplaneSection I]
    exact hboundaryPrime.comap _
  have hsectionDegree : HasProjectiveDimensionDegree
      (I ⊔ Ideal.span ({X (0 : Fin (N + 2))} : Set _)) r degree := by
    exact projectiveSection_preserves_degree I hIprime hIhom hIdegree
      (X (0 : Fin (N + 2)))
      (MvPolynomial.isHomogeneous_X (R := ℚ) (0 : Fin (N + 2)))
      hX hsectionPrime
  apply (projectiveBoundary_dimensionDegree_iff_comap I).mp
  rwa [comap_projectiveBoundaryIdeal_eq_hyperplaneSection I]

end

end TranslatedDepthSeven
