import TranslatedDepthSeven.RankSevenDegreeOneProperStarSource
import TranslatedDepthSeven.HomogeneousMinimalComponents
import TranslatedDepthSeven.FiniteComponentFrontier
import TranslatedDepthSeven.JacobianCertificatePolynomialHeight
import TranslatedDepthSeven.ProjectiveLinearHeightBound
import TranslatedDepthSeven.HomogeneousProjectionCountingBridge
import TranslatedDepthSeven.RationalPrimeGeometricFrontier
import TranslatedDepthSeven.ProjectiveConePila

/-!
# The two geometric alternatives for a literal low-direction star

This file starts with the explicit coefficient equations of
`ProjectiveStarLocus`.  It records, at ideal level, the two geometric facts
needed by the degree-one ledger.

* At a rank-seven centre, three actual rows of the evaluated integral
  Jacobian give a rank-three rational linear section containing the whole
  star.  The Pluecker height of that section is bounded explicitly from the
  coefficients of the original equations and the height of the centre.
* At a nonvertex centre, the ideal of the star strictly contains the ideal
  of the original cone.  Consequently every irreducible component of the
  star has affine-cone dimension at most five.

The first assertion is proved entirely from the displayed equations and
linear algebra.  For the second, the only external geometric input is the
standard equivalence between equality of the line-coefficient ideal and the
projective-vertex condition.  It is isolated below as a proposition about
two literal ideals; it contains no component count or point estimate.
-/

namespace TranslatedDepthSeven

noncomputable section

open MvPolynomial Published
open scoped LinearAlgebra.Projectivization

attribute [local instance] MvPolynomial.gradedAlgebra

set_option maxHeartbeats 8000000

/-- The rational homogeneous ideal generated by all coefficients of
`f(h+Tz)`, for the original displayed integral equations `f`. -/
def rationalProjectiveStarIdeal {n : ℕ}
    (equations : Finset (MvPolynomial (Fin n) ℤ))
    (degree : MvPolynomial (Fin n) ℤ → ℕ) (h : IntVector n) :
    Ideal (MvPolynomial (Fin n) ℚ) :=
  finiteEquationIdeal
    (rationalizedEquationFinset
      (projectiveStarEquationFamily equations degree h))

/-- Every generator of the original homogeneous ideal is the highest line
coefficient and hence belongs to the star ideal. -/
theorem rationalDepthSevenEquationIdeal_le_rationalProjectiveStarIdeal
    (equations : Finset (MvPolynomial (Fin 13) ℤ))
    (degree : MvPolynomial (Fin 13) ℤ → ℕ)
    (hdegree : ∀ f ∈ equations, f.IsHomogeneous (degree f))
    (h : IntVector 13) :
    rationalDepthSevenEquationIdeal equations ≤
      rationalProjectiveStarIdeal equations degree h := by
  rw [rationalDepthSevenEquationIdeal, rationalProjectiveStarIdeal,
    finiteEquationIdeal, finiteEquationIdeal]
  apply Ideal.span_mono
  intro g hg
  rw [rationalizedEquationFinset, Finset.coe_image] at hg ⊢
  obtain ⟨f, hf, rfl⟩ := hg
  refine ⟨starCoefficient f h (degree f), ?_, ?_⟩
  · change starCoefficient f h (degree f) ∈
      projectiveStarEquationFamily equations degree h
    apply Finset.mem_biUnion.mpr
    refine ⟨f, hf, ?_⟩
    apply Finset.mem_image.mpr
    exact ⟨degree f, Finset.mem_range.mpr (Nat.lt_succ_self _), rfl⟩
  · rw [starCoefficient_eq_of_isHomogeneous f h (degree f)
      (hdegree f hf)]

/-- The displayed star ideal is homogeneous because every coefficient of
order `k` is homogeneous of degree `k`. -/
theorem rationalProjectiveStarIdeal_isHomogeneous {n : ℕ}
    (equations : Finset (MvPolynomial (Fin n) ℤ))
    (degree : MvPolynomial (Fin n) ℤ → ℕ) (h : IntVector n) :
    (rationalProjectiveStarIdeal equations degree h).IsHomogeneous
      (MvPolynomial.homogeneousSubmodule (Fin n) ℚ) := by
  rw [rationalProjectiveStarIdeal, finiteEquationIdeal]
  apply Ideal.homogeneous_span
  intro g hg
  rw [rationalizedEquationFinset, Finset.coe_image] at hg
  obtain ⟨f, hf, rfl⟩ := hg
  obtain ⟨k, hk⟩ :=
    mem_projectiveStarEquationFamily_isHomogeneous
      equations degree h hf
  exact ⟨k, hk.map (Int.castRingHom ℚ)⟩

/-- A concrete representative of a point of the equation-level projective
star is a zero of the rational star ideal. -/
theorem rationalVector_mem_rationalProjectiveStarIdeal_zeroLocus
    {n : ℕ}
    (equations : Finset (MvPolynomial (Fin n) ℤ))
    (degree : MvPolynomial (Fin n) ℤ → ℕ)
    (hdegree : ∀ f ∈ equations, f.IsHomogeneous (degree f))
    (h : IntVector n) (x : Fin n → ℚ) (hx : x ≠ 0)
    (hstar : Projectivization.mk ℚ x hx ∈
      integralProjectiveStarLocus equations degree h) :
    x ∈ affineIdealZeroLocus
      (rationalProjectiveStarIdeal equations degree h) := by
  classical
  have hcone : x ∈ integralAffineConeZeroSetOver ℚ
      (projectiveStarEquationFamily equations degree h) := by
    let starDegree : MvPolynomial (Fin n) ℤ → ℕ := fun g ↦
      if hg : ∃ k, g.IsHomogeneous k then Classical.choose hg else 0
    have hstarHom : ∀ g ∈ projectiveStarEquationFamily equations degree h,
        g.IsHomogeneous (starDegree g) := by
      intro g hg
      have hex := mem_projectiveStarEquationFamily_isHomogeneous
        equations degree h hg
      simp only [starDegree, dif_pos hex]
      exact Classical.choose_spec hex
    exact (mk_mem_integralProjectiveConeZeroSetOver_iff
      (projectiveStarEquationFamily equations degree h)
        starDegree hstarHom x hx).1 hstar
  rw [rationalProjectiveStarIdeal,
    affineIdealZeroLocus_finiteEquationIdeal]
  intro g hg
  rw [rationalizedEquationFinset, Finset.mem_image] at hg
  obtain ⟨f, hf, rfl⟩ := hg
  exact hcone f hf

/-! ## Three bounded Jacobian rows at a smooth centre -/

/-- Three selected rows of the integral Jacobian at `h`. -/
def threeSelectedIntegralJacobianRows
    (equations : Finset (MvPolynomial (Fin 13) ℤ))
    (h : IntVector 13) (rows : Fin 3 → Fin equations.card) :
    Matrix (Fin 3) (Fin 13) ℤ :=
  (integralJacobianMatrix (indexedFinsetFamily equations) h).submatrix
    rows (Equiv.refl (Fin 13))

/-- A nonzero selected `3 x 3` Jacobian minor makes the displayed three-row
matrix have rank exactly three over the rationals. -/
theorem threeSelectedIntegralJacobianRows_rank
    (equations : Finset (MvPolynomial (Fin 13) ℤ))
    (h : IntVector 13)
    (rows : Fin 3 → Fin equations.card) (cols : Fin 3 → Fin 13)
    (hminor : integralJacobianMinor
      (indexedFinsetFamily equations) h rows cols ≠ 0) :
    (threeSelectedIntegralJacobianRows equations h rows |>.map
      (Int.castRingHom ℚ)).rank = 3 := by
  let D := threeSelectedIntegralJacobianRows equations h rows |>.map
    (Int.castRingHom ℚ)
  have hdet : (D.submatrix (Equiv.refl (Fin 3)) cols).det ≠ 0 := by
    have hmatrix : D.submatrix (Equiv.refl (Fin 3)) cols =
        ((integralJacobianMatrix (indexedFinsetFamily equations) h)
          |>.submatrix rows cols).map (Int.castRingHom ℚ) := by
      ext i j
      rfl
    rw [hmatrix]
    have hmap :
        ((integralJacobianMatrix (indexedFinsetFamily equations) h)
          |>.submatrix rows cols).map (Int.castRingHom ℚ) =
        (Int.castRingHom ℚ).mapMatrix
          ((integralJacobianMatrix (indexedFinsetFamily equations) h)
            |>.submatrix rows cols) := by
      ext i j
      rfl
    rw [hmap]
    have hcast := (Int.castRingHom ℚ).map_det
      ((integralJacobianMatrix (indexedFinsetFamily equations) h)
        |>.submatrix rows cols)
    rw [← hcast]
    change (((integralJacobianMatrix (indexedFinsetFamily equations) h)
      |>.submatrix rows cols).det : ℚ) ≠ 0
    change ((integralJacobianMatrix (indexedFinsetFamily equations) h)
      |>.submatrix rows cols).det ≠ 0 at hminor
    exact_mod_cast hminor
  have hlower : 3 ≤ D.rank :=
    rank_ge_card_of_submatrix_det_ne_zero D (Equiv.refl (Fin 3)) cols hdet
  have hupper : D.rank ≤ 3 := Matrix.rank_le_height D
  change D.rank = 3
  exact Nat.le_antisymm hupper hlower

/-- Every coordinate is bounded by the sup height of the integral vector. -/
theorem intVector_natAbs_le_directionHeight {n : ℕ}
    (h : IntVector n) (i : Fin n) :
    (h i).natAbs ≤ directionHeight h := by
  exact Finset.le_sup (f := fun j ↦ (h j).natAbs) (Finset.mem_univ i)

/-- Every entry of three selected Jacobian rows has the crude, completely
explicit coefficient-height bound used by the packet cutoff. -/
theorem threeSelectedIntegralJacobianRows_entry_bound
    (equations : Finset (MvPolynomial (Fin 13) ℤ))
    (h : IntVector 13) (rows : Fin 3 → Fin equations.card) (i j) :
    (threeSelectedIntegralJacobianRows equations h rows i j).natAbs ≤
      equationFamilySupportBound equations *
        equationFamilyDegreeBound equations *
        equationFamilyCoefficientBound equations *
        max 1 (directionHeight h) ^ equationFamilyDegreeBound equations := by
  classical
  let f := indexedFinsetFamily equations (rows i)
  have hf : f ∈ equations := (equations.equivFin.symm (rows i)).2
  change (MvPolynomial.eval h (MvPolynomial.pderiv j f)).natAbs ≤ _
  calc
    (MvPolynomial.eval h (MvPolynomial.pderiv j f)).natAbs ≤
        f.support.card * equationFamilyDegreeBound equations *
          equationFamilyCoefficientBound equations *
          max 1 (directionHeight h) ^ equationFamilyDegreeBound equations :=
      eval_pderiv_natAbs_le_support_mul_degree_mul_coeff_mul_pow f h j
        (fun μ hμ ↦ coeff_natAbs_le_equationFamilyCoefficientBound hf hμ)
        (totalDegree_le_equationFamilyDegreeBound hf)
        (intVector_natAbs_le_directionHeight h)
    _ ≤ equationFamilySupportBound equations *
        equationFamilyDegreeBound equations *
        equationFamilyCoefficientBound equations *
        max 1 (directionHeight h) ^ equationFamilyDegreeBound equations := by
      gcongr
      exact support_card_le_equationFamilySupportBound hf

/-- Three actual Jacobian rows at a rank-seven centre give a rank-three
rational section containing the whole tangent kernel.  Its Pluecker height
is bounded before any point of the star is selected. -/
theorem exists_threeRowSection_containing_tangentKernel
    (equations : Finset (MvPolynomial (Fin 13) ℤ))
    (h : IntVector 13)
    (hregular : IsDepthSevenJacobianRegularAt equations h) :
    ∃ D : Matrix (Fin 3) (Fin 13) ℚ,
      D.rank = 3 ∧
      rationalProjectiveLinearHeight D ≤
        Nat.factorial 3 *
          (equationFamilySupportBound equations *
            equationFamilyDegreeBound equations *
            equationFamilyCoefficientBound equations *
            max 1 (directionHeight h) ^
              equationFamilyDegreeBound equations) ^ 3 ∧
      ∀ x ∈ equationFamilyRationalTangentKernel equations h,
        Matrix.mulVec D x = 0 := by
  classical
  have hrank3 : 3 ≤
      ((integralJacobianMatrix (indexedFinsetFamily equations) h).map
        (Int.castRingHom ℚ)).rank := hregular.trans' (by omega)
  obtain ⟨rows, cols, _hrows, _hcols, hminor⟩ :=
    exists_nonzero_integralJacobianMinor_of_rank_ge
      (indexedFinsetFamily equations) h hrank3
  let A := threeSelectedIntegralJacobianRows equations h rows
  let D := A.map (Int.castRingHom ℚ)
  refine ⟨D, threeSelectedIntegralJacobianRows_rank
    equations h rows cols hminor, ?_, ?_⟩
  · apply rationalProjectiveLinearHeight_map_intCast_le
    intro i j
    exact threeSelectedIntegralJacobianRows_entry_bound
      equations h rows i j
  · intro x hx
    funext i
    have hxzero : equationFamilyRationalJacobianLinearMap equations h x = 0 :=
      LinearMap.mem_ker.mp hx
    let f : {f // f ∈ equations} :=
      ⟨indexedFinsetFamily equations (rows i),
        (equations.equivFin.symm (rows i)).2⟩
    have hrow := congrFun hxzero f
    change ∑ j, ((MvPolynomial.eval h
      (MvPolynomial.pderiv j f.1) : ℤ) : ℚ) * x j = 0 at hrow
    simpa [D, A, threeSelectedIntegralJacobianRows,
      equationFamilyRationalJacobianLinearMap,
      equationFamilyRationalJacobianMatrix, Matrix.mulVec,
      dotProduct, f] using hrow

/-- Every rational representative of a point of the explicit star is
annihilated by the bounded rank-three matrix chosen at a rank-seven centre. -/
theorem exists_threeRowSection_containing_projectiveStar
    (equations : Finset (MvPolynomial (Fin 13) ℤ))
    (degree : MvPolynomial (Fin 13) ℤ → ℕ)
    (hdegree : ∀ f ∈ equations, f.IsHomogeneous (degree f))
    (h : IntVector 13)
    (hregular : IsDepthSevenJacobianRegularAt equations h) :
    ∃ D : Matrix (Fin 3) (Fin 13) ℚ,
      D.rank = 3 ∧
      rationalProjectiveLinearHeight D ≤
        Nat.factorial 3 *
          (equationFamilySupportBound equations *
            equationFamilyDegreeBound equations *
            equationFamilyCoefficientBound equations *
            max 1 (directionHeight h) ^
              equationFamilyDegreeBound equations) ^ 3 ∧
      ∀ (x : Fin 13 → ℚ) (hx : x ≠ 0),
        Projectivization.mk ℚ x hx ∈
            integralProjectiveStarLocus equations degree h →
          Matrix.mulVec D x = 0 := by
  obtain ⟨D, hDrank, hDheight, hDtangent⟩ :=
    exists_threeRowSection_containing_tangentKernel equations h hregular
  refine ⟨D, hDrank, hDheight, ?_⟩
  intro x hx hstar
  have htangent :=
    (integralProjectiveStarLocus_subset_cone_inter_tangent
      equations degree h hdegree hstar).2
  have hxTangent : x ∈ equationFamilyRationalTangentKernel equations h :=
    (mk_mem_equationFamilyRationalProjectiveTangentSpace_iff
      equations h x hx).1 htangent
  exact hDtangent x hxTangent

/-- The fixed coefficient contribution to the height of the three selected
Jacobian rows.  It depends only on the displayed equation family. -/
def smoothStarJacobianHeightConstant
    (equations : Finset (MvPolynomial (Fin 13) ℤ)) : ℕ :=
  Nat.factorial 3 *
    (equationFamilySupportBound equations *
      equationFamilyDegreeBound equations *
      equationFamilyCoefficientBound equations) ^ 3

/-- One explicit exponent which absorbs both the fixed coefficients and the
height of a low direction.  No parameter of the translated box enters this
definition. -/
def smoothStarJacobianHeightExponent
    (equations : Finset (MvPolynomial (Fin 13) ℤ)) : ℕ :=
  smoothStarJacobianHeightConstant equations +
    3 * equationFamilyDegreeBound equations

/-- A low primitive direction has ordinary integral height at most the
manuscript height `H`.  This is just
`floor(T^(2/21)) <= T^(2/21) <= T <= H`. -/
theorem lowDirectionHeight_cast_le_manuscriptHeight
    (p : Parameters) (h : IntVector 13)
    (hlow : directionHeight h ≤
      lowDirectionNaturalRadius (surfaceTangentRealSide p)) :
    (directionHeight h : ℝ) ≤ p.H := by
  have hfloor : (lowDirectionNaturalRadius
      (surfaceTangentRealSide p) : ℝ) ≤
      (xScale (surfaceTangentRealSide p) : ℝ) := by
    simpa [lowDirectionNaturalRadius] using
      (Nat.floor_le
        (a := xScale (surfaceTangentRealSide p))
        (show 0 ≤ xScale (surfaceTangentRealSide p) by positivity))
  have hxT : (xScale (surfaceTangentRealSide p) : ℝ) ≤ p.T := by
    rw [xScale, NNReal.coe_rpow, coe_surfaceTangentRealSide]
    have hbase : (1 : ℝ) ≤ p.T := p.one_le_T
    have hexponent : (2 / 21 : ℝ) ≤ 1 := by norm_num
    simpa only [Real.rpow_one] using
      (Real.rpow_le_rpow_of_exponent_le hbase hexponent)
  have hlowReal : (directionHeight h : ℝ) ≤
      (lowDirectionNaturalRadius (surfaceTangentRealSide p) : ℝ) := by
    exact_mod_cast hlow
  exact hlowReal.trans (hfloor.trans (hxT.trans p.T_le_H))

/-- The raw three-row Jacobian height at a low direction is bounded by one
fixed power of `H`.  The deliberately generous exponent is useful because
it is chosen once from the fixed equations, before the box and direction. -/
theorem smoothStarJacobianHeight_le_ceil_heightPower
    (p : Parameters)
    (equations : Finset (MvPolynomial (Fin 13) ℤ))
    (h : IntVector 13)
    (hlow : directionHeight h ≤
      lowDirectionNaturalRadius (surfaceTangentRealSide p)) :
    Nat.factorial 3 *
      (equationFamilySupportBound equations *
        equationFamilyDegreeBound equations *
        equationFamilyCoefficientBound equations *
        max 1 (directionHeight h) ^
          equationFamilyDegreeBound equations) ^ 3 ≤
      ⌈p.H ^ smoothStarJacobianHeightExponent equations⌉₊ := by
  let C := smoothStarJacobianHeightConstant equations
  let e := equationFamilyDegreeBound equations
  have hH : (1 : ℝ) ≤ p.H := by linarith [p.five_le_H]
  have hdir : (max 1 (directionHeight h) : ℝ) ≤ p.H := by
    exact max_le hH (lowDirectionHeight_cast_le_manuscriptHeight p h hlow)
  have hC : (C : ℝ) ≤ p.H ^ C := by
    have hself : C ≤ 2 ^ C := self_le_two_pow C
    have hselfReal : (C : ℝ) ≤ (2 ^ C : ℕ) := by
      exact_mod_cast hself
    have htwo : (2 : ℝ) ≤ p.H := by linarith [p.five_le_H]
    have hpow : (2 : ℝ) ^ C ≤ p.H ^ C :=
      pow_le_pow_left₀ (by positivity) htwo C
    exact hselfReal.trans (by simpa using hpow)
  have hdirPow :
      (max 1 (directionHeight h) : ℝ) ^ (3 * e) ≤
        p.H ^ (3 * e) :=
    pow_le_pow_left₀ (by positivity) hdir (3 * e)
  have hraw :
      (Nat.factorial 3 *
        (equationFamilySupportBound equations *
          equationFamilyDegreeBound equations *
          equationFamilyCoefficientBound equations *
          max 1 (directionHeight h) ^ e) ^ 3 : ℕ) ≤
        (p.H ^ smoothStarJacobianHeightExponent equations : ℝ) := by
    have hlhs :
        ((Nat.factorial 3 *
          (equationFamilySupportBound equations *
            equationFamilyDegreeBound equations *
            equationFamilyCoefficientBound equations *
            max 1 (directionHeight h) ^ e) ^ 3 : ℕ) : ℝ) =
          (C : ℝ) * (max 1 (directionHeight h) : ℝ) ^ (3 * e) := by
      dsimp only [C, smoothStarJacobianHeightConstant]
      norm_num only [Nat.cast_mul, Nat.cast_pow, Nat.cast_max, Nat.cast_one,
        Nat.cast_ofNat]
      ring
    rw [hlhs]
    rw [smoothStarJacobianHeightExponent]
    dsimp only [C, e]
    calc
      (smoothStarJacobianHeightConstant equations : ℝ) *
          (max 1 (directionHeight h) : ℝ) ^
            (3 * equationFamilyDegreeBound equations) ≤
        p.H ^ smoothStarJacobianHeightConstant equations *
          p.H ^ (3 * equationFamilyDegreeBound equations) := by
            gcongr
      _ = p.H ^ smoothStarJacobianHeightExponent equations := by
        rw [smoothStarJacobianHeightExponent]
        ring
  exact_mod_cast hraw.trans
    (Nat.le_ceil (p.H ^ smoothStarJacobianHeightExponent equations))

/-- The same bound at every later exceptional-locus exponent. -/
theorem smoothStarJacobianHeight_le_ceil_laterHeightPower
    (p : Parameters)
    (equations : Finset (MvPolynomial (Fin 13) ℤ))
    (CF : ℕ)
    (hCF : smoothStarJacobianHeightExponent equations ≤ CF)
    (h : IntVector 13)
    (hlow : directionHeight h ≤
      lowDirectionNaturalRadius (surfaceTangentRealSide p)) :
    Nat.factorial 3 *
      (equationFamilySupportBound equations *
        equationFamilyDegreeBound equations *
        equationFamilyCoefficientBound equations *
        max 1 (directionHeight h) ^
          equationFamilyDegreeBound equations) ^ 3 ≤
      ⌈p.H ^ CF⌉₊ := by
  exact (smoothStarJacobianHeight_le_ceil_heightPower
    p equations h hlow).trans (Nat.ceil_mono
      (pow_le_pow_right₀ (by linarith [p.five_le_H] : (1 : ℝ) ≤ p.H) hCF))

/-- Smooth-centre specialization for an actual normalized point.  Once the
explicit Jacobian height displayed above lies below the already fixed
exceptional-locus cutoff, the existing codimension-three section theorem
extracts an actual geometric component through the point.  Thus every such
component has projective dimension at most two, and a surface component has
degree at least eight. -/
theorem exists_smoothStar_codimensionThreeComponent_through_normalizedPoint
    (p : Parameters) (x₀ : IntVector 13)
    (equations : Finset (MvPolynomial (Fin 13) ℤ)) (CF : ℕ)
    (degree : MvPolynomial (Fin 13) ℤ → ℕ)
    (hdegree : ∀ f ∈ equations, f.IsHomogeneous (degree f))
    (hhomogeneous : (finiteEquationIdeal
      (rationalizedEquationFinset equations)).IsHomogeneous
        (MvPolynomial.homogeneousSubmodule (Fin 13) ℚ))
    (h : IntVector 13)
    (hregular : IsDepthSevenJacobianRegularAt equations h)
    (hheight : Nat.factorial 3 *
      (equationFamilySupportBound equations *
        equationFamilyDegreeBound equations *
        equationFamilyCoefficientBound equations *
        max 1 (directionHeight h) ^
          equationFamilyDegreeBound equations) ^ 3 ≤ ⌈p.H ^ CF⌉₊)
    {z : IntVector 13}
    (hz : z ∈ depthSevenNormalizedDisplacementFinset p x₀ equations CF)
    (hstar : ∃ hx : integralAffineMap x₀ z p.m ≠ 0,
      integralProjectiveClass (integralAffineMap x₀ z p.m) hx ∈
        integralProjectiveStarLocus equations degree h) :
    ∃ D : Matrix (Fin 3) (Fin 13) ℚ,
      D.rank = 3 ∧
      rationalProjectiveLinearHeight D ≤ ⌈p.H ^ CF⌉₊ ∧
      Matrix.mulVec D
        (fun j ↦ (integralAffineMap x₀ z p.m j : ℚ)) = 0 ∧
      ∃ hx : integralAffineMap x₀ z p.m ≠ 0,
        ∃ Q : Ideal (MvPolynomial (Fin 13) Qbar),
          IsProjectiveSectionComponent equations D Q ∧
          ProjectivePointVanishesOnGeometricIdeal Q
            (integralProjectiveClass (integralAffineMap x₀ z p.m) hx) ∧
          ∀ r d, HasGeometricProjectiveDimensionDegree Q r d →
            r ≤ 2 ∧ (r = 2 → 8 ≤ d) := by
  obtain ⟨D, hDrank, hDraw, hDstar⟩ :=
    exists_threeRowSection_containing_projectiveStar
      equations degree hdegree h hregular
  obtain ⟨hx, hxstar⟩ := hstar
  have hxQ : (fun j ↦ (integralAffineMap x₀ z p.m j : ℚ)) ≠ 0 :=
    intCast_ne_zero hx
  have hDpoint : Matrix.mulVec D
      (fun j ↦ (integralAffineMap x₀ z p.m j : ℚ)) = 0 := by
    apply hDstar _ hxQ
    simpa only [integralProjectiveClass] using hxstar
  have hDheight : rationalProjectiveLinearHeight D ≤ ⌈p.H ^ CF⌉₊ :=
    hDraw.trans hheight
  refine ⟨D, hDrank, hDheight, hDpoint, ?_⟩
  exact exists_codimensionThree_component_through_normalizedPoint
    p x₀ equations CF hhomogeneous D hDrank hDheight hz hDpoint

/-- Fully specialized smooth low-direction statement.  The height premise
of the preceding theorem is now discharged by the literal low-direction
cutoff, so the only exponent condition is a fixed inequality depending on
the original equation family. -/
theorem exists_smoothLowDirectionStar_component_through_normalizedPoint
    (p : Parameters) (x₀ : IntVector 13)
    (equations : Finset (MvPolynomial (Fin 13) ℤ)) (CF : ℕ)
    (hCF : smoothStarJacobianHeightExponent equations ≤ CF)
    (degree : MvPolynomial (Fin 13) ℤ → ℕ)
    (hdegree : ∀ f ∈ equations, f.IsHomogeneous (degree f))
    (hhomogeneous : (finiteEquationIdeal
      (rationalizedEquationFinset equations)).IsHomogeneous
        (MvPolynomial.homogeneousSubmodule (Fin 13) ℚ))
    (h : IntVector 13)
    (hlow : directionHeight h ≤
      lowDirectionNaturalRadius (surfaceTangentRealSide p))
    (hregular : IsDepthSevenJacobianRegularAt equations h)
    {z : IntVector 13}
    (hz : z ∈ depthSevenNormalizedDisplacementFinset p x₀ equations CF)
    (hstar : ∃ hx : integralAffineMap x₀ z p.m ≠ 0,
      integralProjectiveClass (integralAffineMap x₀ z p.m) hx ∈
        integralProjectiveStarLocus equations degree h) :
    ∃ D : Matrix (Fin 3) (Fin 13) ℚ,
      D.rank = 3 ∧
      rationalProjectiveLinearHeight D ≤ ⌈p.H ^ CF⌉₊ ∧
      Matrix.mulVec D
        (fun j ↦ (integralAffineMap x₀ z p.m j : ℚ)) = 0 ∧
      ∃ hx : integralAffineMap x₀ z p.m ≠ 0,
        ∃ Q : Ideal (MvPolynomial (Fin 13) Qbar),
          IsProjectiveSectionComponent equations D Q ∧
          ProjectivePointVanishesOnGeometricIdeal Q
            (integralProjectiveClass (integralAffineMap x₀ z p.m) hx) ∧
          ∀ r d, HasGeometricProjectiveDimensionDegree Q r d →
            r ≤ 2 ∧ (r = 2 → 8 ≤ d) := by
  apply exists_smoothStar_codimensionThreeComponent_through_normalizedPoint
    p x₀ equations CF degree hdegree hhomogeneous h hregular
    (smoothStarJacobianHeight_le_ceil_laterHeightPower
      p equations CF hCF h hlow) hz hstar

/-! ## Properness at a singular nonvertex centre -/

namespace StandardAG

/-- Equality of the original homogeneous ideal with the ideal generated by
all line coefficients at `h` forces `[h]` to be a projective vertex.

This is the elementary cone--star incidence lemma: after extending to an
algebraic closure, every coefficient of `f(h+Tz)` vanishes at every point
of the cone; homogeneity changes the affine-line identity into the complete
projective-line identity.  The statement has no dimension, degree, height,
component-count, or rational-point conclusion. -/
def ProjectiveStarEqualityForcesVertex : Prop :=
  ∀ (equations : Finset (MvPolynomial (Fin 13) ℤ))
    (degree : MvPolynomial (Fin 13) ℤ → ℕ)
    (hdegree : ∀ f ∈ equations, f.IsHomogeneous (degree f))
    (h : IntVector 13),
    h ≠ 0 →
    IntegralCommonZero equations h →
    rationalDepthSevenEquationIdeal equations =
        rationalProjectiveStarIdeal equations degree h →
      LiesInGeometricProjectiveVertex h
        (rationalDepthSevenEquationIdeal equations)

/-- The narrow affine-Bezout consequence needed for a finite homogeneous
equation family.  It bounds the number of actual minimal primes and the
degree of every nonempty projective component by the fixed product-degree
majorant.  This is the usual component-degree form of affine Bezout (or
Heintz's lemma); it contains no rational-point estimate and no assertion
about stars, lines, packets, or translated boxes. -/
def FiniteEquationProjectiveComponentBezoutBounds : Prop :=
  ∀ (N : ℕ) (family : Finset (MvPolynomial (Fin (N + 1)) ℚ))
    (D : ℕ),
    (∀ f ∈ family, f.totalDegree ≤ D) →
      (finiteMinimalPrimes (finiteEquationIdeal family)).card ≤
          max 1 D ^ (N + 1) ∧
        ∀ Q ∈ finiteMinimalPrimes (finiteEquationIdeal family),
          ∀ r d : ℕ, HasProjectiveDimensionDegree Q r d →
            d ≤ max 1 D ^ (N + 1)

end StandardAG

/-- Every rationalized coefficient equation of the literal star has degree
at most the maximum degree of the original fixed equations. -/
theorem rationalizedProjectiveStarEquation_totalDegree_le
    (equations : Finset (MvPolynomial (Fin 13) ℤ))
    (degree : MvPolynomial (Fin 13) ℤ → ℕ)
    (hdegree : ∀ f ∈ equations, f.IsHomogeneous (degree f))
    (h : IntVector 13)
    {g : MvPolynomial (Fin 13) ℚ}
    (hg : g ∈ rationalizedEquationFinset
      (projectiveStarEquationFamily equations degree h)) :
    g.totalDegree ≤ equationFamilyDegreeBound equations := by
  classical
  rw [rationalizedEquationFinset, Finset.mem_image] at hg
  obtain ⟨gℤ, hgℤ, rfl⟩ := hg
  rw [projectiveStarEquationFamily, Finset.mem_biUnion] at hgℤ
  obtain ⟨f, hf, hgf⟩ := hgℤ
  rw [Finset.mem_image] at hgf
  obtain ⟨k, hk, rfl⟩ := hgf
  by_cases hfzero : f = 0
  · subst f
    simp [starCoefficient, symbolicLinePolynomial]
  · have hmapDegree :
        (MvPolynomial.map (Int.castRingHom ℚ)
          (starCoefficient f h k)).totalDegree =
            (starCoefficient f h k).totalDegree := by
      unfold MvPolynomial.totalDegree
      rw [MvPolynomial.support_map_of_injective _ Int.cast_injective]
    rw [hmapDegree]
    have hkdegree : k ≤ degree f := Nat.lt_succ_iff.mp
      (Finset.mem_range.mp hk)
    exact (starCoefficient_isHomogeneous f h k).totalDegree_le |>.trans
      (hkdegree.trans (by
        rw [← (hdegree f hf).totalDegree hfzero]
        exact totalDegree_le_equationFamilyDegreeBound hf))

/-- Literal Bezout bounds for the actual minimal-prime list of every star.
The bound is chosen from the original equation degrees before the centre. -/
theorem rationalProjectiveStar_componentBezoutBounds
    (hBezout : StandardAG.FiniteEquationProjectiveComponentBezoutBounds)
    (equations : Finset (MvPolynomial (Fin 13) ℤ))
    (degree : MvPolynomial (Fin 13) ℤ → ℕ)
    (hdegree : ∀ f ∈ equations, f.IsHomogeneous (degree f))
    (h : IntVector 13) :
    (finiteMinimalPrimes
      (rationalProjectiveStarIdeal equations degree h)).card ≤
        max 1 (equationFamilyDegreeBound equations) ^ 13 ∧
      ∀ Q ∈ finiteMinimalPrimes
          (rationalProjectiveStarIdeal equations degree h),
        ∀ r d : ℕ, HasProjectiveDimensionDegree Q r d →
          d ≤ max 1 (equationFamilyDegreeBound equations) ^ 13 := by
  simpa only [rationalProjectiveStarIdeal] using
    hBezout 12
      (rationalizedEquationFinset
        (projectiveStarEquationFamily equations degree h))
      (equationFamilyDegreeBound equations)
      (fun g hg ↦ rationalizedProjectiveStarEquation_totalDegree_le
        equations degree hdegree h hg)

/-- At a nonvertex centre, the ideal of the literal projective star is a
strict enlargement of the original cone ideal. -/
theorem rationalDepthSevenEquationIdeal_lt_rationalProjectiveStarIdeal
    (hstarVertex : StandardAG.ProjectiveStarEqualityForcesVertex)
    (equations : Finset (MvPolynomial (Fin 13) ℤ))
    (degree : MvPolynomial (Fin 13) ℤ → ℕ)
    (hdegree : ∀ f ∈ equations, f.IsHomogeneous (degree f))
    (h : IntVector 13) (hh : h ≠ 0)
    (hzero : IntegralCommonZero equations h)
    (hnotVertex : ¬ LiesInGeometricProjectiveVertex h
      (rationalDepthSevenEquationIdeal equations)) :
    rationalDepthSevenEquationIdeal equations <
      rationalProjectiveStarIdeal equations degree h := by
  refine lt_of_le_of_ne
    (rationalDepthSevenEquationIdeal_le_rationalProjectiveStarIdeal
      equations degree hdegree h) ?_
  intro heq
  apply hnotVertex
  apply hstarVertex equations degree hdegree h hh hzero
  exact heq

/-- Every actual minimal-prime component of a nonvertex star has strictly
smaller affine-cone dimension than the original six-dimensional cone. -/
theorem nonvertexStar_minimalPrime_dimension_lt_six
    (hstarVertex : StandardAG.ProjectiveStarEqualityForcesVertex)
    (equations : Finset (MvPolynomial (Fin 13) ℤ))
    (degree : MvPolynomial (Fin 13) ℤ → ℕ)
    (hdegree : ∀ f ∈ equations, f.IsHomogeneous (degree f))
    (h : IntVector 13) (hh : h ≠ 0)
    (hzero : IntegralCommonZero equations h)
    (hnotVertex : ¬ LiesInGeometricProjectiveVertex h
      (rationalDepthSevenEquationIdeal equations))
    (hprime : (rationalDepthSevenEquationIdeal equations).IsPrime)
    (hdim : ringKrullDim
      (MvPolynomial (Fin 13) ℚ ⧸
        rationalDepthSevenEquationIdeal equations) = 6)
    (Q : Ideal (MvPolynomial (Fin 13) ℚ))
    (hQ : Q ∈ finiteMinimalPrimes
      (rationalProjectiveStarIdeal equations degree h)) :
    ringKrullDim (MvPolynomial (Fin 13) ℚ ⧸ Q) < 6 := by
  letI : (rationalDepthSevenEquationIdeal equations).IsPrime := hprime
  letI : Q.IsPrime := isPrime_of_mem_finiteMinimalPrimes hQ
  have hstrict : rationalDepthSevenEquationIdeal equations < Q :=
    (rationalDepthSevenEquationIdeal_lt_rationalProjectiveStarIdeal
      hstarVertex equations degree hdegree h hh hzero hnotVertex).trans_le
        (le_of_mem_finiteMinimalPrimes hQ)
  have hfinite : ringKrullDim
      (MvPolynomial (Fin 13) ℚ ⧸
        rationalDepthSevenEquationIdeal equations) < ⊤ := by
    rw [hdim]
    change (↑(6 : ℕ∞) : WithBot ℕ∞) < ↑(⊤ : ℕ∞)
    exact WithBot.coe_lt_coe.mpr (ENat.coe_lt_top 6)
  have hdrop := ringKrullDim_quotient_lt_of_prime_lt
    (rationalDepthSevenEquationIdeal equations) Q hstrict hfinite
  rwa [hdim] at hdrop

/-- The same minimal-prime component is homogeneous.  Together with the
previous theorem, this is the exact algebraic input for the existing Pila
bridge in affine dimension at most four and the existing proper-fourfold
Salberger bridge in affine dimension five. -/
theorem nonvertexStar_minimalPrime_isHomogeneous
    (equations : Finset (MvPolynomial (Fin 13) ℤ))
    (degree : MvPolynomial (Fin 13) ℤ → ℕ)
    (h : IntVector 13)
    (Q : Ideal (MvPolynomial (Fin 13) ℚ))
    (hQ : Q ∈ finiteMinimalPrimes
      (rationalProjectiveStarIdeal equations degree h)) :
    Q.IsHomogeneous
      (MvPolynomial.homogeneousSubmodule (Fin 13) ℚ) := by
  apply isHomogeneous_of_mem_minimalPrimes_of_isHomogeneous
    (rationalProjectiveStarIdeal_isHomogeneous equations degree h)
  exact (mem_finiteMinimalPrimes_iff _ _).1 hQ

/-- A nonzero rational point on a minimal component supplies the
nonemptiness condition needed by projective Hilbert--Serre.  Combining it
with the strict dimension drop proves that the component is a projective
variety of dimension at most four and positive degree. -/
theorem nonvertexStar_minimalPrime_projectiveDimensionDegree
    (hHilbert : StandardAG.ProjectiveHilbertDegreeCertification ℚ)
    (hstarVertex : StandardAG.ProjectiveStarEqualityForcesVertex)
    (equations : Finset (MvPolynomial (Fin 13) ℤ))
    (degree : MvPolynomial (Fin 13) ℤ → ℕ)
    (hdegree : ∀ f ∈ equations, f.IsHomogeneous (degree f))
    (h : IntVector 13) (hh : h ≠ 0)
    (hzero : IntegralCommonZero equations h)
    (hnotVertex : ¬ LiesInGeometricProjectiveVertex h
      (rationalDepthSevenEquationIdeal equations))
    (hprime : (rationalDepthSevenEquationIdeal equations).IsPrime)
    (hdim : ringKrullDim
      (MvPolynomial (Fin 13) ℚ ⧸
        rationalDepthSevenEquationIdeal equations) = 6)
    (Q : Ideal (MvPolynomial (Fin 13) ℚ))
    (hQ : Q ∈ finiteMinimalPrimes
      (rationalProjectiveStarIdeal equations degree h))
    (x : Fin 13 → ℚ) (hxne : x ≠ 0)
    (hxQ : x ∈ affineIdealZeroLocus Q) :
    ∃ r d : ℕ,
      HasProjectiveDimensionDegree Q r d ∧ r ≤ 4 := by
  have hQprime : Q.IsPrime := isPrime_of_mem_finiteMinimalPrimes hQ
  have hQhomogeneous : Q.IsHomogeneous
      (MvPolynomial.homogeneousSubmodule (Fin 13) ℚ) :=
    nonvertexStar_minimalPrime_isHomogeneous equations degree h Q hQ
  have hirrelevant : ¬ Published.projectiveIrrelevantIdeal ℚ 12 ≤ Q := by
    intro hirr
    exact hxne (eq_zero_of_mem_affineIdealZeroLocus_of_irrelevant_le
      hirr hxQ)
  obtain ⟨r, d, P, hcert⟩ :=
    hHilbert 12 Q hQprime hQhomogeneous hirrelevant
  have hdimlt : ringKrullDim (MvPolynomial (Fin 13) ℚ ⧸ Q) < 6 :=
    nonvertexStar_minimalPrime_dimension_lt_six
      hstarVertex equations degree hdegree h hh hzero hnotVertex
        hprime hdim Q hQ
  have hrlt : (r + 1 : WithBot ℕ∞) < 6 := by
    rw [← hcert.1]
    exact hdimlt
  have hrltNat : r + 1 < 6 := by exact_mod_cast hrlt
  exact ⟨r, d, hcert.toPublished, by omega⟩

end

end TranslatedDepthSeven
