import TranslatedDepthSeven.EquationFamilyProjectiveTangentSpace
import Mathlib.LinearAlgebra.Matrix.Notation

/-!
# Rational projective lines and tangent-space containment

This file gives the projective line generated by two rational vectors as an
actual `Projectivization.Subspace`: it is the projectivization of their
two-generator vector span.  Membership is converted into a literal
representative `a • h + b • z`.  For an integral affine line lying on a
finite homogeneous equation family, this actual projective subspace is then
shown to lie in the evaluated rational projective tangent space.
-/

namespace TranslatedDepthSeven

noncomputable section

open scoped LinearAlgebra.Projectivization

open Finset MvPolynomial

section TwoVectors

variable {V : Type*} [AddCommGroup V] [Module ℚ V]

/-- The two-dimensional vector cone generated by `h` and `z`.  It may have
dimension less than two when the generators are dependent. -/
def rationalProjectiveLineCone (h z : V) : Submodule ℚ V :=
  Submodule.span ℚ ({h, z} : Set V)

/-- The actual rational projective subspace generated by `h` and `z`.
When the two vectors are linearly independent, its vector cone has dimension
two, so this is a projective line in the usual sense. -/
def rationalProjectiveLine (h z : V) : Projectivization.Subspace ℚ V :=
  (rationalProjectiveLineCone h z).projectivization

/-- A nonzero vector represents a point of the generated projective line
exactly when it is a rational linear combination of the two generators. -/
@[simp]
theorem mk_mem_rationalProjectiveLine_iff (h z x : V) (hx : x ≠ 0) :
    Projectivization.mk ℚ x hx ∈ rationalProjectiveLine h z ↔
      ∃ a b : ℚ, a • h + b • z = x := by
  rw [rationalProjectiveLine, Submodule.mk_mem_projectivization_iff,
    rationalProjectiveLineCone, Submodule.mem_span_pair]

/-- Every point of the generated projective line has a literal nonzero
representative of the form `a • h + b • z`. -/
theorem mem_rationalProjectiveLine_iff_exists_representation
    (h z : V) (x : Projectivization ℚ V) :
    x ∈ rationalProjectiveLine h z ↔
      ∃ (a b : ℚ) (hab : a • h + b • z ≠ 0),
        x = Projectivization.mk ℚ (a • h + b • z) hab := by
  constructor
  · intro hx
    have hxrep : Projectivization.mk ℚ x.rep x.rep_nonzero ∈
        rationalProjectiveLine h z := by
      simpa using hx
    obtain ⟨a, b, hab⟩ :=
      (mk_mem_rationalProjectiveLine_iff h z x.rep x.rep_nonzero).mp hxrep
    have hab0 : a • h + b • z ≠ 0 := by
      rw [hab]
      exact x.rep_nonzero
    refine ⟨a, b, hab0, ?_⟩
    calc
      x = Projectivization.mk ℚ x.rep x.rep_nonzero :=
        (Projectivization.mk_rep x).symm
      _ = Projectivization.mk ℚ (a • h + b • z) hab0 := by
        apply (Projectivization.mk_eq_mk_iff' ℚ _ _ _ _).mpr
        exact ⟨1, by simpa using hab⟩
  · rintro ⟨a, b, hab, rfl⟩
    exact (mk_mem_rationalProjectiveLine_iff h z _ hab).mpr ⟨a, b, rfl⟩

/-- The cone generated by two linearly independent vectors has dimension
exactly two. -/
theorem finrank_rationalProjectiveLineCone_eq_two (h z : V)
    (hlin : LinearIndependent ℚ ![h, z]) :
    Module.finrank ℚ (rationalProjectiveLineCone h z) = 2 := by
  have hdim := finrank_span_eq_card hlin
  have hrange : Set.range ![h, z] = ({h, z} : Set V) := by
    ext x
    simp only [Set.mem_range, Set.mem_insert_iff, Set.mem_singleton_iff]
    constructor
    · rintro ⟨i, rfl⟩
      fin_cases i <;> simp
    · rintro (rfl | rfl)
      · exact ⟨0, by simp⟩
      · exact ⟨1, by simp⟩
  rw [rationalProjectiveLineCone, ← hrange]
  simpa using hdim

/-- The submodule underlying the actual projective line has vector-space
dimension two.  Mathlib presently represents projective subspaces through
this underlying submodule rather than assigning them a separate numerical
projective dimension. -/
theorem finrank_rationalProjectiveLine_submodule_eq_two (h z : V)
    (hlin : LinearIndependent ℚ ![h, z]) :
    Module.finrank ℚ
        (Projectivization.Subspace.submodule (rationalProjectiveLine h z)) = 2 := by
  have hsubmodule :
      Projectivization.Subspace.submodule (rationalProjectiveLine h z) =
        rationalProjectiveLineCone h z := by
    exact Projectivization.Subspace.submodule.apply_symm_apply _
  rw [hsubmodule]
  exact finrank_rationalProjectiveLineCone_eq_two h z hlin

end TwoVectors

section EquationFamily

/-- If the full integral affine line `h + ℤ z` lies on every displayed
homogeneous equation, then the actual rational projective line generated by
`h` and `z` lies in the evaluated rational projective tangent space at `h`. -/
theorem rationalProjectiveLine_le_equationFamilyRationalProjectiveTangentSpace
    {n : ℕ} (equations : Finset (MvPolynomial (Fin n) ℤ))
    (degree : MvPolynomial (Fin n) ℤ → ℕ) (h z : IntVector n)
    (hhom : ∀ f ∈ equations, f.IsHomogeneous (degree f))
    (hline : ∀ f ∈ equations, ∀ t : ℤ,
      MvPolynomial.eval (fun i ↦ h i + t * z i) f = 0) :
    rationalProjectiveLine
        (fun i ↦ (h i : ℚ)) (fun i ↦ (z i : ℚ)) ≤
      equationFamilyRationalProjectiveTangentSpace equations h := by
  intro x hx
  obtain ⟨a, b, hab, rfl⟩ :=
    (mem_rationalProjectiveLine_iff_exists_representation
      (fun i ↦ (h i : ℚ)) (fun i ↦ (z i : ℚ)) x).mp hx
  simpa [Pi.smul_apply] using
    (rationalProjectiveLine_mem_equationFamilyRationalProjectiveTangentSpace
      equations degree h z hhom hline a b (by simpa [Pi.smul_apply] using hab))

end EquationFamily

end

end TranslatedDepthSeven
