import TranslatedDepthSeven.RelativePersistentSurfaceChartIdeals

/-!
# Literal relative charts modulo a parameter stratum

A relation constructed over the coordinate ring of a parameter stratum need
not be a polynomial identity in the ambient parameter space.  This file
records the missing data literally: every equation and every colon-clearing
identity comes with finite syzygy coefficients and with an explicit error
which is a linear combination of the stratum equations.  Specialization at
an integral point of the stratum kills those error terms term by term.

The principal parameter denominator is kept as an actual polynomial.  It is
inserted into the local certificate, so every prime at which the relative
model may fail is among the prime divisors of the resulting integer.  No
existence theorem for these charts is asserted here.
-/

namespace TranslatedDepthSeven

noncomputable section

open scoped BigOperators
open MvPolynomial Published

/-- A parameter polynomial, regarded as a constant in the affine variables. -/
def liftRelativeIntegralParameterPolynomial {M N : ℕ}
    (f : MvPolynomial (Fin M) ℤ) :
    RelativeIntegralAffinePolynomial M N :=
  MvPolynomial.C f

/-- A fixed relative chart, a fixed component-generator list, and completely
explicit syzygies modulo a finite list of equations of the parameter
stratum. -/
structure RelativePersistentSurfaceStratumSyzygy
    (M N equationCount clearingCount componentGeneratorCount
      stratumEquationCount : ℕ)
    extends RelativePersistentSurfaceChart M N equationCount clearingCount where
  componentGenerator : Fin componentGeneratorCount →
    RelativeIntegralAffinePolynomial M N
  stratumEquation : Fin stratumEquationCount → MvPolynomial (Fin M) ℤ
  parameterDenominator : MvPolynomial (Fin M) ℤ
  equationInComponentCoefficient :
    Fin equationCount → Fin componentGeneratorCount →
      RelativeIntegralAffinePolynomial M N
  equationStratumErrorCoefficient :
    Fin equationCount → Fin stratumEquationCount →
      RelativeIntegralAffinePolynomial M N
  equation_syzygy : ∀ i,
    toRelativePersistentSurfaceChart.equation i =
      ∑ j, equationInComponentCoefficient i j * componentGenerator j +
      ∑ r, equationStratumErrorCoefficient i r *
        liftRelativeIntegralParameterPolynomial (stratumEquation r)
  clearingInEquationCoefficient :
    Fin clearingCount → Fin componentGeneratorCount →
      Fin equationCount → RelativeIntegralAffinePolynomial M N
  clearingStratumErrorCoefficient :
    Fin clearingCount → Fin componentGeneratorCount →
      Fin stratumEquationCount → RelativeIntegralAffinePolynomial M N
  clearing_syzygy : ∀ mark j,
    toRelativePersistentSurfaceChart.clearingPolynomial mark *
        componentGenerator j =
      ∑ i, clearingInEquationCoefficient mark j i *
        toRelativePersistentSurfaceChart.equation i +
      ∑ r, clearingStratumErrorCoefficient mark j r *
        liftRelativeIntegralParameterPolynomial (stratumEquation r)

/-- An integral parameter point lies on the displayed closed stratum. -/
def RelativePersistentSurfaceStratumSyzygy.OnStratum
    {M N equationCount clearingCount componentGeneratorCount
      stratumEquationCount : ℕ}
    (data : RelativePersistentSurfaceStratumSyzygy M N equationCount
      clearingCount componentGeneratorCount stratumEquationCount)
    (parameter : Fin M → ℤ) : Prop :=
  ∀ r, MvPolynomial.eval parameter (data.stratumEquation r) = 0

/-- The principal parameter denominator does not vanish at the displayed
integral parameter point. -/
def RelativePersistentSurfaceStratumSyzygy.InDenominatorOpen
    {M N equationCount clearingCount componentGeneratorCount
      stratumEquationCount : ℕ}
    (data : RelativePersistentSurfaceStratumSyzygy M N equationCount
      clearingCount componentGeneratorCount stratumEquationCount)
    (parameter : Fin M → ℤ) : Prop :=
  MvPolynomial.eval parameter data.parameterDenominator ≠ 0

/-- The specialized finite component-generator list. -/
def RelativePersistentSurfaceStratumSyzygy.specializedComponentGenerator
    {M N equationCount clearingCount componentGeneratorCount
      stratumEquationCount : ℕ}
    (data : RelativePersistentSurfaceStratumSyzygy M N equationCount
      clearingCount componentGeneratorCount stratumEquationCount)
    (parameter : Fin M → ℤ) :
    Fin componentGeneratorCount → MvPolynomial (Fin N) ℤ :=
  fun j ↦ specializeRelativeIntegralAffinePolynomial parameter
    (data.componentGenerator j)

/-- The ideal generated by the specialized component equations. -/
def RelativePersistentSurfaceStratumSyzygy.specializedComponentIdeal
    {M N equationCount clearingCount componentGeneratorCount
      stratumEquationCount : ℕ}
    (data : RelativePersistentSurfaceStratumSyzygy M N equationCount
      clearingCount componentGeneratorCount stratumEquationCount)
    (parameter : Fin M → ℤ) : Ideal (MvPolynomial (Fin N) ℤ) :=
  Ideal.span (Set.range (data.specializedComponentGenerator parameter))

/-- The ideal generated by the specialized local equations. -/
def RelativePersistentSurfaceStratumSyzygy.specializedEquationIdeal
    {M N equationCount clearingCount componentGeneratorCount
      stratumEquationCount : ℕ}
    (data : RelativePersistentSurfaceStratumSyzygy M N equationCount
      clearingCount componentGeneratorCount stratumEquationCount)
    (parameter : Fin M → ℤ) : Ideal (MvPolynomial (Fin N) ℤ) :=
  Ideal.span (Set.range
    (data.toRelativePersistentSurfaceChart.specializedEquations parameter))

/-- A lifted stratum equation specializes to zero at every integral point of
the stratum. -/
theorem RelativePersistentSurfaceStratumSyzygy.specialize_lift_stratumEquation
    {M N equationCount clearingCount componentGeneratorCount
      stratumEquationCount : ℕ}
    (data : RelativePersistentSurfaceStratumSyzygy M N equationCount
      clearingCount componentGeneratorCount stratumEquationCount)
    (parameter : Fin M → ℤ) (hparameter : data.OnStratum parameter)
    (r : Fin stratumEquationCount) :
    specializeRelativeIntegralAffinePolynomial parameter
        (liftRelativeIntegralParameterPolynomial (N := N)
          (data.stratumEquation r)) =
      (0 : MvPolynomial (Fin N) ℤ) := by
  simp [specializeRelativeIntegralAffinePolynomial,
    liftRelativeIntegralParameterPolynomial, hparameter r]

/-- The displayed equation-in-component syzygy becomes an exact identity
after specialization to the stratum. -/
theorem RelativePersistentSurfaceStratumSyzygy.specialized_equation_syzygy
    {M N equationCount clearingCount componentGeneratorCount
      stratumEquationCount : ℕ}
    (data : RelativePersistentSurfaceStratumSyzygy M N equationCount
      clearingCount componentGeneratorCount stratumEquationCount)
    (parameter : Fin M → ℤ) (hparameter : data.OnStratum parameter)
    (i : Fin equationCount) :
    data.toRelativePersistentSurfaceChart.specializedEquations parameter i =
      ∑ j, specializeRelativeIntegralAffinePolynomial parameter
          (data.equationInComponentCoefficient i j) *
        data.specializedComponentGenerator parameter j := by
  have h := congrArg
    (specializeRelativeIntegralAffinePolynomial parameter)
    (data.equation_syzygy i)
  simpa [RelativePersistentSurfaceChart.specializedEquations,
    RelativePersistentSurfaceStratumSyzygy.specializedComponentGenerator,
    map_sum, data.specialize_lift_stratumEquation parameter hparameter] using h

/-- The displayed colon syzygy becomes an exact clearing identity after
specialization to the stratum. -/
theorem RelativePersistentSurfaceStratumSyzygy.specialized_clearing_syzygy
    {M N equationCount clearingCount componentGeneratorCount
      stratumEquationCount : ℕ}
    (data : RelativePersistentSurfaceStratumSyzygy M N equationCount
      clearingCount componentGeneratorCount stratumEquationCount)
    (parameter : Fin M → ℤ) (hparameter : data.OnStratum parameter)
    (mark : Fin clearingCount) (j : Fin componentGeneratorCount) :
    data.toRelativePersistentSurfaceChart.specializedClearingPolynomial
          parameter mark * data.specializedComponentGenerator parameter j =
      ∑ i, specializeRelativeIntegralAffinePolynomial parameter
          (data.clearingInEquationCoefficient mark j i) *
        data.toRelativePersistentSurfaceChart.specializedEquations parameter i := by
  have h := congrArg
    (specializeRelativeIntegralAffinePolynomial parameter)
    (data.clearing_syzygy mark j)
  simpa [RelativePersistentSurfaceChart.specializedEquations,
    RelativePersistentSurfaceChart.specializedClearingPolynomial,
    RelativePersistentSurfaceStratumSyzygy.specializedComponentGenerator,
    map_sum, data.specialize_lift_stratumEquation parameter hparameter] using h

/-- The specialized local-equation ideal is contained in the specialized
component ideal. -/
theorem RelativePersistentSurfaceStratumSyzygy.specializedEquationIdeal_le
    {M N equationCount clearingCount componentGeneratorCount
      stratumEquationCount : ℕ}
    (data : RelativePersistentSurfaceStratumSyzygy M N equationCount
      clearingCount componentGeneratorCount stratumEquationCount)
    (parameter : Fin M → ℤ) (hparameter : data.OnStratum parameter) :
    data.specializedEquationIdeal parameter ≤
      data.specializedComponentIdeal parameter := by
  apply Ideal.span_le.mpr
  rintro _ ⟨i, rfl⟩
  rw [data.specialized_equation_syzygy parameter hparameter i]
  apply Ideal.sum_mem
  intro j _
  exact (data.specializedComponentIdeal parameter).mul_mem_left _
    (Ideal.subset_span (Set.mem_range_self j))

/-- Multiplication by any displayed clearing polynomial sends the whole
specialized component ideal into the specialized local-equation ideal. -/
theorem RelativePersistentSurfaceStratumSyzygy.specializedClearing_mul_mem
    {M N equationCount clearingCount componentGeneratorCount
      stratumEquationCount : ℕ}
    (data : RelativePersistentSurfaceStratumSyzygy M N equationCount
      clearingCount componentGeneratorCount stratumEquationCount)
    (parameter : Fin M → ℤ) (hparameter : data.OnStratum parameter)
    (mark : Fin clearingCount) :
    ∀ f ∈ data.specializedComponentIdeal parameter,
      data.toRelativePersistentSurfaceChart.specializedClearingPolynomial
          parameter mark * f ∈ data.specializedEquationIdeal parameter := by
  let I := data.specializedEquationIdeal parameter
  let J := data.specializedComponentIdeal parameter
  let u := data.toRelativePersistentSurfaceChart.specializedClearingPolynomial
    parameter mark
  have hgenerator : ∀ j : Fin componentGeneratorCount,
      u * data.specializedComponentGenerator parameter j ∈ I := by
    intro j
    rw [data.specialized_clearing_syzygy parameter hparameter mark j]
    apply Ideal.sum_mem
    intro i _
    exact I.mul_mem_left _ (Ideal.subset_span (Set.mem_range_self i))
  intro f hf
  change f ∈ Ideal.span
    (Set.range (data.specializedComponentGenerator parameter)) at hf
  refine Submodule.span_induction
    (p := fun f (_ : f ∈ Submodule.span
      (MvPolynomial (Fin N) ℤ)
      (Set.range (data.specializedComponentGenerator parameter))) ↦
        u * f ∈ I)
    ?gen ?zero ?add ?smul hf
  · rintro _ ⟨j, rfl⟩
    exact hgenerator j
  · simp
  · intro f g _ _ hf hg
    simpa [mul_add] using I.add_mem hf hg
  · intro a f _ hf
    simpa [mul_assoc, mul_left_comm] using I.mul_mem_left a hf

/-- Insert the principal parameter denominator into every clearing
polynomial.  This is the chart whose certificates exclude all primes at
which the spread-out model itself may fail. -/
def RelativePersistentSurfaceStratumSyzygy.denominatorAugmentedChart
    {M N equationCount clearingCount componentGeneratorCount
      stratumEquationCount : ℕ}
    (data : RelativePersistentSurfaceStratumSyzygy M N equationCount
      clearingCount componentGeneratorCount stratumEquationCount) :
    RelativePersistentSurfaceChart M N equationCount clearingCount where
  equation := data.toRelativePersistentSurfaceChart.equation
  selectedVar := data.toRelativePersistentSurfaceChart.selectedVar
  selectedVar_injective :=
    data.toRelativePersistentSurfaceChart.selectedVar_injective
  clearingPolynomial := fun mark ↦
    liftRelativeIntegralParameterPolynomial data.parameterDenominator *
      data.toRelativePersistentSurfaceChart.clearingPolynomial mark

/-- The denominator-augmented clearing polynomial specializes to the
displayed integer parameter denominator times the original clearing
polynomial. -/
theorem RelativePersistentSurfaceStratumSyzygy.specialized_augmentedClearing
    {M N equationCount clearingCount componentGeneratorCount
      stratumEquationCount : ℕ}
    (data : RelativePersistentSurfaceStratumSyzygy M N equationCount
      clearingCount componentGeneratorCount stratumEquationCount)
    (parameter : Fin M → ℤ) (mark : Fin clearingCount) :
    data.denominatorAugmentedChart.specializedClearingPolynomial parameter mark =
      MvPolynomial.C (MvPolynomial.eval parameter data.parameterDenominator) *
        data.toRelativePersistentSurfaceChart.specializedClearingPolynomial
          parameter mark := by
  simp [RelativePersistentSurfaceStratumSyzygy.denominatorAugmentedChart,
    RelativePersistentSurfaceChart.specializedClearingPolynomial,
    specializeRelativeIntegralAffinePolynomial,
    liftRelativeIntegralParameterPolynomial]

/-- At a point where the original clearing polynomial and the parameter
denominator are nonzero, the augmented clearing polynomial is nonzero. -/
theorem RelativePersistentSurfaceStratumSyzygy.eval_augmentedClearing_ne_zero
    {M N equationCount clearingCount componentGeneratorCount
      stratumEquationCount : ℕ}
    (data : RelativePersistentSurfaceStratumSyzygy M N equationCount
      clearingCount componentGeneratorCount stratumEquationCount)
    (parameter : Fin M → ℤ) (point : Fin N → ℤ)
    (mark : Fin clearingCount) (hdenominator : data.InDenominatorOpen parameter)
    (hclearing : MvPolynomial.eval point
      (data.toRelativePersistentSurfaceChart.specializedClearingPolynomial
        parameter mark) ≠ 0) :
    MvPolynomial.eval point
      (data.denominatorAugmentedChart.specializedClearingPolynomial
        parameter mark) ≠ 0 := by
  rw [data.specialized_augmentedClearing parameter mark, map_mul,
    MvPolynomial.eval_C]
  exact mul_ne_zero hdenominator hclearing

/-- The denominator-augmented clearing polynomial still clears the whole
specialized component ideal. -/
theorem RelativePersistentSurfaceStratumSyzygy.specializedAugmentedClearing_mul_mem
    {M N equationCount clearingCount componentGeneratorCount
      stratumEquationCount : ℕ}
    (data : RelativePersistentSurfaceStratumSyzygy M N equationCount
      clearingCount componentGeneratorCount stratumEquationCount)
    (parameter : Fin M → ℤ) (hparameter : data.OnStratum parameter)
    (mark : Fin clearingCount) :
    ∀ f ∈ data.specializedComponentIdeal parameter,
      data.denominatorAugmentedChart.specializedClearingPolynomial
          parameter mark * f ∈ data.specializedEquationIdeal parameter := by
  intro f hf
  rw [data.specialized_augmentedClearing parameter mark]
  rw [mul_assoc]
  exact (data.specializedEquationIdeal parameter).mul_mem_left _
    (data.specializedClearing_mul_mem parameter hparameter mark f hf)

/-- A convenient stronger special case: if multiplication by one copy of
the evaluated parameter denominator carries `K` into the displayed
generator ideal, then the denominator-augmented clearing polynomial clears
all of `K`.  Equality after localization alone gives elementwise powers,
not this exponent-one hypothesis; the pointwise-power theorem below handles
that exact situation. -/
theorem RelativePersistentSurfaceStratumSyzygy.specializedAugmentedClearing_mul_mem_of_denominator
    {M N equationCount clearingCount componentGeneratorCount
      stratumEquationCount : ℕ}
    (data : RelativePersistentSurfaceStratumSyzygy M N equationCount
      clearingCount componentGeneratorCount stratumEquationCount)
    (parameter : Fin M → ℤ) (hparameter : data.OnStratum parameter)
    (mark : Fin clearingCount) (K : Ideal (MvPolynomial (Fin N) ℤ))
    (hdenominatorClear : ∀ f ∈ K,
      MvPolynomial.C (MvPolynomial.eval parameter data.parameterDenominator) *
          f ∈ data.specializedComponentIdeal parameter) :
    ∀ f ∈ K,
      data.denominatorAugmentedChart.specializedClearingPolynomial
          parameter mark * f ∈ data.specializedEquationIdeal parameter := by
  intro f hf
  rw [data.specialized_augmentedClearing parameter mark]
  have h := data.specializedClearing_mul_mem parameter hparameter mark
    (MvPolynomial.C (MvPolynomial.eval parameter data.parameterDenominator) * f)
    (hdenominatorClear f hf)
  simpa [mul_assoc, mul_left_comm, mul_comm] using h

/-- Pointwise powers of one element which clear a finitely generated ideal
admit one common exponent.  The exponent is chosen only after the ideal and
the specialization are fixed; no uniform exponent is asserted. -/
theorem exists_common_power_mul_mem_of_pointwise_power
    {R : Type*} [CommRing R] [IsNoetherian R R]
    (I J : Ideal R) (a : R)
    (hclear : ∀ x ∈ J, ∃ e : ℕ, a ^ e * x ∈ I) :
    ∃ E : ℕ, ∀ x ∈ J, a ^ E * x ∈ I := by
  classical
  obtain ⟨n, f, hf⟩ :=
    Submodule.fg_iff_exists_fin_generating_family.mp
      (IsNoetherian.noetherian J)
  have hgenerator : ∀ i : Fin n, ∃ e : ℕ, a ^ e * f i ∈ I := by
    intro i
    apply hclear (f i)
    rw [← hf]
    exact Submodule.subset_span (Set.mem_range_self i)
  choose e he using hgenerator
  refine ⟨∑ i, e i, ?_⟩
  intro x hx
  apply power_sum_mul_mem_of_mem_span_range I f a e he
  change x ∈ Submodule.span R (Set.range f)
  rw [hf]
  exact hx

/-- A prime avoiding `(d*g)*m` also avoids `(d^E*g)*m`.  This is the
elementary observation which allows a fibrewise common localization power
without enlarging the public bad-prime certificate. -/
theorem not_dvd_natAbs_powered_first_factor
    {p : ℕ} (hp : p.Prime) (d g m : ℤ) (E : ℕ)
    (h : ¬ p ∣ ((d * g) * m).natAbs) :
    ¬ p ∣ ((d ^ E * g) * m).natAbs := by
  simp only [Int.natAbs_mul, Int.natAbs_pow] at h ⊢
  intro hnew
  apply h
  rw [hp.dvd_mul] at hnew ⊢
  rcases hnew with hdg | hm
  · left
    rw [hp.dvd_mul] at hdg ⊢
    rcases hdg with hdE | hg
    · exact Or.inl (hp.dvd_of_dvd_pow hdE)
    · exact Or.inr hg
  · exact Or.inr hm

/-- General localization lemma used by the relative chart adapter. -/
theorem localized_cast_ideal_eq_of_clearing
    {N : ℕ} (I J : Ideal (MvPolynomial (Fin N) ℤ))
    (u : MvPolynomial (Fin N) ℤ) (point : Fin N → ℤ)
    (hIJ : I ≤ J) (hclear : ∀ f ∈ J, u * f ∈ I)
    (hu : MvPolynomial.eval point u ≠ 0) :
    Ideal.map
        (algebraMap (MvPolynomial (Fin N) ℚ)
          (Localization.AtPrime
            (RingHom.ker
              (MvPolynomial.eval (fun j ↦ (point j : ℚ))))))
        (Ideal.map (MvPolynomial.map (Int.castRingHom ℚ)) I) =
      Ideal.map
        (algebraMap (MvPolynomial (Fin N) ℚ)
          (Localization.AtPrime
            (RingHom.ker
              (MvPolynomial.eval (fun j ↦ (point j : ℚ))))))
        (Ideal.map (MvPolynomial.map (Int.castRingHom ℚ)) J) := by
  let φ : MvPolynomial (Fin N) ℤ →+* MvPolynomial (Fin N) ℚ :=
    MvPolynomial.map (Int.castRingHom ℚ)
  let P : Ideal (MvPolynomial (Fin N) ℚ) :=
    RingHom.ker (MvPolynomial.eval (fun j ↦ (point j : ℚ)))
  let R := Localization.AtPrime P
  have hmapIJ : Ideal.map φ I ≤ Ideal.map φ J := Ideal.map_mono hIJ
  have hspan₀ : Ideal.span {u} * J ≤ I := by
    rw [Ideal.span_singleton_mul_le_iff]
    exact hclear
  have hspan : Ideal.map φ (Ideal.span {u}) * Ideal.map φ J ≤
      Ideal.map φ I := by
    rw [← Ideal.map_mul]
    exact Ideal.map_mono hspan₀
  have hmapClear : ∀ f ∈ Ideal.map φ J,
      φ u * f ∈ Ideal.map φ I := by
    intro f hf
    apply hspan
    exact Ideal.mul_mem_mul
      (Ideal.mem_map_of_mem φ (Ideal.subset_span (by simp))) hf
  have huEval : MvPolynomial.eval (fun j ↦ (point j : ℚ)) (φ u) ≠ 0 := by
    rw [eval_map_intCast]
    exact_mod_cast hu
  have huP : φ u ∉ P := fun huP ↦ huEval (RingHom.mem_ker.mp huP)
  apply le_antisymm
  · exact Ideal.map_mono hmapIJ
  · rw [Ideal.map_le_iff_le_comap]
    intro f hf
    rw [Ideal.mem_comap]
    let us : P.primeCompl := ⟨φ u, huP⟩
    have huUnit : IsUnit (algebraMap (MvPolynomial (Fin N) ℚ) R (φ u)) :=
      IsLocalization.map_units R us
    rw [← Ideal.unit_mul_mem_iff_mem
      (Ideal.map (algebraMap (MvPolynomial (Fin N) ℚ) R)
        (Ideal.map φ I)) huUnit]
    rw [← map_mul]
    exact Ideal.mem_map_of_mem _ (hmapClear f hf)

/-- Exact equality of the specialized equation and component ideals in the
local ring at a point covered by one fixed principal-open chart. -/
theorem RelativePersistentSurfaceStratumSyzygy.specializedIdeals_eq_atPoint
    {M N equationCount clearingCount componentGeneratorCount
      stratumEquationCount : ℕ}
    (data : RelativePersistentSurfaceStratumSyzygy M N equationCount
      clearingCount componentGeneratorCount stratumEquationCount)
    (parameter : Fin M → ℤ) (hparameter : data.OnStratum parameter)
    (point : Fin N → ℤ) (mark : Fin clearingCount)
    (hdenominator : data.InDenominatorOpen parameter)
    (hclearing : MvPolynomial.eval point
      (data.toRelativePersistentSurfaceChart.specializedClearingPolynomial
        parameter mark) ≠ 0) :
    Ideal.map
        (algebraMap (MvPolynomial (Fin N) ℚ)
          (Localization.AtPrime
            (RingHom.ker
              (MvPolynomial.eval (fun j ↦ (point j : ℚ))))))
        (Ideal.map (MvPolynomial.map (Int.castRingHom ℚ))
          (data.specializedEquationIdeal parameter)) =
      Ideal.map
        (algebraMap (MvPolynomial (Fin N) ℚ)
          (Localization.AtPrime
            (RingHom.ker
              (MvPolynomial.eval (fun j ↦ (point j : ℚ))))))
        (Ideal.map (MvPolynomial.map (Int.castRingHom ℚ))
          (data.specializedComponentIdeal parameter)) := by
  exact localized_cast_ideal_eq_of_clearing
    (data.specializedEquationIdeal parameter)
    (data.specializedComponentIdeal parameter)
    (data.denominatorAugmentedChart.specializedClearingPolynomial
      parameter mark)
    point
    (data.specializedEquationIdeal_le parameter hparameter)
    (data.specializedAugmentedClearing_mul_mem parameter hparameter mark)
    (data.eval_augmentedClearing_ne_zero parameter point mark
      hdenominator hclearing)

/-- Local equality with an arbitrary integral component model which is
identified with the fixed specialized generator ideal after the displayed
parameter denominator is inverted.  The hypothesis is the exact
elementwise-power formulation of that localized equality. -/
theorem RelativePersistentSurfaceStratumSyzygy.specializedEquationIdeal_eq_componentModel_atPoint
    {M N equationCount clearingCount componentGeneratorCount
      stratumEquationCount : ℕ}
    (data : RelativePersistentSurfaceStratumSyzygy M N equationCount
      clearingCount componentGeneratorCount stratumEquationCount)
    (parameter : Fin M → ℤ) (hparameter : data.OnStratum parameter)
    (point : Fin N → ℤ) (mark : Fin clearingCount)
    (hdenominator : data.InDenominatorOpen parameter)
    (hclearing : MvPolynomial.eval point
      (data.toRelativePersistentSurfaceChart.specializedClearingPolynomial
        parameter mark) ≠ 0)
    (K : Ideal (MvPolynomial (Fin N) ℤ))
    (hcomponentLe : data.specializedComponentIdeal parameter ≤ K)
    (hdenominatorPowerClear : ∀ f ∈ K, ∃ e : ℕ,
      MvPolynomial.C (MvPolynomial.eval parameter data.parameterDenominator) ^ e *
          f ∈ data.specializedComponentIdeal parameter) :
    Ideal.map
        (algebraMap (MvPolynomial (Fin N) ℚ)
          (Localization.AtPrime
            (RingHom.ker
              (MvPolynomial.eval (fun j ↦ (point j : ℚ))))))
        (Ideal.map (MvPolynomial.map (Int.castRingHom ℚ))
          (data.specializedEquationIdeal parameter)) =
      Ideal.map
        (algebraMap (MvPolynomial (Fin N) ℚ)
          (Localization.AtPrime
            (RingHom.ker
              (MvPolynomial.eval (fun j ↦ (point j : ℚ))))))
        (Ideal.map (MvPolynomial.map (Int.castRingHom ℚ)) K) := by
  let denominator : MvPolynomial (Fin N) ℤ :=
    MvPolynomial.C (MvPolynomial.eval parameter data.parameterDenominator)
  obtain ⟨E, hcommonPower⟩ :=
    exists_common_power_mul_mem_of_pointwise_power
      (data.specializedComponentIdeal parameter) K denominator
      hdenominatorPowerClear
  let poweredClearing : MvPolynomial (Fin N) ℤ :=
    denominator ^ E *
      data.toRelativePersistentSurfaceChart.specializedClearingPolynomial
        parameter mark
  have hclear : ∀ f ∈ K,
      poweredClearing * f ∈ data.specializedEquationIdeal parameter := by
    intro f hf
    have h := data.specializedClearing_mul_mem parameter hparameter mark
      (denominator ^ E * f) (hcommonPower f hf)
    simpa [poweredClearing, mul_assoc, mul_left_comm, mul_comm] using h
  have hu : MvPolynomial.eval point poweredClearing ≠ 0 := by
    simp only [poweredClearing, denominator, map_mul, map_pow,
      MvPolynomial.eval_C]
    exact mul_ne_zero (pow_ne_zero E hdenominator) hclearing
  exact localized_cast_ideal_eq_of_clearing
    (data.specializedEquationIdeal parameter) K
    poweredClearing
    point
    ((data.specializedEquationIdeal_le parameter hparameter).trans hcomponentLe)
    hclear hu

/-- A literal relative stratum chart with `c` local equations supplies the
exact multiplicity-one certificate in local dimension `N - c`.  The
geometric-model input is stated in its exact localized form: the fixed
specialized generator ideal is contained in the contracted integral affine
chart of `I`, and every element of the latter is carried back into the former
by some power of the evaluated parameter denominator.  Finite generation
selects one common power only after the fibre is fixed.  That power is used
inside the proof but does not enlarge the displayed bad-prime certificate.

This dimension-generic form is shared by the persistent surfaces (`c=N-2`)
and the persistent quotient curves (`c=N-1`). -/
theorem RelativePersistentSurfaceStratumSyzygy.specialized_multiplicityOne_of_denominatorModel_dimension
    {M N c clearingCount componentGeneratorCount stratumEquationCount : ℕ}
    (data : RelativePersistentSurfaceStratumSyzygy M N c
      clearingCount componentGeneratorCount stratumEquationCount)
    (parameter : Fin M → ℤ) (hparameter : data.OnStratum parameter)
    (hdenominator : data.InDenominatorOpen parameter)
    (I : Ideal (MvPolynomial (Fin (N + 1)) ℚ))
    (hcomponentLe : data.specializedComponentIdeal parameter ≤
      Ideal.map integralDehomogenizeAtZeroHom
        (projectiveIntegralClosureIdeal I))
    (hdenominatorPowerClear :
      ∀ f ∈ Ideal.map integralDehomogenizeAtZeroHom
          (projectiveIntegralClosureIdeal I),
        ∃ e : ℕ,
          MvPolynomial.C
                (MvPolynomial.eval parameter data.parameterDenominator) ^ e * f ∈
            data.specializedComponentIdeal parameter)
    (point : Fin N → ℤ)
    (hpoint : ∀ f ∈ Ideal.map rationalDehomogenizeAtZeroHom I,
      MvPolynomial.eval (fun i ↦ (point i : ℚ)) f = 0)
    (mark : Fin clearingCount)
    (hclearing : MvPolynomial.eval point
      (data.toRelativePersistentSurfaceChart.specializedClearingPolynomial
        parameter mark) ≠ 0)
    (hminor : MvPolynomial.eval point
      (selectedJacobianDeterminant
        (data.toRelativePersistentSurfaceChart.specializedEquations parameter)
        data.toRelativePersistentSurfaceChart.selectedVar) ≠ 0) :
    let Δ : ℤ := integralSelectedJacobianChartCertificate
      (data.denominatorAugmentedChart.specializedEquations parameter)
      data.denominatorAugmentedChart.selectedVar
      (data.denominatorAugmentedChart.specializedClearingPolynomial
        parameter mark) point
    Δ ≠ 0 ∧
      ∀ (p : ℕ) (hp : p.Prime), ¬p ∣ Δ.natAbs →
        HasHilbertSamuelMultiplicityAt hp
          (projectiveSpecialFiberIdeal I)
          (fun i ↦ (integralAffineProjectivePoint point i : ZMod p))
          (N - c) 1 := by
  let K : Ideal (MvPolynomial (Fin N) ℤ) :=
    Ideal.map integralDehomogenizeAtZeroHom
      (projectiveIntegralClosureIdeal I)
  let denominator : MvPolynomial (Fin N) ℤ :=
    MvPolynomial.C
      (MvPolynomial.eval parameter data.parameterDenominator)
  obtain ⟨E, hcommonPower⟩ :=
    exists_common_power_mul_mem_of_pointwise_power
      (data.specializedComponentIdeal parameter) K denominator
      hdenominatorPowerClear
  let poweredClearing : MvPolynomial (Fin N) ℤ :=
    denominator ^ E *
      data.toRelativePersistentSurfaceChart.specializedClearingPolynomial
        parameter mark
  have hpointIntegral :=
    integralAffineChart_point_of_rationalProjectivePoint I point hpoint
  have hIJ :=
    (data.specializedEquationIdeal_le parameter hparameter).trans hcomponentLe
  have hclear : ∀ f ∈ K,
      poweredClearing * f ∈ data.specializedEquationIdeal parameter := by
    intro f hf
    have h := data.specializedClearing_mul_mem parameter hparameter mark
      (denominator ^ E * f) (hcommonPower f hf)
    simpa [poweredClearing, mul_assoc, mul_left_comm, mul_comm] using h
  have hu : MvPolynomial.eval point poweredClearing ≠ 0 := by
    simp only [poweredClearing, denominator, map_mul, map_pow,
      MvPolynomial.eval_C]
    exact mul_ne_zero (pow_ne_zero E hdenominator) hclearing
  have hpowered :=
    hasHilbertSamuelMultiplicityAt_one_of_integral_localEquations
      (projectiveIntegralClosureIdeal I) point
      (data.denominatorAugmentedChart.specializedEquations parameter)
      data.denominatorAugmentedChart.selectedVar
      data.denominatorAugmentedChart.selectedVar_injective
      poweredClearing hpointIntegral hIJ hclear hu hminor
  have hdesired : integralSelectedJacobianChartCertificate
      (data.denominatorAugmentedChart.specializedEquations parameter)
      data.denominatorAugmentedChart.selectedVar
      (data.denominatorAugmentedChart.specializedClearingPolynomial
        parameter mark) point ≠ 0 :=
    mul_ne_zero
      (data.eval_augmentedClearing_ne_zero parameter point mark
        hdenominator hclearing) hminor
  refine ⟨hdesired, ?_⟩
  intro p hp hpDesired
  have hpPowered : ¬ p ∣
      (integralSelectedJacobianChartCertificate
        (data.denominatorAugmentedChart.specializedEquations parameter)
        data.denominatorAugmentedChart.selectedVar poweredClearing point).natAbs := by
    let d : ℤ := MvPolynomial.eval parameter data.parameterDenominator
    let g : ℤ := MvPolynomial.eval point
      (data.toRelativePersistentSurfaceChart.specializedClearingPolynomial
        parameter mark)
    let m : ℤ := MvPolynomial.eval point
      (selectedJacobianDeterminant
        (data.toRelativePersistentSurfaceChart.specializedEquations parameter)
        data.toRelativePersistentSurfaceChart.selectedVar)
    have haugEquations :
        data.denominatorAugmentedChart.specializedEquations parameter =
          data.toRelativePersistentSurfaceChart.specializedEquations parameter := rfl
    have haugSelected : data.denominatorAugmentedChart.selectedVar =
        data.toRelativePersistentSurfaceChart.selectedVar := rfl
    have hdesiredFormula :
        integralSelectedJacobianChartCertificate
          (data.denominatorAugmentedChart.specializedEquations parameter)
          data.denominatorAugmentedChart.selectedVar
          (data.denominatorAugmentedChart.specializedClearingPolynomial
            parameter mark) point = (d * g) * m := by
      rw [haugEquations, haugSelected, data.specialized_augmentedClearing]
      simp [integralSelectedJacobianChartCertificate, d, g, m]
    have hpoweredFormula :
        integralSelectedJacobianChartCertificate
          (data.denominatorAugmentedChart.specializedEquations parameter)
          data.denominatorAugmentedChart.selectedVar poweredClearing point =
            (d ^ E * g) * m := by
      rw [haugEquations, haugSelected]
      simp [integralSelectedJacobianChartCertificate, poweredClearing,
        denominator, d, g, m]
    rw [hpoweredFormula]
    apply not_dvd_natAbs_powered_first_factor hp d g m E
    simpa only [hdesiredFormula] using hpDesired
  simpa [Published.projectiveSpecialFiberIdeal] using
    hpowered.2 p hp hpPowered

/-- Surface specialization of the preceding dimension-generic theorem. -/
theorem RelativePersistentSurfaceStratumSyzygy.specialized_multiplicityOne_of_denominatorModel
    {M N clearingCount componentGeneratorCount stratumEquationCount : ℕ}
    (hN : 2 ≤ N)
    (data : RelativePersistentSurfaceStratumSyzygy M N (N - 2)
      clearingCount componentGeneratorCount stratumEquationCount)
    (parameter : Fin M → ℤ) (hparameter : data.OnStratum parameter)
    (hdenominator : data.InDenominatorOpen parameter)
    (I : Ideal (MvPolynomial (Fin (N + 1)) ℚ))
    (hcomponentLe : data.specializedComponentIdeal parameter ≤
      Ideal.map integralDehomogenizeAtZeroHom
        (projectiveIntegralClosureIdeal I))
    (hdenominatorPowerClear :
      ∀ f ∈ Ideal.map integralDehomogenizeAtZeroHom
          (projectiveIntegralClosureIdeal I),
        ∃ e : ℕ,
          MvPolynomial.C
                (MvPolynomial.eval parameter data.parameterDenominator) ^ e * f ∈
            data.specializedComponentIdeal parameter)
    (point : Fin N → ℤ)
    (hpoint : ∀ f ∈ Ideal.map rationalDehomogenizeAtZeroHom I,
      MvPolynomial.eval (fun i ↦ (point i : ℚ)) f = 0)
    (mark : Fin clearingCount)
    (hclearing : MvPolynomial.eval point
      (data.toRelativePersistentSurfaceChart.specializedClearingPolynomial
        parameter mark) ≠ 0)
    (hminor : MvPolynomial.eval point
      (selectedJacobianDeterminant
        (data.toRelativePersistentSurfaceChart.specializedEquations parameter)
        data.toRelativePersistentSurfaceChart.selectedVar) ≠ 0) :
    let Δ : ℤ := integralSelectedJacobianChartCertificate
      (data.denominatorAugmentedChart.specializedEquations parameter)
      data.denominatorAugmentedChart.selectedVar
      (data.denominatorAugmentedChart.specializedClearingPolynomial
        parameter mark) point
    Δ ≠ 0 ∧
      ∀ (p : ℕ) (hp : p.Prime), ¬p ∣ Δ.natAbs →
        HasHilbertSamuelMultiplicityAt hp
          (projectiveSpecialFiberIdeal I)
          (fun i ↦ (integralAffineProjectivePoint point i : ZMod p)) 2 1 := by
  simpa only [show N - (N - 2) = 2 by omega] using
    data.specialized_multiplicityOne_of_denominatorModel_dimension
      parameter hparameter hdenominator I hcomponentLe
      hdenominatorPowerClear point hpoint mark hclearing hminor

/-- Equality with the contracted integral component model is a convenient
special case of the denominator-cleared formulation. -/
theorem RelativePersistentSurfaceStratumSyzygy.specialized_multiplicityOne
    {M N clearingCount componentGeneratorCount stratumEquationCount : ℕ}
    (hN : 2 ≤ N)
    (data : RelativePersistentSurfaceStratumSyzygy M N (N - 2)
      clearingCount componentGeneratorCount stratumEquationCount)
    (parameter : Fin M → ℤ) (hparameter : data.OnStratum parameter)
    (hdenominator : data.InDenominatorOpen parameter)
    (I : Ideal (MvPolynomial (Fin (N + 1)) ℚ))
    (hcomponent : data.specializedComponentIdeal parameter =
      Ideal.map integralDehomogenizeAtZeroHom
        (projectiveIntegralClosureIdeal I))
    (point : Fin N → ℤ)
    (hpoint : ∀ f ∈ Ideal.map rationalDehomogenizeAtZeroHom I,
      MvPolynomial.eval (fun i ↦ (point i : ℚ)) f = 0)
    (mark : Fin clearingCount)
    (hclearing : MvPolynomial.eval point
      (data.toRelativePersistentSurfaceChart.specializedClearingPolynomial
        parameter mark) ≠ 0)
    (hminor : MvPolynomial.eval point
      (selectedJacobianDeterminant
        (data.toRelativePersistentSurfaceChart.specializedEquations parameter)
        data.toRelativePersistentSurfaceChart.selectedVar) ≠ 0) :
    let Δ : ℤ := integralSelectedJacobianChartCertificate
      (data.denominatorAugmentedChart.specializedEquations parameter)
      data.denominatorAugmentedChart.selectedVar
      (data.denominatorAugmentedChart.specializedClearingPolynomial
        parameter mark) point
    Δ ≠ 0 ∧
      ∀ (p : ℕ) (hp : p.Prime), ¬p ∣ Δ.natAbs →
        HasHilbertSamuelMultiplicityAt hp
          (projectiveSpecialFiberIdeal I)
          (fun i ↦ (integralAffineProjectivePoint point i : ZMod p)) 2 1 := by
  apply data.specialized_multiplicityOne_of_denominatorModel hN parameter
    hparameter hdenominator I
  · exact hcomponent.le
  · intro f hf
    refine ⟨0, ?_⟩
    simpa [hcomponent] using hf
  · exact hpoint
  · exact hclearing
  · exact hminor

/-- The elementary fixed-polynomial height estimate for the full
denominator-augmented certificate. -/
theorem RelativePersistentSurfaceStratumSyzygy.augmentedCertificateSize_for_mark
    {M N equationCount clearingCount componentGeneratorCount
      stratumEquationCount Y coordinateExponent : ℕ}
    (data : RelativePersistentSurfaceStratumSyzygy M N equationCount
      clearingCount componentGeneratorCount stratumEquationCount)
    (parameter : Fin M → ℤ) (X : Finset (Fin N → ℤ))
    (markOf : (Fin N → ℤ) → Fin clearingCount)
    (hparameter : ∀ j, (parameter j).natAbs ≤ Y)
    (hpoint : ∀ point ∈ X, ∀ j, (point j).natAbs ≤ Y)
    (H A : ℝ) (hH : 2 ≤ H)
    (hY : (Y : ℝ) ≤ H ^ coordinateExponent)
    (hA :
      (data.denominatorAugmentedChart.certificateHeightExponent
        coordinateExponent : ℝ) ≤ A) :
    ∀ point ∈ X,
      ((integralSelectedJacobianChartCertificate
        (data.denominatorAugmentedChart.specializedEquations parameter)
        data.denominatorAugmentedChart.selectedVar
        (data.denominatorAugmentedChart.specializedClearingPolynomial
          parameter (markOf point)) point).natAbs : ℝ) ≤ H ^ A := by
  intro point hpointX
  exact data.denominatorAugmentedChart.certificate_natAbs_cast_le_rpow
    parameter point hparameter (hpoint point hpointX) (markOf point)
      H A hH hY hA

end

end TranslatedDepthSeven
