import TranslatedDepthSeven.RelativePersistentMultiplicityCertificate
import TranslatedDepthSeven.IntegralLocalEquationMultiplicitySpecialization

/-!
# Specializing literal relative component charts

This file adds exactly the ideal-theoretic data needed in the persistent
surface application to the relative certificate chart.  A chart contains a
finite list of component generators and literal containment/clearing
identities in the polynomial ring over the parameter ring.  Because
specialization is a surjective coefficient homomorphism, these identities
specialize to the two ideal containments required by the integral
multiplicity-one theorem.

The statement neither constructs the relative component nor claims that its
specialization is an irreducible component.  Those are the remaining standard
algebraic-geometric spreading assertions.  Once a relative component model is
supplied, all assertions below are ordinary polynomial-ring algebra.
-/

namespace TranslatedDepthSeven

noncomputable section

open MvPolynomial Published

/-- One relative chart together with finite generators of the reduced
component model and explicit colon witnesses. -/
structure RelativePersistentSurfaceComponentChart
    (M N equationCount clearingCount componentGeneratorCount : ℕ)
    extends RelativePersistentSurfaceChart M N equationCount clearingCount where
  componentGenerator : Fin componentGeneratorCount →
    RelativeIntegralAffinePolynomial M N
  equationIdeal_le_componentIdeal :
    Ideal.span (Set.range toRelativePersistentSurfaceChart.equation) ≤
      Ideal.span (Set.range componentGenerator)
  clearing_mul_componentIdeal_le_equationIdeal :
    ∀ i, ∀ f ∈ Ideal.span (Set.range componentGenerator),
      toRelativePersistentSurfaceChart.clearingPolynomial i * f ∈
        Ideal.span (Set.range toRelativePersistentSurfaceChart.equation)

/-- The finite component-generator list after integral specialization of the
family parameters. -/
def RelativePersistentSurfaceComponentChart.specializedComponentGenerator
    {M N equationCount clearingCount componentGeneratorCount : ℕ}
    (chart : RelativePersistentSurfaceComponentChart M N equationCount
      clearingCount componentGeneratorCount)
    (parameter : Fin M → ℤ) :
    Fin componentGeneratorCount → MvPolynomial (Fin N) ℤ :=
  fun i ↦ specializeRelativeIntegralAffinePolynomial parameter
    (chart.componentGenerator i)

/-- The ideal generated by the specialized local equations. -/
def RelativePersistentSurfaceComponentChart.specializedEquationIdeal
    {M N equationCount clearingCount componentGeneratorCount : ℕ}
    (chart : RelativePersistentSurfaceComponentChart M N equationCount
      clearingCount componentGeneratorCount)
    (parameter : Fin M → ℤ) : Ideal (MvPolynomial (Fin N) ℤ) :=
  Ideal.span (Set.range
    (chart.toRelativePersistentSurfaceChart.specializedEquations parameter))

/-- The ideal generated by the specialized component equations. -/
def RelativePersistentSurfaceComponentChart.specializedComponentIdeal
    {M N equationCount clearingCount componentGeneratorCount : ℕ}
    (chart : RelativePersistentSurfaceComponentChart M N equationCount
      clearingCount componentGeneratorCount)
    (parameter : Fin M → ℤ) : Ideal (MvPolynomial (Fin N) ℤ) :=
  Ideal.span (Set.range (chart.specializedComponentGenerator parameter))

/-- Coefficient specialization is surjective, since integral constants give
a section. -/
theorem specializeRelativeIntegralAffinePolynomial_surjective
    {M N : ℕ} (parameter : Fin M → ℤ) :
    Function.Surjective
      (specializeRelativeIntegralAffinePolynomial parameter :
        RelativeIntegralAffinePolynomial M N →
          MvPolynomial (Fin N) ℤ) := by
  apply MvPolynomial.map_surjective
  intro z
  exact ⟨MvPolynomial.C z, by simp⟩

/-- Mapping the relative equation ideal is exactly the specialized equation
ideal. -/
theorem RelativePersistentSurfaceComponentChart.map_relativeEquationIdeal
    {M N equationCount clearingCount componentGeneratorCount : ℕ}
    (chart : RelativePersistentSurfaceComponentChart M N equationCount
      clearingCount componentGeneratorCount)
    (parameter : Fin M → ℤ) :
    Ideal.map (specializeRelativeIntegralAffinePolynomial parameter)
        (Ideal.span (Set.range
          chart.toRelativePersistentSurfaceChart.equation)) =
      chart.specializedEquationIdeal parameter := by
  exact map_span_range_mvPolynomial_map
    (MvPolynomial.eval parameter)
    chart.toRelativePersistentSurfaceChart.equation

/-- Mapping the relative component-generator ideal is exactly the
specialized component ideal. -/
theorem RelativePersistentSurfaceComponentChart.map_relativeComponentIdeal
    {M N equationCount clearingCount componentGeneratorCount : ℕ}
    (chart : RelativePersistentSurfaceComponentChart M N equationCount
      clearingCount componentGeneratorCount)
    (parameter : Fin M → ℤ) :
    Ideal.map (specializeRelativeIntegralAffinePolynomial parameter)
        (Ideal.span (Set.range chart.componentGenerator)) =
      chart.specializedComponentIdeal parameter := by
  exact map_span_range_mvPolynomial_map
    (MvPolynomial.eval parameter) chart.componentGenerator

/-- The relative containment of the equation ideal in the component ideal
specializes literally. -/
theorem RelativePersistentSurfaceComponentChart.specializedEquationIdeal_le
    {M N equationCount clearingCount componentGeneratorCount : ℕ}
    (chart : RelativePersistentSurfaceComponentChart M N equationCount
      clearingCount componentGeneratorCount)
    (parameter : Fin M → ℤ) :
    chart.specializedEquationIdeal parameter ≤
      chart.specializedComponentIdeal parameter := by
  rw [← chart.map_relativeEquationIdeal parameter,
    ← chart.map_relativeComponentIdeal parameter]
  exact Ideal.map_mono chart.equationIdeal_le_componentIdeal

/-- Every displayed relative colon witness continues to clear the whole
specialized component-generator ideal into the specialized equation ideal. -/
theorem RelativePersistentSurfaceComponentChart.specializedClearing_mul_mem
    {M N equationCount clearingCount componentGeneratorCount : ℕ}
    (chart : RelativePersistentSurfaceComponentChart M N equationCount
      clearingCount componentGeneratorCount)
    (parameter : Fin M → ℤ) (i : Fin clearingCount) :
    ∀ f ∈ chart.specializedComponentIdeal parameter,
      chart.toRelativePersistentSurfaceChart.specializedClearingPolynomial
          parameter i * f ∈
        chart.specializedEquationIdeal parameter := by
  intro f hf
  rw [← chart.map_relativeComponentIdeal parameter] at hf
  obtain ⟨g, hg, hgf⟩ :=
    (Ideal.mem_map_iff_of_surjective
      (specializeRelativeIntegralAffinePolynomial parameter)
      (specializeRelativeIntegralAffinePolynomial_surjective parameter)).mp hf
  subst f
  change
    specializeRelativeIntegralAffinePolynomial parameter
          (chart.toRelativePersistentSurfaceChart.clearingPolynomial i) *
        specializeRelativeIntegralAffinePolynomial parameter g ∈
      chart.specializedEquationIdeal parameter
  rw [← map_mul, ← chart.map_relativeEquationIdeal parameter]
  exact Ideal.mem_map_of_mem _
    (chart.clearing_mul_componentIdeal_le_equationIdeal i g hg)

/-- If the supplied relative component model specializes to the contracted
integral affine chart of `I`, the two literal ideal hypotheses required by
the persistent-surface theorem follow immediately. -/
theorem RelativePersistentSurfaceComponentChart.specialized_component_hypotheses
    {M N equationCount clearingCount componentGeneratorCount : ℕ}
    (chart : RelativePersistentSurfaceComponentChart M N equationCount
      clearingCount componentGeneratorCount)
    (parameter : Fin M → ℤ)
    (I : Ideal (MvPolynomial (Fin (N + 1)) ℚ))
    (hcomponent : chart.specializedComponentIdeal parameter =
      Ideal.map integralDehomogenizeAtZeroHom
        (projectiveIntegralClosureIdeal I)) :
    Ideal.span (Set.range
        (chart.toRelativePersistentSurfaceChart.specializedEquations
          parameter)) ≤
        Ideal.map integralDehomogenizeAtZeroHom
          (projectiveIntegralClosureIdeal I) ∧
      ∀ i, ∀ f ∈ Ideal.map integralDehomogenizeAtZeroHom
          (projectiveIntegralClosureIdeal I),
        (chart.toRelativePersistentSurfaceChart.specializedClearingPolynomial
            parameter i) * f ∈
          Ideal.span (Set.range
            (chart.toRelativePersistentSurfaceChart.specializedEquations
              parameter)) := by
  rw [← hcomponent]
  exact ⟨chart.specializedEquationIdeal_le parameter,
    chart.specializedClearing_mul_mem parameter⟩

/-- At a point where a displayed clearing polynomial is nonzero, the
specialized local-equation and component-generator ideals have equal
extensions to the local ring of that point.  This supplies the literal
`hatPoint` hypothesis used by the persistent-surface record theorem. -/
theorem RelativePersistentSurfaceComponentChart.specializedIdeals_eq_atPoint
    {M N equationCount clearingCount componentGeneratorCount : ℕ}
    (chart : RelativePersistentSurfaceComponentChart M N equationCount
      clearingCount componentGeneratorCount)
    (parameter : Fin M → ℤ) (point : Fin N → ℤ)
    (i : Fin clearingCount)
    (hclearing : MvPolynomial.eval point
      (chart.toRelativePersistentSurfaceChart.specializedClearingPolynomial
        parameter i) ≠ 0) :
    Ideal.map
        (algebraMap (MvPolynomial (Fin N) ℚ)
          (Localization.AtPrime
            (RingHom.ker
              (MvPolynomial.eval (fun j ↦ (point j : ℚ))))))
        (Ideal.map (MvPolynomial.map (Int.castRingHom ℚ))
          (chart.specializedEquationIdeal parameter)) =
      Ideal.map
        (algebraMap (MvPolynomial (Fin N) ℚ)
          (Localization.AtPrime
            (RingHom.ker
              (MvPolynomial.eval (fun j ↦ (point j : ℚ))))))
        (Ideal.map (MvPolynomial.map (Int.castRingHom ℚ))
          (chart.specializedComponentIdeal parameter)) := by
  let I₀ := chart.specializedEquationIdeal parameter
  let J₀ := chart.specializedComponentIdeal parameter
  let u := chart.toRelativePersistentSurfaceChart.specializedClearingPolynomial
    parameter i
  let φ : MvPolynomial (Fin N) ℤ →+* MvPolynomial (Fin N) ℚ :=
    MvPolynomial.map (Int.castRingHom ℚ)
  let P : Ideal (MvPolynomial (Fin N) ℚ) :=
    RingHom.ker (MvPolynomial.eval (fun j ↦ (point j : ℚ)))
  let R := Localization.AtPrime P
  have hIJ₀ : I₀ ≤ J₀ := chart.specializedEquationIdeal_le parameter
  have hIJ : Ideal.map φ I₀ ≤ Ideal.map φ J₀ := Ideal.map_mono hIJ₀
  have hspan₀ : Ideal.span {u} * J₀ ≤ I₀ := by
    rw [Ideal.span_singleton_mul_le_iff]
    exact chart.specializedClearing_mul_mem parameter i
  have hspan : Ideal.map φ (Ideal.span {u}) * Ideal.map φ J₀ ≤
      Ideal.map φ I₀ := by
    rw [← Ideal.map_mul]
    exact Ideal.map_mono hspan₀
  have hclear : ∀ f ∈ Ideal.map φ J₀,
      φ u * f ∈ Ideal.map φ I₀ := by
    intro f hf
    apply hspan
    exact Ideal.mul_mem_mul
      (Ideal.mem_map_of_mem φ (Ideal.subset_span (by simp))) hf
  have huEval : MvPolynomial.eval (fun j ↦ (point j : ℚ)) (φ u) ≠ 0 := by
    rw [eval_map_intCast]
    exact_mod_cast hclearing
  have huP : φ u ∉ P := fun hu ↦
    huEval (RingHom.mem_ker.mp hu)
  apply le_antisymm
  · exact Ideal.map_mono hIJ
  · rw [Ideal.map_le_iff_le_comap]
    intro f hf
    rw [Ideal.mem_comap]
    let us : P.primeCompl := ⟨φ u, huP⟩
    have huUnit : IsUnit (algebraMap (MvPolynomial (Fin N) ℚ) R (φ u)) :=
      IsLocalization.map_units R us
    rw [← Ideal.unit_mul_mem_iff_mem
      (Ideal.map (algebraMap (MvPolynomial (Fin N) ℚ) R)
        (Ideal.map φ I₀)) huUnit]
    rw [← map_mul]
    exact Ideal.mem_map_of_mem _ (hclear f hf)

/-- Component-model form of the preceding local equality, written exactly
with the rational affine component ideal occurring in
`exists_finite_persistentSurface_multiplicityOne_records`. -/
theorem RelativePersistentSurfaceComponentChart.specializedIdeals_eq_component_atPoint
    {M N equationCount clearingCount componentGeneratorCount : ℕ}
    (chart : RelativePersistentSurfaceComponentChart M N equationCount
      clearingCount componentGeneratorCount)
    (parameter : Fin M → ℤ) (point : Fin N → ℤ)
    (i : Fin clearingCount)
    (I : Ideal (MvPolynomial (Fin (N + 1)) ℚ))
    (hcomponent : chart.specializedComponentIdeal parameter =
      Ideal.map integralDehomogenizeAtZeroHom
        (projectiveIntegralClosureIdeal I))
    (hclearing : MvPolynomial.eval point
      (chart.toRelativePersistentSurfaceChart.specializedClearingPolynomial
        parameter i) ≠ 0) :
    Ideal.map
        (algebraMap (MvPolynomial (Fin N) ℚ)
          (Localization.AtPrime
            (RingHom.ker
              (MvPolynomial.eval (fun j ↦ (point j : ℚ))))))
        (Ideal.map (MvPolynomial.map (Int.castRingHom ℚ))
          (Ideal.span (Set.range
            (chart.toRelativePersistentSurfaceChart.specializedEquations
              parameter)))) =
      Ideal.map
        (algebraMap (MvPolynomial (Fin N) ℚ)
          (Localization.AtPrime
            (RingHom.ker
              (MvPolynomial.eval (fun j ↦ (point j : ℚ))))))
        (Ideal.map rationalDehomogenizeAtZeroHom I) := by
  have hlocal := chart.specializedIdeals_eq_atPoint
    parameter point i hclearing
  rw [hcomponent,
    map_integralAffineChart_projectiveIntegralClosureIdeal I] at hlocal
  exact hlocal

/-- Pointwise form of the uniform certificate estimate, with the clearing
polynomial selected from the fixed finite relative menu.  Its conclusion is
the local-certificate size premise of the persistent-record construction,
with `menu i` instantiated by the specialized relative clearing polynomial. -/
theorem RelativePersistentSurfaceComponentChart.localCertificateSize_for_mark
    {M N equationCount clearingCount componentGeneratorCount Y
      coordinateExponent : ℕ}
    (chart : RelativePersistentSurfaceComponentChart M N equationCount
      clearingCount componentGeneratorCount)
    (parameter : Fin M → ℤ)
    (X : Finset (Fin N → ℤ))
    (markOf : (Fin N → ℤ) → Fin clearingCount)
    (hparameter : ∀ j, (parameter j).natAbs ≤ Y)
    (hpoint : ∀ point ∈ X, ∀ j, (point j).natAbs ≤ Y)
    (H A : ℝ) (hH : 2 ≤ H)
    (hY : (Y : ℝ) ≤ H ^ coordinateExponent)
    (hA :
      (chart.toRelativePersistentSurfaceChart.certificateHeightExponent
        coordinateExponent : ℝ) ≤ A) :
    ∀ point ∈ X,
      ((integralSelectedJacobianChartCertificate
        (chart.toRelativePersistentSurfaceChart.specializedEquations parameter)
        chart.toRelativePersistentSurfaceChart.selectedVar
        (chart.toRelativePersistentSurfaceChart.specializedClearingPolynomial
          parameter (markOf point))
        point).natAbs : ℝ) ≤ H ^ A := by
  intro point hpointX
  exact chart.toRelativePersistentSurfaceChart.certificate_natAbs_cast_le_rpow
    parameter point hparameter (hpoint point hpointX) (markOf point)
      H A hH hY hA

end

end TranslatedDepthSeven
