import Mathlib
import TranslatedDepthSeven.AffinePlaneMonomialDivisibility

/-!
# A concrete smooth-point p-adic determinant lemma

This file isolates the elementary local algebra behind the multiplicity-one
surface case of the p-adic determinant method.

For an integral affine point `y`, let

`J(p,y) = (p, X_i - y_i)`.

If `x` is congruent to `y` modulo `p`, evaluation at `x` sends `J(p,y)^e`
into `(p^e)`.  Hence an evaluation matrix whose `i`-th row belongs to
`J(p,y)^(weight i)` has determinant divisible by
`p^(sum_i weight i)`.  An actual row operation that is invertible modulo `p`
does not alter this conclusion.

The final statements instantiate this with the literal bivariate jet
monomials of weights

`0, 1, 1, 2, 2, 2, ...`.

Thus the complete block through degree `k`, together with `s` terms of the
next degree, contributes exactly

`affinePlaneMonomialWeight k + (k + 1) * s`.

This is the exact divisibility calculation after a regular system of two
parameters and a filtration-adapted family have been produced.  It does not
assert the remaining local-algebra theorem that an arbitrary family of
functions on a standard-smooth surface admits such an adapted family.
-/

namespace TranslatedDepthSeven

noncomputable section

open MvPolynomial
open scoped BigOperators

/-- The ideal generated by the coordinate differences `X i - y i`. -/
def affinePointIdeal {σ : Type*} (y : σ → ℤ) :
    Ideal (MvPolynomial σ ℤ) :=
  Ideal.span (Set.range fun i ↦ X i - C (y i))

/-- The ideal cutting out the residue class of `y` modulo `p`. -/
def affineResidueClassIdeal {σ : Type*} (p : ℤ) (y : σ → ℤ) :
    Ideal (MvPolynomial σ ℤ) :=
  Ideal.span (Set.insert (C p) (Set.range fun i ↦ X i - C (y i)))

/-- Evaluation at a point congruent to `y` modulo `p` maps the point ideal
into the principal ideal `(p)`. -/
theorem map_affinePointIdeal_eval_le_span {σ : Type*}
    (p : ℤ) (x y : σ → ℤ) (hxy : ∀ i, p ∣ x i - y i) :
    Ideal.map (eval₂Hom (RingHom.id ℤ) x) (affinePointIdeal y) ≤
      Ideal.span {p} := by
  rw [Ideal.map_le_iff_le_comap, affinePointIdeal, Ideal.span_le]
  rintro _ ⟨i, rfl⟩
  change eval₂Hom (RingHom.id ℤ) x (X i - C (y i)) ∈ Ideal.span {p}
  rw [Ideal.mem_span_singleton]
  simpa using hxy i

/-- Evaluation at a point congruent to `y` modulo `p` maps the full residue
class ideal `(p, X_i-y_i)` into `(p)`. -/
theorem map_affineResidueClassIdeal_eval_le_span {σ : Type*}
    (p : ℤ) (x y : σ → ℤ) (hxy : ∀ i, p ∣ x i - y i) :
    Ideal.map (eval₂Hom (RingHom.id ℤ) x) (affineResidueClassIdeal p y) ≤
      Ideal.span {p} := by
  rw [Ideal.map_le_iff_le_comap, affineResidueClassIdeal, Ideal.span_le]
  intro f hf
  rcases hf with (rfl | ⟨i, rfl⟩)
  · change eval₂Hom (RingHom.id ℤ) x (C p) ∈ Ideal.span {p}
    rw [Ideal.mem_span_singleton]
    simp
  · change eval₂Hom (RingHom.id ℤ) x (X i - C (y i)) ∈ Ideal.span {p}
    rw [Ideal.mem_span_singleton]
    simpa using hxy i

/-- A function in the `e`-th power of the point ideal takes values divisible
by `p^e` throughout the residue class. -/
theorem eval_dvd_pow_of_mem_affinePointIdeal_pow {σ : Type*}
    (p : ℤ) (x y : σ → ℤ) (hxy : ∀ i, p ∣ x i - y i)
    (e : ℕ) (f : MvPolynomial σ ℤ) (hf : f ∈ affinePointIdeal y ^ e) :
    p ^ e ∣ eval₂Hom (RingHom.id ℤ) x f := by
  have hfmap : eval₂Hom (RingHom.id ℤ) x f ∈
      Ideal.map (eval₂Hom (RingHom.id ℤ) x) (affinePointIdeal y ^ e) :=
    Ideal.mem_map_of_mem _ hf
  rw [Ideal.map_pow] at hfmap
  have hpow := pow_le_pow_left'
    (map_affinePointIdeal_eval_le_span p x y hxy) e
  have hmem : eval₂Hom (RingHom.id ℤ) x f ∈ Ideal.span {p} ^ e :=
    hpow hfmap
  rw [Ideal.span_singleton_pow, Ideal.mem_span_singleton] at hmem
  exact hmem

/-- A function in `J(p,y)^e` takes values divisible by `p^e` throughout the
residue class of `y`. -/
theorem eval_dvd_pow_of_mem_affineResidueClassIdeal_pow {σ : Type*}
    (p : ℤ) (x y : σ → ℤ) (hxy : ∀ i, p ∣ x i - y i)
    (e : ℕ) (f : MvPolynomial σ ℤ)
    (hf : f ∈ affineResidueClassIdeal p y ^ e) :
    p ^ e ∣ eval₂Hom (RingHom.id ℤ) x f := by
  have hfmap : eval₂Hom (RingHom.id ℤ) x f ∈
      Ideal.map (eval₂Hom (RingHom.id ℤ) x)
        (affineResidueClassIdeal p y ^ e) :=
    Ideal.mem_map_of_mem _ hf
  rw [Ideal.map_pow] at hfmap
  have hpow := pow_le_pow_left'
    (map_affineResidueClassIdeal_eval_le_span p x y hxy) e
  have hmem : eval₂Hom (RingHom.id ℤ) x f ∈ Ideal.span {p} ^ e :=
    hpow hfmap
  rw [Ideal.span_singleton_pow, Ideal.mem_span_singleton] at hmem
  exact hmem

/-- The integral evaluation matrix of a finite polynomial family. -/
def filteredPolynomialEvaluationMatrix {ι σ : Type*}
    (F : ι → MvPolynomial σ ℤ) (x : ι → σ → ℤ) : Matrix ι ι ℤ :=
  fun i j ↦ eval₂Hom (RingHom.id ℤ) (x j) (F i)

/-- Weighted powers of the point ideal give the sum of the weights in the
determinant valuation. -/
theorem affinePointFilteredEvaluation_det_dvd
    {ι σ : Type*} [Fintype ι] [DecidableEq ι]
    (p : ℤ) (y : σ → ℤ) (x : ι → σ → ℤ)
    (F : ι → MvPolynomial σ ℤ) (weight : ι → ℕ)
    (hx : ∀ j i, p ∣ x j i - y i)
    (hF : ∀ i, F i ∈ affinePointIdeal y ^ weight i) :
    p ^ (∑ i, weight i) ∣ (filteredPolynomialEvaluationMatrix F x).det := by
  have hdiv := prod_dvd_det_of_rows_dvd
    (filteredPolynomialEvaluationMatrix F x)
    (fun i ↦ p ^ weight i)
    (fun i j ↦ eval_dvd_pow_of_mem_affinePointIdeal_pow
      p (x j) y (hx j) (weight i) (F i) (hF i))
  simpa only [Finset.prod_pow_eq_pow_sum Finset.univ weight p] using hdiv

/-- Weighted powers of the full residue-class ideal give the sum of the
weights in the determinant valuation. -/
theorem affineResidueFilteredEvaluation_det_dvd
    {ι σ : Type*} [Fintype ι] [DecidableEq ι]
    (p : ℤ) (y : σ → ℤ) (x : ι → σ → ℤ)
    (F : ι → MvPolynomial σ ℤ) (weight : ι → ℕ)
    (hx : ∀ j i, p ∣ x j i - y i)
    (hF : ∀ i, F i ∈ affineResidueClassIdeal p y ^ weight i) :
    p ^ (∑ i, weight i) ∣ (filteredPolynomialEvaluationMatrix F x).det := by
  have hdiv := prod_dvd_det_of_rows_dvd
    (filteredPolynomialEvaluationMatrix F x)
    (fun i ↦ p ^ weight i)
    (fun i j ↦ eval_dvd_pow_of_mem_affineResidueClassIdeal_pow
      p (x j) y (hx j) (weight i) (F i) (hF i))
  simpa only [Finset.prod_pow_eq_pow_sum Finset.univ weight p] using hdiv

/-- The preceding integral divisibility as literal vanishing modulo `p^a`,
for every `a` not exceeding the sum of the filtration weights. -/
theorem affineResidueFilteredEvaluation_det_eq_zero_zmod
    {ι σ : Type*} [Fintype ι] [DecidableEq ι]
    {p : ℕ} (a : ℕ) (weight : ι → ℕ)
    (ha : a ≤ ∑ i, weight i)
    (y : σ → ℤ) (x : ι → σ → ℤ)
    (F : ι → MvPolynomial σ ℤ)
    (hx : ∀ j i, (p : ℤ) ∣ x j i - y i)
    (hF : ∀ i, F i ∈ affineResidueClassIdeal (p : ℤ) y ^ weight i) :
    ((filteredPolynomialEvaluationMatrix F x).det : ZMod (p ^ a)) = 0 := by
  rw [ZMod.intCast_zmod_eq_zero_iff_dvd]
  have hsmall : (p : ℤ) ^ a ∣ (p : ℤ) ^ (∑ i, weight i) :=
    pow_dvd_pow (p : ℤ) ha
  have hdiv := affineResidueFilteredEvaluation_det_dvd
    (p : ℤ) y x F weight hx hF
  simpa using hsmall.trans hdiv

/-- Actual integral row combinations of a finite polynomial family. -/
def rowCombinationPolynomials {ι σ : Type*} [Fintype ι]
    (U : Matrix ι ι ℤ) (F : ι → MvPolynomial σ ℤ) :
    ι → MvPolynomial σ ℤ :=
  fun i ↦ ∑ j, C (U i j) * F j

/-- Evaluation commutes with the displayed row operation. -/
theorem filteredPolynomialEvaluationMatrix_rowCombinationPolynomials
    {ι σ : Type*} [Fintype ι] [DecidableEq ι]
    (U : Matrix ι ι ℤ) (F : ι → MvPolynomial σ ℤ)
    (x : ι → σ → ℤ) :
    filteredPolynomialEvaluationMatrix (rowCombinationPolynomials U F) x =
      U * filteredPolynomialEvaluationMatrix F x := by
  ext i j
  simp [filteredPolynomialEvaluationMatrix, rowCombinationPolynomials,
    Matrix.mul_apply]

/-- A row operation invertible modulo `p` may be used to put the functions
into the residue-class filtration without changing the resulting p-adic
determinant bound. -/
theorem prime_pow_dvd_det_of_rowCombination_mem_affineResidueClassIdeal_pow
    {ι σ : Type*} [Fintype ι] [DecidableEq ι]
    {p : ℕ} (hp : p.Prime)
    (y : σ → ℤ) (x : ι → σ → ℤ)
    (F : ι → MvPolynomial σ ℤ) (weight : ι → ℕ)
    (U : Matrix ι ι ℤ)
    (hU : (U.map (Int.castRingHom (ZMod p))).det ≠ 0)
    (hx : ∀ j i, (p : ℤ) ∣ x j i - y i)
    (hF : ∀ i, rowCombinationPolynomials U F i ∈
      affineResidueClassIdeal (p : ℤ) y ^ weight i) :
    (p : ℤ) ^ (∑ i, weight i) ∣
      (filteredPolynomialEvaluationMatrix F x).det := by
  letI : Fact p.Prime := ⟨hp⟩
  have hUdet : ¬(p : ℤ) ∣ U.det := by
    intro hdvd
    apply hU
    have hmapdet : (U.map (Int.castRingHom (ZMod p))).det =
        ((U.det : ℤ) : ZMod p) := by
      simpa using ((Int.castRingHom (ZMod p)).map_det U).symm
    rw [hmapdet]
    exact (ZMod.intCast_zmod_eq_zero_iff_dvd U.det p).2 hdvd
  have hdiv := affineResidueFilteredEvaluation_det_dvd
    (p : ℤ) y x (rowCombinationPolynomials U F) weight hx hF
  rw [filteredPolynomialEvaluationMatrix_rowCombinationPolynomials,
    Matrix.det_mul] at hdiv
  exact (Nat.prime_iff_prime_int.mp hp).pow_dvd_of_dvd_mul_left
    (∑ i, weight i) hUdet hdiv

/-! ## The literal multiplicity-one surface jet block -/

/-- The shifted affine monomial
`(X₁-y₁)^a (X₂-y₂)^(j-a)` attached to the existing surface-monomial index. -/
def shiftedAffinePlaneMonomial (y : Fin 2 → ℤ) {k : ℕ}
    (u : AffinePlaneMonomialIndex k) : MvPolynomial (Fin 2) ℤ :=
  (X 0 - C (y 0)) ^ u.2.1 *
    (X 1 - C (y 1)) ^ (u.1.1 - u.2.1)

/-- The shifted monomial has its displayed affine order at `y`. -/
theorem shiftedAffinePlaneMonomial_mem_affinePointIdeal_pow
    (y : Fin 2 → ℤ) {k : ℕ} (u : AffinePlaneMonomialIndex k) :
    shiftedAffinePlaneMonomial y u ∈
      affinePointIdeal y ^ affinePlaneMonomialIndexWeight u := by
  have hzero : X 0 - C (y 0) ∈ affinePointIdeal y := by
    apply Ideal.subset_span
    exact Set.mem_range_self 0
  have hone : X 1 - C (y 1) ∈ affinePointIdeal y := by
    apply Ideal.subset_span
    exact Set.mem_range_self 1
  have hmul : shiftedAffinePlaneMonomial y u ∈
      affinePointIdeal y ^ (u.2.1 + (u.1.1 - u.2.1)) := by
    rw [pow_add]
    exact Ideal.mul_mem_mul (Ideal.pow_mem_pow hzero u.2.1)
      (Ideal.pow_mem_pow hone (u.1.1 - u.2.1))
  have hua : u.2.1 ≤ u.1.1 := Nat.lt_succ_iff.mp u.2.2
  simpa [affinePlaneMonomialIndexWeight, Nat.add_sub_of_le hua] using hmul

/-- A complete bivariate jet block through degree `k`, followed by `s`
monomials in degree `k + 1`. -/
abbrev AffinePlaneJetPacket (k s : ℕ) :=
  AffinePlaneMonomialIndex k ⊕ Fin s

/-- The m-adic order of a member of the displayed jet packet. -/
def affinePlaneJetPacketWeight {k s : ℕ} : AffinePlaneJetPacket k s → ℕ
  | Sum.inl u => affinePlaneMonomialIndexWeight u
  | Sum.inr _ => k + 1

/-- The exact number of terms in a complete block plus a partial next
layer. -/
theorem card_affinePlaneJetPacket (k s : ℕ) :
    Fintype.card (AffinePlaneJetPacket k s) =
      affinePlaneMonomialCount k + s := by
  rw [Fintype.card_sum, card_affinePlaneMonomialIndex, Fintype.card_fin]

/-- The exact sum of the bivariate jet orders. -/
theorem sum_affinePlaneJetPacketWeight (k s : ℕ) :
    (∑ u : AffinePlaneJetPacket k s, affinePlaneJetPacketWeight u) =
      affinePlaneMonomialWeight k + (k + 1) * s := by
  rw [show (∑ u : AffinePlaneJetPacket k s, affinePlaneJetPacketWeight u) =
      (∑ u : AffinePlaneMonomialIndex k,
        affinePlaneMonomialIndexWeight u) + ∑ _ : Fin s, (k + 1) by
    simp [AffinePlaneJetPacket, affinePlaneJetPacketWeight]]
  rw [sum_affinePlaneMonomialIndexWeight]
  simp [Nat.mul_comm]

/-- The literal shifted monomials in a complete block and a partial next
layer.  The inequality `s ≤ k + 2` is exactly the number of degree-`k+1`
monomials in two variables. -/
def shiftedAffinePlaneJetPacketMonomial
    (y : Fin 2 → ℤ) {k s : ℕ} :
    AffinePlaneJetPacket k s → MvPolynomial (Fin 2) ℤ
  | Sum.inl u => shiftedAffinePlaneMonomial y u
  | Sum.inr a =>
      (X 0 - C (y 0)) ^ a.val *
        (X 1 - C (y 1)) ^ (k + 1 - a.val)

/-- Every displayed jet monomial belongs to the power of the point ideal
given by its weight. -/
theorem shiftedAffinePlaneJetPacketMonomial_mem_affinePointIdeal_pow
    (y : Fin 2 → ℤ) {k s : ℕ} (hs : s ≤ k + 2)
    (u : AffinePlaneJetPacket k s) :
    shiftedAffinePlaneJetPacketMonomial y u ∈
      affinePointIdeal y ^ affinePlaneJetPacketWeight u := by
  rcases u with (u | a)
  · exact shiftedAffinePlaneMonomial_mem_affinePointIdeal_pow y u
  · have hzero : X 0 - C (y 0) ∈ affinePointIdeal y := by
      apply Ideal.subset_span
      exact Set.mem_range_self 0
    have hone : X 1 - C (y 1) ∈ affinePointIdeal y := by
      apply Ideal.subset_span
      exact Set.mem_range_self 1
    have ha : a.val ≤ k + 1 := by omega
    have hmul : (X 0 - C (y 0)) ^ a.val *
        (X 1 - C (y 1)) ^ (k + 1 - a.val) ∈
        affinePointIdeal y ^ (a.val + (k + 1 - a.val)) := by
      rw [pow_add]
      exact Ideal.mul_mem_mul (Ideal.pow_mem_pow hzero a.val)
        (Ideal.pow_mem_pow hone (k + 1 - a.val))
    simpa [shiftedAffinePlaneJetPacketMonomial,
      affinePlaneJetPacketWeight, Nat.add_sub_of_le ha] using hmul

/-- Exact p-adic divisibility of the literal multiplicity-one surface jet
evaluation determinant, including a partial final degree. -/
theorem shiftedAffinePlaneJetPacketEvaluation_det_dvd
    (k s : ℕ) (hs : s ≤ k + 2) (p : ℤ) (y : Fin 2 → ℤ)
    (x : AffinePlaneJetPacket k s → Fin 2 → ℤ)
    (hx : ∀ j i, p ∣ x j i - y i) :
    p ^ (affinePlaneMonomialWeight k + (k + 1) * s) ∣
      (filteredPolynomialEvaluationMatrix
        (shiftedAffinePlaneJetPacketMonomial y) x).det := by
  rw [← sum_affinePlaneJetPacketWeight]
  exact affinePointFilteredEvaluation_det_dvd p y x
    (shiftedAffinePlaneJetPacketMonomial y) affinePlaneJetPacketWeight hx
    (shiftedAffinePlaneJetPacketMonomial_mem_affinePointIdeal_pow y hs)

end

end TranslatedDepthSeven
