import TranslatedDepthSeven.ConcreteExceptionalRescaling
import TranslatedDepthSeven.ExplicitLineContribution
import TranslatedDepthSeven.GeometricPrimeness
import TranslatedDepthSeven.HomogeneousLinearElimination
import TranslatedDepthSeven.LinearPrimitiveElement
import TranslatedDepthSeven.RelativeDetectorCharts
import TranslatedDepthSeven.PilaSubpower
import TranslatedDepthSeven.PacketSectionHeightDomination
import TranslatedDepthSeven.PrimitiveTerminalLedger
import TranslatedDepthSeven.PublishedCountingTheorems
import Mathlib.RingTheory.Ideal.KrullsHeightTheorem
import Mathlib.RingTheory.UniqueFactorizationDomain.Ideal
import Mathlib.RingTheory.Polynomial.Resultant.Basic
import Mathlib.LinearAlgebra.Matrix.Charpoly.Minpoly
import Mathlib.RingTheory.Adjoin.PowerBasis
import Mathlib.RingTheory.TensorProduct.MvPolynomial
import Mathlib.RingTheory.Flat.FaithfullyFlat.Algebra

/-!
# The strict root statement

This file records the literal theorem which the development must prove and
closes the elementary normalization and final-exponent steps around it.  The
counted object is `depthSevenTranslatedPointFinset`; no supplied closed-piece
family, packet cover, terminal family, or branch estimate occurs here.

`strictTranslatedDepthSevenStatement` is only a proposition.  Giving it a
name does **not** assert that it has been proved.  Its four antecedents are
the exact separately stated published results which are permitted at the
external boundary.  All remaining antecedents describe the fixed input
fivefold itself: geometric integrality, projective dimension five, and its
degree.  In particular there is no geometric decomposition or counting
conclusion among the hypotheses.

The proved results in this file are:

* exact equality with the normalized displacement count at every counted
  base point, including a pointwise and a uniform equivalence;
* vacuity of the linear case, directly from the literal exceptional-locus
  definition;
* passage from the sharper exponent `94/21` to `449/100`.

The nonlinear estimate in `strictTranslatedDepthSevenStatement` remains the
root obligation.  It must not be manufactured from an assumed terminal
majorant.
-/

namespace TranslatedDepthSeven

noncomputable section

open scoped NNReal
open scoped TensorProduct

/-- The rational homogeneous ideal literally generated by the displayed
integral equations. -/
def rationalDepthSevenEquationIdeal
    (equations : Finset (MvPolynomial (Fin 13) ℤ)) :
    Ideal (MvPolynomial (Fin 13) ℚ) :=
  finiteEquationIdeal (rationalizedEquationFinset equations)

/-- `H = 2+B+L+m`, regarded as a nonnegative real. -/
def Parameters.strictHeight (p : Parameters) : NNReal :=
  ⟨p.H, p.H_pos.le⟩

/-- `T = 1+L/m`, regarded as a nonnegative real. -/
def Parameters.strictNormalizedSide (p : Parameters) : NNReal :=
  ⟨p.T, p.T_pos.le⟩

@[simp]
theorem Parameters.coe_strictHeight (p : Parameters) :
    (p.strictHeight : ℝ) = p.H := rfl

@[simp]
theorem Parameters.coe_strictNormalizedSide (p : Parameters) :
    (p.strictNormalizedSide : ℝ) = p.T := rfl

theorem Parameters.one_le_strictHeight (p : Parameters) :
    1 ≤ p.strictHeight := by
  exact_mod_cast p.five_le_H.trans' (by norm_num : (1 : ℝ) ≤ 5)

theorem Parameters.one_le_strictNormalizedSide (p : Parameters) :
    1 ≤ p.strictNormalizedSide := by
  exact_mod_cast p.one_le_T

theorem Parameters.strictNormalizedSide_le_strictHeight (p : Parameters) :
    p.strictNormalizedSide ≤ p.strictHeight := by
  exact_mod_cast p.T_le_H

/-- The precise strict root proposition.

The displayed integral generators are required individually to be
homogeneous.  Homogeneity of their generated rational ideal would not imply
this for an arbitrary chosen generating family, while the translated-cone
and Jacobian constructions use the individual degrees.

The existential integer `CF` is the fixed exponent in the Plücker-height
cutoff defining `Upsilon_H(Z)`.  It is chosen once from the fixed equation
family, before `ε` and before any translated box or residue class.  The
constant `C` may depend on the fixed equation family and on `ε`, but not on
`p`. -/
def strictTranslatedDepthSevenStatement : Prop :=
  Published.Pila1995TheoremA →
  Published.Salberger2007Corollary37 →
  Published.Salberger2023Theorem01 →
  Published.Salberger2023Theorem04 →
  ∀ (equations : Finset (MvPolynomial (Fin 13) ℤ)) (degree : ℕ),
    (∀ f ∈ equations, ∃ e : ℕ, f.IsHomogeneous e) →
    GeometricallyPrimeMvPolynomialIdeal
      (rationalDepthSevenEquationIdeal equations) →
    Published.IsIntegralProjectiveVariety
      (N := 12) (rationalDepthSevenEquationIdeal equations) 5 degree →
    ∃ CF : ℕ, ∀ ε : ℝ, 0 < ε →
      ∃ C : NNReal, ∀ p : Parameters,
        ((depthSevenTranslatedPointFinset p equations CF).card : NNReal) ≤
          powerEnvelope C p.strictHeight p.strictNormalizedSide
            targetExponent ε

/-- Direct coefficient-uniform curve specialization of Pila 1995,
Theorem A.  The constant is selected before the affine ideal, and Pila's
printed exponential factor is absorbed explicitly.  This is the precise
source result needed after a nonlinear curve occurrence has been rescaled
into an integral box. -/
theorem pila1995_curve_halfPower_uniform
    (hPila : Published.Pila1995TheoremA)
    (N d : ℕ) (hd : 2 ≤ d) (ε : ℝ) (hε : 0 < ε) :
    ∃ C : ℝ, 0 < C ∧
      ∀ (I : Ideal (MvPolynomial (Fin N) ℝ)),
        Published.HasAffineDimensionDegree I 1 d →
        ∀ U : ℝ, 1 < U →
          ((Published.pilaIntegralPoints I U).card : ℝ) ≤
            C * U ^ ((1 / 2 : ℝ) + ε) := by
  obtain ⟨c, hc, hsource⟩ := hPila 1 d N (by omega)
  let C : ℝ := c * pilaConstant d ε
  have hconstant : 0 < pilaConstant d ε := by
    unfold pilaConstant
    positivity
  refine ⟨C, mul_pos hc hconstant, ?_⟩
  intro I hI U hU
  have hprinted := hsource I
    (Published.HasAffineDimensionDegree.toHilbert hI) U hU
  have hUone : 1 ≤ U := hU.le
  have habsorb := pilaCurvePower_mul_factor_le_const_mul_rpow
    hd hε hUone
  calc
    ((Published.pilaIntegralPoints I U).card : ℝ) ≤
        c * U ^ ((d : ℝ)⁻¹) * pilaFactor d U := by
      simpa [pilaFactor] using hprinted
    _ = c * (U ^ ((d : ℝ)⁻¹) * pilaFactor d U) := by ring
    _ ≤ c * (pilaConstant d ε * U ^ ((1 / 2 : ℝ) + ε)) := by
      exact mul_le_mul_of_nonneg_left habsorb hc.le
    _ = C * U ^ ((1 / 2 : ℝ) + ε) := by
      simp only [C]
      ring

/-- Transfer the preceding Pila bound to a literal finite point set through
an injective integral-coordinate map.  The hypotheses are only the displayed
map and membership in Pila's actual source point set. -/
theorem finiteSet_card_le_pilaCurve_halfPower
    (hPila : Published.Pila1995TheoremA)
    {Point : Type*} [DecidableEq Point]
    (N d : ℕ) (hd : 2 ≤ d) (ε : ℝ) (hε : 0 < ε)
    (I : Ideal (MvPolynomial (Fin N) ℝ))
    (hI : Published.HasAffineDimensionDegree I 1 d)
    (U : ℝ) (hU : 1 < U)
    (points : Finset Point) (coordinate : Point → IntVector N)
    (hinjective : Set.InjOn coordinate (↑points : Set Point))
    (hcoordinate : ∀ x ∈ points,
      coordinate x ∈ Published.pilaIntegralPoints I U) :
    ∃ C : ℝ, 0 < C ∧
      (points.card : ℝ) ≤ C * U ^ ((1 / 2 : ℝ) + ε) := by
  classical
  obtain ⟨C, hC, hbound⟩ :=
    pila1995_curve_halfPower_uniform hPila N d hd ε hε
  refine ⟨C, hC, ?_⟩
  let image := points.image coordinate
  have hcard : image.card = points.card :=
    Finset.card_image_iff.mpr hinjective
  have hsubset : image ⊆ Published.pilaIntegralPoints I U := by
    intro z hz
    obtain ⟨x, hx, rfl⟩ := Finset.mem_image.mp hz
    exact hcoordinate x hx
  calc
    (points.card : ℝ) = (image.card : ℝ) := by rw [hcard]
    _ ≤ ((Published.pilaIntegralPoints I U).card : ℝ) := by
      exact_mod_cast Finset.card_le_card hsubset
    _ ≤ C * U ^ ((1 / 2 : ℝ) + ε) := hbound I hI U hU

/-- Direct finite-subset form of Salberger 2023, Theorem 0.1.  The source
constant is non-uniform in the fixed projective variety, exactly as in the
published theorem. -/
theorem finiteProjectivePointSet_card_le_salberger2023
    (hSalberger : Published.Salberger2023Theorem01)
    {N r d : ℕ}
    (I : Ideal (MvPolynomial (Fin (N + 1)) ℚ))
    (hI : Published.IsIntegralProjectiveVariety I r d)
    (hd : 2 ≤ d) (ε : ℝ) (hε : 0 < ε) :
    ∃ C : ℝ, 0 < C ∧ ∀ (B : ℝ), 1 ≤ B →
      ∀ S : Finset (Projectivization ℚ (Fin (N + 1) → ℚ)),
        (∀ x ∈ S, x ∈ Published.rationalProjectivePoints I B) →
        (S.card : ℝ) ≤ C * B ^ ((r : ℝ) + ε) := by
  obtain ⟨C, hC, hsource⟩ := hSalberger N r d I hI hd ε hε
  refine ⟨C, hC, ?_⟩
  intro B hB S hS
  obtain ⟨hfinite, hbound⟩ := hsource B hB
  have hsubset : (↑S : Set (Projectivization ℚ (Fin (N + 1) → ℚ))) ⊆
      Published.rationalProjectivePoints I B := by
    intro x hx
    exact hS x hx
  have hncard : S.card ≤
      (Published.rationalProjectivePoints I B).ncard := by
    simpa only [Set.ncard_coe_finset] using
      Set.ncard_le_ncard hsubset hfinite
  exact (by exact_mod_cast hncard :
    (S.card : ℝ) ≤
      ((Published.rationalProjectivePoints I B).ncard : ℝ)).trans hbound

/-- Bounded-fibre transfer of Salberger 2023, Theorem 0.4 to a literal
finite set.  This theorem performs all counting after a concrete projection
has been supplied; the remaining input is exactly the algebraic construction
of that projection and of the displayed absolutely irreducible top homogeneous part. -/
theorem finiteSet_card_le_salberger2023_affineHypersurface
    {Point : Type*} [DecidableEq Point]
    (hSalberger : Published.Salberger2023Theorem04)
    (N d D : ℕ) (hN : 3 ≤ N) (hd : d = 3 ∨ 4 ≤ d)
    (ε : ℝ) (hε : 0 < ε) :
    ∃ C : ℝ, 0 < C ∧
      ∀ (f : MvPolynomial (Fin N) ℤ)
        (topPart : MvPolynomial (Fin N) ℚ),
        Published.IsTopHomogeneousPart f topPart d →
        Published.IsAbsolutelyIrreducible topPart →
        ∀ (B : ℝ), 1 ≤ B →
          ∀ (points : Finset Point) (projection : Point → IntVector N),
            (∀ x ∈ points,
              projection x ∈ Published.affineHypersurfaceIntegerPoints f B) →
            (∀ z ∈ Published.affineHypersurfaceIntegerPoints f B,
              (points.filter fun x ↦ projection x = z).card ≤ D) →
            (points.card : ℝ) ≤
              C * B ^ Published.salberger2023AffineExponent N d ε := by
  obtain ⟨C₀, hC₀, hsource⟩ := hSalberger N d hN hd ε hε
  have hD : (0 : ℝ) < max 1 D := by positivity
  -- Using `max 1 D` keeps the displayed constant positive even when the
  -- supplied fibre bound is zero.
  let C' : ℝ := max 1 D * C₀
  refine ⟨C', mul_pos hD hC₀, ?_⟩
  intro f topPart htop hirred B hB points projection himage hfibre
  have hcardNat : points.card ≤
      (Published.affineHypersurfaceIntegerPoints f B).card * D :=
    finiteSet_card_le_index_card_mul_of_fibres
      points (Published.affineHypersurfaceIntegerPoints f B)
      projection D himage hfibre
  have hsourceBound := hsource f topPart htop hirred B hB
  have hcardReal : (points.card : ℝ) ≤
      (Published.affineHypersurfaceIntegerPoints f B).card * D := by
    exact_mod_cast hcardNat
  calc
    (points.card : ℝ) ≤
        (Published.affineHypersurfaceIntegerPoints f B).card * D := hcardReal
    _ ≤ (C₀ * B ^ Published.salberger2023AffineExponent N d ε) * D := by
      gcongr
    _ ≤ C' * B ^ Published.salberger2023AffineExponent N d ε := by
      dsimp only [C']
      have hDle : (D : ℝ) ≤ max 1 D := by
        exact_mod_cast Nat.le_max_right 1 D
      have hpow : 0 ≤ B ^ Published.salberger2023AffineExponent N d ε :=
        Real.rpow_nonneg (by positivity) _
      nlinarith [hC₀.le]

/-- One coefficient-uniform constant for all degree-at-least-four
hypersurfaces of bounded degree in affine six-space.  In this range the
exponent in Salberger 2023, Theorem 0.4 is literally `4 + ε`.  This is the
source specialization needed after a projective fourfold has been given a
concrete finite linear projection to an affine hypersurface. -/
theorem salberger2023_affineSix_boundedDegree
    (hSalberger : Published.Salberger2023Theorem04)
    (degreeBound : ℕ)
    (ε : ℝ) (hε : 0 < ε) :
    ∃ C : ℝ, 0 < C ∧
      ∀ d : ℕ, 4 ≤ d → d ≤ degreeBound →
        ∀ (f : MvPolynomial (Fin 6) ℤ)
          (topPart : MvPolynomial (Fin 6) ℚ),
          Published.IsTopHomogeneousPart f topPart d →
          Published.IsAbsolutelyIrreducible topPart →
          ∀ B : ℝ, 1 ≤ B →
            ((Published.affineHypersurfaceIntegerPoints f B).card : ℝ) ≤
              C * B ^ ((4 : ℝ) + ε) := by
  let degreeSet : Finset ℕ := Finset.Icc 4 degreeBound
  let Degree := {d : ℕ // d ∈ degreeSet}
  have hEach : ∀ d : Degree, ∃ C : ℝ, 0 < C ∧
      ∀ (f : MvPolynomial (Fin 6) ℤ)
        (topPart : MvPolynomial (Fin 6) ℚ),
        Published.IsTopHomogeneousPart f topPart d.1 →
        Published.IsAbsolutelyIrreducible topPart →
        ∀ B : ℝ, 1 ≤ B →
          ((Published.affineHypersurfaceIntegerPoints f B).card : ℝ) ≤
            C * B ^ ((4 : ℝ) + ε) := by
    intro d
    have hd : 4 ≤ d.1 := by
      exact (Finset.mem_Icc.mp (show d.1 ∈ Finset.Icc 4 degreeBound by
        exact d.2)).1
    obtain ⟨C, hC, hbound⟩ :=
      hSalberger 6 d.1 (by omega) (Or.inr hd) ε hε
    refine ⟨C, hC, ?_⟩
    intro f topPart htop hirred B hB
    have h := hbound f topPart htop hirred B hB
    convert h using 1
    norm_num [Published.salberger2023AffineExponent,
      (show d.1 ≠ 3 by omega)]
  choose c hc hbound using hEach
  let C : ℝ := 1 + ∑ d : Degree, c d
  have hC : 0 < C := by
    have hsum : 0 ≤ ∑ d : Degree, c d :=
      Finset.sum_nonneg fun d _ ↦ (hc d).le
    dsimp only [C]
    linarith
  refine ⟨C, hC, ?_⟩
  intro d hd hdBound f topPart htop hirred B hB
  have hdMem : d ∈ degreeSet := by
    simp only [degreeSet, Finset.mem_Icc]
    exact ⟨hd, hdBound⟩
  let d' : Degree := ⟨d, hdMem⟩
  have hcSum : c d' ≤ ∑ e : Degree, c e := by
    classical
    exact Finset.single_le_sum
      (fun e _ ↦ (hc e).le) (Finset.mem_univ d')
  have hcC : c d' ≤ C := by
    dsimp only [C]
    linarith
  exact (hbound d' f topPart (by simpa [d'] using htop) hirred B hB).trans
    (mul_le_mul_of_nonneg_right hcC (Real.rpow_nonneg (by positivity) _))

/-- Bounded-fibre transfer of the preceding bounded-degree specialization.
No geometric projection is hidden here: the map, its image statement, and
the numerical bound for every literal fibre are hypotheses. -/
theorem finiteSet_card_le_salberger2023_affineSix_boundedDegree
    {Point : Type*} [DecidableEq Point]
    (hSalberger : Published.Salberger2023Theorem04)
    (degreeBound fibreBound : ℕ)
    (ε : ℝ) (hε : 0 < ε) :
    ∃ C : ℝ, 0 < C ∧
      ∀ d : ℕ, 4 ≤ d → d ≤ degreeBound →
        ∀ (f : MvPolynomial (Fin 6) ℤ)
          (topPart : MvPolynomial (Fin 6) ℚ),
          Published.IsTopHomogeneousPart f topPart d →
          Published.IsAbsolutelyIrreducible topPart →
          ∀ B : ℝ, 1 ≤ B →
            ∀ (points : Finset Point) (projection : Point → IntVector 6),
              (∀ x ∈ points,
                projection x ∈
                  Published.affineHypersurfaceIntegerPoints f B) →
              (∀ z ∈ Published.affineHypersurfaceIntegerPoints f B,
                (points.filter fun x ↦ projection x = z).card ≤ fibreBound) →
              (points.card : ℝ) ≤ C * B ^ ((4 : ℝ) + ε) := by
  classical
  obtain ⟨C₀, hC₀, hsource⟩ :=
    salberger2023_affineSix_boundedDegree
      hSalberger degreeBound ε hε
  let C : ℝ := max 1 fibreBound * C₀
  have hC : 0 < C := mul_pos (by positivity) hC₀
  refine ⟨C, hC, ?_⟩
  intro d hd hdBound f topPart htop hirred B hB points projection
    himage hfibre
  have hcardNat : points.card ≤
      (Published.affineHypersurfaceIntegerPoints f B).card * fibreBound :=
    finiteSet_card_le_index_card_mul_of_fibres
      points (Published.affineHypersurfaceIntegerPoints f B)
      projection fibreBound himage hfibre
  have hcardReal : (points.card : ℝ) ≤
      (Published.affineHypersurfaceIntegerPoints f B).card * fibreBound := by
    exact_mod_cast hcardNat
  have hsourceBound := hsource d hd hdBound f topPart htop hirred B hB
  have hfibreLe : (fibreBound : ℝ) ≤ max 1 fibreBound := by
    exact_mod_cast Nat.le_max_right 1 fibreBound
  have hpow : 0 ≤ B ^ ((4 : ℝ) + ε) :=
    Real.rpow_nonneg (by positivity) _
  calc
    (points.card : ℝ) ≤
        (Published.affineHypersurfaceIntegerPoints f B).card * fibreBound :=
      hcardReal
    _ ≤ (C₀ * B ^ ((4 : ℝ) + ε)) * fibreBound := by
      gcongr
    _ ≤ C * B ^ ((4 : ℝ) + ε) := by
      dsimp only [C]
      nlinarith [hC₀.le]

/-! ## The exact hypersurface kernel of a six-coordinate projection -/

/-- A nonzero height-at-most-one prime ideal in a noetherian UFD is
generated by one prime element.  This is the commutative-algebra step which
turns a generically finite map to affine six-space into one literal
hypersurface equation; it does not assume a hypersurface presentation.

The proof selects a prime element in the ideal by unique factorization.
Krull's principal ideal theorem shows that its principal prime has height at
most one.  Since the ground ring is a domain and the generator is nonzero,
that height is exactly one.  The height comparison then makes the original
prime minimal over the principal prime, hence equal to it. -/
theorem nonzeroPrimeIdeal_eq_span_singleton_of_height_le_one
    {R : Type*} [CommRing R] [IsDomain R] [IsNoetherianRing R]
    [UniqueFactorizationMonoid R]
    (P : Ideal R) (hPprime : P.IsPrime) (hPne : P ≠ ⊥)
    (hPheight : P.height ≤ 1) :
    ∃ f : R, Prime f ∧ P = Ideal.span {f} := by
  obtain ⟨f, hfP, hfprime⟩ :=
    hPprime.exists_mem_prime_of_ne_bot hPne
  let Q : Ideal R := Ideal.span {f}
  have hQprime : Q.IsPrime :=
    (Ideal.span_singleton_prime hfprime.ne_zero).mpr hfprime
  letI : Q.IsPrime := hQprime
  letI : P.IsPrime := hPprime
  have hQP : Q ≤ P :=
    Ideal.span_le.mpr (Set.singleton_subset_iff.mpr hfP)
  have hQne : Q ≠ ⊥ :=
    Ideal.span_singleton_eq_bot.not.mpr hfprime.ne_zero
  have hQmin : Q ∈ Q.minimalPrimes := by
    rw [Ideal.minimalPrimes_eq_subsingleton_self]
    exact Set.mem_singleton Q
  have hQheightLe : Q.height ≤ 1 :=
    Ideal.height_le_one_of_isPrincipal_of_mem_minimalPrimes Q Q hQmin
  have hQheightGe : 1 ≤ Q.height := by
    rw [Order.one_le_iff_pos, Ideal.height_eq_primeHeight,
      Ideal.primeHeight, Order.height_pos]
    change ¬ IsMin (⟨Q, inferInstance⟩ : PrimeSpectrum R)
    exact not_isMin_of_lt
      (b := (⟨⊥, Ideal.bot_prime⟩ : PrimeSpectrum R)) (by
        change (⊥ : Ideal R) < Q
        exact bot_lt_iff_ne_bot.mpr hQne)
  have hQheight : Q.height = 1 :=
    le_antisymm hQheightLe hQheightGe
  have hPheightQ : P.height ≤ Q.height := by
    rw [hQheight]
    exact hPheight
  have hPmin : P ∈ Q.minimalPrimes :=
    Ideal.mem_minimalPrimes_of_height_eq hQP hPheightQ
  have hPQ : P = Q := by
    rw [Ideal.minimalPrimes_eq_subsingleton_self] at hPmin
    exact Set.mem_singleton_iff.mp hPmin
  exact ⟨f, hfprime, hPQ⟩

/-- The literal algebra map attached to six displayed coordinate functions.
In the fourfold application, five of these are homogeneous linear
normalization parameters and the sixth is the rational linear primitive
element supplied by `LinearPrimitiveElement`. -/
def sixCoordinateProjectionAlgHom
    {K A : Type*} [CommRing K] [CommRing A] [Algebra K A]
    (coordinate : Fin 6 → A) : MvPolynomial (Fin 6) K →ₐ[K] A :=
  MvPolynomial.aeval coordinate

@[simp]
theorem sixCoordinateProjectionAlgHom_X
    {K A : Type*} [CommRing K] [CommRing A] [Algebra K A]
    (coordinate : Fin 6 → A) (i : Fin 6) :
    sixCoordinateProjectionAlgHom (K := K) coordinate
        (MvPolynomial.X i : MvPolynomial (Fin 6) K) =
      coordinate i := by
  simp [sixCoordinateProjectionAlgHom]

/-- Exact principal-kernel conclusion for a displayed six-coordinate map
to a domain.  The resulting polynomial is prime (hence irreducible), and
the final equivalence says literally that every polynomial relation among
the six coordinates is a multiple of this one equation.

Thus the only dimension-theoretic input still needed from the geometric
projection construction is that this concrete nonzero kernel has height at
most one. -/
theorem exists_irreducible_projectionEquation_of_kernel_height_le_one
    {K A : Type*} [Field K] [CommRing A] [IsDomain A] [Algebra K A]
    (coordinate : Fin 6 → A)
    (hker : RingHom.ker
      (sixCoordinateProjectionAlgHom (K := K) coordinate).toRingHom ≠ ⊥)
    (hheight :
      (RingHom.ker
        (sixCoordinateProjectionAlgHom
          (K := K) coordinate).toRingHom).height ≤ 1) :
    ∃ f : MvPolynomial (Fin 6) K,
      Prime f ∧ Irreducible f ∧
      RingHom.ker
        (sixCoordinateProjectionAlgHom (K := K) coordinate).toRingHom =
        Ideal.span {f} ∧
      ∀ g,
        sixCoordinateProjectionAlgHom (K := K) coordinate g = 0 ↔ f ∣ g := by
  have hprime :
      (RingHom.ker
        (sixCoordinateProjectionAlgHom
          (K := K) coordinate).toRingHom).IsPrime :=
    RingHom.ker_isPrime
      (sixCoordinateProjectionAlgHom (K := K) coordinate).toRingHom
  obtain ⟨f, hfprime, hkerf⟩ :=
    nonzeroPrimeIdeal_eq_span_singleton_of_height_le_one
      (RingHom.ker
        (sixCoordinateProjectionAlgHom (K := K) coordinate).toRingHom)
      hprime hker hheight
  refine ⟨f, hfprime, hfprime.irreducible, hkerf, ?_⟩
  intro g
  change g ∈ RingHom.ker
      (sixCoordinateProjectionAlgHom (K := K) coordinate).toRingHom ↔ f ∣ g
  rw [hkerf, Ideal.mem_span_singleton]

/-! ## A literal finite menu of bounded integral projection matrices -/

/-- Read a vector of `r*n` coefficients as an `r` by `n` matrix, using
Lean's standard product equivalence for finite ordinals. -/
def projectionMatrixOfCoefficientVector (r n : ℕ)
    (x : Fin (r * n) → ℤ) : Matrix (Fin r) (Fin n) ℤ :=
  fun i j ↦ x (finProdFinEquiv (i, j))

/-- The concrete finite menu of integral `r` by `n` matrices whose entries
belong to `{0, ..., D}`.  In particular, with `r=6` and `n=13`, this is a
finite menu of literal integer linear maps from thirteen to six
coordinates. -/
def boundedIntegerProjectionMatrixMenu (r n D : ℕ) :
    Finset (Matrix (Fin r) (Fin n) ℤ) := by
  classical
  exact (boundedIntegerProjectionMenu (r * n) D).image
    (projectionMatrixOfCoefficientVector r n)

@[simp]
theorem card_boundedIntegerProjectionMatrixMenu (r n D : ℕ) :
    (boundedIntegerProjectionMatrixMenu r n D).card = (D + 1) ^ (r * n) := by
  classical
  have hinjective : Function.Injective
      (projectionMatrixOfCoefficientVector r n) := by
    intro x y hxy
    funext k
    have hentry := congrFun₂ hxy
      (finProdFinEquiv.symm k).1 (finProdFinEquiv.symm k).2
    change x (finProdFinEquiv
      ((finProdFinEquiv.symm k).1, (finProdFinEquiv.symm k).2)) =
        y (finProdFinEquiv
          ((finProdFinEquiv.symm k).1, (finProdFinEquiv.symm k).2)) at hentry
    have hk : finProdFinEquiv
        ((finProdFinEquiv.symm k).1, (finProdFinEquiv.symm k).2) = k := by
      rw [Prod.eta, Equiv.apply_symm_apply]
    rwa [hk] at hentry
  rw [boundedIntegerProjectionMatrixMenu,
    Finset.card_image_of_injective _ hinjective,
    card_boundedIntegerProjectionMenu]

theorem mem_boundedIntegerProjectionMatrixMenu_entry_bounds
    {r n D : ℕ} {M : Matrix (Fin r) (Fin n) ℤ}
    (hM : M ∈ boundedIntegerProjectionMatrixMenu r n D) :
    ∀ i j, 0 ≤ M i j ∧ M i j ≤ D := by
  classical
  obtain ⟨x, hx, rfl⟩ := Finset.mem_image.mp hM
  intro i j
  exact mem_boundedIntegerProjectionMenu_iff.mp hx
    (finProdFinEquiv (i, j))

/-- Flatten a displayed matrix in precisely the order used by
`projectionMatrixOfCoefficientVector`. -/
def projectionCoefficientVector (r n : ℕ)
    (M : Matrix (Fin r) (Fin n) ℤ) : Fin (r * n) → ℤ :=
  fun k ↦ M (finProdFinEquiv.symm k).1 (finProdFinEquiv.symm k).2

@[simp]
theorem projectionCoefficientVector_projectionMatrixOfCoefficientVector
    (r n : ℕ) (x : Fin (r * n) → ℤ) :
    projectionCoefficientVector r n
      (projectionMatrixOfCoefficientVector r n x) = x := by
  funext k
  change x (finProdFinEquiv
    ((finProdFinEquiv.symm k).1, (finProdFinEquiv.symm k).2)) = x k
  rw [Prod.eta, Equiv.apply_symm_apply]

/-- A nonzero polynomial detector of degree at most `D` selects a literal
bounded integral projection matrix from the fixed menu.  This is the exact
`6 x 13` finite-menu step when specialized to `r=6`, `n=13`; it contains no
abstract projection predicate. -/
theorem exists_boundedIntegerProjectionMatrix_eval_ne_zero
    {r n D : ℕ} (detector : MvPolynomial (Fin (r * n)) ℤ)
    (hne : detector ≠ 0) (hdegree : detector.totalDegree ≤ D) :
    ∃ M ∈ boundedIntegerProjectionMatrixMenu r n D,
      MvPolynomial.eval (projectionCoefficientVector r n M) detector ≠ 0 := by
  classical
  obtain ⟨x, hx, hnonzero⟩ :=
    exists_mem_boundedIntegerProjectionMenu_eval_ne_zero
      detector hne hdegree
  refine ⟨projectionMatrixOfCoefficientVector r n x,
    Finset.mem_image.mpr ⟨x, hx, rfl⟩, ?_⟩
  simpa using hnonzero

/-- Relative form of the preceding theorem.  A single integral polynomial
in family parameters and the `6*13` matrix coefficients gives one fixed
finite menu of bounded integer `6 x 13` matrices.  At every integral family
point, one matrix in that same menu has nonzero specialized detector. -/
theorem exists_boundedIntegerSixByThirteenProjection_of_relativeDetector
    {τ : Type*} {D : ℕ}
    (detector : MvPolynomial (Sum τ (Fin (6 * 13))) ℤ)
    (hne : ∀ t : τ → ℤ,
      specializeParameterVariables t detector ≠ 0)
    (hdegree : ∀ t : τ → ℤ,
      (specializeParameterVariables t detector).totalDegree ≤ D)
    (t : τ → ℤ) :
    ∃ M ∈ boundedIntegerProjectionMatrixMenu 6 13 D,
      MvPolynomial.eval (Sum.elim t (projectionCoefficientVector 6 13 M))
        detector ≠ 0 := by
  classical
  obtain ⟨M, hM, hnonzero⟩ :=
    exists_boundedIntegerProjectionMatrix_eval_ne_zero
      (specializeParameterVariables t detector) (hne t) (hdegree t)
  refine ⟨M, hM, ?_⟩
  rwa [← eval_specializeParameterVariables]

/-! ## Literal determinant and primitive-element discriminant factors -/

/-- The determinant of the generic square matrix.  This is the literal
minor which records invertibility of a selected block of normalization
linear forms. -/
def genericNormalizationMinor (r : ℕ) :
    MvPolynomial (Fin r × Fin r) ℚ :=
  Matrix.det (fun i j ↦ MvPolynomial.X (i, j))

@[simp]
theorem eval_genericNormalizationMinor_at_identity (r : ℕ) :
    MvPolynomial.eval
      (fun ij : Fin r × Fin r ↦ if ij.1 = ij.2 then (1 : ℚ) else 0)
      (genericNormalizationMinor r) = 1 := by
  let x : Fin r × Fin r → ℚ :=
    fun ij ↦ if ij.1 = ij.2 then 1 else 0
  let M : Matrix (Fin r) (Fin r) (MvPolynomial (Fin r × Fin r) ℚ) :=
    fun i j ↦ MvPolynomial.X (i, j)
  change MvPolynomial.eval x (Matrix.det M) = 1
  calc
    MvPolynomial.eval x (Matrix.det M) =
        Matrix.det (M.map (MvPolynomial.eval x)) := by
          exact RingHom.map_det (MvPolynomial.eval x) M
    _ = Matrix.det (1 : Matrix (Fin r) (Fin r) ℚ) := by
      congr 1
      ext i j
      simp [M, x, Matrix.one_apply]
    _ = 1 := Matrix.det_one

theorem genericNormalizationMinor_ne_zero (r : ℕ) :
    genericNormalizationMinor r ≠ 0 := by
  intro hzero
  have hone := eval_genericNormalizationMinor_at_identity r
  rw [hzero, map_zero] at hone
  exact zero_ne_one hone

/-- Multiplication matrix of the generic linear combination of displayed
elements of a finite algebra, written directly from their multiplication
matrices. -/
def genericLinearCombinationMultiplicationMatrix
    {ι : Type*} [Fintype ι] [DecidableEq ι] (d : ℕ)
    (multiplicationMatrix : ι → Matrix (Fin d) (Fin d) ℚ) :
    Matrix (Fin d) (Fin d) (MvPolynomial ι ℚ) :=
  ∑ i, (MvPolynomial.X i : MvPolynomial ι ℚ) •
    (multiplicationMatrix i).map
      (MvPolynomial.C : ℚ →+* MvPolynomial ι ℚ)

/-- The discriminant of the characteristic polynomial of the preceding
generic multiplication matrix.  This is an actual multivariate polynomial,
not a predicate asserting that a primitive element exists. -/
def genericPrimitiveElementDiscriminant
    {ι : Type*} [Fintype ι] [DecidableEq ι] (d : ℕ)
    (multiplicationMatrix : ι → Matrix (Fin d) (Fin d) ℚ) :
    MvPolynomial ι ℚ :=
  Polynomial.discr
    (genericLinearCombinationMultiplicationMatrix d
      multiplicationMatrix).charpoly

/-- Put two detector factors in disjoint sets of variables and multiply
them.  For the application, `f` is a normalization minor and `g` is the
primitive-element discriminant. -/
def jointDetector {α β : Type*}
    (f : MvPolynomial α ℚ) (g : MvPolynomial β ℚ) :
    MvPolynomial (Sum α β) ℚ :=
  MvPolynomial.rename Sum.inl f * MvPolynomial.rename Sum.inr g

theorem eval_jointDetector {α β : Type*}
    (f : MvPolynomial α ℚ) (g : MvPolynomial β ℚ)
    (x : α → ℚ) (y : β → ℚ) :
    MvPolynomial.eval (Sum.elim x y) (jointDetector f g) =
      MvPolynomial.eval x f * MvPolynomial.eval y g := by
  simp [jointDetector, MvPolynomial.eval_rename]

/-- Independent nonvanishing specializations of the normalization minor
and primitive discriminant give a nonzero specialization of their literal
joint detector. -/
theorem jointDetector_eval_ne_zero {α β : Type*}
    (f : MvPolynomial α ℚ) (g : MvPolynomial β ℚ)
    (x : α → ℚ) (y : β → ℚ)
    (hfx : MvPolynomial.eval x f ≠ 0)
    (hgy : MvPolynomial.eval y g ≠ 0) :
    MvPolynomial.eval (Sum.elim x y) (jointDetector f g) ≠ 0 := by
  rw [eval_jointDetector]
  exact mul_ne_zero hfx hgy

theorem jointDetector_ne_zero_of_specializations {α β : Type*}
    (f : MvPolynomial α ℚ) (g : MvPolynomial β ℚ)
    (x : α → ℚ) (y : β → ℚ)
    (hfx : MvPolynomial.eval x f ≠ 0)
    (hgy : MvPolynomial.eval y g ≠ 0) :
    jointDetector f g ≠ 0 := by
  intro hzero
  have := jointDetector_eval_ne_zero f g x y hfx hgy
  exact this (by rw [hzero, map_zero])

/-- If a single element generates a finite field extension, multiplication
by that element has characteristic polynomial equal to its minimal
polynomial.  This is proved with the literal power basis generated by the
element; no primitive-element interface is introduced. -/
theorem leftMulMatrix_charpoly_eq_minpoly_of_adjoin_eq_top
    {K E : Type*} [Field K] [Field E] [Algebra K E]
    [FiniteDimensional K E]
    {ι : Type*} [Fintype ι] [DecidableEq ι]
    (b : Module.Basis ι K E) (theta : E)
    (htop : Algebra.adjoin K ({theta} : Set E) = ⊤) :
    (Algebra.leftMulMatrix b theta).charpoly = minpoly K theta := by
  let pb : PowerBasis K E := PowerBasis.ofAdjoinEqTop
    (Algebra.IsIntegral.isIntegral theta) htop
  calc
    (Algebra.leftMulMatrix b theta).charpoly =
        (Algebra.lmul K E theta).charpoly :=
      LinearMap.charpoly_toMatrix (Algebra.lmul K E theta) b
    _ = (Algebra.leftMulMatrix pb.basis theta).charpoly :=
      (LinearMap.charpoly_toMatrix
        (Algebra.lmul K E theta) pb.basis).symm
    _ = (Algebra.leftMulMatrix pb.basis pb.gen).charpoly := by
      rw [PowerBasis.ofAdjoinEqTop_gen]
    _ = minpoly K pb.gen := charpoly_leftMulMatrix pb
    _ = minpoly K theta := by rw [PowerBasis.ofAdjoinEqTop_gen]

/-- Over a characteristic-zero field, a nonconstant monic separable
polynomial has nonzero polynomial discriminant. -/
theorem polynomial_discr_ne_zero_of_monic_separable
    {K : Type*} [Field K] [CharZero K] {f : Polynomial K}
    (hmonic : f.Monic) (hsep : f.Separable)
    (hdegree : 0 < f.natDegree) : f.discr ≠ 0 := by
  have hderivDegree : f.derivative.natDegree = f.natDegree - 1 := by
    have hdegreeEq := Polynomial.degree_derivative_eq f hdegree
    have hderivNe : f.derivative ≠ 0 := by
      intro hzero
      rw [hzero, Polynomial.degree_zero] at hdegreeEq
      exact WithBot.bot_ne_coe hdegreeEq
    rw [Polynomial.degree_eq_natDegree
      hderivNe] at hdegreeEq
    exact WithBot.coe_eq_coe.mp hdegreeEq
  have hcoprime : IsCoprime f f.derivative :=
    (Polynomial.separable_def f).mp hsep
  have hresultant :
      Polynomial.resultant f f.derivative f.natDegree
        (f.natDegree - 1) ≠ 0 := by
    simpa [hderivDegree] using Polynomial.resultant_ne_zero f f.derivative hcoprime
  have hpositiveDegree : 0 < f.degree := by
    simpa [Polynomial.degree_eq_natDegree hmonic.ne_zero] using hdegree
  intro hzero
  apply hresultant
  rw [Polynomial.resultant_deriv hpositiveDegree, hmonic.leadingCoeff,
    hzero, mul_zero]

/-- Primitive generation in a finite separable characteristic-zero field
extension forces the discriminant of the multiplication characteristic
polynomial to be nonzero. -/
theorem leftMulMatrix_charpoly_discr_ne_zero_of_adjoin_eq_top
    {K E : Type*} [Field K] [CharZero K] [Field E] [Algebra K E]
    [FiniteDimensional K E] [Algebra.IsSeparable K E]
    {ι : Type*} [Fintype ι] [DecidableEq ι]
    (b : Module.Basis ι K E) (theta : E)
    (htop : Algebra.adjoin K ({theta} : Set E) = ⊤)
    (hfinrank : 0 < Module.finrank K E) :
    (Algebra.leftMulMatrix b theta).charpoly.discr ≠ 0 := by
  rw [leftMulMatrix_charpoly_eq_minpoly_of_adjoin_eq_top b theta htop]
  apply polynomial_discr_ne_zero_of_monic_separable
    (minpoly.monic (Algebra.IsIntegral.isIntegral theta))
    (Algebra.IsSeparable.isSeparable K theta)
  let pb : PowerBasis K E := PowerBasis.ofAdjoinEqTop
    (Algebra.IsIntegral.isIntegral theta) htop
  have hdim : pb.dim = (minpoly K theta).natDegree := by
    exact PowerBasis.ofAdjoinEqTop_dim
      (Algebra.IsIntegral.isIntegral theta) htop
  rw [← hdim, ← PowerBasis.finrank pb]
  exact hfinrank

/-- A resultant version of the primitive-element detector.  The two degree
parameters are fixed before specialization, so its base change is literal
even before any nonvanishing statement has been proved. -/
def genericPrimitiveElementResultantDetector
    {ι : Type*} [Fintype ι] [DecidableEq ι] (d : ℕ)
    (multiplicationMatrix : ι → Matrix (Fin d) (Fin d) ℚ) :
    MvPolynomial ι ℚ :=
  let P := (genericLinearCombinationMultiplicationMatrix d
    multiplicationMatrix).charpoly
  Polynomial.resultant P P.derivative d (d - 1)

/-- Specialization of the fixed-degree resultant detector is exactly the
resultant of the specialized characteristic polynomial and its derivative. -/
theorem eval_genericPrimitiveElementResultantDetector
    {ι : Type*} [Fintype ι] [DecidableEq ι] (d : ℕ)
    (multiplicationMatrix : ι → Matrix (Fin d) (Fin d) ℚ)
    (c : ι → ℚ) :
    MvPolynomial.eval c
      (genericPrimitiveElementResultantDetector d multiplicationMatrix) =
      Polynomial.resultant
        (Matrix.charpoly (∑ i, (c i) • multiplicationMatrix i))
        (Matrix.charpoly
          (∑ i, (c i) • multiplicationMatrix i)).derivative d (d - 1) := by
  let G := genericLinearCombinationMultiplicationMatrix d multiplicationMatrix
  let phi : MvPolynomial ι ℚ →+* ℚ := MvPolynomial.eval c
  let A : Matrix (Fin d) (Fin d) ℚ :=
    ∑ i, (c i) • multiplicationMatrix i
  have hmatrix : G.map phi = A := by
    ext i j
    dsimp [G, A, phi, genericLinearCombinationMultiplicationMatrix]
    rw [Matrix.sum_apply i j Finset.univ,
      Matrix.sum_apply i j Finset.univ]
    rw [map_sum]
    apply Finset.sum_congr rfl
    intro k _hk
    simp
  have hchar : G.charpoly.map phi = A.charpoly := by
    rw [← Matrix.charpoly_map, hmatrix]
  change phi (Polynomial.resultant G.charpoly G.charpoly.derivative
    d (d - 1)) = Polynomial.resultant A.charpoly A.charpoly.derivative
      d (d - 1)
  rw [← Polynomial.resultant_map_map, ← Polynomial.derivative_map, hchar]

/-- For literal multiplication matrices of displayed field elements, a
rational linear combination which generates the field makes the generic
resultant detector nonzero at that coefficient vector. -/
theorem eval_genericPrimitiveElementResultantDetector_ne_zero_of_adjoin_eq_top
    {E : Type*} [Field E] [Algebra ℚ E] [FiniteDimensional ℚ E]
    [Algebra.IsSeparable ℚ E]
    {ι : Type*} [Fintype ι] [DecidableEq ι] {d : ℕ}
    (b : Module.Basis (Fin d) ℚ E) (generator : ι → E) (c : ι → ℚ)
    (htop : Algebra.adjoin ℚ
      ({∑ i, (c i) • generator i} : Set E) = ⊤) :
    MvPolynomial.eval c
      (genericPrimitiveElementResultantDetector d
        (fun i ↦ Algebra.leftMulMatrix b (generator i))) ≠ 0 := by
  let theta : E := ∑ i, (c i) • generator i
  have hdim : Module.finrank ℚ E = d := by
    rw [Module.finrank_eq_card_basis b]
    simp
  have hdpos : 0 < d := by
    rw [← hdim]
    exact Module.finrank_pos
  have hmatrix :
      (∑ i, (c i) • Algebra.leftMulMatrix b (generator i)) =
        Algebra.leftMulMatrix b theta := by
    ext u v
    simp [theta, Algebra.leftMulMatrix_apply]
  rw [eval_genericPrimitiveElementResultantDetector, hmatrix]
  have hdisc : (Algebra.leftMulMatrix b theta).charpoly.discr ≠ 0 :=
    leftMulMatrix_charpoly_discr_ne_zero_of_adjoin_eq_top
      b theta htop (by simpa [hdim] using hdpos)
  have hdegree : 0 < (Algebra.leftMulMatrix b theta).charpoly.degree := by
    rw [Matrix.charpoly_degree_eq_dim]
    simpa using hdpos
  have hnat : (Algebra.leftMulMatrix b theta).charpoly.natDegree = d := by
    have hdeg := Matrix.charpoly_degree_eq_dim
      (Algebra.leftMulMatrix b theta)
    rw [Polynomial.degree_eq_natDegree
      (Matrix.charpoly_monic _).ne_zero] at hdeg
    have hcard : Fintype.card (Fin d) = d := Fintype.card_fin d
    rw [hcard] at hdeg
    exact WithBot.coe_eq_coe.mp hdeg
  have hresultantFormula := Polynomial.resultant_deriv hdegree
  have hresultantFormula' :
      Polynomial.resultant (Algebra.leftMulMatrix b theta).charpoly
        (Algebra.leftMulMatrix b theta).charpoly.derivative d (d - 1) =
        (-1) ^ (d * (d - 1) / 2) *
          (Algebra.leftMulMatrix b theta).charpoly.leadingCoeff *
            (Algebra.leftMulMatrix b theta).charpoly.discr := by
    simpa [hnat] using hresultantFormula
  rw [hresultantFormula', (Matrix.charpoly_monic _).leadingCoeff]
  exact mul_ne_zero (mul_ne_zero (pow_ne_zero _ (neg_ne_zero.mpr one_ne_zero))
    one_ne_zero) hdisc

/-! ## Clearing the rational detector to an integral polynomial -/

/-- Literal common denominator of the finitely many nonzero coefficients. -/
def mvPolynomialRationalCommonDenominator {σ : Type*}
    (f : MvPolynomial σ ℚ) : ℕ :=
  f.support.prod fun m ↦ (f.coeff m).den

theorem mvPolynomialRationalCommonDenominator_pos {σ : Type*}
    (f : MvPolynomial σ ℚ) :
    0 < mvPolynomialRationalCommonDenominator f := by
  classical
  exact Finset.prod_pos fun m _ ↦ (f.coeff m).den_pos

theorem exists_integer_coefficient_after_commonDenominator
    {σ : Type*} (f : MvPolynomial σ ℚ) {m : σ →₀ ℕ}
    (hm : m ∈ f.support) :
    ∃ z : ℤ, (z : ℚ) =
      (mvPolynomialRationalCommonDenominator f : ℚ) * f.coeff m := by
  classical
  have hdiv : (f.coeff m).den ∣ mvPolynomialRationalCommonDenominator f :=
    Finset.dvd_prod_of_mem (fun u ↦ (f.coeff u).den) hm
  obtain ⟨k, hk⟩ := hdiv
  refine ⟨(f.coeff m).num * (k : ℤ), ?_⟩
  rw [hk]
  have hcross : ((f.coeff m).num : ℚ) =
      ((f.coeff m).den : ℚ) * f.coeff m := by
    calc
      ((f.coeff m).num : ℚ) = ((f.coeff m).den : ℚ) *
          (((f.coeff m).num : ℚ) / (f.coeff m).den) := by
            field_simp
      _ = ((f.coeff m).den : ℚ) * f.coeff m := by
        rw [Rat.num_div_den]
  push_cast
  rw [hcross]
  ring

/-- Integral polynomial obtained by clearing the displayed common
denominator coefficient-by-coefficient. -/
noncomputable def clearRationalMvPolynomial {σ : Type*}
    (f : MvPolynomial σ ℚ) : MvPolynomial σ ℤ := by
  classical
  exact f.support.attach.sum fun m ↦ MvPolynomial.monomial m.1
    (Classical.choose
      (exists_integer_coefficient_after_commonDenominator f
        (m := m.1) m.2))

/-- Exact coefficientwise denominator-clearing identity. -/
theorem map_clearRationalMvPolynomial {σ : Type*}
    (f : MvPolynomial σ ℚ) :
    MvPolynomial.map (Int.castRingHom ℚ)
      (clearRationalMvPolynomial f) =
      MvPolynomial.C (mvPolynomialRationalCommonDenominator f : ℚ) * f := by
  classical
  ext m
  by_cases hm : m ∈ f.support
  · rw [MvPolynomial.coeff_map]
    rw [clearRationalMvPolynomial, MvPolynomial.coeff_sum]
    rw [Finset.sum_eq_single ⟨m, hm⟩]
    · rw [MvPolynomial.coeff_monomial, if_pos rfl,
        MvPolynomial.coeff_C_mul]
      exact Classical.choose_spec
        (exists_integer_coefficient_after_commonDenominator f hm)
    · intro u hu hune
      rw [MvPolynomial.coeff_monomial, if_neg]
      exact fun hval ↦ hune (Subtype.ext hval)
    · simp
  · have hcoeff : f.coeff m = 0 := MvPolynomial.notMem_support_iff.mp hm
    rw [MvPolynomial.coeff_map]
    rw [clearRationalMvPolynomial, MvPolynomial.coeff_sum]
    have hsum : (∑ u ∈ f.support.attach,
        MvPolynomial.coeff m (MvPolynomial.monomial u.1
          (Classical.choose
            (exists_integer_coefficient_after_commonDenominator f u.2)))) = 0 := by
      apply Finset.sum_eq_zero
      intro u hu
      rw [MvPolynomial.coeff_monomial, if_neg]
      exact fun hval ↦ hm (hval ▸ u.2)
    rw [hsum, MvPolynomial.coeff_C_mul, hcoeff]
    simp

theorem clearRationalMvPolynomial_ne_zero {σ : Type*}
    {f : MvPolynomial σ ℚ} (hf : f ≠ 0) :
    clearRationalMvPolynomial f ≠ 0 := by
  intro hzero
  have hmap := map_clearRationalMvPolynomial f
  rw [hzero, map_zero] at hmap
  have hD : (mvPolynomialRationalCommonDenominator f : ℚ) ≠ 0 := by
    exact_mod_cast (mvPolynomialRationalCommonDenominator_pos f).ne'
  exact hf (by
    apply (mul_eq_zero.mp hmap.symm).resolve_left
    simpa using hD)

theorem support_clearRationalMvPolynomial_subset {σ : Type*}
    (f : MvPolynomial σ ℚ) :
    (clearRationalMvPolynomial f).support ⊆ f.support := by
  classical
  intro m hm
  by_contra hnot
  have hcoeff : MvPolynomial.coeff m (clearRationalMvPolynomial f) = 0 := by
    rw [clearRationalMvPolynomial, MvPolynomial.coeff_sum]
    apply Finset.sum_eq_zero
    intro u hu
    rw [MvPolynomial.coeff_monomial, if_neg]
    exact fun hval ↦ hnot (hval ▸ u.2)
  exact MvPolynomial.mem_support_iff.mp hm hcoeff

/-- Clearing denominators introduces no new monomial and hence does not
increase total degree. -/
theorem totalDegree_clearRationalMvPolynomial_le {σ : Type*}
    (f : MvPolynomial σ ℚ) :
    (clearRationalMvPolynomial f).totalDegree ≤ f.totalDegree := by
  classical
  exact Finset.sup_mono (support_clearRationalMvPolynomial_subset f)

/-- Evaluation of the integral detector is the common denominator times
evaluation of the original rational detector. -/
theorem eval_clearRationalMvPolynomial {σ : Type*}
    (f : MvPolynomial σ ℚ) (x : σ → ℤ) :
    MvPolynomial.eval (fun i ↦ (x i : ℚ))
      (MvPolynomial.map (Int.castRingHom ℚ)
        (clearRationalMvPolynomial f)) =
      (mvPolynomialRationalCommonDenominator f : ℚ) *
        MvPolynomial.eval (fun i ↦ (x i : ℚ)) f := by
  rw [map_clearRationalMvPolynomial]
  simp

/-- Nonvanishing of a rational detector at an integral point is preserved
by the explicitly cleared integral detector. -/
theorem eval_clearRationalMvPolynomial_ne_zero {σ : Type*}
    {f : MvPolynomial σ ℚ} (x : σ → ℤ)
    (hfx : MvPolynomial.eval (fun i ↦ (x i : ℚ)) f ≠ 0) :
    MvPolynomial.eval x (clearRationalMvPolynomial f) ≠ 0 := by
  intro hzero
  have heval := eval_clearRationalMvPolynomial f x
  have hleft : MvPolynomial.eval (fun i ↦ (x i : ℚ))
      (MvPolynomial.map (Int.castRingHom ℚ)
        (clearRationalMvPolynomial f)) = 0 := by
    rw [← MvPolynomial.eval₂_eq_eval_map]
    change MvPolynomial.eval₂ (Int.castRingHom ℚ)
      ((Int.castRingHom ℚ) ∘ x) (clearRationalMvPolynomial f) = 0
    rw [← MvPolynomial.eval₂_comp, hzero, map_zero]
  rw [hleft] at heval
  have hD : (mvPolynomialRationalCommonDenominator f : ℚ) ≠ 0 := by
    exact_mod_cast (mvPolynomialRationalCommonDenominator_pos f).ne'
  exact hfx ((mul_eq_zero.mp heval.symm).resolve_left hD)

/-! ## Faithfully flat coefficient extension for polynomial rings -/

noncomputable local instance polynomialTensorRightAlgebra
    {K L σ : Type*} [Field K] [Field L] [Algebra K L] :
    Algebra (MvPolynomial σ K) ((MvPolynomial σ K) ⊗[K] L) :=
  (Algebra.TensorProduct.includeLeft :
    MvPolynomial σ K →ₐ[K] ((MvPolynomial σ K) ⊗[K] L)).toAlgebra

noncomputable local instance polynomialCoefficientExtensionAlgebra
    {K L σ : Type*} [Field K] [Field L] [Algebra K L] :
    Algebra (MvPolynomial σ K) (MvPolynomial σ L) :=
  MvPolynomial.algebraMvPolynomial

/-- The standard tensor description of coefficient extension, promoted to
an algebra equivalence over the source polynomial ring. -/
noncomputable def polynomialCoefficientExtensionTensorAlgEquiv
    {K L σ : Type*} [Field K] [Field L] [Algebra K L] :
    ((MvPolynomial σ K) ⊗[K] L) ≃ₐ[MvPolynomial σ K]
      (MvPolynomial σ L) := by
  let e := (Algebra.TensorProduct.comm K (MvPolynomial σ K) L).trans
    ((MvPolynomial.algebraTensorAlgEquiv K L (σ := σ)).restrictScalars K)
  exact
    { e.toRingEquiv with
      commutes' := by
        intro p
        change e (p ⊗ₜ[K] 1) = MvPolynomial.map (algebraMap K L) p
        dsimp [e]
        rw [MvPolynomial.algebraTensorAlgEquiv_tmul]
        simp }

/-- Membership of a base point supplies exactly the translated-box and
residue hypotheses needed by the already-proved affine normalization. -/
theorem card_depthSevenNormalizedDisplacementFinset_eq_translated_of_mem
    (p : Parameters)
    (equations : Finset (MvPolynomial (Fin 13) ℤ))
    (CF : ℕ) {x₀ : IntVector 13}
    (hx₀ : x₀ ∈ depthSevenTranslatedPointFinset p equations CF) :
    (depthSevenNormalizedDisplacementFinset p x₀ equations CF).card =
      (depthSevenTranslatedPointFinset p equations CF).card := by
  have hx₀' :=
    (mem_depthSevenTranslatedPointFinset_iff p equations CF x₀).mp hx₀
  exact card_depthSevenNormalizedDisplacementFinset_eq_translated
    p x₀ equations CF hx₀'.1 hx₀'.2.1

/-- A pointwise bound for the original set is equivalent to the same bound
for the normalized set based at every counted point.  When the original set
is empty, both sides have the correct logical meaning and no base point is
chosen. -/
theorem card_depthSevenTranslatedPointFinset_le_iff_normalized
    (p : Parameters)
    (equations : Finset (MvPolynomial (Fin 13) ℤ))
    (CF : ℕ) (M : NNReal) :
    ((depthSevenTranslatedPointFinset p equations CF).card : NNReal) ≤ M ↔
      ∀ x₀, x₀ ∈ depthSevenTranslatedPointFinset p equations CF →
        ((depthSevenNormalizedDisplacementFinset
          p x₀ equations CF).card : NNReal) ≤ M := by
  constructor
  · intro h x₀ hx₀
    rw [card_depthSevenNormalizedDisplacementFinset_eq_translated_of_mem
      p equations CF hx₀]
    exact h
  · intro h
    classical
    by_cases hX : depthSevenTranslatedPointFinset p equations CF = ∅
    · simp [hX]
    · obtain ⟨x₀, hx₀⟩ := Finset.nonempty_iff_ne_empty.mpr hX
      rw [← card_depthSevenNormalizedDisplacementFinset_eq_translated_of_mem
        p equations CF hx₀]
      exact h x₀ hx₀

/-- Uniformly bounding every normalized displacement set based at a counted
point is exactly equivalent to the strict `94/21` estimate for the original
translated set.  This theorem eliminates the normalization step; it does not
assume or prove any geometric branch estimate. -/
theorem translated_uniform_bound_iff_normalized_uniform_bound
    (equations : Finset (MvPolynomial (Fin 13) ℤ)) (CF : ℕ) :
    (∀ ε : ℝ, 0 < ε → ∃ C : NNReal, ∀ p : Parameters,
      ((depthSevenTranslatedPointFinset p equations CF).card : NNReal) ≤
        powerEnvelope C p.strictHeight p.strictNormalizedSide
          targetExponent ε) ↔
    (∀ ε : ℝ, 0 < ε → ∃ C : NNReal, ∀ (p : Parameters) x₀,
      x₀ ∈ depthSevenTranslatedPointFinset p equations CF →
      ((depthSevenNormalizedDisplacementFinset
        p x₀ equations CF).card : NNReal) ≤
        powerEnvelope C p.strictHeight p.strictNormalizedSide
          targetExponent ε) := by
  constructor
  · intro h ε hε
    obtain ⟨C, hC⟩ := h ε hε
    exact ⟨C, fun p x₀ hx₀ ↦
      (card_depthSevenTranslatedPointFinset_le_iff_normalized
        p equations CF _).mp (hC p) x₀ hx₀⟩
  · intro h ε hε
    obtain ⟨C, hC⟩ := h ε hε
    exact ⟨C, fun p ↦
      (card_depthSevenTranslatedPointFinset_le_iff_normalized
        p equations CF _).mpr (hC p)⟩

/-- The target set is literally empty when the displayed equations define a
rational projective linear space.  This completes the linear branch without
using any counting theorem. -/
theorem depthSevenTranslatedPointFinset_eq_empty_of_linear
    (p : Parameters)
    (equations : Finset (MvPolynomial (Fin 13) ℤ))
    (CF : ℕ)
    (hlinear : EquationFamilyDefinesLinearProjectiveSpace equations) :
    depthSevenTranslatedPointFinset p equations CF = ∅ := by
  classical
  apply Finset.eq_empty_iff_forall_notMem.mpr
  intro x hx
  have hx' :=
    (mem_depthSevenTranslatedPointFinset_iff p equations CF x).mp hx
  exact hx'.2.2.2.choose_spec.1 hlinear

/-- Consequently the entire strict counting conclusion holds in the linear
case, with zero constant and without invoking any external theorem. -/
theorem translated_bound_targetExponent_of_linear
    (equations : Finset (MvPolynomial (Fin 13) ℤ))
    (hlinear : EquationFamilyDefinesLinearProjectiveSpace equations) :
    ∃ CF : ℕ, ∀ ε : ℝ, 0 < ε →
      ∃ C : NNReal, ∀ p : Parameters,
        ((depthSevenTranslatedPointFinset p equations CF).card : NNReal) ≤
          powerEnvelope C p.strictHeight p.strictNormalizedSide
            targetExponent ε := by
  refine ⟨0, ?_⟩
  intro ε _hε
  refine ⟨0, ?_⟩
  intro p
  rw [depthSevenTranslatedPointFinset_eq_empty_of_linear
    p equations 0 hlinear]
  simp [powerEnvelope]

/-- Pointwise monotonicity of the explicit power envelope in its `T`
exponent, for the only range used in the theorem. -/
theorem powerEnvelope_mono_exponent
    {C H T : NNReal} {a b ε : ℝ}
    (hT : 1 ≤ T) (hab : a ≤ b) :
    powerEnvelope C H T a ε ≤ powerEnvelope C H T b ε := by
  unfold powerEnvelope
  exact mul_le_mul_right
    (NNReal.rpow_le_rpow_of_exponent_le hT (by linarith)) (C * H ^ ε)

/-- The formally sharper `94/21` conclusion implies the manuscript's
displayed `9/2-1/100 = 449/100` conclusion with the same `CF` and the same
constant at each epsilon. -/
theorem translated_bound_targetExponent_implies_weakerExponent
    (equations : Finset (MvPolynomial (Fin 13) ℤ))
    (h : ∃ CF : ℕ, ∀ ε : ℝ, 0 < ε →
      ∃ C : NNReal, ∀ p : Parameters,
        ((depthSevenTranslatedPointFinset p equations CF).card : NNReal) ≤
          powerEnvelope C p.strictHeight p.strictNormalizedSide
            targetExponent ε) :
    ∃ CF : ℕ, ∀ ε : ℝ, 0 < ε →
      ∃ C : NNReal, ∀ p : Parameters,
        ((depthSevenTranslatedPointFinset p equations CF).card : NNReal) ≤
          powerEnvelope C p.strictHeight p.strictNormalizedSide
            weakerExponent ε := by
  obtain ⟨CF, hCF⟩ := h
  refine ⟨CF, ?_⟩
  intro ε hε
  obtain ⟨C, hC⟩ := hCF ε hε
  refine ⟨C, ?_⟩
  intro p
  exact (hC p).trans
    (powerEnvelope_mono_exponent p.one_le_strictNormalizedSide
      targetExponent_lt_weaker.le)

end

end TranslatedDepthSeven
