import TranslatedDepthSeven.NilpotentCotangentSurjectivity
import Mathlib.Data.Finsupp.Multiset
import Mathlib.Data.Sym.Card
import Mathlib.LinearAlgebra.Projection
import Mathlib.RingTheory.MvPolynomial.Basic
import Mathlib.RingTheory.MvPolynomial.Homogeneous
import Mathlib.RingTheory.MvPolynomial.Ideal

/-!
# Jets of the origin in affine space

We compute the quotient of a polynomial ring by a power of the origin
ideal directly from its monomial basis.  This is the explicit model used in
the smooth-point calculation; no Hilbert--Samuel or regular-local theorem is
invoked.
-/

namespace TranslatedDepthSeven

noncomputable section

open scoped BigOperators

universe u v

variable {K : Type u} [Field K] {σ : Type v}

/-- The monomial ideal consisting of polynomials all of whose terms have
total degree at least `e`. -/
def totalDegreeAtLeastIdeal (e : ℕ) : Ideal (MvPolynomial σ K) :=
  Ideal.span ((fun s : σ →₀ ℕ ↦ MvPolynomial.monomial s (1 : K)) ''
    {s : σ →₀ ℕ | e ≤ Finsupp.degree s})

private theorem finsupp_degree_mono {a b : σ →₀ ℕ} (hab : a ≤ b) :
    Finsupp.degree a ≤ Finsupp.degree b := by
  classical
  change a.sum (fun _ ↦ id) ≤ b.sum (fun _ ↦ id)
  rw [← Finsupp.card_toMultiset, ← Finsupp.card_toMultiset]
  exact Multiset.card_le_card (Finsupp.orderIsoMultiset.monotone hab)

/-- Membership in the degree-at-least ideal is the literal support
condition suggested by its name. -/
theorem mem_totalDegreeAtLeastIdeal_iff (e : ℕ) (p : MvPolynomial σ K) :
    p ∈ totalDegreeAtLeastIdeal (K := K) e ↔
      ∀ s ∈ p.support, e ≤ Finsupp.degree s := by
  rw [totalDegreeAtLeastIdeal, MvPolynomial.mem_ideal_span_monomial_image]
  constructor
  · intro h s hs
    obtain ⟨t, ht, hts⟩ := h s hs
    exact ht.trans (finsupp_degree_mono hts)
  · intro h s hs
    exact ⟨s, h s hs, le_rfl⟩

/-- The kernel of evaluation at the origin is generated by the coordinate
variables. -/
theorem ker_constantCoeff_eq_span_X :
    RingHom.ker (MvPolynomial.constantCoeff : MvPolynomial σ K →+* K) =
      Ideal.span (Set.range (MvPolynomial.X : σ → MvPolynomial σ K)) := by
  ext p
  rw [RingHom.mem_ker,
    show Set.range (MvPolynomial.X : σ → MvPolynomial σ K) =
      MvPolynomial.X '' Set.univ by simp,
    MvPolynomial.mem_ideal_span_X_image]
  constructor
  · intro hp s hs
    have hs0 : s ≠ 0 := by
      intro h
      subst s
      exact (MvPolynomial.mem_support_iff.mp hs)
        (by simpa [MvPolynomial.constantCoeff_eq] using hp)
    obtain ⟨i, hi⟩ : ∃ i, s i ≠ 0 := by
      by_contra h
      push_neg at h
      apply hs0
      ext i
      simpa using h i
    exact ⟨i, Set.mem_univ i, hi⟩
  · intro hp
    rw [MvPolynomial.constantCoeff_eq]
    by_contra hzero
    have hz : (0 : σ →₀ ℕ) ∈ p.support := MvPolynomial.mem_support_iff.mpr hzero
    obtain ⟨i, -, hi⟩ := hp 0 hz
    exact hi rfl

/-- The origin ideal is exactly the degree-at-least-one monomial ideal. -/
theorem ker_constantCoeff_eq_totalDegreeAtLeastIdeal_one :
    RingHom.ker (MvPolynomial.constantCoeff : MvPolynomial σ K →+* K) =
      totalDegreeAtLeastIdeal (K := K) 1 := by
  ext p
  rw [RingHom.mem_ker, mem_totalDegreeAtLeastIdeal_iff]
  constructor
  · intro hp s hs
    have hs0 : s ≠ 0 := by
      intro h
      subst s
      exact (MvPolynomial.mem_support_iff.mp hs)
        (by simpa [MvPolynomial.constantCoeff_eq] using hp)
    exact (Nat.one_le_iff_ne_zero.mpr ((Finsupp.degree_eq_zero_iff s).not.mpr hs0))
  · intro hp
    rw [MvPolynomial.constantCoeff_eq]
    by_contra hzero
    have hz : (0 : σ →₀ ℕ) ∈ p.support := MvPolynomial.mem_support_iff.mpr hzero
    exact (Nat.not_succ_le_zero 0) (by simpa using hp 0 hz)

/-- Multiplication by one coordinate raises the lower total-degree bound by
one. -/
theorem X_mul_mem_totalDegreeAtLeastIdeal {e : ℕ} (i : σ)
    {p : MvPolynomial σ K}
    (hp : p ∈ totalDegreeAtLeastIdeal (K := K) e) :
    MvPolynomial.X i * p ∈ totalDegreeAtLeastIdeal (K := K) (e + 1) := by
  rw [mem_totalDegreeAtLeastIdeal_iff] at hp ⊢
  intro s hs
  rw [MvPolynomial.support_X_mul] at hs
  obtain ⟨t, ht, rfl⟩ := Finset.mem_map.mp hs
  change e + 1 ≤ Finsupp.degree (Finsupp.single i 1 + t)
  rw [map_add, Finsupp.degree_single]
  have := hp t ht
  omega

/-- The `e`-th power of the origin ideal contains no term of degree below
`e`. -/
theorem pow_ker_constantCoeff_le_totalDegreeAtLeastIdeal (e : ℕ) :
    RingHom.ker (MvPolynomial.constantCoeff : MvPolynomial σ K →+* K) ^ e ≤
      totalDegreeAtLeastIdeal (K := K) e := by
  induction e with
  | zero =>
      intro p _
      rw [mem_totalDegreeAtLeastIdeal_iff]
      exact fun _ _ ↦ Nat.zero_le _
  | succ e ih =>
      rw [pow_succ', ker_constantCoeff_eq_span_X, Ideal.mul_le]
      intro x hx y hy
      have hy₀ : y ∈
          RingHom.ker
            (MvPolynomial.constantCoeff : MvPolynomial σ K →+* K) ^ e := by
        rwa [ker_constantCoeff_eq_span_X]
      have hy' : y ∈ totalDegreeAtLeastIdeal (K := K) e := ih hy₀
      induction hx using Submodule.span_induction with
      | mem x hx =>
          obtain ⟨i, rfl⟩ := hx
          simpa only [Nat.succ_eq_add_one] using
            X_mul_mem_totalDegreeAtLeastIdeal i hy'
      | zero => simp
      | add x z _ _ hx hz =>
          simpa only [add_mul] using add_mem hx hz
      | smul a x _ hx =>
          change (a * x) * y ∈ totalDegreeAtLeastIdeal (K := K) (e + 1)
          rw [mul_assoc]
          exact (totalDegreeAtLeastIdeal (K := K) (e + 1)).mul_mem_left a hx

/-- Conversely, every monomial of degree at least `e` belongs to the `e`-th
power of the origin ideal. -/
theorem totalDegreeAtLeastIdeal_le_pow_ker_constantCoeff (e : ℕ) :
    totalDegreeAtLeastIdeal (K := K) e ≤
      RingHom.ker (MvPolynomial.constantCoeff : MvPolynomial σ K →+* K) ^ e := by
  rw [totalDegreeAtLeastIdeal, Ideal.span_le]
  rintro p ⟨s, hs, rfl⟩
  have hdegreeOne : MvPolynomial.homogeneousSubmodule σ K 1 ≤
      (RingHom.ker
        (MvPolynomial.constantCoeff : MvPolynomial σ K →+* K)).restrictScalars K := by
    intro q hq
    change MvPolynomial.constantCoeff q = 0
    rw [MvPolynomial.constantCoeff_eq]
    exact hq.coeff_eq_zero (by simp)
  have hpower : ∀ d : ℕ,
      MvPolynomial.homogeneousSubmodule σ K 1 ^ d ≤
        (RingHom.ker
          (MvPolynomial.constantCoeff : MvPolynomial σ K →+* K) ^ d).restrictScalars K := by
    intro d
    induction d with
    | zero => simp
    | succ d ih =>
        rw [pow_succ', Submodule.mul_le]
        intro x hx y hy
        change x * y ∈
          RingHom.ker
            (MvPolynomial.constantCoeff : MvPolynomial σ K →+* K) ^ (d + 1)
        rw [pow_succ']
        exact Ideal.mul_mem_mul (hdegreeOne hx) (ih hy)
  have hmonomial : MvPolynomial.monomial s (1 : K) ∈
      RingHom.ker
        (MvPolynomial.constantCoeff : MvPolynomial σ K →+* K) ^
          Finsupp.degree s :=
    hpower (Finsupp.degree s)
      (MvPolynomial.monomial_mem_homogeneousSubmodule_pow_degree (1 : K) s)
  exact Ideal.pow_le_pow_right hs hmonomial

/-- Powers of the origin ideal are exactly the monomial lower-degree
filtration. -/
theorem pow_ker_constantCoeff_eq_totalDegreeAtLeastIdeal (e : ℕ) :
    RingHom.ker (MvPolynomial.constantCoeff : MvPolynomial σ K →+* K) ^ e =
      totalDegreeAtLeastIdeal (K := K) e :=
  le_antisymm (pow_ker_constantCoeff_le_totalDegreeAtLeastIdeal e)
    (totalDegreeAtLeastIdeal_le_pow_ker_constantCoeff e)

/-- As a vector subspace, the degree-at-least ideal is the coordinate
subspace supported on the corresponding monomials. -/
theorem totalDegreeAtLeastIdeal_restrictScalars_eq_restrictSupport (e : ℕ) :
    (totalDegreeAtLeastIdeal (K := K) e).restrictScalars K =
      MvPolynomial.restrictSupport K
        {s : σ →₀ ℕ | e ≤ Finsupp.degree s} := by
  ext p
  change p ∈ totalDegreeAtLeastIdeal (K := K) e ↔ _
  rw [mem_totalDegreeAtLeastIdeal_iff]
  change (∀ s ∈ p.support, e ≤ Finsupp.degree s) ↔
    p ∈ Finsupp.supported K K {s : σ →₀ ℕ | e ≤ Finsupp.degree s}
  rw [Finsupp.mem_supported]
  rfl

/-- Monomials of degree at least `e` and monomials of degree below `e`
give complementary coordinate subspaces. -/
theorem isCompl_totalDegreeAtLeastIdeal_restrictScalars_restrictSupport_lt
    (e : ℕ) :
    IsCompl
      (show Submodule K (MvPolynomial σ K) from
        (totalDegreeAtLeastIdeal (K := K) e).restrictScalars K)
      (MvPolynomial.restrictSupport K
        {s : σ →₀ ℕ | Finsupp.degree s < e}) := by
  rw [totalDegreeAtLeastIdeal_restrictScalars_eq_restrictSupport
    (K := K) (σ := σ)]
  constructor
  · apply Finsupp.disjoint_supported_supported
    rw [Set.disjoint_left]
    exact fun _ hge hlt ↦ (Nat.not_lt_of_ge hge) hlt
  · apply Finsupp.codisjoint_supported_supported
    rw [codisjoint_iff]
    ext s
    change (e ≤ Finsupp.degree s ∨ Finsupp.degree s < e) ↔ True
    constructor
    · exact fun _ ↦ trivial
    · intro _
      exact (lt_or_ge (Finsupp.degree s) e).elim Or.inr Or.inl

/-! ## Stars and bars in arbitrary finite dimension -/

/-- Add a slack coordinate to an exponent vector of total degree at most
`k`. -/
def finExponentLEEquivFinSuccSum (r k : ℕ) :
    {P : Fin r →₀ ℕ // Finsupp.degree P ≤ k} ≃
      {Q : Fin (r + 1) → ℕ // ∑ i, Q i = k} where
  toFun P := ⟨Fin.cons (k - Finsupp.degree P.1) (fun i ↦ P.1 i), by
    rw [Fin.sum_univ_succ]
    simpa [Finsupp.degree_eq_sum] using Nat.sub_add_cancel P.2⟩
  invFun Q := ⟨Finsupp.equivFunOnFinite.symm (Fin.tail Q.1), by
    have htail :
        Finsupp.degree (Finsupp.equivFunOnFinite.symm (Fin.tail Q.1)) =
          ∑ i, Fin.tail Q.1 i := by
      rw [Finsupp.degree_eq_sum]
      rfl
    rw [htail]
    have hsum : Q.1 0 + ∑ i, Fin.tail Q.1 i = k := by
      simpa only [Fin.sum_univ_succ] using Q.2
    omega⟩
  left_inv P := by
    apply Subtype.ext
    apply Finsupp.ext
    intro i
    simp
  right_inv Q := by
    apply Subtype.ext
    funext i
    refine Fin.cases ?_ (fun j ↦ ?_) i
    · simp only [Fin.cons_zero]
      have htail :
          Finsupp.degree (Finsupp.equivFunOnFinite.symm (Fin.tail Q.1)) =
            ∑ j, Fin.tail Q.1 j := by
        rw [Finsupp.degree_eq_sum]
        rfl
      rw [htail]
      have hsum : Q.1 0 + ∑ j, Fin.tail Q.1 j = k := by
        simpa only [Fin.sum_univ_succ] using Q.2
      omega
    · change Q.1 j.succ = Q.1 j.succ
      rfl

/-- The number of monomials in `r` variables of total degree at most `k`.
-/
theorem natCard_finExponent_totalDegree_le (r k : ℕ) :
    Nat.card {P : Fin r →₀ ℕ // Finsupp.degree P ≤ k} =
      (k + r).choose r := by
  classical
  rw [Nat.card_congr (finExponentLEEquivFinSuccSum r k)]
  rw [← Nat.card_congr (Sym.equivNatSumOfFintype (Fin (r + 1)) k)]
  rw [Nat.card_eq_fintype_card, Sym.card_sym_eq_choose]
  simp only [Fintype.card_fin]
  have harg : r + 1 + k - 1 = r + k := by omega
  rw [harg]
  simpa [Nat.add_comm] using (Nat.choose_symm_add (a := r) (b := k)).symm

/-- The cumulative degree-`k` part of a polynomial ring in `r` variables
has the expected stars-and-bars dimension. -/
theorem finrank_mvPolynomial_restrictTotalDegree_fin
    (K : Type u) [Field K] (r k : ℕ) :
    Module.finrank K (MvPolynomial.restrictTotalDegree (Fin r) K k) =
      (k + r).choose r := by
  change Module.finrank K
    (MvPolynomial.restrictSupport K
      {P : Fin r →₀ ℕ | Finsupp.degree P ≤ k}) = (k + r).choose r
  rw [Module.finrank_eq_nat_card_basis
    (MvPolynomial.basisRestrictSupport K
      {P : Fin r →₀ ℕ | Finsupp.degree P ≤ k})]
  exact natCard_finExponent_totalDegree_le r k

/-! ## The truncated polynomial quotient -/

/-- The low-degree support subspace is the usual cumulative total-degree
subspace. -/
theorem restrictSupport_degree_lt_succ_eq_restrictTotalDegree
    (K : Type u) [Field K] (r k : ℕ) :
    MvPolynomial.restrictSupport K
        {s : Fin r →₀ ℕ | Finsupp.degree s < k + 1} =
      MvPolynomial.restrictTotalDegree (Fin r) K k := by
  apply congrArg (MvPolynomial.restrictSupport K)
  ext s
  change (Finsupp.degree s < k + 1) ↔
    s.sum (fun _ e ↦ e) ≤ k
  change (Finsupp.degree s < k + 1) ↔ Finsupp.degree s ≤ k
  omega

/-- The quotient by the `(k+1)`-st power of the origin ideal is linearly
equivalent to the polynomials of total degree at most `k`. -/
noncomputable def originPowerQuotientLinearEquivRestrictTotalDegree
    (K : Type u) [Field K] (r k : ℕ) :
    (MvPolynomial (Fin r) K ⧸
        RingHom.ker
          (MvPolynomial.constantCoeff : MvPolynomial (Fin r) K →+* K) ^ (k + 1))
      ≃ₗ[K] MvPolynomial.restrictTotalDegree (Fin r) K k := by
  rw [pow_ker_constantCoeff_eq_totalDegreeAtLeastIdeal]
  let E := Submodule.quotientEquivOfIsCompl
    (show Submodule K (MvPolynomial (Fin r) K) from
      (totalDegreeAtLeastIdeal (K := K) (k + 1)).restrictScalars K)
    (MvPolynomial.restrictSupport K
      {s : Fin r →₀ ℕ | Finsupp.degree s < k + 1})
    (isCompl_totalDegreeAtLeastIdeal_restrictScalars_restrictSupport_lt
      (K := K) (σ := Fin r) (k + 1))
  exact E.trans (LinearEquiv.ofEq _ _
    (restrictSupport_degree_lt_succ_eq_restrictTotalDegree K r k))

/-- Explicit dimension of the `k`-th jet of the origin in affine
`r`-space. -/
theorem finrank_originPowerQuotient_eq_choose
    (K : Type u) [Field K] (r k : ℕ) :
    Module.finrank K
        (MvPolynomial (Fin r) K ⧸
          RingHom.ker
            (MvPolynomial.constantCoeff : MvPolynomial (Fin r) K →+* K) ^ (k + 1)) =
      (k + r).choose r := by
  rw [(originPowerQuotientLinearEquivRestrictTotalDegree K r k).finrank_eq]
  exact finrank_mvPolynomial_restrictTotalDegree_fin K r k

end

end TranslatedDepthSeven
