import CubicTenVariables.CubicMassEquations
import CubicTenVariables.GeometricEquationDimensionProved

/-! The actual gradient ideal for the characteristic-zero slicing argument.
Its generators, homogeneity and geometric quotient dimension are supplied
internally. The singular cone need not be irreducible or reduced. -/

set_option autoImplicit false
noncomputable section
namespace CubicTenVariables.CubicGeometricSingularDimension
open MvPolynomial HessianTheorem11 CubicMassEquations
attribute [local instance] MvPolynomial.gradedAlgebra

variable {K L : Type*} [Field K] [Field L] {n : ℕ}

/-- The ideal generated by the actual first partial derivatives. -/
def gradientIdeal (F : MvPolynomial (Fin n) K) :
    Ideal (MvPolynomial (Fin n) K) :=
  equationIdeal (gradientEquation F)

theorem gradientIdeal_isHomogeneous (F : MvPolynomial (Fin n) K)
    (hF : F.IsHomogeneous 3) :
    (gradientIdeal F).IsHomogeneous (homogeneousSubmodule (Fin n) K) := by
  apply Ideal.homogeneous_span
  rintro _ ⟨i, rfl⟩
  exact ⟨2, hF.pderiv⟩

theorem gradientIdeal_map (ρ : K →+* L) (F : MvPolynomial (Fin n) K) :
    (gradientIdeal F).map (map ρ) = gradientIdeal (map ρ F) := by
  unfold gradientIdeal
  rw [map_equationIdeal]
  simp only [map_gradientEquation]

theorem mem_zeroLocus_gradientIdeal_iff (F : MvPolynomial (Fin n) K)
    (x : Fin n → K) :
    x ∈ zeroLocus K (gradientIdeal F) ↔ gradient F x = 0 := by
  rw [gradientIdeal, mem_zeroLocus_equationIdeal]
  simp only [eval_gradientEquation, funext_iff, Pi.zero_apply]

/-- The required affine-cone dimension bound holds for the literal
gradient ideal over the algebraic closure, before choosing generic normals.
No geometric primality hypothesis is imposed on this ideal. -/
theorem geometric_gradient_quotient_dimension_le_five
    (F : MvPolynomial (Fin 10) ℤ) (hF : F.IsHomogeneous 3)
    (hA : Anisotropic (map (Int.castRingHom ℚ) F)) :
    ringKrullDim (MvPolynomial (Fin 10) (AlgebraicClosure ℚ) ⧸
      gradientIdeal (map (Int.castRingHom (AlgebraicClosure ℚ)) F)) ≤ 5 := by
  have hmap : (rationalGradientIdeal F).map
      (map (algebraMap ℚ (AlgebraicClosure ℚ))) =
      gradientIdeal (map (Int.castRingHom (AlgebraicClosure ℚ)) F) := by
    rw [rationalGradientIdeal_eq]
    change (gradientIdeal (map (Int.castRingHom ℚ) F)).map _ = _
    rw [gradientIdeal_map, map_map]
    congr 2
  rw [← hmap, GeometricEquationDimensionProved.algebraicClosure_quotient_dimension]
  exact gradient_quotient_dimension_le_five F hF hA

end CubicTenVariables.CubicGeometricSingularDimension
