import TranslatedDepthSeven.NoetherNormalizationCoordinateRelations
import TranslatedDepthSeven.HomogeneousLinearNormalizationBoxCount
import TranslatedDepthSeven.RelativeComponentQuantitativeNormalization
import TranslatedDepthSeven.FixedConeResidueCount
import Mathlib.RingTheory.Localization.LocalizationLocalization

/-! Finite normalization of the original integral equation family. The
normalization coefficients and monic coordinate relations descend to one
principal localization. The equations themselves are exactly the original
integral equations mapped into that localization. A further nonzero element
clears the equality of the original ideal and its finite model, so the
resulting finite-field bound counts every zero of the original equations.
No geometric, prime-component, or literature assumption is used. -/

noncomputable section
namespace CubicTenVariables.FixedEquationNormalization
open MvPolynomial Polynomial TranslatedDepthSeven

set_option maxHeartbeats 4000000
set_option synthInstance.maxHeartbeats 300000

/-- The original equation family under the unique coefficient map from integers. -/
def equationsOver {N t : ℕ} (f : Fin t → MvPolynomial (Fin N) ℤ)
    (R : Type*) [CommRing R] : Fin t → MvPolynomial (Fin N) R :=
  fun i => MvPolynomial.map (Int.castRingHom R) (f i)

/-- The ideal generated by the original equations over a coefficient ring. -/
def equationIdeal {N t : ℕ} (f : Fin t → MvPolynomial (Fin N) ℤ)
    (R : Type*) [CommRing R] : Ideal (MvPolynomial (Fin N) R) :=
  Ideal.span (Set.range (equationsOver f R))

/-- An arbitrary coefficient map preserves the displayed integral equations. -/
theorem map_equationsOver {N t : ℕ}
    (f : Fin t → MvPolynomial (Fin N) ℤ)
    {R S : Type*} [CommRing R] [CommRing S] (ρ : R →+* S) (i : Fin t) :
    MvPolynomial.map ρ (equationsOver f R i) = equationsOver f S i := by
  unfold equationsOver
  have hcomp : ρ.comp (Int.castRingHom R) = Int.castRingHom S :=
    RingHom.ext_int _ _
  rw [MvPolynomial.map_map, hcomp]

/-- Specializing an original equation ideal gives exactly the original
ideal over the target coefficient ring. -/
theorem map_equationIdeal {N t : ℕ}
    (f : Fin t → MvPolynomial (Fin N) ℤ)
    {R S : Type*} [CommRing R] [CommRing S] (ρ : R →+* S) :
    (equationIdeal f R).map (MvPolynomial.map ρ) = equationIdeal f S := by
  rw [equationIdeal, equationIdeal, Ideal.map_span]
  congr 1
  ext g
  constructor
  · rintro ⟨_, ⟨i, rfl⟩, rfl⟩
    exact ⟨i, (map_equationsOver f ρ i).symm⟩
  · rintro ⟨i, rfl⟩
    exact ⟨equationsOver f R i, ⟨i, rfl⟩, map_equationsOver f ρ i⟩

/-- A proper rational equation quotient of dimension at most `r` has a
literal finite model over one principal localization, with at most `r`
parameters. Its displayed equations are exactly the original equations. -/
theorem exists_finite_model {N t r : ℕ}
    (f : Fin t → MvPolynomial (Fin N) ℤ)
    (hproper : equationIdeal f ℚ ≠ ⊤)
    (hdim : ringKrullDim (MvPolynomial (Fin N) ℚ ⧸ equationIdeal f ℚ) ≤
      (r : WithBot ℕ∞)) :
    ∃ s : ℕ, s ≤ r ∧ ∃ (Δ : ℤ) (hΔ : Δ ≠ 0),
      ∃ q : Fin s → MvPolynomial (Fin N) (Localization.Away Δ),
      ∃ p : Fin N → (MvPolynomial (Fin s) (Localization.Away Δ))[X],
        (∀ i, (p i).Monic) ∧
        Ideal.map (MvPolynomial.map
            (awayToFractionRing (R := ℤ) (K := ℚ) Δ hΔ))
            (finiteNormalizationModelIdeal
              (equationsOver f (Localization.Away Δ)) q p) = equationIdeal f ℚ ∧
        equationIdeal f (Localization.Away Δ) ≤
          finiteNormalizationModelIdeal (equationsOver f (Localization.Away Δ)) q p ∧
        (finiteNormalizationModelAlgHom
          (equationsOver f (Localization.Away Δ)) q p).Finite := by
  classical
  let I := equationIdeal f ℚ
  letI : Nontrivial (MvPolynomial (Fin N) ℚ ⧸ I) :=
    Ideal.Quotient.nontrivial_iff.mpr hproper
  obtain ⟨s, g, hinj, hfinite, p, hp⟩ :=
    exists_finite_normalization_with_quotient_coordinate_relations I hproper
  have hs : s ≤ r := by
    apply Nat.le_of_lt_succ
    apply normalization_parameter_lt_of_ringKrullDim_lt_nat
      g hinj hfinite.to_isIntegral
    exact lt_of_le_of_lt hdim (by exact_mod_cast Nat.lt_succ_self r)
  have hrepresentative : ∀ j : Fin s, ∃ qj : MvPolynomial (Fin N) ℚ,
      Ideal.Quotient.mk I qj = g (MvPolynomial.X j) := by
    intro j
    exact Ideal.Quotient.mk_surjective (g (MvPolynomial.X j))
  choose q hq using hrepresentative
  have hmap : (Ideal.Quotient.mkₐ ℚ I).comp (MvPolynomial.aeval q) = g := by
    apply MvPolynomial.algHom_ext
    intro j
    simpa using hq j
  have hrel : ∀ i, normalizationCoordinateRelation q p i ∈ I := by
    intro i
    apply Ideal.Quotient.eq_zero_iff_mem.mp
    have heval := Polynomial.hom_eval₂ (p i) (MvPolynomial.aeval q).toRingHom
      (Ideal.Quotient.mkₐ ℚ I).toRingHom (MvPolynomial.X i)
    have heq : Ideal.Quotient.mk I (normalizationCoordinateRelation q p i) =
        (p i).eval₂ g.toRingHom (Ideal.Quotient.mk I (MvPolynomial.X i)) := by
      rw [normalizationCoordinateRelation, ← hmap]
      exact heval
    rw [heq]
    exact (hp i).2
  obtain ⟨Δ, hΔ, f₀, q₀, p₀, hf₀, _hq₀, hp₀, _hp₀map, hmodel, hfinite₀⟩ :=
    exists_vertical_finite_normalization_model (R := ℤ) (K := ℚ)
      (equationsOver f ℚ) q p (fun i => (hp i).1) I rfl hrel
  have hactual : f₀ = equationsOver f (Localization.Away Δ) := by
    funext i
    apply MvPolynomial.map_injective
      (awayToFractionRing (R := ℤ) (K := ℚ) Δ hΔ)
      (awayToFractionRing_injective Δ hΔ)
    rw [hf₀ i, map_equationsOver]
  subst f₀
  refine ⟨s, hs, Δ, hΔ, q₀, p₀, hp₀, hmodel, ?_, hfinite₀⟩
  exact Ideal.span_mono Set.subset_union_left


/-- Vanishing on the actual equation ideal is exactly vanishing on each
original integral equation. -/
theorem mem_zeroLocus_equationIdeal_iff {N t : ℕ}
    (f : Fin t → MvPolynomial (Fin N) ℤ)
    (K : Type*) [CommRing K] (x : Fin N → K) :
    x ∈ affineIdealZeroLocusOver (R := K) (K := K) (equationIdeal f K) ↔
      ∀ i, MvPolynomial.eval₂ (Int.castRingHom K) x (f i) = 0 := by
  have heval : ∀ i, MvPolynomial.aeval x (equationsOver f K i) =
      MvPolynomial.eval₂ (Int.castRingHom K) x (f i) := by
    intro i
    rw [MvPolynomial.aeval_eq_eval, equationsOver, ← MvPolynomial.eval₂_eq_eval_map]
  constructor
  · intro hx i
    rw [← heval i]
    exact hx _ (Ideal.subset_span ⟨i, rfl⟩)
  · intro hx
    have hker : equationIdeal f K ≤
        RingHom.ker (MvPolynomial.aeval x).toRingHom := by
      apply Ideal.span_le.mpr
      rintro _ ⟨i, rfl⟩
      change MvPolynomial.aeval x (equationsOver f K i) = 0
      rw [heval]
      exact hx i
    exact fun g hg => hker hg

/-- Literal common zeros correspond to points of the original quotient. -/
def commonZerosEquivQuotientHom {N t : ℕ}
    (f : Fin t → MvPolynomial (Fin N) ℤ)
    (K : Type*) [CommRing K] :
    {x : Fin N → K // ∀ i, MvPolynomial.eval₂ (Int.castRingHom K) x (f i) = 0} ≃
      ((MvPolynomial (Fin N) K ⧸ equationIdeal f K) →ₐ[K] K) :=
  (Equiv.subtypeEquivRight (fun x => (mem_zeroLocus_equationIdeal_iff f K x).symm)).trans
    (affineIdealZeroLocusEquivQuotientAlgHomOver (R := K) (K := K) (equationIdeal f K))

/-- After excluding one nonzero element of one principal localization, a
fixed integral equation family has at most `C * (#K)^r` actual common zeros
in every finite-field specialization. The choices of denominator, excluded
element, and constant all precede the field and coefficient map. -/
theorem exists_specialization_bound {N t r : ℕ}
    (f : Fin t → MvPolynomial (Fin N) ℤ)
    (hproper : equationIdeal f ℚ ≠ ⊤)
    (hdim : ringKrullDim (MvPolynomial (Fin N) ℚ ⧸ equationIdeal f ℚ) ≤
      (r : WithBot ℕ∞)) :
    ∃ Δ : ℤ, Δ ≠ 0 ∧ ∃ δ : Localization.Away Δ, δ ≠ 0 ∧
      ∃ C : ℕ, 1 ≤ C ∧
        ∀ (K : Type) [Field K] [Finite K]
          (ρ : Localization.Away Δ →+* K), IsUnit (ρ δ) →
          Nat.card {x : Fin N → K //
            ∀ i, MvPolynomial.eval₂ (Int.castRingHom K) x (f i) = 0} ≤
            C * Nat.card K ^ r := by
  obtain ⟨s, hs, Δ, hΔ, q, p, hmonic, hmodel, hle, _hfinite⟩ :=
    exists_finite_model f hproper hdim
  let S := Localization.Away Δ
  letI : Algebra S ℚ := (awayToFractionRing (R := ℤ) (K := ℚ) Δ hΔ).toAlgebra
  letI : IsDomain S := IsLocalization.isDomain_of_le_nonZeroDivisors S
    (powers_le_nonZeroDivisors_of_noZeroDivisors hΔ)
  letI := IsScalarTower.of_algebraMap_eq (R := ℤ) (S := S) (A := ℚ)
    (fun z => (awayToFractionRing_algebraMap (R := ℤ) (K := ℚ) Δ hΔ z).symm)
  letI : IsFractionRing S ℚ :=
    IsFractionRing.isFractionRing_of_isLocalization (Submonoid.powers Δ) S ℚ
      (powers_le_nonZeroDivisors_of_noZeroDivisors hΔ)
  obtain ⟨δ, hδ, _hclear, _hquantitative, hbound⟩ :=
    exists_nonzero_base_open_quantitative_model_eq_componentClosure
      (equationIdeal f S) (equationsOver f S) q p hmonic
      (equationIdeal f ℚ) hle
      (map_equationIdeal f (algebraMap S ℚ)) hmodel
  refine ⟨Δ, hΔ, δ, hδ, max 1 (∏ i, (p i).natDegree), Nat.le_max_left _ _, ?_⟩
  intro K _ _ ρ hρ
  have hcount := hbound K ρ hρ
  rw [map_equationIdeal] at hcount
  calc
    Nat.card {x : Fin N → K //
        ∀ i, MvPolynomial.eval₂ (Int.castRingHom K) x (f i) = 0} =
        Nat.card ((MvPolynomial (Fin N) K ⧸ equationIdeal f K) →ₐ[K] K) :=
      Nat.card_congr (commonZerosEquivQuotientHom f K)
    _ ≤ (∏ i, (p i).natDegree) * Nat.card K ^ s := hcount
    _ ≤ max 1 (∏ i, (p i).natDegree) * Nat.card K ^ r :=
      Nat.mul_le_mul (Nat.le_max_right _ _)
        (Nat.pow_le_pow_right Nat.card_pos hs)

end CubicTenVariables.FixedEquationNormalization
