import Mathlib.FieldTheory.IntermediateField.Adjoin.Algebra
import Mathlib.RingTheory.AlgebraicIndependent.TranscendenceBasis

/-! Elementary field-generation facts for generic hyperplane avoidance.
One nonzero point coordinate lets each linear row equation recover one
normal coefficient. Adjoining the remaining coefficients increases
transcendence degree by at most their number. -/

set_option autoImplicit false
noncomputable section
open scoped BigOperators IntermediateField.algebraAdjoinAdjoin
namespace CubicTenVariables.GenericNormalParameterRecovery

universe u
variable {k Ω : Type u} [Field k] [Field Ω] [Algebra k Ω]

/-- A linear equation recovers its coefficient at any nonzero coordinate
inside the field generated by the other coefficients and point coordinates. -/
theorem coefficient_mem_of_linear_equation
    {σ : Type*} [Fintype σ] (L : IntermediateField k Ω)
    (x c : σ → Ω) (b : σ) (hxb : x b ≠ 0)
    (hx : ∀ i, x i ∈ L) (hc : ∀ i, i ≠ b → c i ∈ L)
    (hrow : ∑ i, c i * x i = 0) : c b ∈ L := by
  classical
  have hsum : (∑ i ∈ Finset.univ.erase b, c i * x i) + c b * x b = 0 := by
    rw [Finset.sum_erase_add _ _ (Finset.mem_univ b)]
    exact hrow
  have heq : c b = -(∑ i ∈ Finset.univ.erase b, c i * x i) / x b := by
    apply (eq_div_iff hxb).mpr
    apply eq_neg_iff_add_eq_zero.mpr
    simpa only [add_comm] using hsum
  rw [heq]
  apply L.div_mem (L.neg_mem (L.sum_mem ?_)) (hx b)
  intro i hi
  exact L.mul_mem (hc i (Finset.mem_erase.mp hi).1) (hx i)

/-- Every normal coefficient belongs to the field once the coefficients
away from one nonzero point coordinate do. -/
theorem all_coefficients_mem
    {σ τ : Type*} [Fintype σ] (L : IntermediateField k Ω)
    (x : σ → Ω) (γ : τ → σ → Ω) (b : σ) (hxb : x b ≠ 0)
    (hx : ∀ i, x i ∈ L) (hγ : ∀ r i, i ≠ b → γ r i ∈ L)
    (hrows : ∀ r, ∑ i, γ r i * x i = 0) :
    ∀ r i, γ r i ∈ L := by
  intro r i
  by_cases hi : i = b
  · subst i
    exact coefficient_mem_of_linear_equation L x (γ r) b hxb hx (hγ r) (hrows r)
  · exact hγ r i hi

/-- The field generated by m displayed elements has transcendence degree
at most m, whether or not those elements are algebraically independent. -/
theorem trdeg_adjoin_fin_le {m : ℕ} (z : Fin m → Ω) :
    Algebra.trdeg k (IntermediateField.adjoin k (Set.range z)) ≤ (m : Cardinal) := by
  let A := Algebra.adjoin k (Set.range z)
  let φ : MvPolynomial (Fin m) k →ₐ[k] A :=
    (MvPolynomial.aeval z).codRestrict A (by
      intro f
      change MvPolynomial.aeval z f ∈ Algebra.adjoin k (Set.range z)
      rw [Algebra.adjoin_range_eq_range_aeval]
      exact ⟨f, rfl⟩)
  have hsurj : Function.Surjective φ := by
    intro a
    have ha : (a : Ω) ∈
        (MvPolynomial.aeval z : MvPolynomial (Fin m) k →ₐ[k] Ω).range := by
      rw [← Algebra.adjoin_range_eq_range_aeval]
      exact a.property
    obtain ⟨f, hf⟩ := ha
    exact ⟨f, Subtype.ext hf⟩
  have hA : Algebra.trdeg k A ≤ (m : Cardinal) := by
    simpa using trdeg_le_of_surjective φ hsurj
  have htower := trdeg_add_eq k A (A := IntermediateField.adjoin k (Set.range z))
  rw [trdeg_eq_zero (R := A) (A := IntermediateField.adjoin k (Set.range z)),
    add_zero] at htower
  exact htower.symm.trans_le hA

end CubicTenVariables.GenericNormalParameterRecovery
