import CubicTenVariables.HomogeneousMacaulayCertificates
import Mathlib.LinearAlgebra.Matrix.NonsingularInverse

/-! A square coefficient determinant transports homogeneous monomial
certificates to a principal open neighborhood of a parameter. The determinant
is exactly one at the original parameter. No fiber-dimension semicontinuity
or identification of bad-parameter closures is used or asserted. -/

noncomputable section
namespace CubicTenVariables.HomogeneousFamilyDeterminant
open MvPolynomial HomogeneousMacaulayCertificates
open scoped BigOperators

variable {n N : ℕ} {K : Type*} [Field K]
local instance : Fintype (monomialIndices n N) := Fintype.ofFinite _
local instance : DecidableEq (monomialIndices n N) := Classical.decEq _

/-- Rows contain the actual coefficients of the given degree-N forms. -/
def coefficientMatrix {R : Type*} [CommRing R]
    (G : monomialIndices n N → MvPolynomial (Fin n) R) :
    Matrix (monomialIndices n N) (monomialIndices n N) R :=
  fun i j => coeff j.val (G i)

/-- An invertible square coefficient matrix spans every degree-N monomial
inside the ideal generated by its actual rows. -/
theorem monomial_mem_of_det_ne_zero
    (G : monomialIndices n N → MvPolynomial (Fin n) K)
    (hG : ∀ i, (G i).IsHomogeneous N)
    (hdet : (coefficientMatrix G).det ≠ 0) (j : monomialIndices n N) :
    monomial j.val 1 ∈ Ideal.span (Set.range G) := by
  classical
  let M := coefficientMatrix G
  have hsurj : Function.Surjective M.transpose.mulVec :=
    Matrix.mulVec_surjective_iff_isUnit.mpr
      ((Matrix.isUnit_iff_isUnit_det M.transpose).mpr
        (isUnit_iff_ne_zero.mpr (by simpa only [Matrix.det_transpose] using hdet)))
  obtain ⟨b,hb⟩ := hsurj (Pi.single j (1 : K))
  have hsumhom : (∑ i, b i • G i).IsHomogeneous N := by
    exact (homogeneousSubmodule (Fin n) K N).sum_mem
      (fun i _ => (homogeneousSubmodule (Fin n) K N).smul_mem (b i) (hG i))
  have heq : (∑ i, b i • G i) = monomial j.val 1 := by
    ext s
    by_cases hs : s.degree = N
    · let t : monomialIndices n N := ⟨s,hs⟩
      have ht := congrFun hb t
      change (∑ i, coeff t.val (G i) * b i) = ((Pi.single j (1 : K) : monomialIndices n N → K) t) at ht
      by_cases hjs : j.val = s
      · have hjt : j = t := Subtype.ext hjs
        subst j
        simpa only [coeff_sum, coeff_smul, smul_eq_mul, coeff_monomial,
          Pi.single_apply, t, if_pos rfl, mul_comm] using ht
      · have hjt : j ≠ t := fun h => hjs (congrArg Subtype.val h)
        simpa only [coeff_sum, coeff_smul, smul_eq_mul, coeff_monomial,
          Pi.single_apply, if_neg hjt, if_neg (Ne.symm hjt), t, if_neg hjs,
          mul_comm] using ht
    · rw [hsumhom.coeff_eq_zero hs]
      have hne : j.val ≠ s := fun h => hs (h ▸ j.property)
      simp only [coeff_monomial, if_neg hne]
  rw [← heq]
  apply (Ideal.span (Set.range G)).restrictScalars K |>.sum_mem
  intro i _
  exact ((Ideal.span (Set.range G)).restrictScalars K).smul_mem _
    (Ideal.subset_span ⟨i,rfl⟩)

variable {τ ι : Type*} [Fintype ι]

/-- Keep the original coefficient certificates fixed while varying the
parameter-dependent homogeneous generators. -/
def assembled (f : ι → MvPolynomial (Fin n) (MvPolynomial τ K))
    (c : monomialIndices n N → ι → MvPolynomial (Fin n) K)
    (s : monomialIndices n N) : MvPolynomial (Fin n) (MvPolynomial τ K) :=
  ∑ j, map C (c s j) * f j

@[simp] theorem assembled_map
    (f : ι → MvPolynomial (Fin n) (MvPolynomial τ K))
    (c : monomialIndices n N → ι → MvPolynomial (Fin n) K)
    (y : τ → K) (s : monomialIndices n N) :
    map (eval y) (assembled f c s) = ∑ j, c s j * map (eval y) (f j) := by
  have hcomp : (eval y).comp (C : K →+* MvPolynomial τ K) = RingHom.id K := by
    ext a
    simp
  simp [assembled, map_map, hcomp, MvPolynomial.map_id]

theorem assembled_homogeneous
    (f : ι → MvPolynomial (Fin n) (MvPolynomial τ K)) (e : ι → ℕ)
    (hf : ∀ j, (f j).IsHomogeneous (e j))
    (c : monomialIndices n N → ι → MvPolynomial (Fin n) K)
    (hc : ∀ s j, (c s j).IsHomogeneous (N-e j))
    (hz : ∀ s j, N<e j → c s j=0) (s : monomialIndices n N) :
    (assembled f c s).IsHomogeneous N := by
  classical
  apply (homogeneousSubmodule (Fin n) (MvPolynomial τ K) N).sum_mem
  intro j _
  by_cases hj : e j ≤ N
  · simpa only [Nat.sub_add_cancel hj] using ((hc s j).map C).mul (hf j)
  · simp only [hz s j (Nat.lt_of_not_ge hj), map_zero, zero_mul]
    exact isHomogeneous_zero _ _ _

/-- Literal certificates at one parameter produce a determinant equal to
one there. Its nonvanishing preserves all degree-N monomial identities. -/
theorem exists_principal_neighborhood
    (f : ι → MvPolynomial (Fin n) (MvPolynomial τ K)) (e : ι → ℕ)
    (hf : ∀ j, (f j).IsHomogeneous (e j)) (y₀ : τ → K)
    (c : monomialIndices n N → ι → MvPolynomial (Fin n) K)
    (hc : ∀ s j, (c s j).IsHomogeneous (N-e j))
    (hz : ∀ s j, N<e j → c s j=0)
    (hcert : ∀ s, monomial s.val 1 = ∑ j, c s j * map (eval y₀) (f j)) :
    ∃ D : MvPolynomial τ K, eval y₀ D=1 ∧
      ∀ y : τ → K, eval y D≠0 →
        ∃ c' : monomialIndices n N → ι → MvPolynomial (Fin n) K,
          (∀ s, monomial s.val 1 = ∑ j, c' s j * map (eval y) (f j)) ∧
          (∀ s j, (c' s j).IsHomogeneous (N-e j)) ∧
          ∀ s j, N<e j → c' s j=0 := by
  classical
  let G := assembled f c
  let M := coefficientMatrix G
  have hmap (y : τ → K) : M.map (eval y) =
      coefficientMatrix (fun s => map (eval y) (G s)) := by
    ext i j
    simp only [M, coefficientMatrix, Matrix.map_apply, coeff_map]
  have hone : M.map (eval y₀) = 1 := by
    rw [hmap]
    ext i j
    change coeff j.val (map (eval y₀) (assembled f c i)) = _
    rw [assembled_map, ← hcert]
    simp only [coeff_monomial, Matrix.one_apply]
    by_cases hij : i = j
    · subst j
      simp
    · have hv : i.val ≠ j.val := fun h => hij (Subtype.ext h)
      simp [hij,hv]
  refine ⟨M.det, ?_, ?_⟩
  · rw [RingHom.map_det]
    change (M.map (eval y₀)).det = 1
    rw [hone, Matrix.det_one]
  · intro y hy
    let f' := fun j => map (eval y) (f j)
    let G' := fun s => map (eval y) (G s)
    have hh : ∀ s, (G' s).IsHomogeneous N :=
      fun s => (assembled_homogeneous f e hf c hc hz s).map (eval y)
    have hdet : (coefficientMatrix G').det ≠ 0 := by
      rw [RingHom.map_det] at hy
      change (M.map (eval y)).det ≠ 0 at hy
      rw [hmap] at hy
      exact hy
    have hle : Ideal.span (Set.range G') ≤ Ideal.span (Set.range f') := by
      apply Ideal.span_le.mpr
      rintro _ ⟨s,rfl⟩
      change map (eval y) (assembled f c s) ∈ _
      rw [assembled_map]
      exact Ideal.sum_mem _ (fun j _ =>
        Ideal.mul_mem_left _ _ (Ideal.subset_span ⟨j,rfl⟩))
    have h (s : monomialIndices n N) :=
      HomogeneousSpanCertificates.exists_homogeneous_coefficients f' e
        (fun j => (hf j).map (eval y)) (monomial s.val 1) N
        (isHomogeneous_monomial 1 s.property)
        (hle (monomial_mem_of_det_ne_zero G' hh hdet s))
    choose c' hcert' hc' hz' using h
    exact ⟨c',hcert',hc',hz'⟩

/-- Finiteness of one homogeneous fiber supplies the certificates internally,
and persists on the displayed principal open; all its common zeros are zero. -/
theorem exists_principal_neighborhood_of_finite_quotient
    (f : ι → MvPolynomial (Fin n) (MvPolynomial τ K)) (e : ι → ℕ)
    (hf : ∀ j, (f j).IsHomogeneous (e j)) (y₀ : τ → K)
    [Module.Finite K (MvPolynomial (Fin n) K ⧸
      Ideal.span (Set.range (fun j => map (eval y₀) (f j))))] :
    ∃ D : MvPolynomial τ K, eval y₀ D=1 ∧
      ∀ y : τ → K, eval y D≠0 →
        Module.Finite K (MvPolynomial (Fin n) K ⧸
          Ideal.span (Set.range (fun j => map (eval y) (f j)))) ∧
        ∀ x : Fin n → K, (∀ j, eval x (map (eval y) (f j))=0) → x=0 := by
  obtain ⟨N,hN,c,hcert,hc,hz⟩ := exists_common_degree_certificates
    (fun j => map (eval y₀) (f j)) e (fun j => (hf j).map (eval y₀))
  obtain ⟨D,hD,hopen⟩ := exists_principal_neighborhood f e hf y₀ c hc hz hcert
  refine ⟨D,hD,?_⟩
  intro y hy
  obtain ⟨c',hcert',_,_⟩ := hopen y hy
  exact ⟨finite_quotient_of_certificates _ N hN c' hcert',
    zero_of_certificates _ N c' hcert'⟩

end CubicTenVariables.HomogeneousFamilyDeterminant
