import CubicTenVariables.HomogeneousPowerCertificates
import CubicTenVariables.HomogeneousSpanCertificates
import CubicTenVariables.TotalDegreePowerSpan
import CubicTenVariables.FixedEquationDimensionReduction

/-! A characteristic-free converse to finite homogeneous cutting. A finite
cut quotient gives coordinate-power relations whose other coefficients have
lower degree. Degree induction makes the original quotient finite over the
algebra generated by the supplied linear forms. Consequently its Krull
dimension is at most the number of forms, over every field. -/

noncomputable section
namespace CubicTenVariables.HomogeneousFiniteCutAlgebra
open MvPolynomial
open scoped BigOperators
attribute [local instance] MvPolynomial.gradedAlgebra
set_option maxHeartbeats 2000000
set_option synthInstance.maxHeartbeats 300000

variable {n s : ℕ} {K : Type*} [Field K]

/-- The actual algebra map defined by the supplied forms. -/
def formsHom (I : Ideal (MvPolynomial (Fin n) K))
    (L : Fin s → MvPolynomial (Fin n) K) :
    MvPolynomial (Fin s) K →ₐ[K] MvPolynomial (Fin n) K ⧸ I :=
  (Ideal.Quotient.mkₐ K I).comp (aeval L)

/-- Extracting the top homogeneous component gives coefficients of degree
strictly below the coordinate power. -/
theorem power_relation_of_cut_membership
    (I : Ideal (MvPolynomial (Fin n) K))
    (hI : I.IsHomogeneous (homogeneousSubmodule (Fin n) K))
    (L : Fin s → MvPolynomial (Fin n) K) (hL : ∀ j, (L j).IsHomogeneous 1)
    (i : Fin n) (d : ℕ) (hd : 0 < d)
    (hpow : X i ^ d ∈ I ⊔ Ideal.span (Set.range L)) :
    ∃ c : Fin s → MvPolynomial (Fin n) K,
      X i ^ d - ∑ j, c j * L j ∈ I ∧ ∀ j, (c j).totalDegree < d := by
  classical
  obtain ⟨f,hf,g,hg,heq⟩ := Submodule.mem_sup.mp hpow
  obtain ⟨a,ha⟩ := Ideal.mem_span_range_iff_exists_fun.mp hg
  have he : X i ^ d - ∑ j, a j * L j = f := by rw [ha, ← heq]; ring
  have hmem : X i ^ d - ∑ j, a j * L j ∈ I := he ▸ hf
  have htop := hI d hmem
  change (MvPolynomial.decomposition.decompose'
    (X i ^ d - ∑ j, a j * L j) d : MvPolynomial (Fin n) K) ∈ I at htop
  rw [MvPolynomial.decomposition.decompose'_apply, map_sub, map_sum,
    homogeneousComponent_of_mem (isHomogeneous_X_pow i d), if_pos rfl] at htop
  have hd1 : 1 ≤ d := by omega
  simp only [HomogeneousSpanCertificates.homogeneousComponent_mul_right _ _ (hL _) d,
    if_pos hd1] at htop
  refine ⟨fun j => homogeneousComponent (d - 1) (a j), htop, ?_⟩
  intro j
  exact (homogeneousComponent_isHomogeneous (d - 1) (a j)).totalDegree_le.trans_lt
    (Nat.sub_lt hd (by decide))

/-- Actual coordinate-power relations, derived from the finite cut quotient.
The ideal and the final quotient may be nonreduced or improper. -/
theorem exists_power_relations
    (I : Ideal (MvPolynomial (Fin n) K))
    (hI : I.IsHomogeneous (homogeneousSubmodule (Fin n) K))
    (L : Fin s → MvPolynomial (Fin n) K) (hL : ∀ j, (L j).IsHomogeneous 1)
    [Module.Finite K (MvPolynomial (Fin n) K ⧸
      (I ⊔ Ideal.span (Set.range L)))] :
    ∃ (d : Fin n → ℕ) (c : Fin n → Fin s → MvPolynomial (Fin n) K),
      (∀ i, 0 < d i) ∧
      (∀ i, X i ^ d i - ∑ j, c i j * L j ∈ I) ∧
      ∀ i j, (c i j).totalDegree < d i := by
  classical
  have hJ : (I ⊔ Ideal.span (Set.range L)).IsHomogeneous
      (homogeneousSubmodule (Fin n) K) := by
    apply hI.sup
    apply Ideal.homogeneous_span
    rintro _ ⟨j,rfl⟩
    exact ⟨1,hL j⟩
  have hp := HomogeneousPowerCertificates.exists_coordinate_power_mem
    (I ⊔ Ideal.span (Set.range L)) hJ
  choose d hd hpow using hp
  have hc := fun i => power_relation_of_cut_membership I hI L hL i (d i) (hd i) (hpow i)
  choose c hrel hdeg using hc
  exact ⟨d,c,hd,hrel,hdeg⟩

/-- Degree induction over the parameter algebra, with the original forms as
scalar coefficients, proves module finiteness from the displayed relations. -/
theorem formsHom_finite_of_power_relations
    (I : Ideal (MvPolynomial (Fin n) K))
    (L : Fin s → MvPolynomial (Fin n) K)
    (d : Fin n → ℕ) (c : Fin n → Fin s → MvPolynomial (Fin n) K)
    (hrel : ∀ i, X i ^ d i - ∑ j, c i j * L j ∈ I)
    (hdeg : ∀ i j, (c i j).totalDegree < d i) : (formsHom I L).Finite := by
  classical
  let A := MvPolynomial (Fin n) K ⧸ I
  let S := MvPolynomial (Fin s) K
  let h := formsHom I L
  letI : Algebra S A := h.toRingHom.toAlgebra
  letI : Module S A := Algebra.toModule
  let q := Ideal.Quotient.mkₐ K I
  let W : Submodule S A :=
    Submodule.span S (Set.range (TotalDegreePowerSpan.boundedMonomial I d))
  have hbounded (e : Fin n →₀ ℕ) (he : ∀ i, e i < d i) (a : K) :
      q (monomial e a) ∈ W := by
    let b : ∀ i, Fin (d i) := fun i => ⟨e i,he i⟩
    have hb : TotalDegreePowerSpan.boundedExponent d b = e := by ext i; simp [b]
    have hm : q (monomial e 1) ∈ W :=
      Submodule.subset_span ⟨b,by simp only [TotalDegreePowerSpan.boundedMonomial,hb]; rfl⟩
    convert W.smul_mem (C a : S) hm using 1
    change q (monomial e a) = h (C a) * q (monomial e 1)
    have hC : h (C a) = q (C a) := by simp [h,formsHom,q]
    rw [hC,← map_mul,C_mul_monomial,mul_one]
  have hmon : ∀ (e : Fin n →₀ ℕ) (a : K), q (monomial e a) ∈ W := by
    intro e
    refine ((measure (fun e : Fin n →₀ ℕ => e.degree)).wf).induction
      (C := fun e => ∀ a : K, q (monomial e a) ∈ W) e ?_
    intro e ih a
    by_cases he : ∀ i, e i < d i
    · exact hbounded e he a
    obtain ⟨i,hi⟩ : ∃ i, d i ≤ e i := by push_neg at he; exact he
    let e' := e - Finsupp.single i (d i)
    have hsplit : e' + Finsupp.single i (d i) = e :=
      tsub_add_cancel_of_le (Finsupp.single_le_iff.mpr hi)
    have hdegree : e'.degree + d i = e.degree := by
      rw [← Finsupp.degree_single i (d i), ← map_add, hsplit]
    have hfactor : (monomial e a : MvPolynomial (Fin n) K) =
        monomial e' a * X i ^ d i := by
      rw [X_pow_eq_monomial, monomial_mul, mul_one, hsplit]
    have hq : q (X i ^ d i) = ∑ j, q (c i j) * q (L j) := by
      have hh : q (X i ^ d i) = q (∑ j, c i j * L j) :=
        Ideal.Quotient.eq.mpr (hrel i)
      simpa only [map_sum,map_mul] using hh
    rw [hfactor,map_mul,hq,Finset.mul_sum]
    apply W.sum_mem
    intro j _
    let P : MvPolynomial (Fin n) K := monomial e' a * c i j
    have hP : P.totalDegree < e.degree := by
      have hm := totalDegree_monomial_le e' a
      have hmul := totalDegree_mul (monomial e' a) (c i j)
      have hc := hdeg i j
      change (monomial e' a * c i j).totalDegree < e.degree
      change (monomial e' a).totalDegree ≤ e'.degree at hm
      omega
    have hPmem : q P ∈ W := by
      rw [P.as_sum,map_sum]
      exact W.sum_mem (fun f hf => ih f ((le_totalDegree hf).trans_lt hP) _)
    convert W.smul_mem (X j : S) hPmem using 1
    change q (monomial e' a) * (q (c i j) * q (L j)) = h (X j) * q P
    simp only [h,formsHom,AlgHom.comp_apply,aeval_X,P,map_mul]
    ring
  change Module.Finite S A
  apply Module.finite_def.mpr
  have hW : W = ⊤ := by
    apply top_unique
    intro x _
    obtain ⟨P,rfl⟩ := Ideal.Quotient.mk_surjective x
    change q P ∈ W
    rw [P.as_sum,map_sum]
    exact W.sum_mem (fun e _ => hmon e _)
  rw [← hW]
  exact Submodule.fg_span (Set.finite_range _)

/-- The original quotient is finite over the polynomial algebra whose
variables map to the given linear forms. This holds in every characteristic. -/
theorem formsHom_finite_of_finite_cut
    (I : Ideal (MvPolynomial (Fin n) K))
    (hI : I.IsHomogeneous (homogeneousSubmodule (Fin n) K))
    (L : Fin s → MvPolynomial (Fin n) K) (hL : ∀ j, (L j).IsHomogeneous 1)
    [Module.Finite K (MvPolynomial (Fin n) K ⧸
      (I ⊔ Ideal.span (Set.range L)))] : (formsHom I L).Finite := by
  obtain ⟨d,c,_hd,hrel,hdeg⟩ := exists_power_relations I hI L hL
  exact formsHom_finite_of_power_relations I L d c hrel hdeg

/-- Characteristic-free dimension bound from a finite homogeneous linear cut.
No geometric-field, perfectness, properness, or radicality input is needed. -/
theorem quotient_dimension_le_of_finite_linear_cuts
    (I : Ideal (MvPolynomial (Fin n) K))
    (hI : I.IsHomogeneous (homogeneousSubmodule (Fin n) K))
    (L : Fin s → MvPolynomial (Fin n) K) (hL : ∀ j, (L j).IsHomogeneous 1)
    [Module.Finite K (MvPolynomial (Fin n) K ⧸
      (I ⊔ Ideal.span (Set.range L)))] :
    ringKrullDim (MvPolynomial (Fin n) K ⧸ I) ≤ (s : WithBot ℕ∞) := by
  letI : Algebra (MvPolynomial (Fin s) K) (MvPolynomial (Fin n) K ⧸ I) :=
    (formsHom I L).toRingHom.toAlgebra
  letI : Module (MvPolynomial (Fin s) K) (MvPolynomial (Fin n) K ⧸ I) :=
    Algebra.toModule
  letI : Module.Finite (MvPolynomial (Fin s) K) (MvPolynomial (Fin n) K ⧸ I) :=
    formsHom_finite_of_finite_cut I hI L hL
  letI : Algebra.IsIntegral (MvPolynomial (Fin s) K) (MvPolynomial (Fin n) K ⧸ I) :=
    Algebra.IsIntegral.of_finite _ _
  simpa only [FixedEquationDimensionReduction.polynomial_dimension] using
    (TranslatedDepthSeven.ringKrullDim_le_of_isIntegral
      (R := MvPolynomial (Fin s) K) (S := MvPolynomial (Fin n) K ⧸ I))

end CubicTenVariables.HomogeneousFiniteCutAlgebra
