import CubicTenVariables.TranslatedHessianMinors
import CubicTenVariables.CubicMassEquations
import CubicTenVariables.HessianRankStrataTen
import CubicTenVariables.SmithProfileNumerics

/-!
# Rational geometry of the fixed homogeneous Hessian-minor family

The literal unshifted minors define the full Hessian rank locus; no cubic
zero equation is added. Existing proved geometry supplies properness and
the ten-variable dimension table required for arbitrary constant translations.
-/

noncomputable section
namespace CubicTenVariables.TranslatedHessianLeadingGeometry
open MvPolynomial HessianTheorem11 TranslatedHessianMinors

/-- Natural version of the manuscript's ten-variable translated-rank exponent. -/
def tauNat (r : ℕ) : ℕ :=
  if r = 0 then 0 else if r < 10 then min (r+2) 9 else 10

theorem tauNat_eq_tau (r : ℕ) : (tauNat r : ℚ) = SmithProfileNumerics.tau r := by
  unfold tauNat SmithProfileNumerics.tau
  split_ifs <;> push_cast <;> simp only [min_comm]

variable {n : ℕ}

/-- The ideal generated by exactly the fixed homogeneous Hessian-minor equations. -/
def rationalIdeal (F : MvPolynomial (Fin n) ℤ) (r : ℕ) :
    Ideal (MvPolynomial (Fin n) ℚ) :=
  Ideal.span (Set.range (fun i : MinorIndex n r =>
    equation (hessianPolynomial (map (Int.castRingHom ℚ) F)) i))

/-- The origin satisfies every positive-size homogeneous minor, so the
ideal is proper without any anisotropy premise. -/
theorem rationalIdeal_ne_top (F : MvPolynomial (Fin n) ℤ)
    (hF : F.IsHomogeneous 3) (r : ℕ) : rationalIdeal F r ≠ ⊤ := by
  apply CubicMassEquations.equationIdeal_ne_top_of_zero _ 0
  intro i
  exact eval_origin_of_positive_homogeneous
    (equation_isHomogeneous _ (hessian_entries_isHomogeneous _ (hF.map _)) i) (degree_pos i).ne'

/-- Scalar extension cuts out the full geometric rank locus, with no F=0
condition, smoothness condition, or chosen irreducible component. -/
theorem geometric_zeroLocus_eq (F : MvPolynomial (Fin n) ℤ) (r : ℕ) :
    zeroLocus GeometricField ((rationalIdeal F r).map
      (map (algebraMap ℚ GeometricField))) =
      rankAtMostLocus (map (Int.castRingHom ℚ) F) r := by
  change zeroLocus GeometricField
    ((CubicMassEquations.equationIdeal (fun i : MinorIndex n r =>
      equation (hessianPolynomial (map (Int.castRingHom ℚ) F)) i)).map _) = _
  rw [CubicMassEquations.map_equationIdeal]
  ext x
  rw [CubicMassEquations.mem_zeroLocus_equationIdeal]
  have hz := hessian_translatedEquation_zero_iff
    (algebraMap ℚ GeometricField) (map (Int.castRingHom ℚ) F) 0 r x
  simpa only [rankAtMostLocus, geometricPolynomial, Set.mem_setOf_eq,
    translatedEquation, translatedMinor, Matrix.map_zero, map_zero, add_zero, zero_add,
    equation, eval_map] using hz

/-- The exact rational equation quotient satisfies the source dimension
bound at every rank label, including zero and all r≥10. -/
theorem quotient_dimension_le (F : MvPolynomial (Fin 10) ℤ)
    (hF : F.IsHomogeneous 3)
    (hA : Anisotropic (map (Int.castRingHom ℚ) F)) (r : ℕ) :
    ringKrullDim (MvPolynomial (Fin 10) ℚ ⧸ rationalIdeal F r) ≤
      (tauNat r : Dimension) := by
  rw [← RationalEquationDimension.rational_quotient_dimension_eq_geometric_zeroLocus
    _ (rationalIdeal_ne_top F hF r), geometric_zeroLocus_eq]
  let Q : AnisotropicCubic 10 := ⟨map (Int.castRingHom ℚ) F, hF.map _, hA⟩
  by_cases hr0 : r = 0
  · subst r
    simpa only [tauNat, if_pos rfl, Nat.cast_zero] using (Geometry.hessianRankZero Q).2.le
  by_cases hr : r < 10
  · simpa only [tauNat, if_neg hr0, if_pos hr] using
      Geometry.hessianRankLocus_dimension_le_min Q r (by omega)
  · have hb := affineDimension_mono
      (Set.subset_univ (rankAtMostLocus Q.polynomial r))
    rw [affineDimension_univ_from_generic_rank Unconditional.genericRankOpen 10] at hb
    simpa only [tauNat, if_neg hr0, if_neg hr] using hb

/-- The properness and dimension facts packaged for the fixed-family
normalization/counting API. No finite-field estimate is a premise. -/
theorem proper_and_dimension_le (F : MvPolynomial (Fin 10) ℤ)
    (hF : F.IsHomogeneous 3)
    (hA : Anisotropic (map (Int.castRingHom ℚ) F)) (r : ℕ) :
    rationalIdeal F r ≠ ⊤ ∧
      ringKrullDim (MvPolynomial (Fin 10) ℚ ⧸ rationalIdeal F r) ≤
        (tauNat r : Dimension) :=
  ⟨rationalIdeal_ne_top F hF r, quotient_dimension_le F hF hA r⟩

end CubicTenVariables.TranslatedHessianLeadingGeometry
