import HessianTheorem11.QuadraticCommonRadical
import HessianTheorem11.FourQuadricsClassification
import HessianTheorem11.ThreeQuadricsClassification

/-! The four-product quadratic classification gives an actual joint
 differential radical of codimension at most four. -/
noncomputable section
namespace HessianTheorem11
open MvPolynomial Matrix Module
variable {K : Type*} [Field K] [CharZero K] {n : ℕ}

theorem four_product_tuple_radical_large
    (P : Fin 4 → MvPolynomial (Fin n) K)
    (u₁ u₂ v₁ v₂ : MvPolynomial (Fin n) K)
    (hu₁ : u₁.IsHomogeneous 1) (hu₂ : u₂.IsHomogeneous 1)
    (hv₁ : v₁.IsHomogeneous 1) (hv₂ : v₂.IsHomogeneous 1)
    (h0 : P 0 = u₁ * v₁) (h1 : P 1 = u₁ * v₂)
    (h2 : P 2 = u₂ * v₁) (h3 : P 3 = u₂ * v₂) :
    n ≤ finrank K (polynomialTupleDifferentialRadical P) + 4 := by
  let B : Matrix (Fin 4) (Fin n) K := fun i =>
    ![ReducibleCubicRank.linearCoefficient u₁, ReducibleCubicRank.linearCoefficient u₂,
      ReducibleCubicRank.linearCoefficient v₁, ReducibleCubicRank.linearCoefficient v₂] i
  let L := LinearMap.ker B.mulVecLin
  have hle : L ≤ polynomialTupleDifferentialRadical P := by
    intro w hw
    have hBu₁ : eval w u₁ = 0 := by
      rw [ReducibleCubicRank.eval_linear u₁ hu₁]
      exact congrFun hw 0
    have hBu₂ : eval w u₂ = 0 := by
      rw [ReducibleCubicRank.eval_linear u₂ hu₂]
      exact congrFun hw 1
    have hBv₁ : eval w v₁ = 0 := by
      rw [ReducibleCubicRank.eval_linear v₁ hv₁]
      exact congrFun hw 2
    have hBv₂ : eval w v₂ = 0 := by
      rw [ReducibleCubicRank.eval_linear v₂ hv₂]
      exact congrFun hw 3
    rw [mem_polynomialTupleDifferentialRadical]
    intro x i
    have hu₁' := polynomialDifferential_homogeneous_one u₁ hu₁ x w
    have hu₂' := polynomialDifferential_homogeneous_one u₂ hu₂ x w
    have hv₁' := polynomialDifferential_homogeneous_one v₁ hv₁ x w
    have hv₂' := polynomialDifferential_homogeneous_one v₂ hv₂ x w
    rw [hBu₁] at hu₁'
    rw [hBu₂] at hu₂'
    rw [hBv₁] at hv₁'
    rw [hBv₂] at hv₂'
    fin_cases i
    · change polynomialDifferential (P (0 : Fin 4)) x w = 0
      rw [h0]
      simp only [polynomialDifferential_mul_apply, hu₁', hv₁', mul_zero, add_zero]
    · change polynomialDifferential (P (1 : Fin 4)) x w = 0
      rw [h1]
      simp only [polynomialDifferential_mul_apply, hu₁', hv₂', mul_zero, add_zero]
    · change polynomialDifferential (P (2 : Fin 4)) x w = 0
      rw [h2]
      simp only [polynomialDifferential_mul_apply, hu₂', hv₁', mul_zero, add_zero]
    · change polynomialDifferential (P (3 : Fin 4)) x w = 0
      rw [h3]
      simp only [polynomialDifferential_mul_apply, hu₂', hv₂', mul_zero, add_zero]
  have hdim := B.mulVecLin.finrank_range_add_finrank_ker
  have hbound := Matrix.rank_le_card_height B
  have hm := Submodule.finrank_mono hle
  change B.rank + finrank K L = finrank K (Fin n → K) at hdim
  simp only [Module.finrank_pi, Module.finrank_self, Fintype.card_fin, mul_one] at hdim
  simp only [Fintype.card_fin] at hbound
  omega

theorem four_quadrics_common_radical_large [IsAlgClosed K]
    (P : Fin 4 → MvPolynomial (Fin n) K)
    (hP : ∀ i, (P i).IsHomogeneous 2) (hlin : LinearIndependent K P)
    (A : Matrix (Fin 4) (Fin 4) K) (hA : A.IsSymm) (hdet : A.det ≠ 0)
    (hrel : TangentHessianRank.quadraticRelation A P = 0) :
    n ≤ finrank K (polynomialTupleDifferentialRadical P) + 4 := by
  obtain ⟨E,hE,u₁,u₂,v₁,v₂,hu₁,hu₂,hv₁,hv₂,h0,h1,h2,h3⟩ :=
    four_quadrics_linear_factorization P hP hlin A hA hdet hrel
  have hb := four_product_tuple_radical_large (combinePolynomials E P)
    u₁ u₂ v₁ v₂ hu₁ hu₂ hv₁ hv₂ h0 h1 h2 h3
  rwa [polynomialTupleDifferentialRadical_combine E hE P] at hb

theorem three_quadrics_common_radical_large [IsAlgClosed K]
    (P : Fin 3 → MvPolynomial (Fin n) K)
    (hP : ∀ i, (P i).IsHomogeneous 2) (hlin : LinearIndependent K P)
    (A : Matrix (Fin 3) (Fin 3) K) (hA : A.IsSymm) (hdet : A.det ≠ 0)
    (hrel : TangentHessianRank.quadraticRelation A P = 0) :
    n ≤ finrank K (polynomialTupleDifferentialRadical P) + 2 := by
  obtain ⟨E,hE,c,_,u,v,hu,hv,h0,h1,h2⟩ :=
    three_quadrics_linear_factorization P hP hlin A hA hdet hrel
  have hb := binary_quadratic_tuple_radical_large (combinePolynomials E P)
    c u v hu hv h0 h1 h2
  rwa [polynomialTupleDifferentialRadical_combine E hE P] at hb

/-- A tuple with trivial common differential radical in at least five
variables cannot be generated by three or four independent quadrics with
a nonsingular relation. This is the nondegenerate deficient-span branch. -/
theorem tuple_not_three_four_nondegenerate_span [IsAlgClosed K] {m r : ℕ}
    (P : Fin m → MvPolynomial (Fin n) K)
    (hP : polynomialTupleDifferentialRadical P = ⊥) (hn : 5 ≤ n)
    (p : Fin r → MvPolynomial (Fin n) K)
    (hp : ∀ i, (p i).IsHomogeneous 2) (hlin : LinearIndependent K p)
    (B : Matrix (Fin m) (Fin r) K) (hB : P = combinePolynomials B p)
    (A : Matrix (Fin r) (Fin r) K) (hA : A.IsSymm) (hdet : A.det ≠ 0)
    (hrel : TangentHessianRank.quadraticRelation A p = 0) (hr : r = 3 ∨ r = 4) : False := by
  have hle := polynomialTupleDifferentialRadical_le_combine B p
  rw [← hB, hP] at hle
  have hz : finrank K (polynomialTupleDifferentialRadical p) = 0 := by
    rw [le_bot_iff.mp hle, finrank_bot]
  rcases hr with rfl | rfl
  · have hb := three_quadrics_common_radical_large p hp hlin A hA hdet hrel
    rw [hz] at hb
    omega
  · have hb := four_quadrics_common_radical_large p hp hlin A hA hdet hrel
    rw [hz] at hb
    omega

end HessianTheorem11
