import Mathlib.LinearAlgebra.Matrix.Transvection
import Mathlib.LinearAlgebra.Matrix.Rank
import Mathlib.LinearAlgebra.Matrix.SchurComplement
import Mathlib.Algebra.Polynomial.Div
import Mathlib.RingTheory.Multiplicity
import Mathlib.Tactic

/-!
Determinant divisibility from the rank of a matrix over a residue field.
This is the algebraic elimination behind the first-normal-rank multiplicity
bound. Matrices and residue maps are actual objects, and row operations are
lifted explicitly from field-valued transvections.
-/

noncomputable section

namespace HessianTheorem11.NormalPencil

open Matrix
open scoped BigOperators

/-- A common divisor in each of `s.card` rows contributes that many
factors to the determinant, over an arbitrary commutative ring. -/
theorem pow_card_dvd_det_of_rows
    {R ι : Type*} [CommRing R] [Fintype ι] [DecidableEq ι]
    (M : Matrix ι ι R) (f : R) (s : Finset ι)
    (hrows : ∀ i ∈ s, ∀ j, f ∣ M i j) : f ^ s.card ∣ M.det := by
  classical
  let a : ι → R := fun i => if i ∈ s then f else 1
  have hdiv (i j : ι) : a i ∣ M i j := by
    by_cases hi : i ∈ s
    · simpa [a, hi] using hrows i hi j
    · simp [a, hi]
  choose N hN using hdiv
  refine ⟨Matrix.det N, ?_⟩
  calc
    M.det = (Matrix.of fun i j => a i * N i j).det := by
      congr 1
      ext i j
      exact hN i j
    _ = (∏ i, a i) * Matrix.det N := Matrix.det_mul_column a N
    _ = f ^ s.card * Matrix.det N := by simp [a]

theorem map_transvection
    {R K ι : Type*} [CommRing R] [CommRing K] [Fintype ι] [DecidableEq ι]
    (φ : R →+* K) (i j : ι) (c : R) :
    φ.mapMatrix (Matrix.transvection i j c) = Matrix.transvection i j (φ c) := by
  change (1 + Matrix.single i j c).map φ = 1 + Matrix.single i j (φ c)
  simp [Matrix.map_add, Matrix.map_single]

/-- Products of elementary matrices over a quotient field lift with
determinant exactly one, rather than merely a nonzero determinant. -/
theorem exists_det_one_lift_of_transvection_product
    {R K ι : Type*} [CommRing R] [Field K] [Fintype ι] [DecidableEq ι]
    (φ : R →+* K) (hφ : Function.Surjective φ)
    (L : List (Matrix.TransvectionStruct ι K)) :
    ∃ P : Matrix ι ι R, P.det = 1 ∧
      φ.mapMatrix P = (L.map Matrix.TransvectionStruct.toMatrix).prod := by
  induction L with
  | nil => exact ⟨1, by simp, by simp⟩
  | cons t L ih =>
    obtain ⟨P, hPdet, hPmap⟩ := ih
    obtain ⟨c, hc⟩ := hφ t.c
    refine ⟨Matrix.transvection t.i t.j c * P, ?_, ?_⟩
    · rw [Matrix.det_mul, Matrix.det_transvection_of_ne _ _ t.hij, hPdet, one_mul]
    · simp only [map_mul, map_transvection, hPmap, hc,
        List.map_cons, List.prod_cons, Matrix.TransvectionStruct.toMatrix]

/-- Field elimination followed by explicit lifting gives determinant-one
left and right row operations over the original coefficient ring. -/
theorem exists_det_one_diagonal_residue
    {R K ι : Type*} [CommRing R] [Field K] [Fintype ι] [DecidableEq ι]
    (φ : R →+* K) (hφ : Function.Surjective φ) (M : Matrix ι ι R) :
    ∃ (P Q : Matrix ι ι R) (D : ι → K),
      P.det = 1 ∧ Q.det = 1 ∧ φ.mapMatrix (P * M * Q) = Matrix.diagonal D := by
  obtain ⟨L, L', D, hD⟩ :=
    Matrix.Pivot.exists_list_transvec_mul_mul_list_transvec_eq_diagonal (φ.mapMatrix M)
  obtain ⟨P, hPdet, hPmap⟩ := exists_det_one_lift_of_transvection_product φ hφ L
  obtain ⟨Q, hQdet, hQmap⟩ := exists_det_one_lift_of_transvection_product φ hφ L'
  refine ⟨P, Q, D, hPdet, hQdet, ?_⟩
  simpa only [map_mul, hPmap, hQmap] using hD

/-- A matrix of residue rank `rho` has determinant divisible by
`f^(size-rho)` when the residue map has principal kernel generated by `f`.
The statement includes zero determinant and does not require a DVR. -/
theorem pow_corank_dvd_det
    {R K ι : Type*} [CommRing R] [Field K] [Fintype ι] [DecidableEq ι]
    (φ : R →+* K) (hφ : Function.Surjective φ) (f : R)
    (hkernel : ∀ a : R, φ a = 0 ↔ f ∣ a) (M : Matrix ι ι R) :
    f ^ (Fintype.card ι - (φ.mapMatrix M).rank) ∣ M.det := by
  classical
  obtain ⟨P, Q, D, hPdet, hQdet, hdiag⟩ :=
    exists_det_one_diagonal_residue φ hφ M
  let N := P * M * Q
  let s : Finset ι := Finset.univ.filter (fun i => D i = 0)
  have hrows : ∀ i ∈ s, ∀ j, f ∣ N i j := by
    intro i hi j
    apply (hkernel _).mp
    have hi' : D i = 0 := (Finset.mem_filter.mp hi).2
    have he := congrArg (fun A : Matrix ι ι K => A i j) hdiag
    simpa [N, RingHom.mapMatrix_apply, Matrix.diagonal_apply, hi'] using he
  have hdetN : N.det = M.det := by simp [N, Matrix.det_mul, hPdet, hQdet]
  have hPunit : IsUnit (φ.mapMatrix P).det := by
    rw [← φ.map_det, hPdet, map_one]
    exact isUnit_one
  have hQunit : IsUnit (φ.mapMatrix Q).det := by
    rw [← φ.map_det, hQdet, map_one]
    exact isUnit_one
  have hrank : (Matrix.diagonal D).rank = (φ.mapMatrix M).rank := by
    rw [← hdiag, map_mul, map_mul,
      Matrix.rank_mul_eq_left_of_isUnit_det _ _ hQunit,
      Matrix.rank_mul_eq_right_of_isUnit_det _ _ hPunit]
  have hcard : s.card = Fintype.card ι - (φ.mapMatrix M).rank := by
    have hsum := Finset.filter_card_add_filter_neg_card_eq_card
      (s := Finset.univ) (fun i : ι => D i = 0)
    rw [Matrix.rank_diagonal, Fintype.card_subtype] at hrank
    simp only [Finset.card_univ] at hsum
    have hsum' : s.card + (φ.mapMatrix M).rank = Fintype.card ι := by
      change (Finset.univ.filter (fun i => D i = 0)).card + _ = _
      rw [← hrank]
      exact hsum
    omega
  simpa only [hdetN, hcard] using pow_card_dvd_det_of_rows N f s hrows

theorem corank_le_multiplicity_det
    {R K ι : Type*} [CommRing R] [Field K] [Fintype ι] [DecidableEq ι]
    (φ : R →+* K) (hφ : Function.Surjective φ) (f : R)
    (hkernel : ∀ a : R, φ a = 0 ↔ f ∣ a) (M : Matrix ι ι R)
    (hfinite : FiniteMultiplicity f M.det) :
    Fintype.card ι - (φ.mapMatrix M).rank ≤ multiplicity f M.det :=
  hfinite.le_multiplicity_of_pow_dvd (pow_corank_dvd_det φ hφ f hkernel M)

/-- Vanishing of a matrix modulo the principal kernel constructs its
scalar factor entry by entry. -/
theorem exists_scalar_factor_of_residue_zero
    {R K ι κ : Type*} [CommRing R] [CommRing K]
    (φ : R →+* K) (f : R)
    (hkernel : ∀ a : R, φ a = 0 ↔ f ∣ a) (S : Matrix ι κ R)
    (hzero : S.map φ = 0) : ∃ M : Matrix ι κ R, S = f • M := by
  have hdiv (i : ι) (j : κ) : f ∣ S i j := by
    apply (hkernel _).mp
    exact congrArg (fun A : Matrix ι κ K => A i j) hzero
  choose M hM using hdiv
  refine ⟨M, ?_⟩
  ext i j
  exact hM i j

/-- The first-normal Schur block is `f*M`. The residue corank of `M`
adds further factors beyond the unavoidable `f^size` scalar factor. -/
theorem first_normal_pow_dvd_det
    {R K ι : Type*} [CommRing R] [Field K] [Fintype ι] [DecidableEq ι]
    (φ : R →+* K) (hφ : Function.Surjective φ) (f : R)
    (hkernel : ∀ a : R, φ a = 0 ↔ f ∣ a) (M : Matrix ι ι R) :
    f ^ (2 * Fintype.card ι - (φ.mapMatrix M).rank) ∣ (f • M).det := by
  have hd := pow_corank_dvd_det φ hφ f hkernel M
  have hr : (φ.mapMatrix M).rank ≤ Fintype.card ι := Matrix.rank_le_card_width _
  have hexp : 2 * Fintype.card ι - (φ.mapMatrix M).rank =
      Fintype.card ι + (Fintype.card ι - (φ.mapMatrix M).rank) := by omega
  rw [hexp, pow_add, Matrix.det_smul]
  exact mul_dvd_mul_left _ hd

/-- The same estimate for an actual block matrix with an invertible
complementary block and displayed first-normal Schur factorization. -/
theorem first_normal_pow_dvd_block_det
    {R K ι κ : Type*} [CommRing R] [Field K]
    [Fintype ι] [DecidableEq ι] [Fintype κ] [DecidableEq κ]
    (φ : R →+* K) (hφ : Function.Surjective φ) (f : R)
    (hkernel : ∀ a : R, φ a = 0 ↔ f ∣ a)
    (A : Matrix κ κ R) (B : Matrix κ ι R) (C : Matrix ι κ R)
    (D M : Matrix ι ι R) [Invertible A]
    (hSchur : D - C * ⅟A * B = f • M) :
    f ^ (2 * Fintype.card ι - (φ.mapMatrix M).rank) ∣
      (Matrix.fromBlocks A B C D).det := by
  rw [Matrix.det_fromBlocks₁₁, hSchur]
  exact dvd_mul_of_dvd_right (first_normal_pow_dvd_det φ hφ f hkernel M) _

/-- The bound in the source's arithmetic form, for the actual multiplicity
of an actual block determinant. Finiteness is explicit, as it must be when
using natural-valued multiplicity. -/
theorem first_normal_block_multiplicity_bound
    {R K ι κ : Type*} [CommRing R] [Field K]
    [Fintype ι] [DecidableEq ι] [Fintype κ] [DecidableEq κ]
    (φ : R →+* K) (hφ : Function.Surjective φ) (f : R)
    (hkernel : ∀ a : R, φ a = 0 ↔ f ∣ a)
    (A : Matrix κ κ R) (B : Matrix κ ι R) (C : Matrix ι κ R)
    (D M : Matrix ι ι R) [Invertible A]
    (hSchur : D - C * ⅟A * B = f • M)
    (hfinite : FiniteMultiplicity f (Matrix.fromBlocks A B C D).det) :
    2 * Fintype.card ι ≤
      multiplicity f (Matrix.fromBlocks A B C D).det + (φ.mapMatrix M).rank := by
  have hbound := hfinite.le_multiplicity_of_pow_dvd
    (first_normal_pow_dvd_block_det φ hφ f hkernel A B C D M hSchur)
  omega

/-- Concrete specialization to a polynomial matrix at the point `t=0`:
the determinant vanishes to order at least the rank drop of its constant
matrix. No residue-field or kernel interface remains as a premise. -/
theorem X_pow_corank_dvd_det
    {K ι : Type*} [Field K] [Fintype ι] [DecidableEq ι]
    (M : Matrix ι ι (Polynomial K)) :
    Polynomial.X ^ (Fintype.card ι -
      ((Polynomial.evalRingHom (0 : K)).mapMatrix M).rank) ∣ M.det := by
  apply pow_corank_dvd_det (Polynomial.evalRingHom (0 : K))
  · intro a
    exact ⟨Polynomial.C a, by simp⟩
  · intro p
    rw [Polynomial.X_dvd_iff, Polynomial.coeff_zero_eq_eval_zero]
    rfl

/-- For `t*M(t)`, a rank-`rho` first normal matrix at zero forces at least
`2*size-rho` factors of `t` in the actual determinant. -/
theorem X_first_normal_pow_dvd_det
    {K ι : Type*} [Field K] [Fintype ι] [DecidableEq ι]
    (M : Matrix ι ι (Polynomial K)) :
    Polynomial.X ^ (2 * Fintype.card ι -
      ((Polynomial.evalRingHom (0 : K)).mapMatrix M).rank) ∣
      ((Polynomial.X : Polynomial K) • M).det := by
  apply first_normal_pow_dvd_det (Polynomial.evalRingHom (0 : K))
  · intro a
    exact ⟨Polynomial.C a, by simp⟩
  · intro p
    rw [Polynomial.X_dvd_iff, Polynomial.coeff_zero_eq_eval_zero]
    rfl

end HessianTheorem11.NormalPencil
